Jui.$define("Jui.option.Grid",Jui.basic.Control);
Jui.option.Grid.getHtml=function(b,c,a){b=b||{};
return"<div class=JuiGrid"+Jui.$p({id:c,style:b.style,title:b.hint})+"><div class=JuiGridTablePanel></div><div class=JuiGridNavigator unselectable=on onselectstart='return false'><div class='JuiGridButton JuiGridFirstPageButton'></div><div class='JuiGridButton JuiGridPreviousPageButton'></div><div><input value=0 class=JuiGridPageIndex></div><div class=JuiGridPageSplitter>/</div><div class=JuiGridPageCount>0</div><div class='JuiGridButton JuiGridNextPageButton'></div><div class='JuiGridButton JuiGridLastPageButton'></div></div></div>";
};
Jui.option.Grid.initialize=function(c,b,a){b=b||{};
a=a||this;
var d=this.superClass.initialize(c,b,a);
d._pageSize=Math.max(1,b.pageSize||10);
d._tablePanel=c.firstChild;
d._navigator=c.lastChild;
d._firstPageButton=d._navigator.children[0];
d._previousPageButton=d._navigator.children[1];
d._pageIndexElem=d._navigator.children[2].firstChild;
d._pageCountElem=d._navigator.children[4];
d._nextPageButton=d._navigator.children[5];
d._lastPageButton=d._navigator.children[6];
d._pageIndexElem.onkeydown=Jui.option.Grid.doPageIndexKeyDown;
d._firstPageButton.onclick=Jui.option.Grid.doPageButtonClick;
d._previousPageButton.onclick=Jui.option.Grid.doPageButtonClick;
d._nextPageButton.onclick=Jui.option.Grid.doPageButtonClick;
d._lastPageButton.onclick=Jui.option.Grid.doPageButtonClick;
d._headerJson=[];
d._dataJson=[];
d._pageIndex=0;
d.loadHeader(b.header||[]);
return d;
};
Jui.option.Grid.prototype.load=function(c){var e=this;
e._headerJson=c.header||[];
e._dataJson=c.data||[];
for(var b=0;
b<e._headerJson.length;
++b){var f=e._headerJson[b];
if(f.type=="Control"&&f.items!=null){for(var a=0;
a<f.items.length;
++a){var d=f.items[a];
if(d.type!="Link"){d.face="Small"+d.type;
}}}}this._loadPage(1);
};
Jui.option.Grid.prototype.loadHeader=function(a){this.load({header:a,data:[]});
};
Jui.option.Grid.prototype.loadData=function(a){this.load({header:this._headerJson,data:a});
};
Jui.option.Grid.prototype.getData=function(){return Jui.util.clone(this._dataJson);
};
Jui.option.Grid.prototype.setValue=Jui.option.Grid.prototype.loadData;
Jui.option.Grid.prototype.getValue=Jui.option.Grid.prototype.getData;
Jui.option.Grid.prototype.getForm=function(){return this._form;
};
Jui.option.Grid.prototype.setForm=function(b){var a=this;
a._form=b;
};
Jui.option.Grid.prototype.focus=function(a){};
Jui.option.Grid.prototype.toText=function(d){if(Jui.array.isEmpty(d)){return"";
}var f=this;
var k=[];
for(var e=0;
e<d.length;
++e){var a=[];
for(var c=0;
c<f._headerJson.length;
++c){var b=f._headerJson[c];
var g=d[e][b.key];
if(!Jui.string.isEmpty(g)){var h;
if(b.type=="Integer"){h=Jui.cast.toString(Jui.cast.toNumber(g),"#,##0");
}else{if(b.type=="Float"){h=Jui.cast.toString(Jui.cast.toNumber(g),"#,##0.00");
}else{if(b.type=="Boolean"){h=Jui.cast.toBool(g)?"Y":"N";
}else{if(b.type=="Date"){h=Jui.cast.toString(Jui.cast.toDate(g),"yyyy-MM-dd");
}else{if(b.type=="DateTime"){h=Jui.cast.toString(Jui.cast.toDate(g),"yyyy-MM-dd HH:mm");
}else{if(b.type=="String"){h=Jui.cast.toString(g);
}else{h="";
}}}}}}a.push(b.title+":"+h);
}}if(a.length>0){k.push("{"+a.join(", ")+"}");
}}return k.length==0?"":"["+k.join(", ")+"]";
};
Jui.option.Grid.prototype.getEventRow=function(){return Jui.util.clone(this._eventRow);
};
Jui.option.Grid.doPageButtonClick=function(){var b=Jui.$owner();
var a=this;
if(!a.hasAttribute("Forbidden")){if(a==b._firstPageButton){b._loadPage(1);
}else{if(a==b._previousPageButton){b._loadPage(b._pageIndex-1);
}else{if(a==b._nextPageButton){b._loadPage(b._pageIndex+1);
}else{if(a==b._lastPageButton){b._loadPage(Math.ceil(b._dataJson.length/b._pageSize));
}}}}}};
Jui.option.Grid.doPageIndexKeyDown=function(){var b=event.keyCode;
if(b==13){var a={pageIndex:parseInt(this.value)||1};
Jui.$owner()._query(a);
}else{if(b!=8&&b!=9&&(b<48||b>57)){Jui.event.stop();
}}};
Jui.option.Grid.doLinkClick=function(){var b=Jui.$owner();
var a=this;
if(!Jui.string.isEmpty(a._handler)){Jui.util.execute(a._handler,b);
}};
Jui.option.Grid.doRowMouseDown=function(){var a=Jui.$owner(null,"JuiGrid");
var b=Jui.dom.getAncestorByTagName("TR");
a._setEventRow(b);
};
Jui.option.Grid.doComboButtonBeforeDrop=function(){var a=Jui.$owner(null,"JuiGrid");
var b=Jui.dom.getAncestorByTagName("TR",this.element);
a._setEventRow(b);
};
Jui.option.Grid.prototype._loadPage=function(g){var v=this;
var l=[];
l.push("<table class=JuiGridTable>");
if(v._headerJson.length>0){l.push("<tr>");
for(var q=0;
q<v._headerJson.length;
++q){var t=v._headerJson[q];
l.push("<td>"+t.title+"</td>");
}l.push("</tr>");
}var d=(g-1)*v._pageSize;
var c=Math.min(v._dataJson.length,g*v._pageSize);
for(var q=d;
q<c;
++q){var e=v._dataJson[q];
l.push("<tr>");
for(var n=0;
n<v._headerJson.length;
++n){var s=v._getCellInfo(v._headerJson[n],e);
l.push("<td");
if(s.align!=null&&s.align!="left"){l.push(" align="+s.align);
}l.push(">"+(s.html||"")+"</td>");
}l.push("</tr>");
}l.push("</table>");
var h=Math.ceil(v._dataJson.length/v._pageSize);
v._tablePanel.innerHTML=l.join("");
v._navigator.style.display=h>1?"block":"none";
v._pageIndex=g;
v._pageIndexElem.value=g;
v._pageCountElem.innerHTML=h;
Jui.dom.tagAttribute(v._firstPageButton,"Forbidden",g<=1);
Jui.dom.tagAttribute(v._previousPageButton,"Forbidden",g<=1);
Jui.dom.tagAttribute(v._nextPageButton,"Forbidden",g>=h);
Jui.dom.tagAttribute(v._lastPageButton,"Forbidden",g>=h);
for(var q=1,f=v._tablePanel.firstChild.rows;
q<f.length;
++q){var e=f[q];
e.onmousedown=Jui.option.Grid.doRowMouseDown;
for(var n=0;
n<v._headerJson.length;
++n){var p=v._headerJson[n];
if(p.type=="Control"){var u=e.cells[n].firstChild.children;
for(var m=0;
m<u.length;
++m){var r=u[m];
var b=p.items[m];
if(b.type=="Link"){r.onclick=Jui.option.Grid.doLinkClick;
r._handler=b.onclick;
}else{var o=Jui.basic[b.type];
var a=o.initialize(r,Jui.object.merge({owner:v},b));
if(b.type=="ComboButton"){a.addEventListener("onbeforedrop",Jui.option.Grid.doComboButtonBeforeDrop);
}}}}}}};
Jui.option.Grid.prototype._getCellInfo=function(b,j){var a={};
if(b.type=="Integer"){var g=Jui.cast.toNumber(j[b.key]);
a.html=Jui.$h(Jui.cast.toString(g,"#,##0"));
a.align=b.align||"right";
}else{if(b.type=="Float"){var g=Jui.cast.toNumber(j[b.key]);
a.html=Jui.$h(Jui.cast.toString(g,"#,##0.00"));
a.align=b.align||"right";
}else{if(b.type=="Boolean"){var g=Jui.cast.toBool(j[b.key]);
a.html=g?"<div class=JuiGridTrueValue></div>":"";
a.align=b.align||"center";
}else{if(b.type=="Date"){var g=Jui.cast.toDate(j[b.key]);
a.html=Jui.cast.toString(g,"yyyy-MM-dd");
a.align=b.align||"center";
}else{if(b.type=="DateTime"){var g=Jui.cast.toDate(j[b.key]);
a.html=Jui.cast.toString(g,"yyyy-MM-dd HH:mm");
a.align=b.align||"center";
}else{if(b.type=="Control"){var c=[];
for(var d=0,f=b.items||[];
d<f.length;
++d){var h=f[d];
if(h.type=="Link"){c.push("<label class=JuiGridLink>"+Jui.$h(h.text)+"</label>");
}else{var e=Jui.basic[h.type];
c.push(e.getHtml(h));
}}a.html="<div class=JuiGridControlContainer>"+c.join("")+" </div>";
a.align=b.align||"center";
}else{a.html=Jui.$h(Jui.cast.toString(j[b.key]));
a.align=b.align;
}}}}}}return a;
};
Jui.option.Grid.prototype._setEventRow=function(c){var a=this;
var b=(a._pageIndex-1)*a._pageSize+c.rowIndex-1;
a._eventRow={index:c.rowIndex-1,totalIndex:b,data:a._dataJson[b]};
};
