Jui.$define("Jui.option.MultiRecipient",Jui.basic.Box);
Jui.option.MultiRecipient.getHtml=function(b,c,a){b=b||{};
return"<textarea class=JuiMultiRecipient"+Jui.$p({id:c,style:b.style,title:b.hint})+"></textarea>";
};
Jui.option.MultiRecipient.initialize=function(c,b,a){b=b||{};
a=a||this;
var d=this.superClass.initialize(c,b,a);
d._maxHeight=b.maxHeight||10000;
d.onblur=b.onblur;
c.onkeydown=Jui.option.MultiRecipient.doKeyDown;
c.onblur=Jui.option.MultiRecipient.doBlur;
d.setValue(b.value);
return d;
};
Jui.option.MultiRecipient.prototype.getRecipients=function(){var a=[];
var b=this.element.value.split(";");
for(var c=0;
c<b.length;
++c){var d=this._extract(b[c]);
if(d.email!=""||d.name!=""){a.push(d);
}}return a;
};
Jui.option.MultiRecipient.prototype.setRecipients=function(a){a=a||[];
var b=[];
for(var e=0;
e<a.length;
++e){var f=a[e];
var d=f.name==null?"":Jui.string.trim(f.name.replace(/\"/g,""));
var c=Jui.string.trim(f.email.replace(/<|>/g,""));
b.push(Jui.string.isEmpty(d)?c:d+"<"+c+">");
}this.element.value=b.join("; ");
};
Jui.option.MultiRecipient.prototype.getValue=function(){var a=this.getRecipients();
var b=[];
for(var c=0;
c<a.length;
++c){var d=a[c];
if(!Jui.string.isEmpty(d.email)&&!Jui.string.isEmpty(d.name)){b.push(d.name+"<"+d.email+">");
}else{if(!Jui.string.isEmpty(d.email)){b.push(d.email);
}else{b.push(d.name+"<>");
}}}return b.join("; ");
};
Jui.option.MultiRecipient.prototype.setValue=function(a){this.element.value=a||"";
};
Jui.option.MultiRecipient.prototype.focus=function(){this.element.focus();
};
Jui.option.MultiRecipient.prototype.add=function(c,b){c=Jui.string.trim(c||"");
b=Jui.string.trim(b||"");
var g=this.element.value.replace(/;?\s*$/g,"");
var e=c==""?b+"<>":(b==""?c:b+"<"+c+">");
for(var d=0,a=g.indexOf(";");
;
d=a+1,a=g.indexOf(";",d)){var h=a==-1?g.substring(d):g.substring(d,a);
var f=this._extract(h);
if(f.email==c&&(c!=""||f.name==b)){g=g.substring(0,d)+(a==-1?"":g.substring(a+1));
this.element.value=Jui.string.isEmpty(g)?e:g.replace(/^\s+|;?\s*$/g,"")+"; "+e;
return;
}if(a==-1){break;
}}this.element.value=Jui.string.isEmpty(g)?e:Jui.string.trim(g)+"; "+e;
};
Jui.option.MultiRecipient.prototype.validate=function(){var e=this;
var a=e.element.value.split(";");
for(var c=0;
c<a.length;
++c){var f=a[c];
if(!Jui.string.isEmpty(f)){var b=Jui.string.trim(/<(.*)>/.test(f)?RegExp.$1:f);
if(!/^[\w\d-_\.]+@[\w\d-_\.]+$/.test(b)){var d=Jui.i18n.getText("Jui.MultiRecipient.InvalidEmail").replace("${0}",b);
Jui.message.alert(d,function(){e.focus();
});
return false;
}}}return true;
};
Jui.option.MultiRecipient.doKeyDown=function(){if(event.keyCode==13){return false;
}};
Jui.option.MultiRecipient.doBlur=function(){Jui.$owner().fireEvent("onblur");
};
Jui.option.MultiRecipient.prototype._extract=function(a){return{email:Jui.string.trim(/<(.*)>/.test(a)?RegExp.$1:a),name:/([^<]+)</.test(a)?Jui.string.trim(RegExp.$1.replace(/\"/g,"")):""};
};
