Jui.$define("Jui.option.PercentBar",Jui.basic.Box);
Jui.option.PercentBar.getHtml=function(b,c,a){b=b||{};
return"<div class=JuiPercentBar"+Jui.$p({id:c,style:b.style})+"><div><div class=JuiPercentBarSlider></div><div class=JuiPercentBarText></div></div></div>";
};
Jui.option.PercentBar.initialize=function(c,b,a){b=b||{};
a=a||this;
var d=this.superClass.initialize(c,b,a);
d._slider=c.firstChild.firstChild;
d._text=c.firstChild.lastChild;
d.setValue(b.value);
return d;
};
Jui.option.PercentBar.prototype.getValue=function(){return this._value||0;
};
Jui.option.PercentBar.prototype.setValue=function(b){var a=this;
a._value=b||0;
a._slider.style.width=a._value*100+"%";
a._text.innerHTML=Math.floor(a._value*100)+"%";
};
