Jui.$define("Jui.option.Sorter",Jui.basic.Control);
Jui.option.Sorter.getHtml=function(b,c,a){b=b||{};
return"<div class=JuiSorter"+Jui.$p({id:c,style:b.style})+" unselectable=on onselectstart='return false'></div>";
};
Jui.option.Sorter.initialize=function(c,b,a){b=b||{};
a=a||this;
var d=this.superClass.initialize(c,b,a);
d._multiSelect=Jui.cast.toBool(b.multiSelect,true);
d.onchange=b.onchange;
d.onclick=b.onclick;
d.ondoubleclick=b.ondoubleclick;
d._anchorRow=null;
d.setDisabled(Jui.cast.toBool(b.disabled,false));
return d;
};
Jui.option.Sorter.prototype.add=function(b){var c=this;
var d=c._getRows().length;
var a=[];
c._getHtml(b,0,a);
Jui.dom.insertHtml(c.element,"BeforeEnd",a.join(""));
c._initializeRows(c._getRows(),d,b);
c.fireEvent("onchange");
};
Jui.option.Sorter.prototype.update=function(b){var d=this;
var f={};
for(var a=0,e=d._getValueRows();
a<e.length;
++a){f[e[a]._value]=e[a];
}for(var a=0;
a<b.length;
++a){var c=b[a];
if(c.value in f){f[c.value].innerHTML=Jui.$h(c.text);
}}d.fireEvent("onchange");
};
Jui.option.Sorter.prototype.clear=function(){this.load([]);
};
Jui.option.Sorter.prototype.deleteSelected=function(){var b=this;
var d=[];
for(var a=0,c=b._getSelectedRows();
a<c.length;
++a){var e=c[a];
d.push(b._getRowJson(e));
Jui.dom.removeElement(e.parentElement);
if(e==b._anchorRow){b._anchorRow=null;
}}b.fireEvent("onchange");
return d;
};
Jui.option.Sorter.prototype.getValues=function(){var a=[];
for(var b=0,c=this._getValueRows();
b<c.length;
++b){a.push(c[b]._value);
}return a;
};
Jui.option.Sorter.prototype.containsValue=function(c){for(var a=0,b=this._getValueRows();
a<b.length;
++a){if(b[a]._value==c){return true;
}}return false;
};
Jui.option.Sorter.prototype.getTexts=function(){var c=[];
for(var a=0,b=this._getValueRows();
a<b.length;
++a){c.push(b[a].innerText);
}return c;
};
Jui.option.Sorter.prototype.getData=function(){var c=[];
for(var a=0,b=this._getValueRows();
a<b.length;
++a){c.push(this._getRowJson(b[a]));
}return c;
};
Jui.option.Sorter.prototype.getIndices=function(){return this._getIndices(this.element,[]);
};
Jui.option.Sorter.prototype.getLevels=function(){return this._getLevels(this.element,[],1);
};
Jui.option.Sorter.prototype.getTreeSerials=function(){return this._getTreeSerials(this.element,[],"");
};
Jui.option.Sorter.prototype.getSelectedValues=function(){var a=[];
for(var b=0,c=this._getSelectedRows();
b<c.length;
++b){a.push(c[b]._value);
}return a;
};
Jui.option.Sorter.prototype.getSelectedData=function(){var c=[];
for(var a=0,b=this._getSelectedRows();
a<b.length;
++a){c.push(this._getRowJson(b[a]));
}return c;
};
Jui.option.Sorter.prototype.load=function(b){var c=this;
var a=[];
c._getHtml(b,0,a);
c.element.innerHTML=a.join("");
c._initializeRows(c.element.getElementsByTagName("span"),0,b);
};
Jui.option.Sorter.prototype.getCurrentItem=function(){var a=this._getSelectedRows()[0];
if(a!=null){return this._getRowJson(a);
}};
Jui.option.Sorter.prototype.getCurrentIndex=function(){var c=this._getSelectedRows()[0];
if(c!=null){for(var a=0,b=this._getRows();
a<b.length;
++a){if(c==b[a]){return a;
}}}return -1;
};
Jui.option.Sorter.prototype.updateItemByIndex=function(a,b){var c=this._getValueRows()[a];
if(c!=null){if("data" in b){c._data=b.data;
}if("text" in b){c.innerHTML=Jui.$h(text);
}this.fireEvent("onchange");
}};
Jui.option.Sorter.prototype.updateCurrentItem=function(a){var b=this._getSelectedRows()[0];
if(b!=null){if("data" in a){b._data=a.data;
}if("text" in a){b.innerHTML=Jui.$h(text);
}this.fireEvent("onchange");
}};
Jui.option.Sorter.prototype.moveUp=function(){for(var a=0,c=this._getSelectedRows();
a<c.length;
++a){var d=c[a];
var b=d.parentElement.previousSibling&&d.parentElement.previousSibling.firstChild;
if(b!=null&&!this._isSelected(b)){Jui.dom.insertElement(b.parentElement,"BeforeBegin",d.parentElement);
}}this.fireEvent("onchange");
};
Jui.option.Sorter.prototype.moveDown=function(){for(var c=this._getSelectedRows(),a=c.length-1;
a>=0;
--a){var d=c[a];
var b=d.parentElement.nextSibling&&d.parentElement.nextSibling.firstChild;
if(b!=null&&!this._isSelected(b)){Jui.dom.insertElement(b.parentElement,"AfterEnd",d.parentElement);
}}this.fireEvent("onchange");
};
Jui.option.Sorter.prototype.moveTop=function(){var g={};
for(var d=0,f=this._getSelectedRows();
d<f.length;
++d){var h=f[d];
var a=h.parentElement.parentElement;
var e=a==this.element?null:a.previousSibling._value;
var c=g[e]||0;
var b=a.children[c];
if(f[d].parentElement!=b){Jui.dom.insertElement(b,"BeforeBegin",f[d].parentElement);
}g[e]=c+1;
}this.fireEvent("onchange");
};
Jui.option.Sorter.prototype.moveBottom=function(){var g={};
for(var f=this._getSelectedRows(),d=f.length-1;
d>=0;
--d){var h=f[d];
var a=h.parentElement.parentElement;
var e=a==this.element?null:a.previousSibling._value;
var c=g[e]||0;
var b=a.children[a.children.length-1-c];
if(f[d].parentElement!=b){Jui.dom.insertElement(b,"AfterEnd",f[d].parentElement);
}g[e]=c+1;
}this.fireEvent("onchange");
};
Jui.option.Sorter.prototype.select=function(e){var c=this;
var g=Jui.array.toSet(Jui.array.make(e));
var a=true;
for(var b=0,d=c._getValueRows();
b<d.length;
++b){var f=d[b];
c._select(f,f._value in g);
if(f._value in g&&a){c._anchorRow=f;
a=false;
}}};
Jui.option.Sorter.prototype.selectByIndex=function(b){var d=this;
var g=Jui.array.toSet(Jui.array.make(b));
var a=true;
for(var c=0,e=d._getValueRows();
c<e.length;
++c){var f=e[c];
d._select(f,c in g);
if(c in g&&a){d._anchorRow=f;
a=false;
}}};
Jui.option.Sorter.prototype.unselect=function(){this._unselectExcept();
};
Jui.option.Sorter.doRowClick=function(){var b=this;
var d=Jui.$owner();
if(d.isDisabled()){return;
}if(d._multiSelect&&(event.ctrlKey||event.shiftKey&&d._anchorRow==null)){d._select(b,event.shiftKey||!d._isSelected(b));
d._anchorRow=b;
}else{if(d._multiSelect&&event.shiftKey&&d._anchorRow!=null){for(var c=0,a=0,e=d._getRows();
c<e.length;
++c){var f=e[c];
if(f==b||f==d._anchorRow){++a;
}d._select(f,f==b||f==d._anchorRow||a==1);
}}else{d._select(b,true);
d._unselectExcept(b);
d._anchorRow=b;
}}d.fireEvent("onclick",d._getRowJson(b));
};
Jui.option.Sorter.doRowDoubleClick=function(){var a=Jui.$owner();
var b=this;
if(!a.isDisabled()){a.fireEvent("ondoubleclick",a._getRowJson(b));
}};
Jui.option.Sorter.doRowMouseOver=function(){var a=event.srcElement;
if(a.tagName=="LABEL"){a.title=a.offsetWidth>a.parentElement.offsetWidth?a.innerText:"";
}};
Jui.option.Sorter.prototype._getHtml=function(c,b,a){if(b>=c.length){return b;
}var h=c[b].level||1;
var g=Jui.theme["Sorter.LevelIndent"];
var e=" style='padding-left:"+(h-1)*g+"px'";
while(b<c.length&&(c[b].level||1)==h){var f=c[b];
var d="JuiSorterItemHead";
if(f.isTitle){d="'JuiSorterItemHead JuiSorterItemHeadTitle'";
}else{if(f.selected){d="'JuiSorterItemHead JuiSorterItemHeadSelected'";
}}a.push("<div class=JuiSorterItem>");
a.push("<span class="+d+e+"><label>"+Jui.$h(f.text)+"<label></span>");
++b;
if(b<c.length&&(c[b].level||1)>h){a.push("<div class=JuiSorterItemBody>");
b=this._getHtml(c,b,a);
a.push("</div>");
}a.push("</div>");
}return b;
};
Jui.option.Sorter.prototype._initializeRows=function(c,e,b){for(var a=0;
a<b.length;
++a){var d=c[e+a];
if(b[a].isTitle){d._isTitle=true;
}else{d._value=b[a].value;
d._data=b[a].data;
d._level=b[a].level||1;
d.onclick=Jui.option.Sorter.doRowClick;
d.ondblclick=Jui.option.Sorter.doRowDoubleClick;
d.onmouseover=Jui.option.Sorter.doRowMouseOver;
}}};
Jui.option.Sorter.prototype._getRows=function(){return this.element.getElementsByTagName("span");
};
Jui.option.Sorter.prototype._getValueRows=function(){var a=[];
for(var b=0,c=this._getRows();
b<c.length;
++b){if(!c[b]._isTitle){a.push(c[b]);
}}return a;
};
Jui.option.Sorter.prototype._getSelectedRows=function(){var c=[];
for(var a=0,b=this._getRows();
a<b.length;
++a){if(this._isSelected(b[a])){c.push(b[a]);
}}return c;
};
Jui.option.Sorter.prototype._getIndices=function(a,e){for(var c=0,b=0;
c<a.children.length;
++c){var d=a.children[c];
if(!d.firstChild._isTitle){e.push(++b);
}if(d.children.length==2){this._getIndices(d.lastChild,e);
}}return e;
};
Jui.option.Sorter.prototype._getLevels=function(a,d,e){for(var b=0;
b<a.children.length;
++b){var c=a.children[b];
if(!c.firstChild._isTitle){d.push(e);
}if(c.children.length==2){this._getLevels(c.lastChild,d,e+1);
}}return d;
};
Jui.option.Sorter.prototype._getTreeSerials=function(a,g,f){for(var d=0;
d<a.children.length;
++d){var e=a.children[d];
var c;
if(d>=999){c=f+(d+1);
}else{var b="00"+(d+1);
c=f+(b.substr(b.length-3));
}if(!e.firstChild._isTitle){g.push(c);
}if(e.children.length==2){this._getTreeSerials(e.lastChild,g,c+".");
}}return g;
};
Jui.option.Sorter.prototype._getRowJson=function(a){return{value:a._value,text:a.innerText,level:a._level,data:a._data};
};
Jui.option.Sorter.prototype._isSelected=function(a){return/Selected/.test(a.className);
};
Jui.option.Sorter.prototype._select=function(b,a){Jui.dom.tagClass(b,"JuiSorterItemHeadSelected",a);
};
Jui.option.Sorter.prototype._unselectExcept=function(c){for(var a=0,b=this._getRows();
a<b.length;
++a){if(b[a]!=c&&this._isSelected(b[a])){Jui.dom.removeClass(b[a],"JuiSorterItemHeadSelected");
}}};
