Jui.$define("Jui.option.TabStrip",Jui.basic.Control);
Jui.option.TabStrip.getHtml=function(c,e,b){c=c||{};
var d;
if(c.face!=null){d="Jui"+c.face;
}else{var a=Jui.string.upperFirstLetter((c.tabPosition||"top").toLowerCase());
d="Jui"+(Jui.cast.toBool(c.dynamic,false)?"Dynamic":"")+a+"TabStrip";
}return"<div"+Jui.$p({"class":d,id:e,style:c.style,border:c.border})+"><div class=JuiTabStripTabZoneOuter><div class=JuiTabStripTabZone></div></div><div class=JuiTabStripBodyZone></div></div>";
};
Jui.option.TabStrip.initialize=function(c,b,a){b=b||{};
a=a||this;
var d=this.superClass.initialize(c,b,a);
d._maxTabCount=b.maxTabCount||20;
d._tabPosition=(b.tabPosition||"top").toLowerCase();
d._dynamic=Jui.cast.toBool(b.dynamic,false);
d._maximizable=Jui.cast.toBool(b.maximizable,false);
d._fireSwitchEventOnLoad=Jui.cast.toBool(b.fireSwitchEventOnLoad,false);
d._useImageText=b.textType=="image";
d.onswitch=b.onswitch;
d._tabZone=c.firstChild.firstChild;
d._bodyZone=c.lastChild;
d._current=null;
d._tabs=d._tabZone.children;
d._queue=[];
d._isHorz=d._tabPosition=="top"||d._tabPosition=="bottom";
d._originSize=0;
d._serial=0;
Jui.event.attach(window,"resize",function(){d._updateTabSize();
});
return d;
};
Jui.option.TabStrip.prototype.size=function(){return this._tabs.length;
};
Jui.option.TabStrip.prototype.isDynamic=function(){return this._dynamic;
};
Jui.option.TabStrip.prototype.getIndex=function(){for(var a=0;
a<this._tabs.length;
++a){if(this._tabs[a]==this._current){return a;
}}return -1;
};
Jui.option.TabStrip.prototype.setIndex=function(a){this._activate(this._tabs[a]);
};
Jui.option.TabStrip.prototype.getIdByWindow=function(c){while(c!=c.parent){for(var a=0;
a<this._tabs.length;
++a){var b=this._tabs[a];
var f=b._body;
try{if(f!=null&&f.contentWindow==c){return b._json.id;
}}catch(d){}}c=c.parent;
}};
Jui.option.TabStrip.prototype.setTabTitle=function(e,d){var c=this;
for(var a=0;
a<c._tabs.length;
++a){var b=c._tabs[a];
if(b._json.id==e){b._text.style[c._isHorz?"width":"height"]="auto";
b._text.innerHTML=Jui.$h(d);
b._textChanged=true;
c._updateTabPosition();
c._updateTabSize();
break;
}}};
Jui.option.TabStrip.prototype.getItem=function(b){var a=this._getTab(b);
return a&&Jui.util.clone(a._json);
};
Jui.option.TabStrip.prototype.getItems=function(){var a=[];
for(var b=0;
b<this._tabs.length;
++b){a.push(Jui.util.clone(this._tabs[b]._json));
}return a;
};
Jui.option.TabStrip.prototype.getCurrentId=function(){return this._current&&this._current._json.id;
};
Jui.option.TabStrip.prototype.setCurrentId=function(a){this._activate(this._getTab(a));
};
Jui.option.TabStrip.prototype.add=function(b,e,d){var f=this;
if(!Jui.string.isEmpty(b.id)){var c=f._getTab(b.id);
if(c!=null){f._processExistingTab(c,b);
return b.id;
}}if(f._dynamic&&!Jui.string.isEmpty(b.url)&&!b.openNewTab){for(var a=0;
a<f._tabs.length;
++a){var c=f._tabs[a];
if(c._url==b.url){f._processExistingTab(c,b);
return c._json.id;
}}}while(f._queue.length>=f._maxTabCount){var c=null;
for(var a=0;
a<f._queue.length;
++a){if(!f._isTabLocked(f._queue[a])){c=f._queue.splice(a,1)[0];
break;
}}f._remove(c||f._queue.shift());
}var c=Jui.dom.insertHtml(f._tabZone,"BeforeEnd",f._getTabHtml(b));
c._body=Jui.dom.insertHtml(f._bodyZone,"BeforeEnd",f._getBodyHtml());
c._url=b.url;
f._initializeTab(c,b);
f._updateTabPosition();
f._updateTabSize();
if(f._tabs.length==1||e!=false){f._activate(c);
}if(b.lock){f._lockTab(c);
}return d?c._json.id:c._body;
};
Jui.option.TabStrip.prototype.exists=function(a){return this._getTab(a)!=null;
};
Jui.option.TabStrip.prototype.remove=function(b){var a=this._getTab(b);
if(a!=null){this._remove(a);
}};
Jui.option.TabStrip.prototype.removeByIndex=function(a){this._remove(this._tabs[a]);
};
Jui.option.TabStrip.prototype.getBody=function(b){var a=this._getTab(b);
return a&&a._body;
};
Jui.option.TabStrip.prototype.getFrameWindow=function(b){var a=this._getTab(b);
return a==null||a._body.tagName!="IFRAME"?null:Jui.dom.getFrameWindow(a._body);
};
Jui.option.TabStrip.prototype.getBodyByIndex=function(a){return this._tabs[a]._body;
};
Jui.option.TabStrip.prototype.load=function(d){d=d||[];
var f=this;
var b=[];
var a=[];
for(var c=0;
c<d.length;
++c){b.push(f._getTabHtml(d[c]));
a.push(f._getBodyHtml());
}f._current=null;
f._queue=[];
f._originSize=0;
f._tabZone.innerHTML=b.join("");
f._bodyZone.innerHTML=a.join("");
for(var c=0;
c<f._tabs.length;
++c){var e=f._tabs[c];
e._body=f._bodyZone.children[c];
f._initializeTab(e,d[c]);
}if(f._tabs.length>0){f._activate(f._tabs[0],f._fireSwitchEventOnLoad);
}f._updateTabPosition();
f._updateTabSize();
};
Jui.option.TabStrip.prototype.getTabAttribute=function(c,a){var b=this._getTab(c);
if(b==null){throw new Error("Invalid tab ID: "+c);
}return b._attributes==null?undefined:b._attributes[a];
};
Jui.option.TabStrip.prototype.setTabAttribute=function(d,a,c){var b=this._getTab(d);
if(b==null){throw new Error("Invalid tab ID: "+d);
}if(b._attributes==null){b._attributes={};
}b._attributes[a]=c;
};
Jui.option.TabStrip.prototype.flash=function(c){var b=this;
var a=b._getTab(c);
if(a==null){throw new Error("Invalid tab ID: "+c);
}if(a==b._current){return;
}b._stopFlash(a);
a._flashIndex=0;
a._flashTimer=setInterval(function(){a._flashIndex++;
a._text.style.visibility=a._flashIndex%2==1?"hidden":"visible";
},400);
};
Jui.option.TabStrip.doTabClick=function(){Jui.$owner()._activate(Jui.dom.getAncestorByClassName("JuiTabStripTab"),true);
};
Jui.option.TabStrip.doTabClose=function(){Jui.event.stopPropagation();
Jui.$owner()._remove(Jui.dom.getAncestorByClassName("JuiTabStripTab"));
};
Jui.option.TabStrip.doTabContextMenu=function(){var f=Jui.$owner();
var e=Jui.dom.getAncestorByClassName("JuiTabStripTab");
if(f._tabMenu==null){f._tabMenu=Jui.basic.PopupMenu.create({owner:f,onclick:Jui.option.TabStrip.doTabMenuClick});
}var b=f._isTabLocked(e);
var g=false;
for(var d=e.nextSibling;
d!=null;
d=d.nextSibling){if(!f._isTabLocked(d)){g=true;
break;
}}var h=false;
for(var c=0;
c<f._tabs.length;
++c){if(f._tabs[c]!=e&&!f._isTabLocked(f._tabs[c])){h=true;
break;
}}var a=[{id:b?"UnlockTab":"LockTab",text:Jui.i18n.getText(b?"Jui.TabStrip.UnlockTab":"Jui.TabStrip.LockTab"),disabled:!b&&!h&&f._tabs.length==f._maxTabCount},{splitter:true},{id:"CloseTab",text:Jui.i18n.getText("Jui.TabStrip.CloseTab")},{id:"CloseOtherTabs",text:Jui.i18n.getText("Jui.TabStrip.CloseOtherTabs"),disabled:!h},{id:"CloseRightTabs",text:Jui.i18n.getText("Jui.TabStrip.CloseRightTabs"),disabled:!g}];
if(f._maximizable&&f._dynamic){a.push({splitter:true});
a.push({id:"Maximize",text:Jui.i18n.getText("Jui.TabStrip.Maximize")});
}f._menuTab=e;
f._tabMenu.load(a);
f._tabMenu.show();
return false;
};
Jui.option.TabStrip.doTabMenuClick=function(c){var b=this.getOwner();
if(c.id=="LockTab"){b._lockTab(b._menuTab);
}else{if(c.id=="UnlockTab"){b._unlockTab(b._menuTab);
}else{if(c.id=="CloseTab"){b._remove(b._menuTab);
}else{if(c.id=="CloseOtherTabs"){for(var a=b._tabs.length-1;
a>=0;
--a){if(!b._isTabLocked(b._tabs[a])&&b._tabs[a]!=b._menuTab){b._remove(b._tabs[a]);
}}}else{if(c.id=="CloseRightTabs"){for(var a=b._tabs.length-1;
a>=0&&b._tabs[a]!=b._menuTab;
--a){if(!b._isTabLocked(b._tabs[a])){b._remove(b._tabs[a]);
}}}else{if(c.id=="Maximize"){b._activate(b._menuTab,true);
b.element.setAttribute("Maximized",true);
if(b._restoreIcon==null){b._restoreIcon=Jui.dom.insertHtml(b.element,"BeforeEnd","<div class=JuiTabStripRestore></div>");
b._restoreIcon.onclick=Jui.option.TabStrip.doRestoreIconClick;
}}}}}}}};
Jui.option.TabStrip.doRestoreIconClick=function(b){var a=Jui.$owner();
a.element.removeAttribute("Maximized");
};
Jui.option.TabStrip.prototype._getTab=function(c){for(var b=0,a=this._tabs;
b<a.length;
++b){if(a[b]._json.id==c){return a[b];
}}};
Jui.option.TabStrip.prototype._getTabHtml=function(a){var b=this._useImageText?"<img src='"+a.text+"'>":Jui.$h(a.text);
return"<div class=JuiTabStripTab unselectable=on onselectstart='return false'><div class='JuiTitle JuiTabStripTabText'"+(a.icon?" WithIcon style='background-image:url("+a.icon+")'":"")+">"+b+"</div>"+(this._dynamic?"<div class=JuiTabStripTabClose onclick=Jui.option.TabStrip.doTabClose()></div>":"")+(this._dynamic?"<div class=JuiTabStripTabLock></div>":"")+"</div>";
};
Jui.option.TabStrip.prototype._getBodyHtml=function(){return this._dynamic?"<iframe class=JuiTabStripBody frameborder=0></iframe>":"<div class=JuiTabStripBody></div>";
};
Jui.option.TabStrip.prototype._initializeTab=function(c,b){var d=this;
if(Jui.string.isEmpty(b.id)){b.id="JUI_TABSTRIP_TAB"+ ++d._serial;
}c._json=b;
c._text=c.firstChild;
c._textChanged=true;
c.onclick=Jui.option.TabStrip.doTabClick;
if(d._dynamic){c.ondblclick=Jui.option.TabStrip.doTabClose;
c.oncontextmenu=Jui.option.TabStrip.doTabContextMenu;
}d._queue.push(c);
if(!d._dynamic&&Jui.dom.element(b.body)!=null){var a=Jui.dom.element(b.body);
c._body.appendChild(a);
a.style.display="block";
}else{if(!Jui.string.isEmpty(b.url)){c._body.src=b.url;
}}};
Jui.option.TabStrip.prototype._updateTabPosition=function(){var c=this._isHorz?"left":"top";
var a=Jui.theme[this._isHorz?"TabStrip.HorzTabOverLap":"TabStrip.VertTabOverLap"];
for(var b=0;
b<this._tabs.length;
++b){this._tabs[b].style[c]="-"+(b*a)+"px";
}};
Jui.option.TabStrip.prototype._processExistingTab=function(b,a){var c=this;
if(a.forceReload){b._body.src=a.url;
}if(b==c._current){c._flashBackground(b,6);
}else{c._activate(b);
}};
Jui.option.TabStrip.prototype._remove=function(c){var d=this;
if(c._body.tagName=="IFRAME"){var a=Jui.dom.getFrameWindow(c._body);
if(Jui.event.fireCustomEvent(a,"beforeclose")==false){return;
}}d._stopFlash(c);
var b=null;
if(c==d._current){b=c.nextSibling||c.previousSibling;
d._current=null;
}delete c._attributes;
Jui.array.remove(d._queue,c);
d._originSize-=c._tabSize||0;
d._bodyZone.removeChild(c._body);
d._tabZone.removeChild(c);
if(b!=null){d._activate(b);
}d._updateTabPosition();
d._updateTabSize();
};
Jui.option.TabStrip.prototype._activate=function(b,a){var c=this;
if(b==c._current){return;
}c._stopFlash(b);
if(c._current!=null){c._current.style.zIndex=0;
c._current.className="JuiTabStripTab";
c._current._body.style.top="";
}b.style.zIndex=1;
b.className="JuiTabStripTab JuiTabStripTabCurrent";
b._body.style.top="0px";
Jui.array.remove(c._queue,b);
c._queue.push(b);
c._current=b;
if(a){c.fireEvent("onswitch",{item:b._json});
}};
Jui.option.TabStrip.prototype._updateTabSize=function(){var g=this;
var j=g._bodyZone[g._isHorz?"clientWidth":"clientHeight"];
if(g._dynamic){j-=Jui.theme["TabStrip.CloseIconSize"];
}if(j<=0||g._tabs.length==0){return;
}var a=0;
for(var e=0;
e<g._tabs.length;
++e){var b=g._tabs[e];
if(b._textChanged){b._textSize=g._isHorz?b._text.offsetWidth:b._text.offsetHeight;
b._tabSize=g._isHorz?b.offsetWidth:b.offsetHeight;
b._textChanged=false;
}a+=b._tabSize;
}g._originSize=a;
var k=Jui.theme[g._isHorz?"TabStrip.HorzTabOverLap":"TabStrip.VertTabOverLap"];
var c=g._originSize-k*(g._tabs.length-1)-j;
if(c<=0){for(var e=0;
e<g._tabs.length;
++e){g._tabs[e]._text.style[g._isHorz?"width":"height"]="auto";
}return;
}var h=Jui.array.wrap(g._tabs).sort(function(n,i){return i._textSize-n._textSize;
});
var m=Jui.array.extractProperty(h,"_textSize");
while(c>0&&m[0]>0){var f=1;
while(f<m.length&&m[f]==m[f-1]){++f;
}var d=f==m.length?m[0]:m[0]-m[f];
var l=Math.min(d*f,c);
d=Math.ceil(l/f);
for(var e=0;
e<f;
++e){m[e]-=d;
}c-=l;
}for(var e=0;
e<h.length;
++e){h[e]._text.style[g._isHorz?"width":"height"]=m[e]+"px";
}};
Jui.option.TabStrip.prototype._stopFlash=function(a){if(a._flashTimer!=null){clearInterval(a._flashTimer);
a._flashTimer=null;
a._text.style.visibility="visible";
}};
Jui.option.TabStrip.prototype._flashBackground=function(a,c){var b=this;
if(c>0&&a==b._current){a.className="JuiTabStripTab JuiTabStripTabCurrent"+(c%2==0?" JuiTabStripTabFlash":"");
setTimeout(function(){b._flashBackground(a,c-1);
},80);
}};
Jui.option.TabStrip.prototype._lockTab=function(a){var b=this;
a.setAttribute("Lock",true);
var c=a;
while(c.previousSibling!=null&&!b._isTabLocked(c.previousSibling)){c=c.previousSibling;
}if(c!=a){Jui.dom.insertElement(c,"BeforeBegin",a);
}};
Jui.option.TabStrip.prototype._unlockTab=function(a){var b=this;
a.removeAttribute("Lock");
var c=a;
while(c.nextSibling!=null&&b._isTabLocked(c.nextSibling)){c=c.nextSibling;
}if(c!=a){Jui.dom.insertElement(c,"AfterEnd",a);
}};
Jui.option.TabStrip.prototype._isTabLocked=function(a){return a.hasAttribute("Lock");
};
