Jui.$define("Jui.option.Tree",Jui.basic.Control);
Jui.option.Tree.getHtml=function(b,c,a){b=b||{};
return"<div"+Jui.$p({"class":"JuiTree",id:c,style:b.style})+" unselectable=on onselectstart='return false'></div>";
};
Jui.option.Tree.initialize=function(c,b,a){b=b||{};
a=a||this;
var d=this.superClass.initialize(c,b,a);
d._hasIcon=Jui.cast.toBool(b.hasIcon,true);
d._sameIcon=Jui.cast.toBool(b.sameIcon,false);
d._multiSelect=Jui.cast.toBool(b.multiSelect,false);
d._autoSelectParent=Jui.cast.toBool(b.autoSelectParent,false);
d.onnodeclick=b.onnodeclick;
d.onleafclick=b.onleafclick;
d.onloadsubnodes=b.onloadsubnodes;
d._map={};
d._current=null;
d.load([]);
return d;
};
Jui.option.Tree.prototype.load=function(a,b){var c=this;
a=a||[];
c._current=null;
c._map={};
c.element.innerHTML=c._getHtml(a,[],true,true).join("");
c._initNodeBody(c.element.firstChild,a);
if(c._multiSelect){if(Jui.cast.toBool(b,true)){c._autoSelectChildChecks(c.element.firstChild);
}c._autoSelectParentChecks(c.element.firstChild);
}};
Jui.option.Tree.prototype.expandLevel=function(a){if(a>0){this._expandLevelRecurse(this.element.firstChild,a);
}};
Jui.option.Tree.prototype.getNodeCount=function(){return this._getDescendants().length;
};
Jui.option.Tree.prototype.clearSelection=function(){this.select([]);
};
Jui.option.Tree.prototype.select=function(b){var d=this;
if(d._multiSelect){var e=Jui.array.toSet(Jui.array.make(b));
for(var c=0,a=d._getDescendants();
c<a.length;
++c){d._setChecked(a[c],a[c]._json.id in e);
}d._autoSelectChildChecks(d.element.firstChild);
d._autoSelectParentChecks(d.element.firstChild);
}};
Jui.option.Tree.prototype.selectAll=function(a){var d=this;
if(d._multiSelect){a=Jui.cast.toBool(a,true);
for(var c=0,b=d._getDescendants();
c<b.length;
++c){d._setChecked(b[c],a);
}}};
Jui.option.Tree.prototype.getSelectedIds=function(e){var c=[];
if(this._multiSelect){var a=Jui.dom.getElementsByClassName(this.element,"JuiTreeCheckCell");
for(var b=0;
b<a.length;
++b){var d=Jui.dom.getAncestorByClassName("JuiTreeNode",a[b]);
if(this._isChecked(d)&&(!e||!this._isDisabled(d))){c.push(d._json.id);
}}}return c;
};
Jui.option.Tree.prototype.getTopmostSelectedIds=function(a){return Jui.array.extractProperty(this.getTopmostSelectedNodes(),"id");
};
Jui.option.Tree.prototype.getTopmostSelectedNodes=function(a){var g=this;
var d=[];
if(a==null){a=g.element.firstChild;
}for(var e=0,c=a.children;
e<c.length;
++e){var f=c[e];
if(g._isChecked(f)){d.push(g._getNodeInfo(f));
}else{if(f._isBranch&&f._body!=null&&(g._isPartial(f)||!g._autoSelectParent)){var b=g.getTopmostSelectedNodes(f._body);
d=d.concat(b);
}}}return d;
};
Jui.option.Tree.prototype.getCurrentId=function(){return this._current==null?null:this._current._json.id;
};
Jui.option.Tree.prototype.setCurrentId=function(a){this._setCurrentNode(this._map[a]);
};
Jui.option.Tree.prototype.getCurrentNode=function(){return this._current==null?null:this._getNodeInfo(this._current);
};
Jui.option.Tree.prototype.getData=function(b){var a=function(d,c,e){for(var g=0;
g<c.children.length;
++g){var h=c.children[g];
var f=d._getNodeInfo(h);
e.push(f);
if(h._body!=null){if(b){a(d,h._body,e);
}else{f.children=a(d,h._body,[]);
}}}return e;
};
return a(this,this.element.firstChild,[]);
};
Jui.option.Tree.prototype.remove=function(a){var c=Jui.array.make(a);
for(var b=0;
b<c.length;
++b){var d=this._map[c[b]];
if(d!=null){this._remove(d);
}}if(this._multiSelect){this._autoSelectParentChecks(this.element.firstChild);
}};
Jui.option.Tree.prototype.update=function(a,b){var j=this;
var h=Jui.array.make(a);
var k=false;
if(b==null){b={add:true,remove:true,move:true};
}for(var d=0;
d<h.length;
++d){var l=h[d];
var c=j._map[l.id];
var f=j._map[l.parentId];
if(f!=null&&!f._isBranch){j._setBranch(f);
}var g=l.parentId==null?j.element.firstChild:f&&f._body;
if(c==null){if(g!=null&&b.add){var e=j._getNodeHtml(l,[],false,true).join("");
Jui.dom.insertHtml(g,"BeforeEnd",e);
c=g.lastChild;
j._initNode(c,l);
j._refreshNodesLine([c,c.previousSibling]);
k=true;
}}else{if(g==null){if(b.remove){j._remove(c);
k=true;
}}else{if("parentId" in l&&c.parentElement!=g&&b.move){j._detachNode(c);
Jui.dom.insertElement(g,"BeforeEnd",c);
j._refreshNodesLine([c,c.previousSibling]);
k=true;
}j._updateNode(c,l);
}}}if(j._multiSelect&&k){j._autoSelectParentChecks(this.element.firstChild);
}};
Jui.option.Tree.doCheckBoxClick=function(){var b=Jui.dom.getAncestorByClassName("JuiTreeNode");
var a=Jui.$owner(b);
if(!a._isDisabled(b)){a._setChecked(b,a._isEmpty(b));
a._syncChildChecks(b);
a._syncParentChecks(b);
}};
Jui.option.Tree.doFlagClick=function(){var a=Jui.dom.getAncestorByClassName("JuiTreeNode");
if(/Closed/.test(a._flag.className)){Jui.$owner(a)._expand(a);
}else{if(/Opened/.test(a._flag.className)){a._flag.className="JuiTreeClosedFlag";
a._body.style.display="none";
}}};
Jui.option.Tree.doTextClick=function(){var c=Jui.dom.getAncestorByClassName("JuiTreeNode");
var b=Jui.$owner(c);
if(!b._isDisabled(c)){b._setCurrentNode(c);
if(c._flag.className=="JuiTreeClosedFlag"){b._expand(c);
}var a={json:b._getNodeInfo(c)};
if(!c._isBranch){b.fireEvent("onleafclick",Jui.util.clone(a));
}b.fireEvent("onnodeclick",a);
}};
Jui.option.Tree._LINE_TYPES=["HorzLine","UpLLine","DownLLine","TLine","HorzLineHorrow","UpLLineHorrow","DownLLineHorrow","TLineHorrow"];
Jui.option.Tree.prototype._getHtml=function(c,a,h,f){var d=h?"":"JuiTreeNodeBody";
if(!f){d+=(h?"":" ")+"JuiTreeNodeBodyWithLine";
}a.push("<div class='"+d+"'>");
for(var b=0;
b<c.length;
++b){var e=c[b];
var g=h&&b==0;
var f=b==c.length-1;
this._getNodeHtml(e,a,g,f);
}a.push("</div>");
return a;
};
Jui.option.Tree.prototype._getNodeHtml=function(e,a,g,f){var c=(e.children!=null&&e.children.length>0)||e.isBranch;
var d=(g?0:1)|(f?0:2)|(c?4:0);
a.push("<div class=JuiTreeNode>");
a.push("<div class='JuiTreeNodeHead JuiCheckParent'"+(e.disabled?" disabled":"")+">");
a.push("<div class='JuiTreeFlagCell JuiTree"+Jui.option.Tree._LINE_TYPES[d]+"'>");
a.push("<div class=JuiTree"+(c?"ClosedFlag":"LeafFlag")+"></div></div>");
if(this._multiSelect){a.push("<div class=JuiTreeCheckCell>");
a.push("<div class=JuiCheck tabindex=0"+(e.checked?" checked=full":"")+"></div>");
a.push("</div>");
}a.push("<div class='JuiTreeTextCell");
if(this._hasIcon){var b=e.iconType=="item"||(!this._sameIcon&&!c);
a.push(b?" JuiTreeLeafIcon":" JuiTreeBranchIcon");
if(e.icon!=null){a.push("' style='background-image:url("+e.icon+")");
}}a.push("'><div>");
a.push(e.html||Jui.$h(e.text));
a.push("</div></div>");
a.push("</div>");
if(e.children!=null&&e.children.length>0){this._getHtml(e.children,a,false,f);
}a.push("</div>");
return a;
};
Jui.option.Tree.prototype._initNodeBody=function(a,d){for(var c=0,b=a.children;
c<b.length;
++c){this._initNode(b[c],d[c]);
if(b[c].children.length>1){this._initNodeBody(b[c].lastChild,d[c].children);
}}};
Jui.option.Tree.prototype._initNode=function(c,b){var a=c.firstChild.children;
c._head=c.firstChild;
c._body=c.children.length==1?null:c.lastChild;
c._flagCell=a[0];
c._flag=a[0].firstChild;
c._check=this._multiSelect?a[1].firstChild:null;
c._textCell=a[a.length-1];
c._text=c._textCell.firstChild;
c._isBranch=!/Leaf/.test(c._flag.className);
c._json=Jui.object.remove(Jui.util.clone(b),"children");
c._flag.onclick=Jui.option.Tree.doFlagClick;
c._textCell.onclick=Jui.option.Tree.doTextClick;
if(c._check){c._check.onclick=Jui.option.Tree.doCheckBoxClick;
}this._map[b.id]=c;
};
Jui.option.Tree.prototype._autoSelectChildChecks=function(a,b){var e=this;
if(a!=null){for(var c=0;
c<a.children.length;
++c){var d=a.children[c];
if(b){e._setChecked(d,true);
}e._autoSelectChildChecks(d._body,e._isChecked(d));
}}};
Jui.option.Tree.prototype._autoSelectParentChecks=function(a){var f=this;
var d=0;
if(a!=null){for(var c=0;
c<a.children.length;
++c){var e=a.children[c];
var b=e._body==null?0:e._body.children.length;
if(b>0){var g=f._autoSelectParentChecks(e._body);
f._setStatusByChildWeight(e,g);
}d+=f._getStatusWeight(e);
}}return d;
};
Jui.option.Tree.prototype._syncChildChecks=function(e){var d=this;
if(e._body!=null){var c=d._isChecked(e);
for(var b=0;
b<e._body.children.length;
++b){var a=e._body.children[b];
d._setChecked(a,c);
d._syncChildChecks(a);
}}};
Jui.option.Tree.prototype._syncParentChecks=function(g){var f=this;
var a=Jui.dom.getAncestorByClassName("JuiTreeNode",g.parentElement);
if(a!=null){var d=0;
var b=a._body.children.length;
for(var c=0;
c<b;
++c){var e=a._body.children[c];
d+=f._getStatusWeight(e);
}f._setStatusByChildWeight(a,d);
f._syncParentChecks(a);
}};
Jui.option.Tree.prototype._isEmpty=function(b){var a=b._check.getAttribute("checked");
return a!="full"&&a!="part";
};
Jui.option.Tree.prototype._setEmpty=function(a){a._check.removeAttribute("checked");
};
Jui.option.Tree.prototype._isChecked=function(a){return a._check.getAttribute("checked")=="full";
};
Jui.option.Tree.prototype._setChecked=function(b,a){b._check.setAttribute("checked",a!=false?"full":null);
};
Jui.option.Tree.prototype._isPartial=function(a){return a._check.getAttribute("checked")=="part";
};
Jui.option.Tree.prototype._setPartial=function(b,a){b._check.setAttribute("checked",a!=false?"part":null);
};
Jui.option.Tree.prototype._getStatusWeight=function(a){if(this._isEmpty(a)){return 0;
}else{if(this._isChecked(a)){return 1;
}else{return 0.5;
}}};
Jui.option.Tree.prototype._setStatusByChildWeight=function(b,c){var a=this;
if(a._isEmpty(b)&&c>0){a._setPartial(b);
}else{if(a._isPartial(b)&&c==0){a._setEmpty(b);
}}};
Jui.option.Tree.prototype._isDisabled=function(a){return a._head.hasAttribute("disabled");
};
Jui.option.Tree.prototype._setDisabled=function(b,a){Jui.dom.tagAttribute(b._head,"disabled",disabled);
};
Jui.option.Tree.prototype._expand=function(a){if(a._body==null){this._loadChildNodes(a);
}else{a._flag.className="JuiTreeOpenedFlag";
a._body.style.display="block";
}};
Jui.option.Tree.prototype._expandLevelRecurse=function(a,f){for(var c=0,b=a.children;
c<b.length;
++c){var d=b[c];
if(/Closed/.test(d._flag.className)&&d._body!=null){this._expand(d);
if(f>1){this._expandLevelRecurse(d._body,f-1);
}}}};
Jui.option.Tree.prototype._loadChildNodes=function(b){var a=this;
a.fireEvent("onloadsubnodes",{id:b._json.id},function(c){if(c==null||c.length==0){a._setLeaf(b);
}else{a._setBranch(b,c);
a._expand(b);
}});
};
Jui.option.Tree.prototype._setCurrentNode=function(c){var b=this;
if(b._current!=null){b._current._text.className="";
}if(c!=null){c._text.className="JuiTreeCurrentText";
var a=Jui.dom.getAncestorByClassName("JuiTreeNode",c.parentElement);
while(a!=null){b._expand(a);
a=Jui.dom.getAncestorByClassName("JuiTreeNode",a.parentElement);
}Jui.dom.scrollToVisible(c._head);
}b._current=c;
};
Jui.option.Tree.prototype._getNodeInfo=function(a){return Jui.object.merge({isBranch:a._isBranch},a._json);
};
Jui.option.Tree.prototype._remove=function(c){this._detachNode(c);
for(var b=0,a=[c].concat(this._getDescendants(c));
b<a.length;
++b){if(a[b]==this._current){this._setCurrentNode(null);
}delete this._map[a[b]._json.id];
}};
Jui.option.Tree.prototype._detachNode=function(e){var d=e.parentElement==this.element.firstChild;
var b=d?null:e.parentElement.parentElement;
var c=e.previousSibling;
var a=e.nextSibling;
Jui.dom.removeElement(e);
if(b!=null&&c==null&&a==null){this._setLeaf(b);
}this._refreshNodesLine([b,c,a]);
};
Jui.option.Tree.prototype._getDescendants=function(e,f){var c=f||[];
var a=e==null?this.element.firstChild:e._body;
if(a!=null){for(var d=0,b=a.children;
d<b.length;
++d){c.push(b[d]);
this._getDescendants(b[d],c);
}}return c;
};
Jui.option.Tree.prototype._updateNode=function(b,a){if("html" in a){b._text.innerHTML=a.html;
}else{if("text" in a){Jui.dom.setInnerText(b._text,a.text);
}}if(this._hasIcon&&"icon" in a){b._textCell.style.backgroundImage="url("+a.icon+")";
}};
Jui.option.Tree.prototype._setLeaf=function(a){a._isBranch=false;
a._flagCell.className=a._flagCell.className.replace(/Horrow/,"");
a._flag.className="";
if(a._body!=null){a.removeChild(a._body);
a._body=null;
}};
Jui.option.Tree.prototype._setBranch=function(c,b){c._isBranch=true;
c._flagCell.className=c._flagCell.className.replace(/Horrow/,"")+"Horrow";
c._flag.className="JuiTreeClosedFlag";
b=b||[];
var d=c.nextSibling==null;
var a=this._getHtml(b,[],false,d).join("");
Jui.dom.insertHtml(c,"BeforeEnd",a);
c._body=c.lastChild;
this._initNodeBody(c._body,b);
};
Jui.option.Tree.prototype._refreshNodesLine=function(a){for(var c=0;
c<a.length;
++c){var d=a[c];
if(d!=null){var f=d.parentElement==this.element.firstChild&&d.previousSibling==null;
var e=d.nextSibling==null;
var b=(f?0:1)|(e?0:2)|(d._isBranch?4:0);
d._flagCell.className="JuiTreeFlagCell JuiTree"+Jui.option.Tree._LINE_TYPES[b];
if(d._body!=null){d._body.className=e?"JuiTreeNodeBody":"JuiTreeNodeBody JuiTreeNodeBodyWithLine";
}}}};
