-----lei.lei User-------------
alter table TsUser add FExtension varchar(10);
alter table TsUser add FPicture uuid;
insert into TsField set FId='f194d44e-8141-4b86-8c55-22b98956be02', FUnitId='00000000-0000-0000-0001-000000001002', FName='FExtension',    FTitle='分機號碼', FType='InputBox-Phone',      FSize=10,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValueType=null,          FDefaultValue=null, FHint='',   FAlwaysBringDataToClient=0, FValidation=null, FMobileListFormat=null, FFollowingField=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='86f98974-7fcc-4372-83cc-a8a755323e3b', FUnitId='00000000-0000-0000-0001-000000001002', FName='FPicture',      FTitle='圖片',     FType='PictureBox',          FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=0, FDictionaryId=null,                                   FEntityUnitId='b785eab6-c1fb-458c-a67a-ea8ba0484a11', FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=3, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValueType=null,          FDefaultValue=null, FHint='',   FAlwaysBringDataToClient=0, FValidation=null, FMobileListFormat=null, FFollowingField=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='e7b1d661-1e77-4f44-82ad-6b099740e1b6', FUnitId='00000000-0000-0000-0001-000000001002', FName='FSqlBirthday',  FTitle='生日(月-日)', FType='InputBox-Text',       FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=1, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='sql',   FJoinField=null, FSourceField=null, FSource='select substr(char(FBirthday,1),6,5) from TsUser as user where user.FId=TsUser.FId', FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValueType=null,          FDefaultValue=null, FHint='',   FAlwaysBringDataToClient=0, FValidation=null, FMobileListFormat=null, FFollowingField=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';

java insertFormField('320ab079-f260-4e81-b545-15c08fe1d955', 'FSqlBirthday', 'after FBirthday');
java insertFormField('320ab079-f260-4e81-b545-15c08fe1d955', 'FExtension', 'after FDuty');
java insertFormField('320ab079-f260-4e81-b545-15c08fe1d955', 'FPicture', 'after FExtension');


