--minglei

java runOnError('select FShowTotalCount from TsHomepageItem', 'alter table TsHomepageItem add FShowTotalCount bit');
java runOnError('select FPageId from TsHomepageItem', 'alter table TsHomepageItem add FPageId uuid');

--Qs.SpecialPath----------------------------------------------------------------

create table TsSpecialPath
(
	FId uuid primary key,
	FPath varchar(100),
	FMatchMode varchar(20),
	FKey varchar(50),
	FValue varchar(100),
	FIndex int
);

insert into TsUnit set FId='178ae474-ffb1-41ed-a470-6521e8b03a7a', FCode='Qs.SpecialPath', FName='特殊路徑', FIcon='quicksilver/image/unit/SpecialPath.png', FBigIcon=null, FEditId='541c707d-79dd-4dbb-85fc-1a214fd5fce4', FModuleId='00000000-0000-0000-0008-990000000020', FOpenMode='System', FIsTreeStructure=0, FMaxTreeLevel=null, FIsSlaveUnit=0, FMasterUnitId=null, FSupportWorkflow=0, FSupportUser=0, FSupportDepartment=0, FSupportEditType=0, FSupportAttachment=0, FSupportDataPrivilege=0, FSupportVersion=0, FSupportBusinessLog=0, FSupportNote=0, FSupportSort=1, FSupportPrivilegeField=0, FIsFullTextSearch=0, FSearchAttachment=0, FSupportEqualQuery=0, FUseSystemI18nTable=0, FExtraQueryResultLimit=0, FRecordCreateInfo=0, FRecordUpdateInfo=0, FRecordDeleteInfo=0, FViewPageConditionForList=null, FViewPageConditionForLink=null, FDataSource='default', FTable='TsSpecialPath', FKeyField='FId', FKeyType='Uuid', FNameField='FPath', FMasterField=null, FHomeClassName='com.jeedsoft.quicksilver.page.SpecialPathHome', FDaoClassName='com.jeedsoft.quicksilver.page.dao.impl.SpecialPathDaoImpl', FServiceClassName='com.jeedsoft.quicksilver.page.service.impl.SpecialPathServiceImpl', FActionClassName='com.jeedsoft.quicksilver.page.action.impl.SpecialPathActionImpl', FWebServiceUniqueField=null, FUnitFilterSql='', FBusinessFilterSql='', FDescription='';

insert into TsField set FId='204bba8e-134c-4792-9b70-729987550f27', FUnitId='178ae474-ffb1-41ed-a470-6521e8b03a7a', FName='FId',        FTitle='ID',       FType='InputBox-Key',        FSize=null, FVisible=0, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=0, FDictionaryId=null,                                   FEntityUnitId='178ae474-ffb1-41ed-a470-6521e8b03a7a', FSupportLocalText=null, FSupportI18n=null, FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=null, FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValueType=null, FDefaultValue=null, FHint=null, FAlwaysBringDataToClient=0, FValidation=null, FMobileListFormat=null, FFollowingField=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData=null;
insert into TsField set FId='016c37c5-2e76-44ae-9a23-85c59a31beb0', FUnitId='178ae474-ffb1-41ed-a470-6521e8b03a7a', FName='FIndex',     FTitle='順序',     FType='InputBox-Integer',    FSize=null, FVisible=0, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=0, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=null, FSupportI18n=null, FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=null, FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValueType=null, FDefaultValue=null, FHint=null, FAlwaysBringDataToClient=0, FValidation=null, FMobileListFormat=null, FFollowingField=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData=null;
insert into TsField set FId='2e9d4081-1b24-471d-89d9-f344e19f6d9f', FUnitId='178ae474-ffb1-41ed-a470-6521e8b03a7a', FName='FKey',       FTitle='鍵',       FType='InputBox-Text',       FSize=50,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValueType=null, FDefaultValue=null, FHint='',   FAlwaysBringDataToClient=0, FValidation=null, FMobileListFormat=null, FFollowingField=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='08660f7a-fbd2-4e66-b7d5-8789ec0d5302', FUnitId='178ae474-ffb1-41ed-a470-6521e8b03a7a', FName='FMatchMode', FTitle='匹配方式', FType='ComboBox-SelectOnly', FSize=20,   FVisible=1, FFilterByRole=0, FRequired=1, FReadOnly=0, FQueryable=1, FDictionaryId='126ccc09-61b3-45f3-b7c1-5ec349c5f3ee', FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValueType=null, FDefaultValue=null, FHint='',   FAlwaysBringDataToClient=0, FValidation=null, FMobileListFormat=null, FFollowingField=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='b7664f01-0f11-4ac2-9624-bdb92983ed28', FUnitId='178ae474-ffb1-41ed-a470-6521e8b03a7a', FName='FPath',      FTitle='路徑',     FType='InputBox-Text',       FSize=100,  FVisible=1, FFilterByRole=0, FRequired=1, FReadOnly=0, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValueType=null, FDefaultValue=null, FHint='',   FAlwaysBringDataToClient=0, FValidation=null, FMobileListFormat=null, FFollowingField=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='727b606c-a07b-424f-bfd0-b0006b039c9a', FUnitId='178ae474-ffb1-41ed-a470-6521e8b03a7a', FName='FValue',     FTitle='值',       FType='InputBox-Text',       FSize=100,  FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValueType=null, FDefaultValue=null, FHint='',   FAlwaysBringDataToClient=0, FValidation=null, FMobileListFormat=null, FFollowingField=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';

java setOrderFields('178ae474-ffb1-41ed-a470-6521e8b03a7a', 'FIndex', '0');
java setQueryFormFields('178ae474-ffb1-41ed-a470-6521e8b03a7a', 'FMatchMode,FPath,FKey,FValue');

insert into TsPage set FId='e6b5c06b-38b4-4e94-ba18-64dc01eddc9f', FName='特殊路徑設置',		FTitle='特殊路徑設置', FCode='Qs.SpecialPath.Config',     FEditId=null,                                   FPlatform='Computer', FType='Other',		FIcon='quicksilver/image/unit/SpecialPath.png', FUrl='quicksilver/page/page/SpecialPathConfig.jsp',	FActionMethodName='Qs.SpecialPath.prepareConfig',	FLoadHandler=null, FRelationId=null, FUnitId='178ae474-ffb1-41ed-a470-6521e8b03a7a', FMasterUnitId=null,                                   FIsSlavePage=0, FIndex=null, FFormColumnCount=null, FDialogWidth=null, FDialogHeight=null, FDialogMaximized=null, FQueryFormAutoQuery=1, FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription=null;
insert into TsPage set FId='f6cbaa71-0570-4e37-9d06-f15f42d10874', FName='特殊路徑主清單',		FTitle='特殊路徑清單', FCode='Qs.SpecialPath.List',       FEditId=null,                                   FPlatform='Computer', FType='EntityList', FIcon='quicksilver/image/unit/SpecialPath.png', FUrl='quicksilver/page/template/EntityList.jsp',	FActionMethodName='Qs.SpecialPath.prepareList',		FLoadHandler=null, FRelationId=null, FUnitId='178ae474-ffb1-41ed-a470-6521e8b03a7a', FMasterUnitId=null,                                   FIsSlavePage=0, FIndex=null, FFormColumnCount=null, FDialogWidth=null, FDialogHeight=null, FDialogMaximized=null, FQueryFormAutoQuery=1, FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription=null;
insert into TsPage set FId='c0245a5b-1c68-4f6f-9081-f4c8a33c5b69', FName='特殊路徑選擇清單',	FTitle='特殊路徑清單', FCode='Qs.SpecialPath.SelectList', FEditId=null,                                   FPlatform='Computer', FType='EntityList', FIcon='quicksilver/image/unit/SpecialPath.png', FUrl='quicksilver/page/template/EntityList.jsp',	FActionMethodName='Qs.SpecialPath.prepareList',		FLoadHandler=null, FRelationId=null, FUnitId='178ae474-ffb1-41ed-a470-6521e8b03a7a', FMasterUnitId=null,                                   FIsSlavePage=0, FIndex=null, FFormColumnCount=null, FDialogWidth=null, FDialogHeight=null, FDialogMaximized=null, FQueryFormAutoQuery=1, FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription=null;
insert into TsPage set FId='d76771d2-ca4c-4632-baae-1ade1a9b513a', FName='特殊路徑排序',		FTitle='排序',         FCode='Qs.SpecialPath.Sort',       FEditId='4e9b96a5-4c20-42a0-8929-d83efc27af4e', FPlatform='Computer', FType='Sort',       FIcon='quicksilver/image/unit/SpecialPath.png', FUrl='quicksilver/page/template/Sorter.jsp',		FActionMethodName='Qs.SpecialPath.prepareSort',		FLoadHandler=null, FRelationId=null, FUnitId='178ae474-ffb1-41ed-a470-6521e8b03a7a', FMasterUnitId=null,                                   FIsSlavePage=0, FIndex=null, FFormColumnCount=null, FDialogWidth=null, FDialogHeight=null, FDialogMaximized=null, FQueryFormAutoQuery=1, FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription=null;
insert into TsPage set FId='1ea48f3b-13b0-40b7-a85f-6ab460aec977', FName='特殊路徑表單',		FTitle='表單',         FCode='Qs.SpecialPath.Form',       FEditId=null,                                   FPlatform='Computer', FType='EntityForm', FIcon='quicksilver/image/unit/Form.png',        FUrl='quicksilver/page/template/EntityForm.jsp',	FActionMethodName='Qs.SpecialPath.prepareForm',		FLoadHandler=null, FRelationId=null, FUnitId='178ae474-ffb1-41ed-a470-6521e8b03a7a', FMasterUnitId='178ae474-ffb1-41ed-a470-6521e8b03a7a', FIsSlavePage=1, FIndex=1,    FFormColumnCount=null, FDialogWidth=null, FDialogHeight=500,  FDialogMaximized=null, FQueryFormAutoQuery=1, FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription=null;

--特殊路徑設置
insert into TsToolItem set FId='85977722-0129-4a30-b3ea-42fa0e07a2b9', FPageId='e6b5c06b-38b4-4e94-ba18-64dc01eddc9f', FCode='Save',       FName='保存', FHint=null, FLabel=null, FType='Button', FAlign='right', FIndex=1, FWidth=0, FIcon='quicksilver/image/16/Save.png',       FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='SpecialPathConfig.doSave';

--特殊路徑主清單
insert into TsToolItem set FId='a577922c-4dca-45dd-806c-1b26211ddc3b', FPageId='f6cbaa71-0570-4e37-9d06-f15f42d10874', FCode='Add',     FName='新增', FHint='新增一筆記錄',                                         FLabel=null, FType='Button',      FAlign='right', FIndex=1, FWidth=0, FIcon='quicksilver/image/16/Add.png',     FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doAdd';
insert into TsToolItem set FId='ae8af37d-a3d0-4810-834f-5c0345b68343', FPageId='f6cbaa71-0570-4e37-9d06-f15f42d10874', FCode='Open',    FName='打開', FHint='打開當前選中的記錄。如果選中了多筆，第一筆將被打開。', FLabel=null, FType='Button',      FAlign='right', FIndex=2, FWidth=0, FIcon='quicksilver/image/16/Open.png',    FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doOpen';
insert into TsToolItem set FId='eea1f1d4-400b-4f58-b0f9-3bc0131c8ae5', FPageId='f6cbaa71-0570-4e37-9d06-f15f42d10874', FCode='Delete',  FName='刪除', FHint='刪除當前選中的記錄',                                   FLabel=null, FType='Button',      FAlign='right', FIndex=3, FWidth=0, FIcon='quicksilver/image/16/Delete.png',  FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doDelete';
insert into TsToolItem set FId='9817f3df-e118-4239-8e8b-a5602c8ae356', FPageId='f6cbaa71-0570-4e37-9d06-f15f42d10874', FCode='Refresh', FName='刷新', FHint='刷新清單內容',                                         FLabel=null, FType='Button',      FAlign='right', FIndex=4, FWidth=0, FIcon='quicksilver/image/16/Refresh.png', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doRefresh';
insert into TsToolItem set FId='b477621b-3376-4980-a54a-7bd94c069c4b', FPageId='f6cbaa71-0570-4e37-9d06-f15f42d10874', FCode='Other',   FName=null,   FHint=null,                                                   FLabel=null, FType='ComboButton', FAlign='right', FIndex=5, FWidth=0, FIcon='quicksilver/image/16/Other.png',   FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource='SubItemTable', FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='None',       FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler=null;
insert into TsToolSubItem set FId='9d8ea49a-0362-4004-8aa2-84d5a58b63a2', FToolItemId='b477621b-3376-4980-a54a-7bd94c069c4b', FCode='Sort',        FName='排序',       FExpandMode='None', FIndex=1, FIcon='quicksilver/image/16/Sort.png',   FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FEventHandler='EntityList.doSort';

--特殊路徑選擇清單
insert into TsToolItem set FId='5ea56b2c-f2cf-496c-95b2-afbb78ac4160', FPageId='c0245a5b-1c68-4f6f-9081-f4c8a33c5b69', FCode='ConfirmSelection', FName='確定', FHint=null,                                                   FLabel=null, FType='Button', FAlign='right', FIndex=1, FWidth=0, FIcon='quicksilver/image/16/Ok.png',   FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doSelectListConfirm';
insert into TsToolItem set FId='511acd52-fbdc-4a9c-af4e-f94e4a30a00c', FPageId='c0245a5b-1c68-4f6f-9081-f4c8a33c5b69', FCode='Add',              FName='新增', FHint='新增一筆記錄',                                         FLabel=null, FType='Button', FAlign='right', FIndex=2, FWidth=0, FIcon='quicksilver/image/16/Add.png',  FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doAdd';
insert into TsToolItem set FId='de36f481-6add-4475-86ff-44351a0b4740', FPageId='c0245a5b-1c68-4f6f-9081-f4c8a33c5b69', FCode='Open',             FName='打開', FHint='打開當前選中的記錄。如果選中了多筆，第一筆將被打開。', FLabel=null, FType='Button', FAlign='right', FIndex=3, FWidth=0, FIcon='quicksilver/image/16/Open.png', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doOpen';

--特殊路徑排序
insert into TsToolItem set FId='0c3bb96b-7d9e-4d84-90ab-7de022a4732f', FPageId='d76771d2-ca4c-4632-baae-1ade1a9b513a', FCode='MoveUp',     FName='上升', FHint=null, FLabel=null, FType='Button', FAlign='left',  FIndex=1, FWidth=0, FIcon='quicksilver/image/16/MoveUp.png',     FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='Sorter.doMoveUp';
insert into TsToolItem set FId='b267c2be-a3ca-48a3-aa4b-2e64ecb5f00c', FPageId='d76771d2-ca4c-4632-baae-1ade1a9b513a', FCode='MoveDown',   FName='下降', FHint=null, FLabel=null, FType='Button', FAlign='left',  FIndex=2, FWidth=0, FIcon='quicksilver/image/16/MoveDown.png',   FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='Sorter.doMoveDown';
insert into TsToolItem set FId='6ecf7f97-cd33-444c-aa41-c5df9d336cc6', FPageId='d76771d2-ca4c-4632-baae-1ade1a9b513a', FCode='MoveTop',    FName='置頂', FHint=null, FLabel=null, FType='Button', FAlign='left',  FIndex=3, FWidth=0, FIcon='quicksilver/image/16/MoveTop.png',    FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='Sorter.doMoveTop';
insert into TsToolItem set FId='cbec4d22-293b-4610-9ae0-42a794b4b548', FPageId='d76771d2-ca4c-4632-baae-1ade1a9b513a', FCode='MoveBottom', FName='置底', FHint=null, FLabel=null, FType='Button', FAlign='left',  FIndex=4, FWidth=0, FIcon='quicksilver/image/16/MoveBottom.png', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='Sorter.doMoveBottom';
insert into TsToolItem set FId='ed1af39d-7ccf-4cf4-8b34-5b3fd9b6df13', FPageId='d76771d2-ca4c-4632-baae-1ade1a9b513a', FCode='Save',       FName='保存', FHint=null, FLabel=null, FType='Button', FAlign='right', FIndex=1, FWidth=0, FIcon='quicksilver/image/16/Save.png',       FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='Sorter.doSave';

--特殊路徑表單
insert into TsToolItem set FId='88039ac6-f257-45f6-9a8f-ad0dd4a55c15', FPageId='1ea48f3b-13b0-40b7-a85f-6ab460aec977', FCode='Save',  FName='保存', FHint=null, FLabel=null, FType='Button',      FAlign='right', FIndex=1, FWidth=0, FIcon='quicksilver/image/16/Save.png',  FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='EntityForm.doSave';

insert into TsForm set FDefault=1, FEditableCondition=null, FGroupMode='Double', FId='bcb34f36-6149-4c1c-9e96-9918b0b19ddd', FIndex=1, FName='默認', FPageId=null, FUnitId='178ae474-ffb1-41ed-a470-6521e8b03a7a';
java setFormFields('bcb34f36-6149-4c1c-9e96-9918b0b19ddd', 'FMatchMode,FPath,FKey,FValue');

insert into TsList set FDefault=1, FId='4fb41bfc-9c4d-44a5-94a8-46d80fe37016', FIndex=null, FMultiPage=1, FName='特殊路徑清單',     FPageId=null,                                   FUnitId='178ae474-ffb1-41ed-a470-6521e8b03a7a';
insert into TsList set FDefault=0, FId='ab9f750a-9eed-4de1-b902-d2bfeccd4497', FIndex=null, FMultiPage=1, FName='特殊路徑選擇清單', FPageId='c0245a5b-1c68-4f6f-9081-f4c8a33c5b69', FUnitId='178ae474-ffb1-41ed-a470-6521e8b03a7a';
insert into TsList set FDefault=0, FId='a6bbc532-7c5e-481d-8549-e09e48217238', FIndex=null, FMultiPage=1, FName='特殊路徑首頁清單', FPageId='9b796431-f132-49d1-b306-5d1d618f9c1b', FUnitId='178ae474-ffb1-41ed-a470-6521e8b03a7a';
java setListFields('4fb41bfc-9c4d-44a5-94a8-46d80fe37016', 'FPath,FMatchMode,FKey,FValue');
java setListFields('ab9f750a-9eed-4de1-b902-d2bfeccd4497', 'FPath,FMatchMode,FKey,FValue');
java setListFields('a6bbc532-7c5e-481d-8549-e09e48217238', 'FPath,FMatchMode,FKey,FValue');

insert into TsPrivilege set FId='a419d698-11e6-4700-9bec-1d7cd15e56b8', FName='特殊路徑查看', FUnitId='178ae474-ffb1-41ed-a470-6521e8b03a7a', FModuleId='00000000-0000-0000-0008-990000000020', FPrivilegeTypeId='00000000-0000-0000-1005-000000000002', FUseExisting=0, FSourcePrivilegeId=null, FEditId='5992c3d2-0b4a-478c-bbfa-2089819ad575', FIndex=null;
insert into TsPrivilege set FId='648b8570-81ee-4db6-85cd-cb77e7b1256b', FName='特殊路徑管理', FUnitId='178ae474-ffb1-41ed-a470-6521e8b03a7a', FModuleId='00000000-0000-0000-0008-990000000020', FPrivilegeTypeId='00000000-0000-0000-1005-000000000006', FUseExisting=0, FSourcePrivilegeId=null, FEditId='5992c3d2-0b4a-478c-bbfa-2089819ad575', FIndex=null;

insert into TsQuerySchema set FId='60781c26-9392-4056-8344-7b0a74be6351', FUnitId='178ae474-ffb1-41ed-a470-6521e8b03a7a', FName='全部特殊路徑',     FType='condition',  FPublic=1, FVisible=1, FTemp=0, FGlobalAutoQuery=0, FShare=0, FUserId=null, FConditionId=null, FSqlSource='None', FSql=null, FIndex=1, FUpdateTime=null, FOriginSchemaId=null, FParentId=null;
insert into TsQuerySchema set FId='1a4892ce-d22e-4358-a185-c7dc71256a47', FUnitId='178ae474-ffb1-41ed-a470-6521e8b03a7a', FName='特殊路徑我的最愛', FType='collection', FPublic=1, FVisible=1, FTemp=0, FGlobalAutoQuery=0, FShare=0, FUserId=null, FConditionId=null, FSqlSource='None', FSql=null, FIndex=3, FUpdateTime=null, FOriginSchemaId=null, FParentId=null;

update TsMenu set FIndex = FIndex + 1 where FParentId='195d73e7-b66f-4b14-9da9-55ff3b3d570a' and FIndex >= 2;
insert into TsMenu set	FId='e35f13d6-5165-4f70-90ec-10a3e7e28ede', FParentId='195d73e7-b66f-4b14-9da9-55ff3b3d570a',	FIndex=2,	FName='特殊路徑設置',	FPageId='e6b5c06b-38b4-4e94-ba18-64dc01eddc9f', FEnabled=1,	FSubMenuSource='MenuTable', FIcon='quicksilver/image/unit/SpecialPath.png', FType='InternalPage', FTabTitleSource='PageTitle';

insert into TsDictionary set FId='126ccc09-61b3-45f3-b7c1-5ec349c5f3ee', FName='QS-特殊路徑-匹配方式', FBuiltin=1, FParentId=null, FTextAsValue=0;
insert into TsDictionaryItem set FDictionaryId='126ccc09-61b3-45f3-b7c1-5ec349c5f3ee', FEnabled=1, FId='51e0256d-90c8-4f52-8b8e-ff77d2688834', FIndex=1, FParentValue=null, FText='純文字',			FValue='PlainText';
insert into TsDictionaryItem set FDictionaryId='126ccc09-61b3-45f3-b7c1-5ec349c5f3ee', FEnabled=1, FId='aa5dfbcb-4888-42f3-80b7-a0d791c28908', FIndex=2, FParentValue=null, FText='萬用字元運算式', FValue='WildcardExpression';
insert into TsDictionaryItem set FDictionaryId='126ccc09-61b3-45f3-b7c1-5ec349c5f3ee', FEnabled=1, FId='fbaf4fb3-d5e4-4ce5-a026-51b31efe7853', FIndex=3, FParentValue=null, FText='規則運算式',		FValue='RegularExpression';

insert into TsTextResource set FId='e3e2f4da-d406-4209-bf4d-17818255f291', FCode='T.Qs.SpecialPath.AllowOrigin',						FValue='允許的調用者';
insert into TsTextResource set FId='db836fd4-6351-4e3f-9de4-815caa70a16a', FCode='T.Qs.SpecialPath.BypassSession',						FValue='允許未登錄調用';
insert into TsTextResource set FId='5055e2fa-6b8e-4a22-9dc4-c82094860df8', FCode='T.Qs.SpecialPath.CrossOriginResourceSharing',			FValue='跨來源資源分享';
insert into TsTextResource set FId='f44af956-0302-4c13-a91f-8db3d11ad0bb', FCode='T.Qs.SpecialPath.JspAccessControl',					FValue='JSP 存取控制';
insert into TsTextResource set FId='5059cf72-9ca1-4e4a-8369-bd88240d9a97', FCode='T.Qs.SpecialPath.JspDirectlyAccessible',				FValue='允許直接訪問';
insert into TsTextResource set FId='d3816ca5-9f14-48e8-87f5-eaa07b92f482', FCode='T.Qs.SpecialPath.VirtualDirectory',					FValue='虛擬路徑';
insert into TsTextResource set FId='7a45dc2d-7b5a-4faa-8c7f-406eecaf4bdf', FCode='T.Qs.SpecialPath.SessionControl',						FValue='會話控制';

insert into TsTextResource set FId='b48d83fc-e667-4711-af59-bc5e510e2171', FCode='E.Qs.SpecialPath.InvalidRegularExpression',			FValue='無效的規則運算式：${0}';

insert into TsSpecialPath (FId, FMatchMode, FPath, FKey, FValue)
select uuid(), 'WildcardExpression', '*/' || FPath, 'JspDirectlyAccessible', '1'
from TsSpecialPage where FJspDirectlyAccessible = 1;

insert into TsSpecialPath (FId, FMatchMode, FPath, FKey, FValue)
select uuid(), 'PlainText', '*/' || FPath, 'BypassSession', '1'
from TsSpecialPage where FBypassSession = 1 and FPath not like '%.jsp';

insert into TsSpecialPath (FId, FMatchMode, FPath, FKey, FValue)
select uuid(), 'WildcardExpression', '*/' || FPath, 'BypassSession', '1'
from TsSpecialPage where FBypassSession = 1 and FPath like '%.jsp';

delete from TsSpecialPath where lower(FPath) = lower('*/FileUpload.jsp');
delete from TsSpecialPath where lower(FPath) = lower('*/Qs.Misc.ActionError.page');          
delete from TsSpecialPath where lower(FPath) = lower('*/Qs.Misc.BrowserInvalid.page');       
delete from TsSpecialPath where lower(FPath) = lower('*/Qs.Misc.InstallWordPaster.page');    
delete from TsSpecialPath where lower(FPath) = lower('*/Qs.Misc.OpenPageFromEmail.page');    
delete from TsSpecialPath where lower(FPath) = lower('*/Qs.User.PasswordForget.page');       
delete from TsSpecialPath where lower(FPath) = lower('*/Qs.User.PasswordReset.page');        
delete from TsSpecialPath where lower(FPath) = lower('*/Qs.EventLog.Log.data');              
delete from TsSpecialPath where lower(FPath) = lower('*/Qs.Misc.PutUrlArguments.data');      
delete from TsSpecialPath where lower(FPath) = lower('*/Qs.Misc.TestConnection.data');       
delete from TsSpecialPath where lower(FPath) = lower('*/Qs.Misc.WriteLog.data');             
delete from TsSpecialPath where lower(FPath) = lower('*/Qs.OnlineUser.IsOnline.data');       
delete from TsSpecialPath where lower(FPath) = lower('*/Qs.OnlineUser.Login.data');          
delete from TsSpecialPath where lower(FPath) = lower('*/Qs.OnlineUser.Logout.data');         
delete from TsSpecialPath where lower(FPath) = lower('*/Qs.Page.GetInformation.data');       
delete from TsSpecialPath where lower(FPath) = lower('*/Qs.TextResource.GetText.data');      
delete from TsSpecialPath where lower(FPath) = lower('*/Qs.User.ResetPassword.data');        
delete from TsSpecialPath where lower(FPath) = lower('*/Qs.User.SendPasswordResetEmail.data');
delete from TsSpecialPath where lower(FPath) = lower('*/Qs.DiskFile.ViewImageByPath.file');  
delete from TsSpecialPath where lower(FPath) = lower('*/Qs.Misc.GetLogo.file');              

insert into TsSpecialPath set FId='315ec30b-3c8d-4822-aae3-5feb9de6c946', FMatchMode='WildcardExpression',	FPath='*.exportList.file',				FKey='VirtualDirectory', FValue='qsvd-export',	FIndex=1;
insert into TsSpecialPath set FId='83149d0f-5f4b-4d28-9e48-d5cadf765213', FMatchMode='PlainText',			FPath='/Qs.Report.Html.page',			FKey='VirtualDirectory', FValue='qsvd-report',	FIndex=3;
insert into TsSpecialPath set FId='37e15d1f-1850-43ee-8dc9-409369847664', FMatchMode='PlainText',			FPath='/Qs.Chart.getChartData.data',	FKey='VirtualDirectory', FValue='qsvd-chart',	FIndex=2;

---------------

insert into TsTextResource set FId='55fdf43b-c491-4216-8504-9020501fb8da', FCode='T.Jui.DateBox.Ok',									FValue='確定';
