workspace:
  base: /drone
  path: pgw

kind: pipeline
name: default

clone:
  depth: 10

steps:
- name: build
  image: plugins/docker
  pull: always
  settings:
    username: aviman1109
    password: ToDrogogOivwad0
    repo: aviman1109/qs6builder
    tags: build
    dockerfile: Dockerfile