--集群節點

drop table TsClusterNode;

create table TsClusterNode
(
	FId uuid primary key,
	FName varchar(50) unique,
	FUpdateTime timestamp,
	FComputerName varchar(50),
	FDomain varchar(50),
	FIpAddress varchar(20),
	FOsName varchar(50),
	FOsVersion varchar(50),
	FCpuModel varchar(50),
	FCpuUsed double,
	FJvmName varchar(50),
	FJavaVersion varchar(20),
	FJavaHome varchar(200),
	FLibraryPath varchar(1000),
	FWorkDir varchar(200),
	FMemoryTotal int,
	FMemoryUsed int,
	FMemoryFree int,
	FJvmMemoryTotal int,
	FJvmMemoryUsed int,
	FJvmMemoryFree int
);

delete from TsField where FUnitId='f580bcca-add9-4d56-8b2e-b43bc3ce13b0';
insert into TsField set FId='cd5268ea-e2d4-47d3-a6f4-52e6df7fc574', FUnitId='f580bcca-add9-4d56-8b2e-b43bc3ce13b0', FName='FComputerName',   FTitle='電腦名',         FType='InputBox-Text',    FSize=50,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='0e1a6f42-d646-4848-94cc-a343d7641cf4', FUnitId='f580bcca-add9-4d56-8b2e-b43bc3ce13b0', FName='FCpuModel',       FTitle='CPU 型號',         FType='InputBox-Text',    FSize=50,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='94cad1b7-2a0b-4399-93de-f7df9edd3296', FUnitId='f580bcca-add9-4d56-8b2e-b43bc3ce13b0', FName='FCpuUsed',        FTitle='CPU 使用率',       FType='InputBox-Percent', FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=1,    FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='9f4d9fc9-0235-4cc3-a329-ebc7b10646f5', FUnitId='f580bcca-add9-4d56-8b2e-b43bc3ce13b0', FName='FDomain',         FTitle='域',               FType='InputBox-Text',    FSize=50,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='4130cdb3-61e8-458d-8abc-a1fda6549bfd', FUnitId='f580bcca-add9-4d56-8b2e-b43bc3ce13b0', FName='FId',             FTitle='ID',               FType='InputBox-Key',     FSize=null, FVisible=0, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=0, FDictionaryId=null, FEntityUnitId='f580bcca-add9-4d56-8b2e-b43bc3ce13b0', FSupportLocalText=null, FSupportI18n=null, FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=null, FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData=null;
insert into TsField set FId='14c5d2b8-52af-4a41-b651-0ccadfa5e76e', FUnitId='f580bcca-add9-4d56-8b2e-b43bc3ce13b0', FName='FIpAddress',      FTitle='IP',               FType='InputBox-Text',    FSize=20,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='031516b9-742f-4418-bdf9-98f5c68fffb8', FUnitId='f580bcca-add9-4d56-8b2e-b43bc3ce13b0', FName='FJavaHome',       FTitle='Java Home',        FType='InputBox-Text',    FSize=200,  FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=0, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='334bd1b0-1ed8-46c1-a28f-f8df352a8acc', FUnitId='f580bcca-add9-4d56-8b2e-b43bc3ce13b0', FName='FJavaVersion',    FTitle='Java 版本',        FType='InputBox-Text',    FSize=20,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='1876a47a-6760-4ff5-b482-ec10e47a0ac1', FUnitId='f580bcca-add9-4d56-8b2e-b43bc3ce13b0', FName='FJvmMemoryFree',  FTitle='JVM 空閒記憶體(MB)', FType='InputBox-Integer', FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=2,    FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='c0d1d7a7-f79e-4d3b-be04-1fd5775f8596', FUnitId='f580bcca-add9-4d56-8b2e-b43bc3ce13b0', FName='FJvmMemoryTotal', FTitle='JVM 總記憶體(MB)',   FType='InputBox-Integer', FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=2,    FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='c9dd4cd1-40ce-453b-9bf9-beeb18bd0fe5', FUnitId='f580bcca-add9-4d56-8b2e-b43bc3ce13b0', FName='FJvmMemoryUsed',  FTitle='JVM 已用記憶體(MB)', FType='InputBox-Integer', FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=1,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='b3034300-ad82-4778-bfe4-b15059a65e6c', FUnitId='f580bcca-add9-4d56-8b2e-b43bc3ce13b0', FName='FJvmName',        FTitle='JVM 名稱',         FType='InputBox-Text',    FSize=50,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='0d7b6485-e277-4455-885d-aab1ee7fa078', FUnitId='f580bcca-add9-4d56-8b2e-b43bc3ce13b0', FName='FLibraryPath',    FTitle='庫路徑',           FType='InputBox-Text',    FSize=1000, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=0, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='e18ce76f-2572-4ac9-82cf-2515bc1ea89d', FUnitId='f580bcca-add9-4d56-8b2e-b43bc3ce13b0', FName='FMemoryFree',     FTitle='空閒記憶體(MB)',     FType='InputBox-Integer', FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='70e6eee8-b3d2-4778-97d6-db590573279c', FUnitId='f580bcca-add9-4d56-8b2e-b43bc3ce13b0', FName='FMemoryTotal',    FTitle='總記憶體(MB)',       FType='InputBox-Integer', FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='0021672e-b5b5-4740-b5b4-3440f6606a3b', FUnitId='f580bcca-add9-4d56-8b2e-b43bc3ce13b0', FName='FMemoryUsed',     FTitle='已用記憶體(MB)',     FType='InputBox-Integer', FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=1,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='22b4b2d6-3b6d-42ec-b71c-dde69555bdd1', FUnitId='f580bcca-add9-4d56-8b2e-b43bc3ce13b0', FName='FName',           FTitle='節點',             FType='InputBox-Text',    FSize=50,   FVisible=1, FFilterByRole=0, FRequired=1, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData=null;
insert into TsField set FId='2559b63c-7822-4e69-a3e2-20687a089a1b', FUnitId='f580bcca-add9-4d56-8b2e-b43bc3ce13b0', FName='FOsName',         FTitle='作業系統',         FType='InputBox-Text',    FSize=50,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='814ab8c9-073f-4e4f-bb7a-82d9dff5c667', FUnitId='f580bcca-add9-4d56-8b2e-b43bc3ce13b0', FName='FOsVersion',      FTitle='作業系統版本',     FType='InputBox-Text',    FSize=50,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='08e2ae66-2648-46cb-beeb-55b6d1192455', FUnitId='f580bcca-add9-4d56-8b2e-b43bc3ce13b0', FName='FUpdateTime',     FTitle='更新時間',         FType='DateBox-DateTime', FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=120, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData=null;
insert into TsField set FId='3787335e-4ba3-40a5-87bf-e68b29d32c1d', FUnitId='f580bcca-add9-4d56-8b2e-b43bc3ce13b0', FName='FWorkDir',        FTitle='工作目錄',         FType='InputBox-Text',    FSize=200,  FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=0, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';

java setOrderFields('f580bcca-add9-4d56-8b2e-b43bc3ce13b0', 'FUpdateTime', '1');
java setQueryFormFields('f580bcca-add9-4d56-8b2e-b43bc3ce13b0', '');
java setKeywordFields('f580bcca-add9-4d56-8b2e-b43bc3ce13b0', 'FName,FComputerName,FIpAddress');
java setFormFields('228b80a4-20da-46f9-b200-2caacf95972e', '基本資訊', '9859d274-94cd-42c1-a507-88f1c36b688f', null, 'FName,FComputerName,FDomain,FIpAddress,FOsName,FOsVersion,FUpdateTime', 'CPU', '8d753eca-3a86-485c-ac3a-b57278e2e9bc', '9859d274-94cd-42c1-a507-88f1c36b688f', 'FCpuModel,FCpuUsed', '記憶體', 'd54d8d71-bdea-47b4-8133-1625a9deb53c', '9859d274-94cd-42c1-a507-88f1c36b688f', 'FMemoryTotal,FMemoryUsed,FMemoryFree,FJvmMemoryTotal,FJvmMemoryUsed,FJvmMemoryFree', 'Java', '0cd607eb-cca9-42f9-98a4-d1c82de91497', '9859d274-94cd-42c1-a507-88f1c36b688f', 'FJvmName,FJavaVersion,FJavaHome,FLibraryPath,FWorkDir');
java setListFields('30821512-4ef4-4906-9697-d628319eacea', 'FName,FComputerName,FIpAddress,FCpuUsed,FMemoryTotal,FMemoryFree,FJvmMemoryTotal,FJvmMemoryFree,FUpdateTime');
java setListFields('75fe232f-abaa-4e0a-903c-d21c45bd2bab', 'FName,FComputerName,FIpAddress');
java setListFields('0be2f7ef-bfa8-4368-9657-b92e9c6d3bb5', 'FName,FComputerName,FIpAddress');

delete from TsPage where FId='f146de65-b7b7-4ac8-bb5e-33c991cdf03d';
insert into TsPage set FId='f146de65-b7b7-4ac8-bb5e-33c991cdf03d', FName='集群節點檔案系統列表', FTitle='檔案系統', FCode='Qs.ClusterNode.ClusterNodeFileSystemList',  FPlatform='Computer', FType='EntityList', FIcon='quicksilver/image/unit/ClusterNodeFileSystem.png',  FUrl='quicksilver/page/template/EntityList.jsp', FActionMethodName='Qs.ClusterNodeFileSystem.prepareList',  FLoadHandler=null, FRelationId='7e1a1cb0-b9a0-49a8-87fe-abcc1dcd3d9c', FUnitId='98480e11-c877-4ee5-8cfd-754a2301d2b1', FMasterUnitId='f580bcca-add9-4d56-8b2e-b43bc3ce13b0', FIsSlavePage=1, FIndex=2,    FDialogWidth=null, FDialogHeight=null, FDialogMaximized=null, FQueryFormAutoQuery=1,    FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox='No', FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription=null;

delete from TsToolItem where FId='351e2730-dcb2-43a6-8617-3d07fdb59550';
delete from TsToolItem where FId='3d06f889-42db-46d5-b87c-4a4a8cba0acd';
delete from TsToolItem where FId='428bfd01-9c70-4398-b96b-1a8d7e5396e8';
delete from TsToolSubItem where FId='2c3d2d92-2161-4eba-84fe-6b933171d1e4';
insert into TsToolItem set FId='351e2730-dcb2-43a6-8617-3d07fdb59550', FPageId='f146de65-b7b7-4ac8-bb5e-33c991cdf03d', FCode='Open',    FName='打開', FHint='打開當前選中的記錄。如果選中了多筆，第一筆將被打開。', FLabel=null, FType='Button',      FAlign='right', FIndex=1, FWidth=0, FIcon='quicksilver/image/16/Open.gif',    FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doOpen';
insert into TsToolItem set FId='3d06f889-42db-46d5-b87c-4a4a8cba0acd', FPageId='f146de65-b7b7-4ac8-bb5e-33c991cdf03d', FCode='Refresh', FName='刷新', FHint='刷新清單內容',                                         FLabel=null, FType='Button',      FAlign='right', FIndex=2, FWidth=0, FIcon='quicksilver/image/16/Refresh.gif', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doRefresh';
insert into TsToolItem set FId='428bfd01-9c70-4398-b96b-1a8d7e5396e8', FPageId='f146de65-b7b7-4ac8-bb5e-33c991cdf03d', FCode='Other',   FName=null,   FHint=null,                                                   FLabel=null, FType='ComboButton', FAlign='right', FIndex=3, FWidth=0, FIcon='quicksilver/image/16/Other.gif',   FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource='SubItemTable', FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='None',       FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler=null;
insert into TsToolSubItem set FId='2c3d2d92-2161-4eba-84fe-6b933171d1e4', FToolItemId='428bfd01-9c70-4398-b96b-1a8d7e5396e8', FCode='ExcelExport', FName='匯出 Excel', FExpandMode='None', FIndex=1, FIcon='quicksilver/image/16/Excel.gif',  FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FEventHandler='EntityList.doExcelExport';

delete from TsPage where FId='e3cb8435-4c9e-4536-a2d8-d141a3a26cc9';
insert into TsPage set FId='e3cb8435-4c9e-4536-a2d8-d141a3a26cc9', FName='集群節點集群節點性能資訊清單', FTitle='性能資訊', FCode='Qs.ClusterNode.ClusterNodePerformanceList', FPlatform='Computer', FType='EntityList', FIcon='quicksilver/image/unit/ClusterNodePerformance.png', FUrl='quicksilver/page/template/EntityList.jsp', FActionMethodName='Qs.ClusterNodePerformance.prepareList', FLoadHandler=null, FRelationId='28f11895-612d-4c30-98b1-b4a65b1832d7', FUnitId='04b12a40-da86-496a-a251-cfdce39c3b3a', FMasterUnitId='f580bcca-add9-4d56-8b2e-b43bc3ce13b0', FIsSlavePage=1, FIndex=3,    FDialogWidth=null, FDialogHeight=null, FDialogMaximized=null, FQueryFormAutoQuery=1,    FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox='No', FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription=null;

delete from TsToolItem where FId='1f6b9e0d-ce6a-44dc-9ddd-ecaf4bf0ac4f';
delete from TsToolItem where FId='2ff0eba2-61de-418b-b3bb-188b6836170e';
delete from TsToolItem where FId='4e95a193-9c73-434c-ae88-3ab1ebcbd205';
delete from TsToolSubItem where FId='b4c834b3-79bb-443d-9a29-4b212c2625c3';
insert into TsToolItem set FId='1f6b9e0d-ce6a-44dc-9ddd-ecaf4bf0ac4f', FPageId='e3cb8435-4c9e-4536-a2d8-d141a3a26cc9', FCode='Open',    FName='打開', FHint='打開當前選中的記錄。如果選中了多筆，第一筆將被打開。', FLabel=null, FType='Button',      FAlign='right', FIndex=1, FWidth=0, FIcon='quicksilver/image/16/Open.gif',    FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doOpen';
insert into TsToolItem set FId='2ff0eba2-61de-418b-b3bb-188b6836170e', FPageId='e3cb8435-4c9e-4536-a2d8-d141a3a26cc9', FCode='Refresh', FName='刷新', FHint='刷新清單內容',                                         FLabel=null, FType='Button',      FAlign='right', FIndex=2, FWidth=0, FIcon='quicksilver/image/16/Refresh.gif', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doRefresh';
insert into TsToolItem set FId='4e95a193-9c73-434c-ae88-3ab1ebcbd205', FPageId='e3cb8435-4c9e-4536-a2d8-d141a3a26cc9', FCode='Other',   FName=null,   FHint=null,                                                   FLabel=null, FType='ComboButton', FAlign='right', FIndex=3, FWidth=0, FIcon='quicksilver/image/16/Other.gif',   FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource='SubItemTable', FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='None',       FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler=null;
insert into TsToolSubItem set FId='b4c834b3-79bb-443d-9a29-4b212c2625c3', FToolItemId='4e95a193-9c73-434c-ae88-3ab1ebcbd205', FCode='ExcelExport', FName='匯出 Excel', FExpandMode='None', FIndex=1, FIcon='quicksilver/image/16/Excel.gif',  FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FEventHandler='EntityList.doExcelExport';

delete from TsPage where FId='b1abf814-b8b7-4c91-8e10-eb377708774d';
insert into TsPage set FId='b1abf814-b8b7-4c91-8e10-eb377708774d', FName='集群節點圖表',		 FTitle='圖表分析',		FCode='Qs.ClusterNode.ClusterNodeChart',			FPlatform='Computer', FType='Other',      FIcon='quicksilver/image/16/Monitor.gif',						FUrl='quicksilver/page/monitor/ClusterNodeChart.jsp',	FActionMethodName=null,										FLoadHandler=null, FRelationId=null,									FUnitId=null,									FMasterUnitId='f580bcca-add9-4d56-8b2e-b43bc3ce13b0', FIsSlavePage=1, FIndex=4,    FDialogWidth=null, FDialogHeight=null, FDialogMaximized=null, FQueryFormAutoQuery=1,    FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription=null;

delete from TsToolItem where FId='96b100de-7e47-4562-8a0e-7008986a0d06';
insert into TsToolItem set FId='96b100de-7e47-4562-8a0e-7008986a0d06', FPageId='b1abf814-b8b7-4c91-8e10-eb377708774d', FCode='Refresh', FName='刷新', FHint='刷新圖表',                                         FLabel=null, FType='Button',      FAlign='right', FIndex=1, FWidth=0, FIcon='quicksilver/image/16/Refresh.gif', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='ClusterNodeChart.doRefresh';

--Qs.ClusterNodePerformance-----------------------------------------------------

create table TsClusterNodePerformance
(
	FId uuid primary key,
	FClusterNodeId uuid,
	FTime timestamp,
	FCpuUsed double,
	FMemoryTotal int,
	FMemoryUsed int,
	FJvmMemoryTotal int,
	FJvmMemoryUsed int
);

insert into TsUnit set FId='04b12a40-da86-496a-a251-cfdce39c3b3a', FCode='Qs.ClusterNodePerformance', FName='集群節點性能資訊', FIcon='quicksilver/image/unit/ClusterNodePerformance.png', FEditId='541c707d-79dd-4dbb-85fc-1a214fd5fce4', FModuleId='00000000-0000-0000-0008-990000000020', FOpenMode='System', FIsTreeStructure=0, FMaxTreeLevel=null, FIsSlaveUnit=1, FMasterUnitId='f580bcca-add9-4d56-8b2e-b43bc3ce13b0', FSupportWorkflow=0, FSupportUser=0, FSupportDepartment=0, FSupportEditType=0, FSupportAttachment=0, FSupportDataPrivilege=0, FSupportVersion=0, FSupportBusinessLog=0, FSupportNote=0, FSupportSort=0, FSupportPrivilegeField=0, FIsFullTextSearch=0, FSearchAttachment=0, FSupportEqualQuery=0, FUseSystemI18nTable=0, FExtraQueryResultLimit=0, FRecordCreateInfo=0, FRecordUpdateInfo=0, FRecordDeleteInfo=0, FViewPageConditionForList=null, FViewPageConditionForLink=null, FDataSource='default', FTable='TsClusterNodePerformance', FKeyField='FId', FKeyType='Uuid', FNameField='FClusterNodeId$', FMasterField='FClusterNodeId', FHomeClassName='com.jeedsoft.quicksilver.monitor.ClusterNodePerformanceHome', FDaoClassName='com.jeedsoft.quicksilver.monitor.dao.impl.ClusterNodePerformanceDaoImpl', FServiceClassName='com.jeedsoft.quicksilver.monitor.service.impl.ClusterNodePerformanceServiceImpl', FActionClassName='com.jeedsoft.quicksilver.monitor.action.impl.ClusterNodePerformanceActionImpl', FWebServiceUniqueField=null, FUnitFilterSql='', FBusinessFilterSql='', FDescription='';

insert into TsField set FId='80bdbba1-fb0f-45fb-afc4-a0635a87d393', FUnitId='04b12a40-da86-496a-a251-cfdce39c3b3a', FName='FClusterNodeId',  FTitle='集群節點',         FType='EntityBox',        FSize=null, FVisible=0, FFilterByRole=0, FRequired=1, FReadOnly=0, FQueryable=0, FDictionaryId=null, FEntityUnitId='f580bcca-add9-4d56-8b2e-b43bc3ce13b0', FSupportLocalText=null, FSupportI18n=null, FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=null, FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData=null;
insert into TsField set FId='f86db582-6764-457f-beab-5e34a3989ba1', FUnitId='04b12a40-da86-496a-a251-cfdce39c3b3a', FName='FCpuUsed',        FTitle='CPU 使用率',       FType='InputBox-Percent', FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=1,    FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='af8fca0a-e0dd-46a2-9c70-b8d473f183d7', FUnitId='04b12a40-da86-496a-a251-cfdce39c3b3a', FName='FId',             FTitle='ID',               FType='InputBox-Key',     FSize=null, FVisible=0, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=0, FDictionaryId=null, FEntityUnitId='04b12a40-da86-496a-a251-cfdce39c3b3a', FSupportLocalText=null, FSupportI18n=null, FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=null, FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData=null;
insert into TsField set FId='1d0f2d7b-f2ca-4b55-aac1-d6a15cb992dc', FUnitId='04b12a40-da86-496a-a251-cfdce39c3b3a', FName='FJvmMemoryTotal', FTitle='JVM 總記憶體(MB)',   FType='InputBox-Integer', FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='86f71971-8f40-4fe9-9db0-f372a46c1358', FUnitId='04b12a40-da86-496a-a251-cfdce39c3b3a', FName='FJvmMemoryUsed',  FTitle='JVM 已用記憶體(MB)', FType='InputBox-Integer', FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='6f48e31d-b312-40b3-baaf-686ac691481b', FUnitId='04b12a40-da86-496a-a251-cfdce39c3b3a', FName='FMemoryTotal',    FTitle='總記憶體(MB)',       FType='InputBox-Integer', FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='e549ca5a-3ad6-48ba-bd85-810048197f80', FUnitId='04b12a40-da86-496a-a251-cfdce39c3b3a', FName='FMemoryUsed',     FTitle='已用記憶體(MB)',     FType='InputBox-Integer', FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='fa641f1b-2e85-40ac-bf71-65ec4283e23d', FUnitId='04b12a40-da86-496a-a251-cfdce39c3b3a', FName='FTime',           FTitle='時間',             FType='DateBox-DateTime', FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=120, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';

java setOrderFields('04b12a40-da86-496a-a251-cfdce39c3b3a', 'FTime', '1');
java setQueryFormFields('04b12a40-da86-496a-a251-cfdce39c3b3a', 'FTime,FCpuUsed,FMemoryUsed,FJvmMemoryUsed');

insert into TsRelation set FId='31b195b0-61f4-4246-9075-dae51e32f908', FOppositeId='28f11895-612d-4c30-98b1-b4a65b1832d7', FName='集群節點性能資訊-集群節點', FOppositeName='集群節點-集群節點性能資訊', FUnitId1='04b12a40-da86-496a-a251-cfdce39c3b3a', FUnitId2='f580bcca-add9-4d56-8b2e-b43bc3ce13b0', FType='field', FTable='', FField1='FId', FField2='FClusterNodeId', FDeleteAction1='unset', FDeleteAction2='cancel', FPrivilegeTypeId1=null, FPrivilegeTypeId2=null;

insert into TsPage set FId='67af1aa2-13c4-47d2-9c3a-e09cdad8967a', FName='集群節點性能資訊主清單',   FTitle='集群節點性能資訊清單', FCode='Qs.ClusterNodePerformance.List',       FPlatform='Computer', FType='EntityList', FIcon='quicksilver/image/unit/ClusterNodePerformance.png', FUrl='quicksilver/page/template/EntityList.jsp', FActionMethodName='Qs.ClusterNodePerformance.prepareList', FLoadHandler=null, FRelationId=null, FUnitId='04b12a40-da86-496a-a251-cfdce39c3b3a', FMasterUnitId=null,                                   FIsSlavePage=0, FIndex=null, FDialogWidth=null, FDialogHeight=null, FDialogMaximized=null, FQueryFormAutoQuery=1, FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription=null;
insert into TsPage set FId='8a013b91-d39d-44de-98c3-562cdf69d56e', FName='集群節點性能資訊選擇清單', FTitle='集群節點性能資訊清單', FCode='Qs.ClusterNodePerformance.SelectList', FPlatform='Computer', FType='EntityList', FIcon='quicksilver/image/unit/ClusterNodePerformance.png', FUrl='quicksilver/page/template/EntityList.jsp', FActionMethodName='Qs.ClusterNodePerformance.prepareList', FLoadHandler=null, FRelationId=null, FUnitId='04b12a40-da86-496a-a251-cfdce39c3b3a', FMasterUnitId=null,                                   FIsSlavePage=0, FIndex=null, FDialogWidth=null, FDialogHeight=null, FDialogMaximized=null, FQueryFormAutoQuery=1, FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription=null;
insert into TsPage set FId='7cc20a60-e10e-4040-9f63-f56a42dfd883', FName='集群節點性能資訊表單',     FTitle='表單',                 FCode='Qs.ClusterNodePerformance.Edit',       FPlatform='Computer', FType='EntityEdit', FIcon='quicksilver/image/unit/Edit.gif',               FUrl='quicksilver/page/template/EntityEdit.jsp', FActionMethodName='Qs.ClusterNodePerformance.prepareEdit', FLoadHandler=null, FRelationId=null, FUnitId='04b12a40-da86-496a-a251-cfdce39c3b3a', FMasterUnitId='04b12a40-da86-496a-a251-cfdce39c3b3a', FIsSlavePage=1, FIndex=1,    FDialogWidth=604,  FDialogHeight=453,  FDialogMaximized=null, FQueryFormAutoQuery=1, FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription=null;

--集群節點性能資訊主清單
insert into TsToolItem set FId='061dee04-ba79-4b8c-b8b8-9205c5cf332f', FPageId='67af1aa2-13c4-47d2-9c3a-e09cdad8967a', FCode='Open',    FName='打開', FHint='打開當前選中的記錄。如果選中了多筆，第一筆將被打開。', FLabel=null, FType='Button',      FAlign='right', FIndex=2, FWidth=0, FIcon='quicksilver/image/16/Open.gif',    FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doOpen';
insert into TsToolItem set FId='eab98a45-91ba-4502-a2a8-26baef8b8c76', FPageId='67af1aa2-13c4-47d2-9c3a-e09cdad8967a', FCode='Refresh', FName='刷新', FHint='刷新清單內容',                                         FLabel=null, FType='Button',      FAlign='right', FIndex=4, FWidth=0, FIcon='quicksilver/image/16/Refresh.gif', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doRefresh';
insert into TsToolItem set FId='9727e4ab-cb5f-4398-a125-1b2cb18954c7', FPageId='67af1aa2-13c4-47d2-9c3a-e09cdad8967a', FCode='Other',   FName=null,   FHint=null,                                                   FLabel=null, FType='ComboButton', FAlign='right', FIndex=5, FWidth=0, FIcon='quicksilver/image/16/Other.gif',   FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource='SubItemTable', FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='None',       FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler=null;
insert into TsToolSubItem set FId='316b5d69-b3f5-458c-9ba9-1d4f0d310171', FToolItemId='9727e4ab-cb5f-4398-a125-1b2cb18954c7', FCode='ExcelExport', FName='匯出 Excel', FExpandMode='None', FIndex=1, FIcon='quicksilver/image/16/Excel.gif',  FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FEventHandler='EntityList.doExcelExport';

--集群節點性能資訊選擇清單
insert into TsToolItem set FId='94f0e85e-d2b1-4b41-a5df-ad14dbaca289', FPageId='8a013b91-d39d-44de-98c3-562cdf69d56e', FCode='ConfirmSelection', FName='確定', FHint=null,                                                   FLabel=null, FType='Button', FAlign='right', FIndex=1, FWidth=0, FIcon='quicksilver/image/16/Ok.gif',   FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doSelectListConfirm';
insert into TsToolItem set FId='bff3ceac-4588-417c-bb43-a216f9a0ec1d', FPageId='8a013b91-d39d-44de-98c3-562cdf69d56e', FCode='Open',             FName='打開', FHint='打開當前選中的記錄。如果選中了多筆，第一筆將被打開。', FLabel=null, FType='Button', FAlign='right', FIndex=3, FWidth=0, FIcon='quicksilver/image/16/Open.gif', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doOpen';

insert into TsForm set FDefault=1, FEditableCondition=null, FGroupMode='Double', FId='6a89ebca-3680-40a3-a8af-f71ec77e594b', FIndex=1, FName='默認', FPageId=null, FUnitId='04b12a40-da86-496a-a251-cfdce39c3b3a';
java setFormFields('6a89ebca-3680-40a3-a8af-f71ec77e594b', '基本資訊', '4b5ca43a-fba1-4ebd-8ac0-06f89f1beffd', null, 'FTime,FCpuUsed,FMemoryTotal,FMemoryUsed,FJvmMemoryTotal,FJvmMemoryUsed');

insert into TsList set FDefault=1, FId='260a7f4b-419c-469f-86a6-a80768147391', FIndex=null, FMultiPage=1, FName='集群節點性能資訊清單',		FPageId=null,                                   FUnitId='04b12a40-da86-496a-a251-cfdce39c3b3a';
insert into TsList set FDefault=0, FId='09324844-df0a-42c0-9bd8-1b8af340b173', FIndex=null, FMultiPage=1, FName='集群節點性能資訊選擇清單', FPageId='8a013b91-d39d-44de-98c3-562cdf69d56e', FUnitId='04b12a40-da86-496a-a251-cfdce39c3b3a';
insert into TsList set FDefault=0, FId='415298ea-3eb3-4a88-9632-2d913c414686', FIndex=null, FMultiPage=1, FName='集群節點性能資訊首頁清單', FPageId='9b796431-f132-49d1-b306-5d1d618f9c1b', FUnitId='04b12a40-da86-496a-a251-cfdce39c3b3a';
java setListFields('260a7f4b-419c-469f-86a6-a80768147391', 'FTime,FCpuUsed,FMemoryTotal,FMemoryUsed,FJvmMemoryTotal,FJvmMemoryUsed');
java setListFields('09324844-df0a-42c0-9bd8-1b8af340b173', 'FTime,FCpuUsed,FMemoryUsed,FJvmMemoryUsed');
java setListFields('415298ea-3eb3-4a88-9632-2d913c414686', 'FTime,FCpuUsed,FMemoryUsed,FJvmMemoryUsed');

insert into TsSlaveUnitPrivilege set FId='b94d42be-17fb-4aa0-8052-1924d30184b1', FUnitId='04b12a40-da86-496a-a251-cfdce39c3b3a', FCreatePrivilegeTypeId='00000000-0000-0000-1005-000000000003', FReadPrivilegeTypeId='00000000-0000-0000-1005-000000000003', FReadUserFieldName='', FUpdatePrivilegeTypeId='00000000-0000-0000-1005-000000000003', FUpdateUserFieldName='', FDeletePrivilegeTypeId='00000000-0000-0000-1005-000000000003', FDeleteUserFieldName='';

--Qs.ClusterNodeFileSystem------------------------------------------------------

create table TsClusterNodeFileSystem
(
	FId uuid primary key,
	FName varchar(50),
	FClusterNodeId uuid,
	FDirName varchar(50),
	FType varchar(20),
	FFormatType varchar(20),
	FSpaceTotal double,
	FSpaceUsed double,
	FSpaceAvailable double,
	FUpdateTime timestamp
);

insert into TsUnit set FId='98480e11-c877-4ee5-8cfd-754a2301d2b1', FCode='Qs.ClusterNodeFileSystem', FName='集群節點檔案系統', FIcon='quicksilver/image/unit/ClusterNodeFileSystem.png', FEditId='541c707d-79dd-4dbb-85fc-1a214fd5fce4', FModuleId='00000000-0000-0000-0008-990000000020', FOpenMode='System', FIsTreeStructure=0, FMaxTreeLevel=null, FIsSlaveUnit=1, FMasterUnitId='f580bcca-add9-4d56-8b2e-b43bc3ce13b0', FSupportWorkflow=0, FSupportUser=0, FSupportDepartment=0, FSupportEditType=0, FSupportAttachment=0, FSupportDataPrivilege=0, FSupportVersion=0, FSupportBusinessLog=0, FSupportNote=0, FSupportSort=0, FSupportPrivilegeField=0, FIsFullTextSearch=0, FSearchAttachment=0, FSupportEqualQuery=0, FUseSystemI18nTable=0, FExtraQueryResultLimit=0, FRecordCreateInfo=0, FRecordUpdateInfo=0, FRecordDeleteInfo=0, FViewPageConditionForList=null, FViewPageConditionForLink=null, FDataSource='default', FTable='TsClusterNodeFileSystem', FKeyField='FId', FKeyType='Uuid', FNameField='FName', FMasterField='FClusterNodeId', FHomeClassName='com.jeedsoft.quicksilver.monitor.ClusterNodeFileSystemHome', FDaoClassName='com.jeedsoft.quicksilver.monitor.dao.impl.ClusterNodeFileSystemDaoImpl', FServiceClassName='com.jeedsoft.quicksilver.monitor.service.impl.ClusterNodeFileSystemServiceImpl', FActionClassName='com.jeedsoft.quicksilver.monitor.action.impl.ClusterNodeFileSystemActionImpl', FWebServiceUniqueField=null, FUnitFilterSql='', FBusinessFilterSql='', FDescription='';

insert into TsField set FId='c3f20bc5-66c4-42c9-b0b1-abd6a5b09a19', FUnitId='98480e11-c877-4ee5-8cfd-754a2301d2b1', FName='FClusterNodeId',  FTitle='集群節點',     FType='EntityBox',        FSize=null, FVisible=0, FFilterByRole=0, FRequired=1, FReadOnly=0, FQueryable=0, FDictionaryId=null, FEntityUnitId='f580bcca-add9-4d56-8b2e-b43bc3ce13b0', FSupportLocalText=null, FSupportI18n=null, FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=null, FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData=null;
insert into TsField set FId='f302a60f-1f29-4213-8bf6-58524f44dc38', FUnitId='98480e11-c877-4ee5-8cfd-754a2301d2b1', FName='FDirName',        FTitle='路徑',         FType='InputBox-Text',    FSize=50,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='1ddd0bc1-7f54-4f4a-bc47-6ab60c98c9db', FUnitId='98480e11-c877-4ee5-8cfd-754a2301d2b1', FName='FFormatType',     FTitle='格式類型',     FType='InputBox-Text',    FSize=20,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='310645d5-bdd0-480f-bc32-6bb4a3117384', FUnitId='98480e11-c877-4ee5-8cfd-754a2301d2b1', FName='FId',             FTitle='ID',           FType='InputBox-Key',     FSize=null, FVisible=0, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=0, FDictionaryId=null, FEntityUnitId='98480e11-c877-4ee5-8cfd-754a2301d2b1', FSupportLocalText=null, FSupportI18n=null, FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=null, FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData=null;
insert into TsField set FId='2f492942-2693-452f-aebb-e0a07423e650', FUnitId='98480e11-c877-4ee5-8cfd-754a2301d2b1', FName='FName',           FTitle='名稱',         FType='InputBox-Text',    FSize=50,   FVisible=1, FFilterByRole=0, FRequired=1, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=null, FSupportI18n=null, FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=null, FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData=null;
insert into TsField set FId='c9a908fd-9d53-4e93-b5a0-5eba005ce7f0', FUnitId='98480e11-c877-4ee5-8cfd-754a2301d2b1', FName='FSpaceAvailable', FTitle='可用空間(GB)', FType='InputBox-Double',  FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=2,    FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='7f95868b-3c80-4c04-b60c-f10dd5976e21', FUnitId='98480e11-c877-4ee5-8cfd-754a2301d2b1', FName='FSpaceTotal',     FTitle='總空間(GB)',   FType='InputBox-Double',  FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=2,    FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='dd5daa27-adb9-44dd-a208-cbfd7f5fc6ea', FUnitId='98480e11-c877-4ee5-8cfd-754a2301d2b1', FName='FSpaceUsed',      FTitle='已用空間(GB)', FType='InputBox-Double',  FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=1,    FListWidth=100, FListAlign='default', FScale=2,    FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='dcfccec4-4334-434c-bb08-1121868652ab', FUnitId='98480e11-c877-4ee5-8cfd-754a2301d2b1', FName='FType',           FTitle='類型',         FType='InputBox-Text',    FSize=20,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='3e144f32-dff1-46c3-a66a-23e37d08eb9f', FUnitId='98480e11-c877-4ee5-8cfd-754a2301d2b1', FName='FUpdateTime',     FTitle='資訊收集時間', FType='DateBox-DateTime', FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=120, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';

java setOrderFields('98480e11-c877-4ee5-8cfd-754a2301d2b1', 'FName', '0');
java setQueryFormFields('98480e11-c877-4ee5-8cfd-754a2301d2b1', 'FName,FDirName,FType,FFormatType,FSpaceTotal,FSpaceUsed,FSpaceAvailable');

insert into TsRelation set FId='9edbe81d-9fda-4d64-bd8d-502c7a36a915', FOppositeId='7e1a1cb0-b9a0-49a8-87fe-abcc1dcd3d9c', FName='集群節點檔案系統-集群節點', FOppositeName='集群節點-集群節點檔案系統', FUnitId1='98480e11-c877-4ee5-8cfd-754a2301d2b1', FUnitId2='f580bcca-add9-4d56-8b2e-b43bc3ce13b0', FType='field', FTable='', FField1='FId', FField2='FClusterNodeId', FDeleteAction1='unset', FDeleteAction2='cancel', FPrivilegeTypeId1=null, FPrivilegeTypeId2=null;

insert into TsPage set FId='0df40408-7b95-4a12-8f23-26b8cb274e8a', FName='集群節點檔案系統主列表',   FTitle='集群節點檔案系統列表', FCode='Qs.ClusterNodeFileSystem.List',       FPlatform='Computer', FType='EntityList', FIcon='quicksilver/image/unit/ClusterNodeFileSystem.png', FUrl='quicksilver/page/template/EntityList.jsp', FActionMethodName='Qs.ClusterNodeFileSystem.prepareList', FLoadHandler=null, FRelationId=null, FUnitId='98480e11-c877-4ee5-8cfd-754a2301d2b1', FMasterUnitId=null,                                   FIsSlavePage=0, FIndex=null, FDialogWidth=null, FDialogHeight=null, FDialogMaximized=null, FQueryFormAutoQuery=1, FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription=null;
insert into TsPage set FId='1f77268d-a60c-480f-9c9b-a240f2d22b1a', FName='集群節點檔案系統選擇列表', FTitle='集群節點檔案系統列表', FCode='Qs.ClusterNodeFileSystem.SelectList', FPlatform='Computer', FType='EntityList', FIcon='quicksilver/image/unit/ClusterNodeFileSystem.png', FUrl='quicksilver/page/template/EntityList.jsp', FActionMethodName='Qs.ClusterNodeFileSystem.prepareList', FLoadHandler=null, FRelationId=null, FUnitId='98480e11-c877-4ee5-8cfd-754a2301d2b1', FMasterUnitId=null,                                   FIsSlavePage=0, FIndex=null, FDialogWidth=null, FDialogHeight=null, FDialogMaximized=null, FQueryFormAutoQuery=1, FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription=null;
insert into TsPage set FId='bc065f2a-7027-43ca-a69d-232c18af9974', FName='集群節點檔案系統表單',     FTitle='表單',                 FCode='Qs.ClusterNodeFileSystem.Edit',       FPlatform='Computer', FType='EntityEdit', FIcon='quicksilver/image/unit/Edit.gif',                  FUrl='quicksilver/page/template/EntityEdit.jsp', FActionMethodName='Qs.ClusterNodeFileSystem.prepareEdit', FLoadHandler=null, FRelationId=null, FUnitId='98480e11-c877-4ee5-8cfd-754a2301d2b1', FMasterUnitId='98480e11-c877-4ee5-8cfd-754a2301d2b1', FIsSlavePage=1, FIndex=1,    FDialogWidth=604,  FDialogHeight=453,  FDialogMaximized=null, FQueryFormAutoQuery=1, FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription=null;

--集群節點檔案系統主列表
insert into TsToolItem set FId='3bf6a3dd-f05b-4a98-875d-a9e291e7083e', FPageId='0df40408-7b95-4a12-8f23-26b8cb274e8a', FCode='Open',    FName='打開', FHint='打開當前選中的記錄。如果選中了多筆，第一筆將被打開。', FLabel=null, FType='Button',      FAlign='right', FIndex=2, FWidth=0, FIcon='quicksilver/image/16/Open.gif',    FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doOpen';
insert into TsToolItem set FId='1f01e10c-09d1-4c0a-b7b2-d520957f71f8', FPageId='0df40408-7b95-4a12-8f23-26b8cb274e8a', FCode='Refresh', FName='刷新', FHint='刷新清單內容',                                         FLabel=null, FType='Button',      FAlign='right', FIndex=4, FWidth=0, FIcon='quicksilver/image/16/Refresh.gif', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doRefresh';
insert into TsToolItem set FId='6b05dc6d-a1e8-4b65-aec4-4ee6ef789dc3', FPageId='0df40408-7b95-4a12-8f23-26b8cb274e8a', FCode='Other',   FName=null,   FHint=null,                                                   FLabel=null, FType='ComboButton', FAlign='right', FIndex=5, FWidth=0, FIcon='quicksilver/image/16/Other.gif',   FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource='SubItemTable', FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='None',       FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler=null;
insert into TsToolSubItem set FId='3b32058b-0426-4f0b-b4e9-14186bc8f5de', FToolItemId='6b05dc6d-a1e8-4b65-aec4-4ee6ef789dc3', FCode='ExcelExport', FName='匯出 Excel', FExpandMode='None', FIndex=2, FIcon='quicksilver/image/16/Excel.gif',  FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FEventHandler='EntityList.doExcelExport';

--集群節點檔案系統選擇列表
insert into TsToolItem set FId='b3a58d7a-5bc7-4097-8eac-8c06c9a343e0', FPageId='1f77268d-a60c-480f-9c9b-a240f2d22b1a', FCode='ConfirmSelection', FName='確定', FHint=null,                                                   FLabel=null, FType='Button', FAlign='right', FIndex=1, FWidth=0, FIcon='quicksilver/image/16/Ok.gif',   FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doSelectListConfirm';
insert into TsToolItem set FId='00cfffba-cabc-497a-952a-9a6e6afb4ae4', FPageId='1f77268d-a60c-480f-9c9b-a240f2d22b1a', FCode='Open',             FName='打開', FHint='打開當前選中的記錄。如果選中了多筆，第一筆將被打開。', FLabel=null, FType='Button', FAlign='right', FIndex=3, FWidth=0, FIcon='quicksilver/image/16/Open.gif', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doOpen';

insert into TsForm set FDefault=1, FEditableCondition=null, FGroupMode='Double', FId='efa854b2-d61f-4884-b52f-35cbf45c8809', FIndex=1, FName='默認', FPageId=null, FUnitId='98480e11-c877-4ee5-8cfd-754a2301d2b1';
java setFormFields('efa854b2-d61f-4884-b52f-35cbf45c8809', '基本資訊', 'bd1e6359-5215-4197-b84d-974407c7d3ce', null, 'FName,FDirName,FType,FFormatType,FUpdateTime', '容量', 'e22325bb-c41c-40d1-bdfe-8ba7608afddc', 'bd1e6359-5215-4197-b84d-974407c7d3ce', 'FSpaceTotal,FSpaceUsed,FSpaceAvailable');

insert into TsList set FDefault=1, FId='ea7cdba9-4b7e-41ee-b9a3-47c36e75c69e', FIndex=null, FMultiPage=1, FName='集群節點檔案系統列表',		FPageId=null,                                   FUnitId='98480e11-c877-4ee5-8cfd-754a2301d2b1';
insert into TsList set FDefault=0, FId='b0b21369-50d3-4b37-a7be-018ecec35e98', FIndex=null, FMultiPage=1, FName='集群節點檔案系統選擇列表', FPageId='1f77268d-a60c-480f-9c9b-a240f2d22b1a', FUnitId='98480e11-c877-4ee5-8cfd-754a2301d2b1';
insert into TsList set FDefault=0, FId='89ef31af-e7e1-4678-9452-abba1dae5cec', FIndex=null, FMultiPage=1, FName='集群節點檔案系統首頁列表', FPageId='9b796431-f132-49d1-b306-5d1d618f9c1b', FUnitId='98480e11-c877-4ee5-8cfd-754a2301d2b1';
java setListFields('ea7cdba9-4b7e-41ee-b9a3-47c36e75c69e', 'FName,FDirName,FType,FFormatType,FSpaceTotal,FSpaceUsed,FSpaceAvailable,FUpdateTime');
java setListFields('b0b21369-50d3-4b37-a7be-018ecec35e98', 'FName,FDirName,FType,FFormatType,FSpaceTotal,FSpaceUsed,FSpaceAvailable,FUpdateTime');
java setListFields('89ef31af-e7e1-4678-9452-abba1dae5cec', 'FName,FDirName,FType,FFormatType,FSpaceTotal,FSpaceUsed,FSpaceAvailable,FUpdateTime');

insert into TsSlaveUnitPrivilege set FId='5c224e75-87ea-4632-802b-f5c20280da28', FUnitId='98480e11-c877-4ee5-8cfd-754a2301d2b1', FCreatePrivilegeTypeId='00000000-0000-0000-1005-000000000003', FReadPrivilegeTypeId='00000000-0000-0000-1005-000000000003', FReadUserFieldName='', FUpdatePrivilegeTypeId='00000000-0000-0000-1005-000000000003', FUpdateUserFieldName='', FDeletePrivilegeTypeId='00000000-0000-0000-1005-000000000003', FDeleteUserFieldName='';
