--節點性能資訊

alter table TsClusterNodePerformance add FDbReadCount bigint;
alter table TsClusterNodePerformance add FDbReadTime bigint;
alter table TsClusterNodePerformance add FDbWriteCount bigint;
alter table TsClusterNodePerformance add FDbWriteTime bigint;

delete from TsField where FId='acacc7e3-2229-4433-a2cb-047aaf5152be';
delete from TsField where FId='e78573f9-6a08-4e41-aabe-3bf88739b7f2';
delete from TsField where FId='9986c302-3c46-46e4-bf2a-425d24e5502e';
delete from TsField where FId='bda3ff4f-5c73-40c6-9187-37aaf97cb5cf';
delete from TsField where FId='13ffb4a3-6c6a-412f-9dc6-81f953ee836d';
delete from TsField where FId='69858e3f-2ee7-4cd7-975d-d683d50111a0';
insert into TsField set FId='acacc7e3-2229-4433-a2cb-047aaf5152be', FUnitId='04b12a40-da86-496a-a251-cfdce39c3b3a', FName='FDbAverageReadTime',  FTitle='資料庫平均讀時間(ms)', FType='InputBox-Double',  FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='sql',   FJoinField=null, FSourceField=null, FSource='case when FDbReadCount = 0 then null else (1.0 * FDbReadTime) / FDbReadCount end',    FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=150, FListAlign='default', FScale=1,    FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='e78573f9-6a08-4e41-aabe-3bf88739b7f2', FUnitId='04b12a40-da86-496a-a251-cfdce39c3b3a', FName='FDbAverageWriteTime', FTitle='資料庫平均寫時間(ms)', FType='InputBox-Double',  FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='sql',   FJoinField=null, FSourceField=null, FSource='case when FDbWriteCount = 0 then null else (1.0 * FDbWriteTime) / FDbWriteCount end', FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=150, FListAlign='default', FScale=1,    FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='9986c302-3c46-46e4-bf2a-425d24e5502e', FUnitId='04b12a40-da86-496a-a251-cfdce39c3b3a', FName='FDbReadCount',        FTitle='資料庫讀次數',         FType='InputBox-BigInt',  FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',                                                                                    FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='bda3ff4f-5c73-40c6-9187-37aaf97cb5cf', FUnitId='04b12a40-da86-496a-a251-cfdce39c3b3a', FName='FDbReadTime',         FTitle='資料庫讀耗時',         FType='InputBox-BigInt',  FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',                                                                                    FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='13ffb4a3-6c6a-412f-9dc6-81f953ee836d', FUnitId='04b12a40-da86-496a-a251-cfdce39c3b3a', FName='FDbWriteCount',       FTitle='資料庫寫次數',         FType='InputBox-BigInt',  FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',                                                                                    FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='69858e3f-2ee7-4cd7-975d-d683d50111a0', FUnitId='04b12a40-da86-496a-a251-cfdce39c3b3a', FName='FDbWriteTime',        FTitle='資料庫寫耗時',         FType='InputBox-BigInt',  FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',                                                                                    FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';

java setFormFields('6a89ebca-3680-40a3-a8af-f71ec77e594b', '基本資訊', '4b5ca43a-fba1-4ebd-8ac0-06f89f1beffd', null, 'FTime,FCpuUsed,FMemoryTotal,FMemoryUsed,FJvmMemoryTotal,FJvmMemoryUsed', '資料庫', '044dc317-c96b-408f-bd60-cac5dde64c0e', '4b5ca43a-fba1-4ebd-8ac0-06f89f1beffd', 'FDbReadCount,FDbWriteCount,FDbReadTime,FDbWriteTime,FDbAverageReadTime,FDbAverageWriteTime');
java setListFields('260a7f4b-419c-469f-86a6-a80768147391', 'FTime,FCpuUsed,FMemoryTotal,FMemoryUsed,FJvmMemoryTotal,FJvmMemoryUsed,FDbReadCount,FDbWriteCount,FDbAverageReadTime,FDbAverageWriteTime');
