--Qs.Deputy---------------------------------------------------------------------

create table TwDeputy
(
	FId uuid primary key,
	FUserId uuid,
	FDeputyId uuid,
	FName varchar(50)
);

insert into TsUnit set FId='ca26ea7b-3292-4184-bb70-0f0f5decb919', FCode='Qs.Deputy', FName='代理人', FIcon='quicksilver/image/unit/New.gif', FEditId='541c707d-79dd-4dbb-85fc-1a214fd5fce4', FModuleId='00000000-0000-0000-0008-010000000020', FOpenMode='System', FIsTreeStructure=0, FMaxTreeLevel=null, FIsSlaveUnit=0, FMasterUnitId=null, FSupportWorkflow=0, FSupportUser=0, FSupportDepartment=0, FSupportEditType=0, FSupportAttachment=0, FSupportDataPrivilege=0, FSupportVersion=0, FSupportBusinessLog=0, FSupportNote=0, FSupportSort=0, FSupportPrivilegeField=0, FIsFullTextSearch=0, FSearchAttachment=0, FSupportEqualQuery=0, FUseSystemI18nTable=0, FExtraQueryResultLimit=0, FRecordCreateInfo=0, FRecordUpdateInfo=0, FRecordDeleteInfo=0, FViewPageConditionForList=null, FViewPageConditionForLink=null, FDataSource='default', FTable='TwDeputy', FKeyField='FId', FKeyType='Uuid', FNameField='FName', FMasterField=null, FHomeClassName='com.jeedsoft.quicksilver.wfinstance.DeputyHome', FDaoClassName='com.jeedsoft.quicksilver.wfinstance.dao.impl.DeputyDaoImpl', FServiceClassName='com.jeedsoft.quicksilver.wfinstance.service.impl.DeputyServiceImpl', FActionClassName='com.jeedsoft.quicksilver.wfinstance.action.impl.DeputyActionImpl', FWebServiceUniqueField=null, FUnitFilterSql='', FBusinessFilterSql='', FDescription='';

insert into TsField set FId='4f59e1c4-38ec-47a9-a4ac-69ac3a24424d', FUnitId='ca26ea7b-3292-4184-bb70-0f0f5decb919', FName='FDeputyId', FTitle='代理人',   FType='EntityBox',     FSize=null, FVisible=1, FFilterByRole=0, FRequired=1, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId='00000000-0000-0000-0001-000000001002', FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='8c0e7a84-08ce-4cfe-bf49-0ada961097d3', FUnitId='ca26ea7b-3292-4184-bb70-0f0f5decb919', FName='FId',       FTitle='ID',       FType='InputBox-Key',  FSize=null, FVisible=0, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=0, FDictionaryId=null, FEntityUnitId='ca26ea7b-3292-4184-bb70-0f0f5decb919', FSupportLocalText=null, FSupportI18n=null, FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=null, FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData=null;
insert into TsField set FId='05f975cb-83b9-4e91-bda2-abb0f0995f21', FUnitId='ca26ea7b-3292-4184-bb70-0f0f5decb919', FName='FName',     FTitle='名稱',     FType='InputBox-Text', FSize=50,   FVisible=0, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=0, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='25aad7da-26aa-4478-aa53-b583a84a6932', FUnitId='ca26ea7b-3292-4184-bb70-0f0f5decb919', FName='FUserId',   FTitle='當前用戶', FType='InputBox-Uuid', FSize=null, FVisible=0, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=0, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';

insert into TsRelation set FId='5ca2a538-c201-42d3-8dc7-cb45573449c2', FOppositeId='bfc41302-2504-4bd7-91c8-845433626a89', FName='代理人-代理人', FOppositeName='代理人-代理人', FUnitId1='ca26ea7b-3292-4184-bb70-0f0f5decb919', FUnitId2='00000000-0000-0000-0001-000000001002', FType='field', FTable=null, FField1='FId', FField2='FDeputyId', FDeleteAction1='unset', FDeleteAction2='cancel', FPrivilegeTypeId1=null, FPrivilegeTypeId2=null;

insert into TsPage set FId='00baad3b-3084-4103-8447-f5de7a3c22a6', FName='代理人主列表',   FTitle='代理人列表', FCode='Qs.Deputy.List',       FPlatform='Computer', FType='EntityList', FIcon='quicksilver/image/unit/New.gif',  FUrl='quicksilver/page/template/EntityList.jsp', FActionMethodName='Qs.Deputy.prepareList', FLoadHandler=null, FRelationId=null, FUnitId='ca26ea7b-3292-4184-bb70-0f0f5decb919', FMasterUnitId=null,                                   FIsSlavePage=0, FIndex=null, FDialogWidth=null, FDialogHeight=null, FDialogMaximized=null, FQueryFormAutoQuery=1, FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription=null;
insert into TsPage set FId='abdb2e99-be30-46aa-a573-e77e7eecf66f', FName='代理人選擇列表', FTitle='代理人列表', FCode='Qs.Deputy.SelectList', FPlatform='Computer', FType='EntityList', FIcon='quicksilver/image/unit/New.gif',  FUrl='quicksilver/page/template/EntityList.jsp', FActionMethodName='Qs.Deputy.prepareList', FLoadHandler=null, FRelationId=null, FUnitId='ca26ea7b-3292-4184-bb70-0f0f5decb919', FMasterUnitId=null,                                   FIsSlavePage=0, FIndex=null, FDialogWidth=null, FDialogHeight=null, FDialogMaximized=null, FQueryFormAutoQuery=1, FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription=null;
insert into TsPage set FId='d68057fc-ef74-42e2-a20a-f27cabb81011', FName='代理人表單',     FTitle='表單',       FCode='Qs.Deputy.Edit',       FPlatform='Computer', FType='EntityEdit', FIcon='quicksilver/image/unit/Edit.gif', FUrl='quicksilver/page/template/EntityEdit.jsp', FActionMethodName='Qs.Deputy.prepareEdit', FLoadHandler=null, FRelationId=null, FUnitId='ca26ea7b-3292-4184-bb70-0f0f5decb919', FMasterUnitId='ca26ea7b-3292-4184-bb70-0f0f5decb919', FIsSlavePage=1, FIndex=1,    FDialogWidth=604,  FDialogHeight=453,  FDialogMaximized=null, FQueryFormAutoQuery=1, FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription=null;

--代理人主列表
insert into TsScript set FId='d8e93e4d-9320-46cd-870a-75f35f9d0d4b', FIndex=1, FPageId='00baad3b-3084-4103-8447-f5de7a3c22a6', FUrl='quicksilver/page/wfinstance/DeputyList.js';
insert into TsToolItem set FId='31700310-f062-4b68-9186-ce8ffd3e18da', FPageId='00baad3b-3084-4103-8447-f5de7a3c22a6', FCode='OnGuard',  FName='在岗', FHint=null,                 FLabel=null, FType='Button',      FAlign='left',  FIndex=1, FWidth=null, FIcon=null,                               FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine='',   FVisibleCondition=null, FEnableCondition='!${user.FOnGuard}',  FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='DeputyList.doOnGuard';
insert into TsToolItem set FId='70056d3d-6296-4962-a6c1-07007a5c5343', FPageId='00baad3b-3084-4103-8447-f5de7a3c22a6', FCode='OffGuard', FName='离岗', FHint=null,                 FLabel=null, FType='Button',      FAlign='left',  FIndex=2, FWidth=null, FIcon=null,                               FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine='',   FVisibleCondition=null, FEnableCondition='!!${user.FOnGuard}', FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='DeputyList.doOffGuard';
insert into TsToolItem set FId='a6505872-9518-486e-aa57-c549fd9f3ee1', FPageId='00baad3b-3084-4103-8447-f5de7a3c22a6', FCode='Add',      FName='新增', FHint=null,                 FLabel=null, FType='Button',      FAlign='left',  FIndex=3, FWidth=null, FIcon=null,                               FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine='',   FVisibleCondition=null, FEnableCondition=null,                 FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='DeputyList.doAdd';
insert into TsToolItem set FId='bad22392-016d-485c-8d66-8346a776232d', FPageId='00baad3b-3084-4103-8447-f5de7a3c22a6', FCode='Delete',   FName='刪除', FHint='刪除當前選中的記錄', FLabel=null, FType='Button',      FAlign='left',  FIndex=3, FWidth=null, FIcon='quicksilver/image/16/Delete.gif',  FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine='',   FVisibleCondition=null, FEnableCondition=null,                 FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doDelete';
insert into TsToolItem set FId='63724464-6526-4105-94f3-94f5dbe1acb2', FPageId='00baad3b-3084-4103-8447-f5de7a3c22a6', FCode='Refresh',  FName='刷新', FHint='刷新清單內容',       FLabel=null, FType='Button',      FAlign='left',  FIndex=4, FWidth=null, FIcon='quicksilver/image/16/Refresh.gif', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine='',   FVisibleCondition=null, FEnableCondition=null,                 FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doRefresh';

--代理人選擇列表
insert into TsToolItem set FId='8b58ab9b-f1e0-479e-a4da-6f304abd6cba', FPageId='abdb2e99-be30-46aa-a573-e77e7eecf66f', FCode='ConfirmSelection', FName='確定', FHint=null,                                                   FLabel=null, FType='Button', FAlign='right', FIndex=1, FWidth=0, FIcon='quicksilver/image/16/Ok.gif',   FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doSelectListConfirm';
insert into TsToolItem set FId='608780a5-9b87-41d1-a48a-cb45e00e133a', FPageId='abdb2e99-be30-46aa-a573-e77e7eecf66f', FCode='Add',              FName='新增', FHint='新增一筆記錄',                                         FLabel=null, FType='Button', FAlign='right', FIndex=2, FWidth=0, FIcon='quicksilver/image/16/Add.gif',  FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doAdd';
insert into TsToolItem set FId='b580677e-8762-4bee-8931-7139bdc40d28', FPageId='abdb2e99-be30-46aa-a573-e77e7eecf66f', FCode='Open',             FName='打開', FHint='打開當前選中的記錄。如果選中了多筆，第一筆將被打開。', FLabel=null, FType='Button', FAlign='right', FIndex=3, FWidth=0, FIcon='quicksilver/image/16/Open.gif', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doOpen';

--代理人表單
insert into TsToolItem set FId='3310b0f2-9250-476a-a24a-fdb8c4b5f39c', FPageId='d68057fc-ef74-42e2-a20a-f27cabb81011', FCode='Save',  FName='保存', FHint=null, FLabel=null, FType='Button',      FAlign='right', FIndex=1, FWidth=0, FIcon='quicksilver/image/16/Save.gif',  FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityEdit.doSave';

insert into TsForm set FDefault=1, FEditableCondition=null, FGroupMode='Double', FId='be9ed35d-85fc-4b04-a494-30fee0f0af9a', FIndex=1, FName='默認', FPageId=null, FUnitId='ca26ea7b-3292-4184-bb70-0f0f5decb919';
java setFormFields('be9ed35d-85fc-4b04-a494-30fee0f0af9a', '基本資訊', 'c6877a7f-58a1-4d1e-b4ca-0908cc012c03', null, 'FDeputyId');

insert into TsList set FDefault=1, FId='84d12970-e72d-477d-81da-de1082c494db', FIndex=null, FMultiPage=1, FName='代理人列表（默認）', FPageId=null,                                   FUnitId='ca26ea7b-3292-4184-bb70-0f0f5decb919';
insert into TsList set FDefault=0, FId='387799a4-d723-4914-9603-41d888bf41b4', FIndex=null, FMultiPage=1, FName='代理人選擇列表',     FPageId='abdb2e99-be30-46aa-a573-e77e7eecf66f', FUnitId='ca26ea7b-3292-4184-bb70-0f0f5decb919';
insert into TsList set FDefault=0, FId='82514611-6671-4973-b0b5-d1a1338423f7', FIndex=null, FMultiPage=1, FName='代理人首頁列表',     FPageId='9b796431-f132-49d1-b306-5d1d618f9c1b', FUnitId='ca26ea7b-3292-4184-bb70-0f0f5decb919';
java setListFields('84d12970-e72d-477d-81da-de1082c494db', 'FDeputyId');
java setListFields('387799a4-d723-4914-9603-41d888bf41b4', 'FDeputyId');
java setListFields('82514611-6671-4973-b0b5-d1a1338423f7', 'FDeputyId');

java setImportTemplateFields('ca26ea7b-3292-4184-bb70-0f0f5decb919', 'FDeputyId');

insert into TsQuerySchema set FId='f03ada83-0884-4dcd-a09d-1318828e2cbb', FUnitId='ca26ea7b-3292-4184-bb70-0f0f5decb919', FName='全部代理人',     FType='condition',  FPublic=1, FVisible=1, FTemp=0, FGlobalAutoQuery=0, FShare=0, FUserId=null, FConditionId=null, FSqlSource='None', FSql=null, FIndex=1, FUpdateTime=null, FOriginSchemaId=null, FParentId=null;
insert into TsQuerySchema set FId='ee18cf19-107a-4093-af8c-097d865b075e', FUnitId='ca26ea7b-3292-4184-bb70-0f0f5decb919', FName='代理人我的最愛', FType='collection', FPublic=1, FVisible=1, FTemp=0, FGlobalAutoQuery=0, FShare=0, FUserId=null, FConditionId=null, FSqlSource='None', FSql=null, FIndex=3, FUpdateTime=null, FOriginSchemaId=null, FParentId=null;

insert into TsMenu set FId='5905fd8f-a96c-4668-86e3-36615cf7aa02', FParentId='00000000-0000-0000-0008-010000000020', FIndex=2, FTreeLevel=3, FTreeSerial='001.002.002', FName='代理人', FIcon='quicksilver/image/unit/New.gif', FPageId='00baad3b-3084-4103-8447-f5de7a3c22a6', FQuerySchemaId=null, FQuerySchemaLocked=0, FArguments='', FLicensed=1, FEnabled=1, FShowMenuNameInTab=0, FReplaceByChildren=0, FFunctionName=null, FSubMenuSource='MenuTable', FSubMenuRoutine='';

--Wf.WorkItem-------------------------------------------------------------------

alter table TwWorkItem add column FDeputingStartTime timestamp;
alter table TwWorkItem add column FHandleUserId uuid;
alter table TwWorkItem add column FDeputable bit;

insert into TsField set FId='f19eeb3f-799b-4316-9131-262c61488695', FUnitId='00000000-0000-0000-0001-000000003005', FName='FDeputingStartTime', FTitle='超时代理开始时间', FType='DateBox-DateTime',    FSize=null, FVisible=1, FFilterByRole=0, FRequired=1, FReadOnly=0, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='15d40b24-d16f-4fdd-a894-bb9309a86924', FUnitId='00000000-0000-0000-0001-000000003005', FName='FHandleUserId',      FTitle='處理人',           FType='InputBox-Uuid',       FSize=null, FVisible=0, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=0, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='81a69b21-01a4-4eb6-b8a9-7681efd04237', FUnitId='00000000-0000-0000-0001-000000003005', FName='FDeputable',         FTitle='是否可以代理',     FType='CheckBox',            FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';

java setListFields('64476587-1ddc-42e6-81ee-98fb46f81004', 'FCreateTime,FEndTime,FStatus,FProcessUserId,FParticipantName,FWorkflowId,FNodeId,FProcessId,FHandleUserId');
java setListFields('790b6cfc-73be-438a-bc1a-b80cac8736a6', 'FEndTime,FNodeId,FParticipantName,FResult,FComment,FHandleUserId');
java setListFields('905e4469-69bf-4db5-aaf7-b8d54271941a', 'FCreateTime,FProcessUserId,FWorkflowId,FNodeId,FProcessId,FHandleUserId');
java setListFields('7a087677-fce8-47a6-a36e-fe30b64eb076', 'FCreateTime,FProcessUserId,FWorkflowId,FNodeId,FProcessId,FHandleUserId');

update TsQuerySchema set FSqlSource='JavaClass', FSql='com.jeedsoft.quicksilver.handler.queryschema.WorkItemToDoSqlGenerator' where FId='d6a812ef-c2f5-4bc3-8571-eb2e77f1906f';
update TsQuerySchema set FSqlSource='Text',      FSql='FStatus=''Finished'' and FHandleUserId=${user.FId} ' where FId='ca134a4c-e679-4a1a-8622-f53a3823213a';
update TsQuerySchema set FSqlSource='JavaClass', FSql='com.jeedsoft.quicksilver.handler.queryschema.WorkItemAllSqlGenerator' where FId='34ba4726-69a8-4818-b855-dea71ae85c92';

--Wf.Node-----------------------------------------------------------------------

alter table TwNode add column FAutoCompleteMode varchar(20);
alter table TwNode add column FAutoCompleteHours int;
alter table TwNode add column FAutoCompleteResult varchar(50);
alter table TwNode add column FDeputeMode varchar(20);
alter table TwNode add column FDeputeHours int;

update TwNode set FAutoCompleteMode=FTimeoutMode, FAutoCompleteHours=FTimeoutDays*24, FAutoCompleteResult=FTimeoutResult;

alter table TwNode drop column FTimeoutMode;
alter table TwNode drop column FTimeoutDays;
alter table TwNode drop column FTimeoutResult;

insert into TsField set FId='190e74dd-c992-4680-a2c8-e4ca5645120f', FUnitId='fd32e77e-07ce-442a-9687-671c017d03ef', FName='FAutoCompleteHours',  FTitle='超時时數',     FType='InputBox-Integer',    FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1,  FIsNewRow=0,    FListWidth=80,  FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null,                                                                                                 FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='57acedee-f1a5-43dc-a038-3b475d1d8f06', FUnitId='fd32e77e-07ce-442a-9687-671c017d03ef', FName='FAutoCompleteMode',   FTitle='超時模式',     FType='ComboBox-SelectOnly', FSize=20,   FVisible=1, FFilterByRole=0, FRequired=1, FReadOnly=0, FQueryable=1, FDictionaryId='65670474-7498-4d59-aa59-74077b0c3cfb', FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1,  FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null,                                                                                                 FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='203302df-493e-4e4d-ae62-7c63de906eab', FUnitId='fd32e77e-07ce-442a-9687-671c017d03ef', FName='FAutoCompleteResult', FTitle='活動結果',     FType='InputBox-Text',       FSize=50,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1,  FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null,                                                                                                 FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='fb835911-03fd-4b07-afc8-f5d9a0c04c9f', FUnitId='fd32e77e-07ce-442a-9687-671c017d03ef', FName='FDeputeHours',        FTitle='代理時長',     FType='InputBox-Integer',    FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=80, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null,                                                                                                 FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='bb820eb2-97c5-421d-a7c4-f3670a2d8d0e', FUnitId='fd32e77e-07ce-442a-9687-671c017d03ef', FName='FDeputeMode',         FTitle='代理模式',     FType='ComboBox-SelectOnly', FSize=20,   FVisible=1, FFilterByRole=0, FRequired=1, FReadOnly=0, FQueryable=1, FDictionaryId='3115401b-fa1c-407a-97d7-62ae67bb82a1', FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1,  FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null,                                                                                                 FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';

delete from TsField where FId in('fe7c6b40-b63e-4d3d-a08f-05897ed81980','fa10d327-cb2a-4984-ac17-b5b4e63d9c8b','fafcde32-8cf3-498a-9adf-4c3208fd9e58');

java setEditFields('6df4a7d7-e1a4-4306-ae26-dc6be86dee45', 'FName,FCode,FAutoFinish,FJoinMode,FJoinConditionType,FJoinCondition,FAutoCompleteMode,FAutoCompleteHours,FAutoCompleteResult');
java setEditFields('ae542383-9d52-43d7-8940-962af2465fbb', 'FName,FCode,FMultiWorkItem,FJoinMode,FJoinCondition,FJoinConditionType,FUrl,FUrlType,FPrivilegeId,FExpectedResult,FSupportClone,FSupportTransfer,FDeputeMode,FAutoCompleteMode,FAutoCompleteHours,FAutoCompleteResult,FDeputeHours');
java setListFields('d10d89d8-ff83-4b64-80a8-3c1bf462239d', 'FName,FCode,FDeputeMode,FAutoCompleteMode,FAutoCompleteHours,FDeputeHours');
java setFormFields('dc16b2d8-e4e9-4801-926f-7b9479d7146c', '-', '38720435-2b81-4bbf-8288-591d481ab509', null, 'FName,FCode,FMultiWorkItem,FExpectedResult,FAutoFinish', '聚合', 'a78770f1-5a4e-4b1e-b081-1b03002e6c02', null, 'FJoinMode,FJoinConditionType,FJoinCondition', '自動完成設置', '5cfe8dda-fb78-4d1c-8e8f-8af8a0f72b1c', null, 'FAutoCompleteMode,FAutoCompleteHours,FAutoCompleteResult', '代理設置', '50496f53-fe5c-4861-a33e-2f20c2bffd52', null, 'FDeputeMode,FDeputeHours', '其它', '941b466d-e4f5-48f3-965c-d37e30a05daf', null, 'FPrivilegeId');
java setImportTemplateFields('fd32e77e-07ce-442a-9687-671c017d03ef', 'FUrl,FUrlType,FSupportClone,FSupportTransfer,FName,FCode,FMultiWorkItem,FExpectedResult,FAutoFinish,FJoinMode,FJoinConditionType,FJoinCondition,FAutoCompleteMode,FAutoCompleteHours,FAutoCompleteResult,FDeputeMode,FDeputeHours,FPrivilegeId');

--Qs.User-----------------------------------------------------------------------

alter table TsUser add column FOnGuard bit default 1;
insert into TsField set FId='4096c13a-be5c-47a5-b175-fb1514650c3e', FUnitId='00000000-0000-0000-0001-000000001002', FName='FOnGuard',      FTitle='是否在崗', FType='CheckBox',            FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
java setImportTemplateFields('00000000-0000-0000-0001-000000001002', 'FMobile,FOnGuard,FIndex,FName,FLoginName,FDepartmentId,FManagerId,FEmail,FGender,FBirthday,FDuty,FDescription');
update TsUser set FOnGuard=1 where 1=1;

--Qs.Parameter----------------

insert into TsSystemParameter set FId='b16297c6-2dac-4c00-901e-8fcf79e928ad', FKey='QsDeputeHours',FValue='24';

--Qs.ParameterDefinition----------------
update TsParameterDefinition set FIndex = FIndex + 1 where FParameterGroupId = 'a1f8cfc6-2cc8-4c27-ba78-74c1455b8ca9' and FIndex >=3;
insert into TsParameterDefinition set FId='9ba8456d-0168-4741-9b59-5fe2748d7fca', FName='默認代理時數', FCode='QsDeputeHours', FParameterGroupId='a1f8cfc6-2cc8-4c27-ba78-74c1455b8ca9', FType='InputBox-Integer', FRange='System', FRowSpan=1, FColSpan=1, FRequired=1, FVisible=1, FIndex=3;

--Qs.TextResource
update TsTextResource set FCode='E.Wf.WorkItem.UserNotParticipantOrDeputy', FValue='您不是該工作項的參與者或者代理人，不能執行該操作。' where FId='d6221a61-fbbf-4220-8af7-9263e2fe07de';
insert into TsTextResource set FId='b746e7fd-2d8a-4967-b183-63c2ecdd1138', FCode='E.Wf.Deputy.CannnotBeSelf',							FValue='代理人不能選擇本人。';

--Qs.Dictionary
insert into TsDictionary set FId='3115401b-fa1c-407a-97d7-62ae67bb82a1', FName='QS-工作流節點-代理模式', FBuiltin=1, FTextAsValue=0, FParentId=null, FDescription=null;
insert into TsDictionaryItem set FId='d7fe4d7c-1db4-4763-b506-79208e2b436b', FDictionaryId='3115401b-fa1c-407a-97d7-62ae67bb82a1', FValue='DefaultHours',		FText='系統默認時數',	FIndex=1;
insert into TsDictionaryItem set FId='fc1c4596-c8f1-4b38-9a43-4e221cd38406', FDictionaryId='3115401b-fa1c-407a-97d7-62ae67bb82a1', FValue='CustomHours',		FText='自定義時數',		FIndex=2;

update TsDictionary set FName='QS-工作流節點-自動完成模式' where FId='65670474-7498-4d59-aa59-74077b0c3cfb';

