--Qs.DataLink-------------------------------------------------------------------

create table TsDataLink
(
	FId uuid primary key,
	FName varchar(50),
	FURLAddress varchar(500),
	FNote varchar(500),
	FEncryption bit,
	FOpenModel varchar(50),
	FDefaultOpen bit,
	FModel varchar(100),
	FUnitId uuid,
	FIndex int,
	FImage varchar(300)
);

insert into TsUnit set FId='71a3a0a5-47bd-4320-80f8-399cdc98db6f', FCode='Qs.DataLink', FName='資料鏈接', FIcon='quicksilver/image/unit/New.gif', FEditId='541c707d-79dd-4dbb-85fc-1a214fd5fce4', FModuleId='00000000-0000-0000-0008-990000000010', FOpenMode='System', FIsTreeStructure=0, FMaxTreeLevel=null, FIsSlaveUnit=0, FMasterUnitId=null, FSupportWorkflow=0, FSupportUser=0, FSupportDepartment=0, FSupportEditType=0, FSupportAttachment=0, FSupportDataPrivilege=0, FSupportVersion=0, FSupportBusinessLog=0, FSupportNote=0, FSupportSort=1, FSupportPrivilegeField=0, FIsFullTextSearch=0, FSearchAttachment=0, FSupportEqualQuery=0, FUseSystemI18nTable=0, FExtraQueryResultLimit=0, FRecordCreateInfo=0, FRecordUpdateInfo=0, FRecordDeleteInfo=0, FViewPageConditionForList=null, FViewPageConditionForLink=null, FDataSource='default', FTable='TsDataLink', FKeyField='FId', FKeyType='Uuid', FNameField='FName', FMasterField=null, FHomeClassName='com.jeedsoft.quicksilver.datalink.DataLinkHome', FDaoClassName='com.jeedsoft.quicksilver.datalink.dao.impl.DataLinkDaoImpl', FServiceClassName='com.jeedsoft.quicksilver.datalink.service.impl.DataLinkServiceImpl', FActionClassName='com.jeedsoft.quicksilver.datalink.action.impl.DataLinkActionImpl', FWebServiceUniqueField=null, FUnitFilterSql='', FBusinessFilterSql='', FDescription='';

insert into TsField set FId='d6ca1d84-f8a0-4d0c-820a-5fccb5baadf5', FUnitId='71a3a0a5-47bd-4320-80f8-399cdc98db6f', FName='FDefaultOpen', FTitle='啟用', FType='CheckBox',         FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,                  FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null,                             FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='0e72b04b-12dd-45df-a799-56a20c071c2e', FUnitId='71a3a0a5-47bd-4320-80f8-399cdc98db6f', FName='FEncryption',  FTitle='加密',     FType='CheckBox',         FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,                  FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null,                             FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='9c3eb69a-2a40-4ffa-8ace-2abd52064577', FUnitId='71a3a0a5-47bd-4320-80f8-399cdc98db6f', FName='FId',          FTitle='ID',       FType='InputBox-Key',     FSize=null, FVisible=0, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=0, FDictionaryId=null,                                   FEntityUnitId='71a3a0a5-47bd-4320-80f8-399cdc98db6f', FSupportLocalText=null, FSupportI18n=null, FLocalTextField=null, FRelationTable=null,                  FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=null, FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null,                             FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData=null;
insert into TsField set FId='81747d1e-f6e9-4e84-9977-55a8e3242b1c', FUnitId='71a3a0a5-47bd-4320-80f8-399cdc98db6f', FName='FImage',       FTitle='圖示',     FType='InputBox-Text',    FSize=300,  FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=0, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,                  FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=3, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue='quicksilver/image/unit/New.gif', FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='5edd7dc1-dba3-4a2e-8bc0-f6d4e160b2cc', FUnitId='71a3a0a5-47bd-4320-80f8-399cdc98db6f', FName='FIndex',       FTitle='順序',     FType='InputBox-Integer', FSize=null, FVisible=0, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=0, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=null, FSupportI18n=null, FLocalTextField=null, FRelationTable=null,                  FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=null, FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null,                             FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData=null;
insert into TsField set FId='b448b87d-610e-470e-adaf-d6ace98edf7b', FUnitId='71a3a0a5-47bd-4320-80f8-399cdc98db6f', FName='FModel',       FTitle='開啟模式', FType='RadioBox',         FSize=100,  FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId='61484ac1-d88f-4acc-ad9e-92855bc6de59', FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,                  FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null,                             FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='84ae9d7e-e69a-46dc-ad3f-6e4f8189ce76', FUnitId='71a3a0a5-47bd-4320-80f8-399cdc98db6f', FName='FName',        FTitle='名稱',     FType='InputBox-Text',    FSize=50,   FVisible=1, FFilterByRole=0, FRequired=1, FReadOnly=0, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=null, FSupportI18n=null, FLocalTextField=null, FRelationTable=null,                  FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=null, FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null,                             FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData=null;
insert into TsField set FId='8b4af1f3-7e9d-4e8c-9df3-13ae8e519e50', FUnitId='71a3a0a5-47bd-4320-80f8-399cdc98db6f', FName='FNote',        FTitle='備注',     FType='TextBox',          FSize=500,  FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,                  FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=0, FRowSpan=3, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null,                             FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='74d93d96-6535-4baf-9cbe-84d85e02ac4a', FUnitId='71a3a0a5-47bd-4320-80f8-399cdc98db6f', FName='FOpenModel',   FTitle='開啟模式', FType='MultiCheckBox',    FSize=50,   FVisible=0, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=0, FDictionaryId='61484ac1-d88f-4acc-ad9e-92855bc6de59', FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable='TsDataLinkOpenModel', FRelationCapacity=10,   FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null,                             FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='cd3ba57d-e88b-4fef-8325-168d5e9eb6b2', FUnitId='71a3a0a5-47bd-4320-80f8-399cdc98db6f', FName='FURLAddress',  FTitle='URL',      FType='InputBox-Url',     FSize=500,  FVisible=1, FFilterByRole=0, FRequired=1, FReadOnly=0, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,                  FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=3, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null,                             FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='5bea231a-2390-4ce3-9926-9b286dab193f', FUnitId='71a3a0a5-47bd-4320-80f8-399cdc98db6f', FName='FUnitId',      FTitle='單元',     FType='EntityBox',        FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId='00000000-0000-0000-0001-000000000001', FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null,                  FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null,                             FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';

java setQueryFormFields('71a3a0a5-47bd-4320-80f8-399cdc98db6f', 'FName');

insert into TsRelation set FId='9979a43b-53e7-416f-b825-bb3d2c7ebd22', FOppositeId='60b204b5-aa61-4918-a335-0c29acecf620', FName='資料鏈接-單元', FOppositeName='單元-資料鏈接', FUnitId1='71a3a0a5-47bd-4320-80f8-399cdc98db6f', FUnitId2='00000000-0000-0000-0001-000000000001', FType='field', FTable=null, FField1='FId', FField2='FUnitId', FDeleteAction1='unset', FDeleteAction2='cancel', FPrivilegeTypeId1=null, FPrivilegeTypeId2=null;

insert into TsPage set FId='63a781e5-8817-49f7-9fc7-e4cbbf1cffd6', FName='資料鏈接主列表',   FTitle='資料鏈接列表', FCode='Qs.DataLink.List',       FPlatform='Computer', FType='EntityList', FIcon='quicksilver/image/unit/New.gif',  FUrl='quicksilver/page/template/EntityList.jsp', FActionMethodName='Qs.DataLink.prepareList', FLoadHandler=null, FRelationId=null, FUnitId='71a3a0a5-47bd-4320-80f8-399cdc98db6f', FMasterUnitId=null,                                   FIsSlavePage=0, FIndex=null, FDialogWidth=null, FDialogHeight=null, FDialogMaximized=null, FQueryFormAutoQuery=1, FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription=null;
insert into TsPage set FId='417a050a-5e82-4cad-8b2c-4b776d560781', FName='資料鏈接選擇列表', FTitle='資料鏈接列表', FCode='Qs.DataLink.SelectList', FPlatform='Computer', FType='EntityList', FIcon='quicksilver/image/unit/New.gif',  FUrl='quicksilver/page/template/EntityList.jsp', FActionMethodName='Qs.DataLink.prepareList', FLoadHandler=null, FRelationId=null, FUnitId='71a3a0a5-47bd-4320-80f8-399cdc98db6f', FMasterUnitId=null,                                   FIsSlavePage=0, FIndex=null, FDialogWidth=null, FDialogHeight=null, FDialogMaximized=null, FQueryFormAutoQuery=1, FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription=null;
insert into TsPage set FId='d0c87f85-d3b9-4c56-ad0b-85d50cfcc38c', FName='資料鏈接排序',     FTitle='排序',         FCode='Qs.DataLink.Sort',       FPlatform='Computer', FType='Sort',       FIcon='quicksilver/image/unit/New.gif',  FUrl='quicksilver/page/template/Sorter.jsp',     FActionMethodName='Qs.DataLink.prepareSort', FLoadHandler=null, FRelationId=null, FUnitId='71a3a0a5-47bd-4320-80f8-399cdc98db6f', FMasterUnitId=null,                                   FIsSlavePage=0, FIndex=null, FDialogWidth=null, FDialogHeight=null, FDialogMaximized=null, FQueryFormAutoQuery=1, FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription=null;
insert into TsPage set FId='2924ce78-a6d5-4bd2-b934-cbdd7149105b', FName='資料鏈接表單',     FTitle='表單',         FCode='Qs.DataLink.Edit',       FPlatform='Computer', FType='EntityEdit', FIcon='quicksilver/image/unit/Edit.gif', FUrl='quicksilver/page/template/EntityEdit.jsp', FActionMethodName='Qs.DataLink.prepareEdit', FLoadHandler=null, FRelationId=null, FUnitId='71a3a0a5-47bd-4320-80f8-399cdc98db6f', FMasterUnitId='71a3a0a5-47bd-4320-80f8-399cdc98db6f', FIsSlavePage=1, FIndex=1,    FDialogWidth=604,  FDialogHeight=453,  FDialogMaximized=null, FQueryFormAutoQuery=1, FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription=null;

--資料鏈接主列表
insert into TsToolItem set FId='26dec3a2-83fa-464f-bb4c-ee0658b45fe8', FPageId='63a781e5-8817-49f7-9fc7-e4cbbf1cffd6', FCode='Add',     FName='新增', FHint='新增一筆記錄',                                         FLabel=null, FType='Button',      FAlign='right', FIndex=1, FWidth=0, FIcon='quicksilver/image/16/Add.gif',     FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doAdd';
insert into TsToolItem set FId='d9f8d50f-5738-42d9-b205-fd5a23ad494d', FPageId='63a781e5-8817-49f7-9fc7-e4cbbf1cffd6', FCode='Open',    FName='打開', FHint='打開當前選中的記錄。如果選中了多筆，第一筆將被打開。', FLabel=null, FType='Button',      FAlign='right', FIndex=2, FWidth=0, FIcon='quicksilver/image/16/Open.gif',    FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doOpen';
insert into TsToolItem set FId='053bbadf-69e1-43da-9b40-8241eb49a0d4', FPageId='63a781e5-8817-49f7-9fc7-e4cbbf1cffd6', FCode='Delete',  FName='刪除', FHint='刪除當前選中的記錄',                                   FLabel=null, FType='Button',      FAlign='right', FIndex=3, FWidth=0, FIcon='quicksilver/image/16/Delete.gif',  FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doDelete';
insert into TsToolItem set FId='3b690e67-36fb-4518-b0cd-ceab79cdf037', FPageId='63a781e5-8817-49f7-9fc7-e4cbbf1cffd6', FCode='Refresh', FName='刷新', FHint='刷新清單內容',                                         FLabel=null, FType='Button',      FAlign='right', FIndex=4, FWidth=0, FIcon='quicksilver/image/16/Refresh.gif', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doRefresh';
insert into TsToolItem set FId='c5dda9fd-f58e-4b89-9aca-29f24177e237', FPageId='63a781e5-8817-49f7-9fc7-e4cbbf1cffd6', FCode='Other',   FName=null,   FHint=null,                                                   FLabel=null, FType='ComboButton', FAlign='right', FIndex=5, FWidth=0, FIcon='quicksilver/image/16/Other.gif',   FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource='SubItemTable', FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='None',       FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler=null;
insert into TsToolSubItem set FId='0b15ca94-1571-4d82-a39d-bcce5a9b011c', FToolItemId='c5dda9fd-f58e-4b89-9aca-29f24177e237', FCode='Sort',        FName='排序',       FExpandMode='None', FIndex=-1, FIcon='quicksilver/image/16/Sort.gif',   FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FEventHandler='EntityList.doSort';
insert into TsToolSubItem set FId='32613b62-d071-4c65-b36b-5bc285a4dfbb', FToolItemId='c5dda9fd-f58e-4b89-9aca-29f24177e237', FCode='Import',      FName='導入',       FExpandMode='None', FIndex=1,  FIcon='quicksilver/image/16/Import.gif', FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FEventHandler='EntityList.doImport';
insert into TsToolSubItem set FId='d7bc214a-a3e0-447c-b86a-1be1c3075312', FToolItemId='c5dda9fd-f58e-4b89-9aca-29f24177e237', FCode='ExcelExport', FName='匯出 Excel', FExpandMode='None', FIndex=2,  FIcon='quicksilver/image/16/Excel.gif',  FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FEventHandler='EntityList.doExcelExport';
insert into TsToolSubItem set FId='a22a7998-386b-4b2f-bfdd-fcd49506aca1', FToolItemId='c5dda9fd-f58e-4b89-9aca-29f24177e237', FCode='BillPrint',   FName='單據列印',   FExpandMode='None', FIndex=3,  FIcon='quicksilver/image/unit/Bill.gif', FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FEventHandler='EntityList.doBillPrint';

--資料鏈接選擇列表
insert into TsToolItem set FId='3a4da0cf-1311-4184-b194-8d5c1d24f972', FPageId='417a050a-5e82-4cad-8b2c-4b776d560781', FCode='ConfirmSelection', FName='確定', FHint=null,                                                   FLabel=null, FType='Button', FAlign='right', FIndex=1, FWidth=0, FIcon='quicksilver/image/16/Ok.gif',   FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doSelectListConfirm';
insert into TsToolItem set FId='a4ec2884-5422-4df5-b553-2b4e48793ebd', FPageId='417a050a-5e82-4cad-8b2c-4b776d560781', FCode='Add',              FName='新增', FHint='新增一筆記錄',                                         FLabel=null, FType='Button', FAlign='right', FIndex=2, FWidth=0, FIcon='quicksilver/image/16/Add.gif',  FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doAdd';
insert into TsToolItem set FId='fd3af17f-611c-4a49-a676-c3ba418e7b8d', FPageId='417a050a-5e82-4cad-8b2c-4b776d560781', FCode='Open',             FName='打開', FHint='打開當前選中的記錄。如果選中了多筆，第一筆將被打開。', FLabel=null, FType='Button', FAlign='right', FIndex=3, FWidth=0, FIcon='quicksilver/image/16/Open.gif', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doOpen';

--資料鏈接排序
insert into TsToolItem set FId='6155d315-cdb3-4b0c-80e7-87fdb76f47d6', FPageId='d0c87f85-d3b9-4c56-ad0b-85d50cfcc38c', FCode='MoveUp',     FName='上升', FHint=null, FLabel=null, FType='Button', FAlign='left',  FIndex=1, FWidth=0, FIcon='quicksilver/image/16/MoveUp.gif',     FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='Sorter.doMoveUp';
insert into TsToolItem set FId='48191f9f-f77c-4d2d-af62-aa396d3254c5', FPageId='d0c87f85-d3b9-4c56-ad0b-85d50cfcc38c', FCode='MoveDown',   FName='下降', FHint=null, FLabel=null, FType='Button', FAlign='left',  FIndex=2, FWidth=0, FIcon='quicksilver/image/16/MoveDown.gif',   FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='Sorter.doMoveDown';
insert into TsToolItem set FId='34b84928-eadb-472f-8058-99a8513da195', FPageId='d0c87f85-d3b9-4c56-ad0b-85d50cfcc38c', FCode='MoveTop',    FName='置頂', FHint=null, FLabel=null, FType='Button', FAlign='left',  FIndex=3, FWidth=0, FIcon='quicksilver/image/16/MoveTop.gif',    FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='Sorter.doMoveTop';
insert into TsToolItem set FId='26a131e0-98b4-46f7-8876-285fcc7cf3b8', FPageId='d0c87f85-d3b9-4c56-ad0b-85d50cfcc38c', FCode='MoveBottom', FName='置底', FHint=null, FLabel=null, FType='Button', FAlign='left',  FIndex=4, FWidth=0, FIcon='quicksilver/image/16/MoveBottom.gif', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='Sorter.doMoveBottom';
insert into TsToolItem set FId='385bb0ca-acc6-4520-b9de-4ddc96b63241', FPageId='d0c87f85-d3b9-4c56-ad0b-85d50cfcc38c', FCode='Save',       FName='保存', FHint=null, FLabel=null, FType='Button', FAlign='right', FIndex=1, FWidth=0, FIcon='quicksilver/image/16/Save.gif',       FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='Sorter.doSave';

--資料鏈接表單
insert into TsScript set FId='cd4c4ed1-590e-45de-bced-cf14e28f4754', FIndex=1, FPageId='2924ce78-a6d5-4bd2-b934-cbdd7149105b', FUrl='quicksilver/page/datalink/DataLinkForm.js';
insert into TsToolItem set FId='23888627-2e1e-4b1b-8f08-8a741ae1e036', FPageId='2924ce78-a6d5-4bd2-b934-cbdd7149105b', FCode='Save',  FName='保存', FHint=null, FLabel=null, FType='Button',      FAlign='right', FIndex=1, FWidth=0, FIcon='quicksilver/image/16/Save.gif',  FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityEdit.doSave';
insert into TsToolItem set FId='bd0de481-c946-4829-b509-29b8e1f47750', FPageId='2924ce78-a6d5-4bd2-b934-cbdd7149105b', FCode='Other', FName=null,   FHint=null, FLabel=null, FType='ComboButton', FAlign='right', FIndex=2, FWidth=0, FIcon='quicksilver/image/16/Other.gif', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource='SubItemTable', FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='None',       FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler=null;
insert into TsToolSubItem set FId='c18849bd-0f33-4688-89ac-c13e21ab6392', FToolItemId='bd0de481-c946-4829-b509-29b8e1f47750', FCode='BillPrint', FName='單據列印', FExpandMode='None', FIndex=1, FIcon='quicksilver/image/unit/Bill.gif', FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FEventHandler='EntityEdit.doBillPrint';

insert into TsForm set FDefault=1, FEditableCondition=null, FGroupMode='Double', FId='04659731-6687-451a-827f-a9f46278db02', FIndex=1, FName='默認', FPageId=null, FUnitId='71a3a0a5-47bd-4320-80f8-399cdc98db6f';
java setFormFields('04659731-6687-451a-827f-a9f46278db02', '基本資訊', '8786d358-f9b6-40c2-977e-c08a0264c760', null, 'FName,FURLAddress,FNote,FEncryption,FDefaultOpen,FModel,FUnitId,FImage');

insert into TsList set FDefault=1, FId='af468b40-d50f-494d-bfd7-40d700ad955d', FIndex=null, FMultiPage=1, FName='資料鏈接列表（默認）', FPageId=null,                                   FUnitId='71a3a0a5-47bd-4320-80f8-399cdc98db6f';
insert into TsList set FDefault=0, FId='0165c301-b464-4e68-b559-61eb635e92b7', FIndex=null, FMultiPage=1, FName='資料鏈接選擇列表',     FPageId='417a050a-5e82-4cad-8b2c-4b776d560781', FUnitId='71a3a0a5-47bd-4320-80f8-399cdc98db6f';
insert into TsList set FDefault=0, FId='5837f91a-4eba-43aa-ad70-6d984af7c40a', FIndex=null, FMultiPage=1, FName='資料鏈接首頁列表',     FPageId='9b796431-f132-49d1-b306-5d1d618f9c1b', FUnitId='71a3a0a5-47bd-4320-80f8-399cdc98db6f';
java setListFields('af468b40-d50f-494d-bfd7-40d700ad955d', 'FName,FURLAddress,FEncryption,FDefaultOpen,FModel,FUnitId');
java setListFields('0165c301-b464-4e68-b559-61eb635e92b7', 'FName');
java setListFields('5837f91a-4eba-43aa-ad70-6d984af7c40a', 'FName');

insert into TsPrivilege set FId='b825d047-aa34-437f-a511-ae6c2c9207a3', FName='資料鏈接管理權限', FUnitId='71a3a0a5-47bd-4320-80f8-399cdc98db6f', FModuleId='00000000-0000-0000-0008-990000000010', FPrivilegeTypeId='00000000-0000-0000-1005-000000000006', FUseExisting=0, FSourcePrivilegeId=null, FEditId='5992c3d2-0b4a-478c-bbfa-2089819ad575', FIndex=null;

java setImportTemplateFields('71a3a0a5-47bd-4320-80f8-399cdc98db6f', 'FName,FURLAddress,FNote,FEncryption,FDefaultOpen,FModel,FUnitId,FImage');

insert into TsQuerySchema set FId='1743493b-3278-410b-9021-70934068c4f4', FUnitId='71a3a0a5-47bd-4320-80f8-399cdc98db6f', FName='全部資料鏈接',     FType='condition',  FPublic=1, FVisible=1, FTemp=0, FGlobalAutoQuery=0, FShare=0, FUserId=null, FConditionId=null, FSqlSource='None', FSql=null, FIndex=1, FUpdateTime=null, FOriginSchemaId=null;
insert into TsQuerySchema set FId='6ca3ff4e-9ed9-45db-bf1a-25442d3878f9', FUnitId='71a3a0a5-47bd-4320-80f8-399cdc98db6f', FName='資料鏈接我的最愛', FType='collection', FPublic=1, FVisible=1, FTemp=0, FGlobalAutoQuery=0, FShare=0, FUserId=null, FConditionId=null, FSqlSource='None', FSql=null, FIndex=3, FUpdateTime=null, FOriginSchemaId=null;

insert into TsMenu set      FId='241e6934-fdf1-4434-a1f9-c9d6b497f5c1', FParentId='00000000-0000-0000-0008-990000000010',   FIndex=12,  FName='資料鏈接',       FPageId='63a781e5-8817-49f7-9fc7-e4cbbf1cffd6', FEnabled=1, FSubMenuSource='MenuTable', FIcon='quicksilver/image/unit/New.gif'; 

insert into TsDictionary set FBuiltin=0, FDescription='', FId='61484ac1-d88f-4acc-ad9e-92855bc6de59', FName='QS-資料鏈接-開啟模式', FParentId=null, FTextAsValue=0;
insert into TsDictionaryItem set FDictionaryId='61484ac1-d88f-4acc-ad9e-92855bc6de59', FId='74312286-a72a-4b60-a393-54bf68cd926f', FIndex=1, FParentValue=null, FText='頁簽',   FValue='TAB';
insert into TsDictionaryItem set FDictionaryId='61484ac1-d88f-4acc-ad9e-92855bc6de59', FId='6922cce2-4571-4875-bad0-c2582b74f059', FIndex=2, FParentValue=null, FText='新視窗', FValue='BROWSER';
insert into TsDictionaryItem set FDictionaryId='61484ac1-d88f-4acc-ad9e-92855bc6de59', FId='52c9ced6-acc7-4e42-af00-f2782306a078', FIndex=3, FParentValue=null, FText='子頁簽', FValue='TABCHILD';
