var records = [
	{
		"FId"				: 22,
		"FName"				: "格罗弗·克利夫兰",
		"FGender"			: 1,
		"FBirthDate"		: "1837-03-18",
		"FDeathDate"		: "1908-06-24",
		"FLive"				: false,
		"FFrom"				: "新泽西州",
		"FSerial"			: "22",
		"FPercentage"		: 48.9,
		"FPartyId"			: "2",
		"FPartyId$"			: "民主党",
		"FPartyIcon"		: "<div class=PartyIcon><img src='../image/Donkey.png'></div>",
		"FSecretaryIds"		: "90",
		"FSecretaryNames"	: "贝亚德",
		"FNote"				: "美国史上唯一一名担任了两任任期并非连续的总统，也是内战后第一个当选总统的民主党人。"
	},
	{
		"FId"				: 23,
		"FName"				: "本杰明·哈里森",
		"FGender"			: 1,
		"FBirthDate"		: "1833-08-20",
		"FDeathDate"		: "1901-03-13",
		"FLive"				: false,
		"FFrom"				: "俄亥俄州",
		"FSerial"			: "23",
		"FPercentage"		: 47.8,
		"FPartyId"			: "1",
		"FPartyId$"			: "共和党",
		"FPartyIcon"		: "<div class=PartyIcon><img src='../image/Elephant.png'></div>",
		"FSecretaryIds"		: "91|92",
		"FSecretaryNames"	: "布莱恩|福斯特",
		"FNote"				: "祖父为威廉·亨利·哈里森第九任美国总统。他是第二个输掉普选，但赢得选举人票而胜出的总统。(另外两位为1876年的海斯和2000年的布什，两者同属共和党)"
	},
	{
		"FId"				: 24,
		"FName"				: "格罗弗·克利夫兰",
		"FGender"			: 1,
		"FBirthDate"		: "1837-03-18",
		"FDeathDate"		: "1908-06-24",
		"FLive"				: false,
		"FFrom"				: "新泽西州",
		"FSerial"			: "24",
		"FPercentage"		: 46.0,
		"FPartyId"			: "2",
		"FPartyId$"			: "民主党",
		"FPartyIcon"		: "<div class=PartyIcon><img src='../image/Donkey.png'></div>",
		"FSecretaryIds"		: "93|94",
		"FSecretaryNames"	: "格雷沙姆|奥尔尼",
		"FNote"				: "美国史上唯一一名担任了两任任期并非连续的总统，也是内战后第一个当选总统的民主党人。"
	},
	{
		"FId"				: 25,
		"FName"				: "威廉·麦金利",
		"FGender"			: 1,
		"FBirthDate"		: "1843-01-29",
		"FDeathDate"		: "1901-09-14",
		"FLive"				: false,
		"FFrom"				: "俄亥俄州",
		"FSerial"			: "25",
		"FPercentage"		: 51.0,
		"FPartyId"			: "1",
		"FPartyId$"			: "共和党",
		"FPartyIcon"		: "<div class=PartyIcon><img src='../image/Elephant.png'></div>",
		"FSecretaryIds"		: "95|96|97",
		"FSecretaryNames"	: "舍曼|戴|海伊",
		"FNote"				: "领导美国在美西战争中击败西班牙。虽然他的总统任期因为刺杀事件的发生而缩短，但是他仍然开创了一个共和党执政三十多年的时代。",
		backgroundColor		: "#FFDDCC"
	},
	{
		"FId"				: 26,
		"FName"				: "西奥多·罗斯福",
		"FGender"			: 1,
		"FBirthDate"		: "1858-10-27",
		"FDeathDate"		: "1929-01-06",
		"FLive"				: false,
		"FFrom"				: "纽约州",
		"FSerial"			: "26",
		"FPercentage"		: 56.4,
		"FPartyId"			: "1",
		"FPartyId$"			: "共和党",
		"FPartyIcon"		: "<div class=PartyIcon><img src='../image/Elephant.png'></div>",
		"FSecretaryIds"		: "97|98|99",
		"FSecretaryNames"	: "海伊|鲁特|培根",
		"FNote"				: "1901年总统威廉·麦金莱被无政府主义者刺杀身亡，他继任成为美国总统，时年42岁，是美国历史上最年轻的在任总统。他的独特个性和改革主义政策，使他成为美国历史上最伟大的总统之一。"
	},
	{
		"FId"				: 27,
		"FName"				: "威廉·塔夫脱",
		"FGender"			: 1,
		"FBirthDate"		: "1857-09-15",
		"FDeathDate"		: "1930-03-08",
		"FLive"				: false,
		"FFrom"				: "俄亥俄州",
		"FSerial"			: "27",
		"FPercentage"		: 51.6,
		"FPartyId"			: "1",
		"FPartyId$"			: "共和党",
		"FPartyIcon"		: "<div class=PartyIcon><img src='../image/Elephant.png'></div>",
		"FSecretaryIds"		: "100",
		"FSecretaryNames"	: "诺克斯",
		"FNote"				: "当过律师、美国首席大法官和战争部长。"
	},
	{
		"FId"				: 28,
		"FName"				: "伍德罗·威尔逊",
		"FGender"			: 1,
		"FBirthDate"		: "1856-12-28",
		"FDeathDate"		: "1924-02-03",
		"FLive"				: false,
		"FFrom"				: "维吉尼亚州",
		"FSerial"			: "28",
		"FPercentage"		: 41.8,
		"FPartyId"			: "2",
		"FPartyId$"			: "民主党",
		"FPartyIcon"		: "<div class=PartyIcon><img src='../image/Donkey.png'></div>",
		"FSecretaryIds"		: "101|102|103",
		"FSecretaryNames"	: "布赖恩|兰辛|科尔比",
		"FNote"				: "曾先后任普林斯顿大学校长，新泽西州州长等职。1912年总统大选中，由于西奥多·罗斯福和威廉·塔夫脱的竞争分散了共和党选票，以民主党人身份当选总统。"
	},
	{
		"FId"				: 29,
		"FName"				: "沃伦·哈定",
		"FGender"			: 1,
		"FBirthDate"		: "1865-11-02",
		"FDeathDate"		: "1923-08-02",
		"FLive"				: false,
		"FFrom"				: "俄亥俄州",
		"FSerial"			: "29",
		"FPercentage"		: 60.3,
		"FPartyId"			: "1",
		"FPartyId$"			: "共和党",
		"FPartyIcon"		: "<div class=PartyIcon><img src='../image/Elephant.png'></div>",
		"FSecretaryIds"		: "104",
		"FSecretaryNames"	: "休斯",
		"FNote"				: "知名报刊发行人。当选总统前曾先后担任俄亥俄州议会参议员、俄亥俄州副州长和联邦参议员等职。",
		backgroundColor		: "#DDDDFF"
	},
	{
		"FId"				: 30,
		"FName"				: "卡尔文·柯立芝",
		"FGender"			: 1,
		"FBirthDate"		: "1872-07-04",
		"FDeathDate"		: "1933-01-05",
		"FLive"				: false,
		"FFrom"				: "佛蒙特州",
		"FSerial"			: "30",
		"FPercentage"		: 54.0,
		"FPartyId"			: "1",
		"FPartyId$"			: "共和党",
		"FPartyIcon"		: "<div class=PartyIcon><img src='../image/Elephant.png'></div>",
		"FSecretaryIds"		: "104|105",
		"FSecretaryNames"	: "休斯|凯洛格",
		"FNote"				: "1923年，哈定在任内病逝，柯立芝递补为总统。"
	},
	{
		"FId"				: 31,
		"FName"				: "赫伯特·胡佛",
		"FGender"			: 1,
		"FBirthDate"		: "1874-08-10",
		"FDeathDate"		: "1964-10-20",
		"FLive"				: false,
		"FFrom"				: "艾奥瓦州",
		"FSerial"			: "31",
		"FPercentage"		: 58.2,
		"FPartyId"			: "1",
		"FPartyId$"			: "共和党",
		"FPartyIcon"		: "<div class=PartyIcon><img src='../image/Elephant.png'></div>",
		"FSecretaryIds"		: "105|106",
		"FSecretaryNames"	: "凯洛格|史汀生",
		"FNote"				: "曾任沃伦·G·哈定和卡尔文·柯立芝两届总统的商务部长。是美国迄今为止由内阁部长直接升为总统的最后一人。"
	},
	{
		"FId"				: 32,
		"FName"				: "富兰克林·罗斯福",
		"FGender"			: 1,
		"FBirthDate"		: "1882-01-30",
		"FDeathDate"		: "1945-04-12",
		"FLive"				: false,
		"FFrom"				: "纽约州",
		"FSerial"			: "32",
		"FPercentage"		: 57.4,
		"FPartyId"			: "2",
		"FPartyId$"			: "民主党",
		"FPartyIcon"		: "<div class=PartyIcon><img src='../image/Donkey.png'></div>",
		"FSecretaryIds"		: "107|108",
		"FSecretaryNames"	: "赫尔|斯特蒂纽斯",
		"FNote"				: "是20世纪美国二三十年代经济危机和第二次世界大战的中心人物之一。从1933年至1945年间，连续出任四届美国总统，且是唯一连任超过两届的美国总统。",
		backgroundColor		: "#DDDDFF"
	},
	{
		"FId"				: 33,
		"FName"				: "哈里·杜鲁门",
		"FGender"			: 1,
		"FBirthDate"		: "1884-05-08",
		"FDeathDate"		: "1972-12-26",
		"FLive"				: false,
		"FFrom"				: "密苏里州",
		"FSerial"			: "33",
		"FPercentage"		: 49.6,
		"FPartyId"			: "2",
		"FPartyId$"			: "民主党",
		"FPartyIcon"		: "<div class=PartyIcon><img src='../image/Donkey.png'></div>",
		"FSecretaryIds"		: "108|109|110|111",
		"FSecretaryNames"	: "斯特蒂纽斯|伯恩斯|马歇尔|艾奇逊",
		"FNote"				: "第34任副总统（1945年），随后接替因病逝世的富兰克林·罗斯福总统。"
	},
	{
		"FId"				: 34,
		"FName"				: "德怀特·艾森豪威尔",
		"FGender"			: 1,
		"FBirthDate"		: "1890-10-14",
		"FDeathDate"		: "1969-03-28",
		"FLive"				: false,
		"FFrom"				: "得克萨斯州",
		"FSerial"			: "34",
		"FPercentage"		: 55.2,
		"FPartyId"			: "1",
		"FPartyId$"			: "共和党",
		"FPartyIcon"		: "<div class=PartyIcon><img src='../image/Elephant.png'></div>",
		"FSecretaryIds"		: "112|113",
		"FSecretaryNames"	: "杜勒斯|赫脱",
		"FNote"				: "美国陆军五星上将。第二次世界大战期间，担任盟军在欧洲的最高指挥官。"
	},
	{
		"FId"				: 35,
		"FName"				: "约翰·肯尼迪",
		"FGender"			: 1,
		"FBirthDate"		: "1917-05-29",
		"FDeathDate"		: "1963-11-22",
		"FLive"				: false,
		"FFrom"				: "马萨诸塞州",
		"FSerial"			: "35",
		"FPercentage"		: 49.7,
		"FPartyId"			: "2",
		"FPartyId$"			: "民主党",
		"FPartyIcon"		: "<div class=PartyIcon><img src='../image/Donkey.png'></div>",
		"FSecretaryIds"		: "114",
		"FSecretaryNames"	: "腊斯克",
		"FNote"				: "于1963年11月22日在德克萨斯州达拉斯市遇刺身亡。",
		backgroundColor		: "#FFDDCC"
	},
	{
		"FId"				: 36,
		"FName"				: "林登·约翰逊",
		"FGender"			: 1,
		"FBirthDate"		: "1908-08-27",
		"FDeathDate"		: "1973-01-22",
		"FLive"				: false,
		"FFrom"				: "德克萨斯州",
		"FSerial"			: "36",
		"FPercentage"		: 61.1,
		"FPartyId"			: "2",
		"FPartyId$"			: "民主党",
		"FPartyIcon"		: "<div class=PartyIcon><img src='../image/Donkey.png'></div>",
		"FSecretaryIds"		: "114",
		"FSecretaryNames"	: "腊斯克",
		"FNote"				: "曾任参议员、副总统。在肯尼迪遇刺案之后，约翰逊继续接任约翰·肯尼迪总统的职务。"
	},
	{
		"FId"				: 37,
		"FName"				: "理查德·尼克松",
		"FGender"			: 1,
		"FBirthDate"		: "1913-01-09",
		"FDeathDate"		: "1994-04-22",
		"FLive"				: false,
		"FFrom"				: "加利福尼亚州",
		"FSerial"			: "37",
		"FPercentage"		: 43.4,
		"FPartyId"			: "1",
		"FPartyId$"			: "共和党",
		"FPartyIcon"		: "<div class=PartyIcon><img src='../image/Elephant.png'></div>",
		"FSecretaryIds"		: "115|116",
		"FSecretaryNames"	: "罗杰斯|基辛格",
		"FNote"				: "第36任美国副总统（1953年－1961年）与第37任美国总统（1969年－1974年）。是美国史上唯一当过两届总统与两届副总统的人，也是唯一于在位期间以辞职的方式离开总统职位的美国总统。",
		backgroundColor		: "#BBFFBB"
	},
	{
		"FId"				: 38,
		"FName"				: "杰拉尔德·福特",
		"FGender"			: 1,
		"FBirthDate"		: "1913-07-14",
		"FDeathDate"		: "2006-12-26",
		"FLive"				: false,
		"FFrom"				: "内布拉斯加州",
		"FSerial"			: "38",
		"FPartyId"			: "1",
		"FPartyId$"			: "共和党",
		"FPartyIcon"		: "<div class=PartyIcon><img src='../image/Elephant.png'></div>",
		"FSecretaryIds"		: "117",
		"FSecretaryNames"	: "基辛格",
		"FNote"				: "美国第40任副总统，1974年8月9日理查德·尼克松辞职后福特继任美国总统。是美国历史上唯一一位未经选举就接任副总统以及总统的人。"
	},
	{
		"FId"				: 39,
		"FName"				: "吉米·卡特",
		"FGender"			: 1,
		"FBirthDate"		: "1924-10-01",
		"FLive"				: true,
		"FFrom"				: "佐治亚州",
		"FSerial"			: "39",
		"FPercentage"		: 50.08,
		"FPartyId"			: "2",
		"FPartyId$"			: "民主党",
		"FPartyIcon"		: "<div class=PartyIcon><img src='../image/Donkey.png'></div>",
		"FSecretaryIds"		: "118|119",
		"FSecretaryNames"	: "万斯|马斯基",
		"FNote"				: "曾任佐治亚州州长。早年一直在军队工作。"
	},
	{
		"FId"				: 40,
		"FName"				: "罗纳德·里根",
		"FGender"			: 1,
		"FBirthDate"		: "1911-02-06",
		"FDeathDate"		: "2004-06-05",
		"FLive"				: false,
		"FFrom"				: "伊利诺伊州",
		"FSerial"			: "40",
		"FPercentage"		: 51.2,
		"FPartyId"			: "1",
		"FPartyId$"			: "共和党",
		"FPartyIcon"		: "<div class=PartyIcon><img src='../image/Elephant.png'></div>",
		"FSecretaryIds"		: "120|121",
		"FSecretaryNames"	: "黑格|舒尔茨",
		"FNote"				: "第33任加利福尼亚州州长（1967年－1975年），曾担任过运动广播员、救生员、报社专栏作家、电影演员、和励志讲师。"
	},
	{
		"FId"				: 41,
		"FName"				: "乔治·布什",
		"FGender"			: 1,
		"FBirthDate"		: "1924-06-12",
		"FLive"				: true,
		"FFrom"				: "马萨诸塞州",
		"FSerial"			: "41",
		"FPercentage"		: 52.35,
		"FPartyId"			: "1",
		"FPartyId$"			: "共和党",
		"FPartyIcon"		: "<div class=PartyIcon><img src='../image/Elephant.png'></div>",
		"FSecretaryIds"		: "122|129",
		"FSecretaryNames"	: "贝克|伊格尔伯格",
		"FNote"				: "曾任美国副总统、美国国会众议员、驻华大使、中央情报总监。"
	},
	{
		"FId"				: 42,
		"FName"				: "比尔·克林顿",
		"FGender"			: 1,
		"FBirthDate"		: "1946-08-19",
		"FLive"				: true,
		"FFrom"				: "阿肯色州",
		"FSerial"			: "42",
		"FPercentage"		: 43.1,
		"FPartyId"			: "2",
		"FPartyId$"			: "民主党",
		"FPartyIcon"		: "<div class=PartyIcon><img src='../image/Donkey.png'></div>",
		"FSecretaryIds"		: "123|124",
		"FSecretaryNames"	: "克里斯托弗|奥尔布莱特",
		"FNote"				: "曾任阿肯色州州长（1979年－1981年、1983年－1992年），是美国历史上仅次于西奥多·罗斯福和约翰·肯尼迪的第三年轻当选总统，也是首位出生于二战后婴儿潮中的总统。"
	},
	{
		"FId"				: 43,
		"FName"				: "乔治·沃克·布什",
		"FGender"			: 1,
		"FBirthDate"		: "1946-07-06",
		"FLive"				: true,
		"FFrom"				: "康涅狄格州",
		"FSerial"			: "43",
		"FPercentage"		: 47.87,
		"FPartyId"			: "1",
		"FPartyId$"			: "共和党",
		"FPartyIcon"		: "<div class=PartyIcon><img src='../image/Elephant.png'></div>",
		"FSecretaryIds"		: "125|126",
		"FSecretaryNames"	: "鲍威尔|赖斯",
		"FNote"				: "于1995年至2000年间担任第46任的得克萨斯州州长。是自本杰明·哈里森在1888年的选举以来第一个输掉普选，但赢得选举人票而胜出的总统。"
	},
	{
		"FId"				: 44,
		"FName"				: "贝拉克·奥巴马",
		"FGender"			: 1,
		"FBirthDate"		: "1961-08-04",
		"FLive"				: true,
		"FFrom"				: "夏威夷州",
		"FSerial"			: "44",
		"FPercentage"		: 52.75,
		"FPartyId"			: "2",
		"FPartyId$"			: "民主党",
		"FPartyIcon"		: "<div class=PartyIcon><img src='../image/Donkey.png'></div>",
		"FSecretaryIds"		: "127|128",
		"FSecretaryNames"	: "希拉里|克里",
		"FNote"				: "第一位非裔美国总统。"
	}
];
