--Qs.ListColor------------------------------------------------------------------

create table TsListColor
(
	FId uuid primary key,
	FName varchar(50),
	FIndex int,
	FUnitId uuid,
	FColor varchar(10),
	FConditionId uuid,
	FExpression varchar(500)
);

insert into TsUnit set FId='f9bb1c95-abac-4970-8622-3f4737c0becb', FCode='Qs.ListColor', FName='顏色設置', FIcon='quicksilver/image/unit/ListColor.png', FEditId='541c707d-79dd-4dbb-85fc-1a214fd5fce4', FModuleId='00000000-0000-0000-0008-990000000020', FOpenMode='System', FIsTreeStructure=0, FMaxTreeLevel=null, FIsSlaveUnit=1, FMasterUnitId='00000000-0000-0000-0001-000000000001', FSupportWorkflow=0, FSupportUser=0, FSupportDepartment=0, FSupportEditType=0, FSupportAttachment=0, FSupportDataPrivilege=0, FSupportVersion=0, FSupportBusinessLog=0, FSupportNote=0, FSupportSort=1, FSupportPrivilegeField=0, FIsFullTextSearch=0, FSearchAttachment=0, FSupportEqualQuery=0, FUseSystemI18nTable=1, FExtraQueryResultLimit=0, FRecordCreateInfo=0, FRecordUpdateInfo=0, FRecordDeleteInfo=0, FViewPageConditionForList=null, FViewPageConditionForLink=null, FDataSource='default', FTable='TsListColor', FKeyField='FId', FKeyType='Uuid', FNameField='FName', FMasterField='FUnitId', FHomeClassName='com.jeedsoft.quicksilver.layout.ListColorHome', FDaoClassName='com.jeedsoft.quicksilver.layout.dao.impl.ListColorDaoImpl', FServiceClassName='com.jeedsoft.quicksilver.layout.service.impl.ListColorServiceImpl', FActionClassName='com.jeedsoft.quicksilver.layout.action.impl.ListColorActionImpl', FWebServiceUniqueField=null, FUnitFilterSql='', FBusinessFilterSql='', FDescription='';

insert into TsField set FId='fa64a463-3304-457e-924e-48e035cb7490', FUnitId='f9bb1c95-abac-4970-8622-3f4737c0becb', FName='FColor',       FTitle='背景顏色', FType='InputBox-Text',    FSize=10,   FVisible=1, FFilterByRole=0, FRequired=1, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='7eb813fe-0a67-475b-a9f9-627ec81c69aa', FUnitId='f9bb1c95-abac-4970-8622-3f4737c0becb', FName='FConditionId', FTitle='條件',     FType='InputBox-Uuid',    FSize=null, FVisible=0, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=0, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='0359398e-72e8-4969-9a67-093c27b84c29', FUnitId='f9bb1c95-abac-4970-8622-3f4737c0becb', FName='FExpression',  FTitle='運算式',   FType='TextBox',          FSize=500,  FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=2, FRowSpan=5, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='d11e6b5c-29de-493f-a8bc-4cf45f37f4f7', FUnitId='f9bb1c95-abac-4970-8622-3f4737c0becb', FName='FId',          FTitle='ID',       FType='InputBox-Key',     FSize=null, FVisible=0, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=0, FDictionaryId=null, FEntityUnitId='f9bb1c95-abac-4970-8622-3f4737c0becb', FSupportLocalText=null, FSupportI18n=null, FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=null, FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData=null;
insert into TsField set FId='7bbe8b43-42e5-4d2f-ad93-eb166d2c2533', FUnitId='f9bb1c95-abac-4970-8622-3f4737c0becb', FName='FIndex',       FTitle='順序',     FType='InputBox-Integer', FSize=null, FVisible=0, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=0, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=null, FSupportI18n=null, FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=null, FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData=null;
insert into TsField set FId='f32409d0-c613-4567-b19d-f31d06d230a5', FUnitId='f9bb1c95-abac-4970-8622-3f4737c0becb', FName='FName',        FTitle='名稱',     FType='InputBox-Text',    FSize=50,   FVisible=1, FFilterByRole=0, FRequired=1, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=1,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='5fee897e-1836-4843-bafe-16b3041a6f65', FUnitId='f9bb1c95-abac-4970-8622-3f4737c0becb', FName='FUnitId',      FTitle='單元',     FType='EntityBox',        FSize=null, FVisible=0, FFilterByRole=0, FRequired=1, FReadOnly=0, FQueryable=0, FDictionaryId=null, FEntityUnitId='00000000-0000-0000-0001-000000000001', FSupportLocalText=null, FSupportI18n=null, FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=null, FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData=null;

java setOrderFields('f9bb1c95-abac-4970-8622-3f4737c0becb', 'FIndex', '0');

insert into TsRelation set FId='673e26f1-ecdd-4513-beec-3dabca03177b', FOppositeId='79df49af-f73e-45d0-b194-6ba1c4561439', FName='顏色設置-單元', FOppositeName='單元-顏色設置', FUnitId1='f9bb1c95-abac-4970-8622-3f4737c0becb', FUnitId2='00000000-0000-0000-0001-000000000001', FType='field', FTable='', FField1='FId', FField2='FUnitId', FDeleteAction1='unset', FDeleteAction2='cancel', FPrivilegeTypeId1=null, FPrivilegeTypeId2=null;

insert into TsPage set FId='8482debf-10ce-4f0b-905e-b5f16eee060e', FName='顏色設置主列表',   FTitle='顏色設置列表', FCode='Qs.ListColor.List',       FPlatform='Computer', FType='EntityList', FIcon='quicksilver/image/unit/ListColor.png',  FUrl='quicksilver/page/template/EntityList.jsp', FActionMethodName='Qs.ListColor.prepareList', FLoadHandler=null,                   FRelationId=null, FUnitId='f9bb1c95-abac-4970-8622-3f4737c0becb', FMasterUnitId=null,                                   FIsSlavePage=0, FIndex=null, FDialogWidth=null, FDialogHeight=null, FDialogMaximized=null, FQueryFormAutoQuery=1, FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription=null;
insert into TsPage set FId='648f28c1-0081-4fd5-8a0e-91d233983c6d', FName='顏色設置選擇列表', FTitle='顏色設置列表', FCode='Qs.ListColor.SelectList', FPlatform='Computer', FType='EntityList', FIcon='quicksilver/image/unit/ListColor.png',  FUrl='quicksilver/page/template/EntityList.jsp', FActionMethodName='Qs.ListColor.prepareList', FLoadHandler=null,                   FRelationId=null, FUnitId='f9bb1c95-abac-4970-8622-3f4737c0becb', FMasterUnitId=null,                                   FIsSlavePage=0, FIndex=null, FDialogWidth=null, FDialogHeight=null, FDialogMaximized=null, FQueryFormAutoQuery=1, FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription=null;
insert into TsPage set FId='3bf7421c-0106-4ce3-9e50-8f102514fb53', FName='顏色設置排序',     FTitle='排序',         FCode='Qs.ListColor.Sort',       FPlatform='Computer', FType='Sort',       FIcon='quicksilver/image/16/Sort.png',  FUrl='quicksilver/page/template/Sorter.jsp',     FActionMethodName='Qs.ListColor.prepareSort', FLoadHandler=null,                   FRelationId=null, FUnitId='f9bb1c95-abac-4970-8622-3f4737c0becb', FMasterUnitId=null,                                   FIsSlavePage=0, FIndex=null, FDialogWidth=null, FDialogHeight=null, FDialogMaximized=null, FQueryFormAutoQuery=1, FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription=null;
insert into TsPage set FId='5a690bd9-51e2-4c1a-be56-14c220cbfe62', FName='顏色設置表單',     FTitle='表單',         FCode='Qs.ListColor.Form',       FPlatform='Computer', FType='EntityForm', FIcon='quicksilver/image/16/Form.png', FUrl='quicksilver/page/template/EntityForm.jsp', FActionMethodName='Qs.ListColor.prepareForm', FLoadHandler='ListColorForm.doLoad', FRelationId=null, FUnitId='f9bb1c95-abac-4970-8622-3f4737c0becb', FMasterUnitId='f9bb1c95-abac-4970-8622-3f4737c0becb', FIsSlavePage=1, FIndex=1,    FDialogWidth=750,  FDialogHeight=500,  FDialogMaximized=0,    FQueryFormAutoQuery=0, FHasViewFrame=0,    FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments='',   FVisible=1, FVisibleCondition=null, FDescription='';

--顏色設置主列表
insert into TsToolItem set FId='50be7bd9-4174-4692-a1fb-af277328767c', FPageId='8482debf-10ce-4f0b-905e-b5f16eee060e', FCode='Add',     FName='新增', FHint='新增一筆記錄',                                         FLabel=null, FType='Button',      FAlign='right', FIndex=1, FWidth=0, FIcon='quicksilver/image/16/Add.png',     FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doAdd';
insert into TsToolItem set FId='e2a5294e-e3ce-406a-b651-c4df3bb34020', FPageId='8482debf-10ce-4f0b-905e-b5f16eee060e', FCode='Open',    FName='打開', FHint='打開當前選中的記錄。如果選中了多筆，第一筆將被打開。', FLabel=null, FType='Button',      FAlign='right', FIndex=2, FWidth=0, FIcon='quicksilver/image/16/Open.png',    FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doOpen';
insert into TsToolItem set FId='d646cb20-b09d-4ef1-9ddd-8fdb074f0c8f', FPageId='8482debf-10ce-4f0b-905e-b5f16eee060e', FCode='Delete',  FName='刪除', FHint='刪除當前選中的記錄',                                   FLabel=null, FType='Button',      FAlign='right', FIndex=3, FWidth=0, FIcon='quicksilver/image/16/Delete.png',  FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doDelete';
insert into TsToolItem set FId='12d35e50-3e91-4677-85d4-bf3b4dba3393', FPageId='8482debf-10ce-4f0b-905e-b5f16eee060e', FCode='Refresh', FName='刷新', FHint='刷新列表內容',                                         FLabel=null, FType='Button',      FAlign='right', FIndex=4, FWidth=0, FIcon='quicksilver/image/16/Refresh.png', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doRefresh';
insert into TsToolItem set FId='5980b954-c196-426c-9b98-77d5459ea0c0', FPageId='8482debf-10ce-4f0b-905e-b5f16eee060e', FCode='Other',   FName=null,   FHint=null,                                                   FLabel=null, FType='ComboButton', FAlign='right', FIndex=5, FWidth=0, FIcon='quicksilver/image/16/Other.png',   FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource='SubItemTable', FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='None',       FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler=null;
insert into TsToolSubItem set FId='b423903f-99df-4ba0-b260-5c8afdf4aab3', FToolItemId='5980b954-c196-426c-9b98-77d5459ea0c0', FCode='Sort',        FName='排序',       FExpandMode='None', FIndex=1, FIcon='quicksilver/image/16/Sort.png',   FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FEventHandler='EntityList.doSort';

--顏色設置選擇列表
insert into TsToolItem set FId='c34f5f8a-e7af-45d3-9545-06a5b68f2dc2', FPageId='648f28c1-0081-4fd5-8a0e-91d233983c6d', FCode='ConfirmSelection', FName='確定', FHint=null,                                                   FLabel=null, FType='Button', FAlign='right', FIndex=1, FWidth=0, FIcon='quicksilver/image/16/Ok.png',   FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doSelectListConfirm';
insert into TsToolItem set FId='27c61864-0e7b-4347-862a-9f20f3408811', FPageId='648f28c1-0081-4fd5-8a0e-91d233983c6d', FCode='Add',              FName='新增', FHint='新增一筆記錄',                                         FLabel=null, FType='Button', FAlign='right', FIndex=2, FWidth=0, FIcon='quicksilver/image/16/Add.png',  FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doAdd';
insert into TsToolItem set FId='3215716e-a81b-4949-8d3d-6947e94f9a08', FPageId='648f28c1-0081-4fd5-8a0e-91d233983c6d', FCode='Open',             FName='打開', FHint='打開當前選中的記錄。如果選中了多筆，第一筆將被打開。', FLabel=null, FType='Button', FAlign='right', FIndex=3, FWidth=0, FIcon='quicksilver/image/16/Open.png', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doOpen';

--顏色設置排序
insert into TsToolItem set FId='789d46cf-aacb-42b5-9ba8-6287d3fae7d5', FPageId='3bf7421c-0106-4ce3-9e50-8f102514fb53', FCode='MoveUp',     FName='上升', FHint=null, FLabel=null, FType='Button', FAlign='left',  FIndex=1, FWidth=0, FIcon='quicksilver/image/16/MoveUp.png',     FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='Sorter.doMoveUp';
insert into TsToolItem set FId='ee022fb4-8943-460b-bee6-db88e875254d', FPageId='3bf7421c-0106-4ce3-9e50-8f102514fb53', FCode='MoveDown',   FName='下降', FHint=null, FLabel=null, FType='Button', FAlign='left',  FIndex=2, FWidth=0, FIcon='quicksilver/image/16/MoveDown.png',   FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='Sorter.doMoveDown';
insert into TsToolItem set FId='a3144e4b-3036-4d41-9be8-a46a10840505', FPageId='3bf7421c-0106-4ce3-9e50-8f102514fb53', FCode='MoveTop',    FName='置頂', FHint=null, FLabel=null, FType='Button', FAlign='left',  FIndex=3, FWidth=0, FIcon='quicksilver/image/16/MoveTop.png',    FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='Sorter.doMoveTop';
insert into TsToolItem set FId='e3fb0d56-2d9b-4478-b4ff-062f70d260e6', FPageId='3bf7421c-0106-4ce3-9e50-8f102514fb53', FCode='MoveBottom', FName='置底', FHint=null, FLabel=null, FType='Button', FAlign='left',  FIndex=4, FWidth=0, FIcon='quicksilver/image/16/MoveBottom.png', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='Sorter.doMoveBottom';
insert into TsToolItem set FId='168d380e-81fd-436e-b6a5-33c6257342f6', FPageId='3bf7421c-0106-4ce3-9e50-8f102514fb53', FCode='Save',       FName='保存', FHint=null, FLabel=null, FType='Button', FAlign='right', FIndex=1, FWidth=0, FIcon='quicksilver/image/16/Save.png',       FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='Sorter.doSave';

--顏色設置表單
insert into TsScript set FId='b65d2271-366e-48f7-8885-92e70531eafd', FIndex=1, FPageId='5a690bd9-51e2-4c1a-be56-14c220cbfe62', FUrl='quicksilver/page/layout/ListColorForm.js';
insert into TsToolItem set FId='0c760892-8754-4cc0-a94e-5e024355534c', FPageId='5a690bd9-51e2-4c1a-be56-14c220cbfe62', FCode='Save',  FName='保存', FHint=null, FLabel=null, FType='Button',      FAlign='right', FIndex=1, FWidth=0, FIcon='quicksilver/image/16/Save.png',  FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityForm.doSave';

insert into TsForm set FDefault=1, FEditableCondition=null, FGroupMode='None', FId='c377e861-f2fb-4584-96a7-999292af4ea0', FIndex=1, FName='默認', FPageId=null, FUnitId='f9bb1c95-abac-4970-8622-3f4737c0becb';
java setFormFields('c377e861-f2fb-4584-96a7-999292af4ea0', 'FName,FColor,FExpression');

insert into TsList set FDefault=1, FId='e85cb4ce-ec8b-4f7f-9040-4d1b94656726', FIndex=null, FMultiPage=1, FName='顏色設置列表',     FPageId=null,                                   FUnitId='f9bb1c95-abac-4970-8622-3f4737c0becb';
insert into TsList set FDefault=0, FId='39a5dfe1-11f1-4ada-805b-9d75c0ee56e8', FIndex=null, FMultiPage=1, FName='顏色設置選擇列表', FPageId='648f28c1-0081-4fd5-8a0e-91d233983c6d', FUnitId='f9bb1c95-abac-4970-8622-3f4737c0becb';
insert into TsList set FDefault=0, FId='7eb5a6cb-2ecd-46c9-bfd7-858bb4562f27', FIndex=null, FMultiPage=1, FName='顏色設置首頁列表', FPageId='9b796431-f132-49d1-b306-5d1d618f9c1b', FUnitId='f9bb1c95-abac-4970-8622-3f4737c0becb';
java setListFields('e85cb4ce-ec8b-4f7f-9040-4d1b94656726', 'FName,FColor,FExpression');
java setListFields('39a5dfe1-11f1-4ada-805b-9d75c0ee56e8', 'FName,FColor,FExpression');
java setListFields('7eb5a6cb-2ecd-46c9-bfd7-858bb4562f27', 'FName,FColor,FExpression');

insert into TsSlaveUnitPrivilege set FId='cb874c11-63ed-42ec-9b2f-129f15e3a1a2', FUnitId='f9bb1c95-abac-4970-8622-3f4737c0becb', FCreatePrivilegeTypeId='00000000-0000-0000-1005-000000000003', FReadPrivilegeTypeId='00000000-0000-0000-1005-000000000003', FReadUserFieldName='', FUpdatePrivilegeTypeId='00000000-0000-0000-1005-000000000003', FUpdateUserFieldName='', FDeletePrivilegeTypeId='00000000-0000-0000-1005-000000000003', FDeleteUserFieldName='';

--單元顏色設置清單
insert into TsPage set FId='ee43501b-5652-49cb-a1b0-d965f56e20b3', FName='單元顏色清單',				FTitle='顏色設置',		FCode='Qs.Unit.ListColorList',			FPlatform='Computer', FType='EntityList',	FIcon='quicksilver/image/unit/ListColor.png',			FUrl='quicksilver/page/template/EntityList.jsp',          FActionMethodName='Qs.ListColor.prepareList',					FLoadHandler='',                FRelationId='79df49af-f73e-45d0-b194-6ba1c4561439', FUnitId='f9bb1c95-abac-4970-8622-3f4737c0becb', FMasterUnitId='00000000-0000-0000-0001-000000000001', FIsSlavePage=1, FIndex=17,    FDialogWidth=null, FDialogHeight=null, FVisible=1, FDescription=null;
insert into TsToolItem set FId='7744a1e5-2d81-4a32-af2b-7c1855ff9c5c', FPageId='ee43501b-5652-49cb-a1b0-d965f56e20b3', FCode='Add',     FName='新增', FLabel=null, FType='Button',      FAlign='right', FIndex=1, FWidth=0, FDefaultEventHandler='EntityList.doAdd',     FIcon='quicksilver/image/16/Add.png',     FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null;
insert into TsToolItem set FId='654f71f8-0536-40ce-afa3-56522e86588b', FPageId='ee43501b-5652-49cb-a1b0-d965f56e20b3', FCode='Open',    FName='打開', FLabel=null, FType='Button',      FAlign='right', FIndex=2, FWidth=0, FDefaultEventHandler='EntityList.doOpen',    FIcon='quicksilver/image/16/Open.png',    FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null;
insert into TsToolItem set FId='1191071f-0b4d-4d05-8c0d-9a1419212c25', FPageId='ee43501b-5652-49cb-a1b0-d965f56e20b3', FCode='Delete',  FName='刪除', FLabel=null, FType='Button',      FAlign='right', FIndex=3, FWidth=0, FDefaultEventHandler='EntityList.doDelete',  FIcon='quicksilver/image/16/Delete.png',  FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null;
insert into TsToolItem set FId='6663e0b7-2889-406d-a1e6-033c6934392c', FPageId='ee43501b-5652-49cb-a1b0-d965f56e20b3', FCode='Refresh', FName='刷新', FLabel=null, FType='Button',      FAlign='right', FIndex=4, FWidth=0, FDefaultEventHandler='EntityList.doRefresh', FIcon='quicksilver/image/16/Refresh.png', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null;
insert into TsToolItem set FId='f10a9607-cf78-473d-b758-8da20409ca83', FPageId='ee43501b-5652-49cb-a1b0-d965f56e20b3', FCode='Other',   FName=null,   FLabel=null, FType='ComboButton', FAlign='right', FIndex=5, FWidth=0, FDefaultEventHandler=null,                   FIcon='quicksilver/image/16/Other.png',   FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource='SubItemTable', FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='None',       FHandlePageId=null;
insert into TsToolSubItem set FId='dc317e66-7245-4202-8543-d5e117c89093', FToolItemId='f10a9607-cf78-473d-b758-8da20409ca83', FCode='Sort', FName='排序', FExpandMode='None', FIndex=1, FIcon='quicksilver/image/16/Sort.png', FEventHandler='EntityList.doSort', FVisibleCondition='', FEnableCondition='', FHandleType='JavaScript', FHandlePageId=null;

insert into TsTextResource set FId='9fc2e9ea-ad5f-41ac-b26b-d0546c0297b7', FCode='T.Qs.ListColor.Condition',							FValue='條件';
insert into TsTextResource set FId='93b291b7-e741-4bb0-b48d-a1c3a6023507', FCode='T.Qs.ListColor.ConditionAndExpressionNullAlert',		FValue='條件和運算式不能都為空。';
