java setListFields('25efd08f-31f4-4415-ba10-6ca999ebc029', 'FName,FMethod,FOccasion,FType,FContent,FMessage');

delete from TsToolItem where FPageId='82ac307d-a366-46f6-af60-e30f96d352bf';
insert into TsToolItem set FId='f91a8015-605f-4b8a-b44a-fb8b57b363cf', FPageId='82ac307d-a366-46f6-af60-e30f96d352bf', FCode='Save', FName='保存',       FLabel='', FType='Button',      FAlign='right', FIndex=1, FWidth=0, FDefaultEventHandler='HomepageConfig.doSave',      FIcon='quicksilver/image/16/Save.gif', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,       FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null;
insert into TsToolItem set FId='30365822-a1e9-4786-bf4d-13a39815678a', FPageId='82ac307d-a366-46f6-af60-e30f96d352bf', FCode='Add',  FName='新增首页项', FLabel='', FType='ComboButton', FAlign='right', FIndex=2, FWidth=0, FDefaultEventHandler='HomepageConfig.doModuleAdd', FIcon='quicksilver/image/16/Add.gif',  FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource='EditType', FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null;

delete from TsToolItem where FPageId='a0e2cebc-c96b-4bdb-85c8-0be4763ca651';
insert into TsToolItem set FId='b78331ff-9f40-4b37-befa-de088496e122', FPageId='a0e2cebc-c96b-4bdb-85c8-0be4763ca651', FCode='Save',   FName='保存',           FLabel='', FType='Button',      FAlign='right', FIndex=1, FWidth=0, FDefaultEventHandler='HomepageConfig.doSave',      FIcon='quicksilver/image/16/Save.gif', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,       FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null;
insert into TsToolItem set FId='7cfd3396-20d0-4fa0-a251-fce029f8baef', FPageId='a0e2cebc-c96b-4bdb-85c8-0be4763ca651', FCode='Resume', FName='恢复为系统首页', FLabel='', FType='Button',      FAlign='right', FIndex=2, FWidth=0, FDefaultEventHandler='HomepageConfig.doResume',    FIcon='quicksilver/image/16/Back.gif', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,       FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null;
insert into TsToolItem set FId='dc96d262-f54b-4d4d-8389-11d36660c0de', FPageId='a0e2cebc-c96b-4bdb-85c8-0be4763ca651', FCode='Add',    FName='新增用户首页项', FLabel='', FType='ComboButton', FAlign='right', FIndex=3, FWidth=0, FDefaultEventHandler='HomepageConfig.doModuleAdd', FIcon='quicksilver/image/16/Add.gif',  FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource='EditType', FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null;
