Jui.$define("Jui.option.BackForm",Jui.basic.Control);
Jui.option.BackForm.initialize=function(c,b,a){b=b||{};
a=a||this;
var d=this.superClass.initialize(c,b,a);
d._list=[];
d._map={};
d._record={};
d._oldValues={};
return d;
};
Jui.option.BackForm.prototype.$bind=function(c,a){var b=Jui.object.merge({control:c},a);
this._list.push(b);
this._map[a.name]=b;
if(c.setForm){c.setForm(this);
}};
Jui.option.BackForm.prototype.isModified=function(){for(var c in this._map){var b=this._map[c].control;
var a=this._oldValues;
if(b.getValue&&b.getValue()!=a[c]){return true;
}if(b instanceof Jui.basic.EntityBox){if(b.isAcceptPureText()&&b.getText()!=a[b.getTextField()]){return true;
}}}return false;
};
Jui.option.BackForm.prototype.clear=function(){var a=this;
for(var b in a._map){a._setControlValue(a._map[b].control);
}a._record={};
a.clearModificationFlag();
};
Jui.option.BackForm.prototype.clearFields=function(){var a=this;
a._list=[];
a._map={};
a._record={};
a._oldValues={};
};
Jui.option.BackForm.prototype.setFieldFocus=function(a){this._map[a].control.focus();
};
Jui.option.BackForm.prototype.hasControl=function(a){return a in this._map;
};
Jui.option.BackForm.prototype.getControl=function(a){return a in this._map?this._map[a].control:undefined;
};
Jui.option.BackForm.prototype.getControls=function(){var a=[];
for(var b=0;
b<this._list.length;
++b){a.push(this._list[b].control);
}return a;
};
Jui.option.BackForm.prototype.getControlMap=function(){var a={};
for(var b in this._map){a[b]=this._map[b].control;
}return a;
};
Jui.option.BackForm.prototype.getFieldValue=function(b){if(b in this._map){var a=this._map[b].control;
return a.getValue==null?null:a.getValue();
}else{return this._record[b];
}};
Jui.option.BackForm.prototype.setFieldValue=function(c,a,b){if(c in this._map){this._setControlValue(this._map[c].control,a,b);
}else{this._record[c]=a;
}};
Jui.option.BackForm.prototype.getNumberFieldValue=function(b){var a=this._map[b];
if(a==null){return Jui.cast.toNumber(this._record[b]);
}else{return a.control instanceof Jui.basic.InputBox?a.control.getNumberValue():0;
}};
Jui.option.BackForm.prototype.getFieldText=function(b){if(!b in this._map){return undefined;
}var a=this._map[b].control;
return a.getText==null?undefined:a.getText();
};
Jui.option.BackForm.prototype.getData=function(){var c={};
for(var e in this._map){var d=this._map[e];
var a=d.control;
if(a.getValue){var b=a.getValue();
if(a instanceof Jui.basic.InputBox&&typeof(b)=="string"){b=Jui.string.trim(b);
}c[e]=b;
if(a instanceof Jui.basic.EntityBox||a instanceof Jui.basic.MultiEntityBox){c[d.textField]=a.getText();
}}}return Jui.object.merge(c,this._record);
};
Jui.option.BackForm.prototype.loadData=function(a){this.clear();
this.updateData(a);
this.clearModificationFlag();
};
Jui.option.BackForm.prototype.isFieldDisabled=function(a){return this._map[a].control.isDisabled();
};
Jui.option.BackForm.prototype.setFieldDisabled=function(b,a){this._map[b].control.setDisabled(Jui.cast.toBool(a,true));
};
Jui.option.BackForm.prototype.setFieldEnabled=function(b,a){this.setFieldDisabled(b,!Jui.cast.toBool(a,true));
};
Jui.option.BackForm.prototype.isFieldRequired=function(a){return this._map[a].required;
};
Jui.option.BackForm.prototype.setFieldRequired=function(b,a){this._map[b].required=Jui.cast.toBool(a,true);
};
Jui.option.BackForm.prototype.validate=function(i){var g=this;
for(var j in g._map){var e=g._map[j];
var f=e.control;
if(f instanceof Jui.option.List){if(!f.validate(i)){return false;
}continue;
}if(!f.getValue){continue;
}var h=f.getValue();
if(g.isFieldRequired(j)&&!f.isDisabled()&&Jui.string.isEmpty(h)){if(!e.acceptPureText||Jui.string.isEmpty(f.getText())){g._showValidationMessage(i,e,"Jui.BackForm.RequiredAlert");
return false;
}}var c=e.maxLength>0?e.maxLength:2147483647;
var k=f instanceof Jui.option.Grid?JSON.stringify(h):h;
if(typeof(k)=="string"&&k.length>c){g._showValidationMessage(i,e,"Jui.BackForm.ValueTooLong");
return false;
}if(!Jui.string.isEmpty(h)){var d=null;
if(!Jui.string.isEmpty(e.validation)){var m=("^"+e.validation+"$").replace(/^\^+/,"^").replace(/\$+$/,"$");
d=new RegExp(m);
}else{if(f instanceof Jui.basic.InputBox){if(f.getType()=="phone"){d=/^\s*[0-9()#+-]+\s*$/;
}else{if(f.getType()=="email"){d=/^\s*[\w\d-_\.]+@[\w\d-_\.]+\s*$/;
}}}}if(d!=null&&!d.test(h)){g._showValidationMessage(i,e,"Jui.BackForm.RegExpAlert");
return false;
}if(f instanceof Jui.basic.MultiCheckBox){var a=f.getArgs().capacity;
if(a>0&&f.getValues().length>a){var b="Jui.BackForm.MultiCheckBox.TooManyItems";
var l=Utility.formatText(b,e.title,a);
g._showValidationMessage(i,e,l);
return false;
}}}}return true;
};
Jui.option.BackForm.prototype.validateJson=function(b){for(var h in this._map){var g=this._map[h];
var e=g.control;
var f=b[h];
if(me.isFieldRequired(h)&&!e.isDisabled()&&Jui.string.isEmpty(f)){if(!g.acceptPureText||Jui.string.isEmpty(b[g.textField])){return false;
}}var a=g.maxLength>0?g.maxLength:2147483647;
if(typeof(f)=="string"&&f.length>a){return false;
}if(!Jui.string.isEmpty(f)){var d=null;
if(!Jui.string.isEmpty(g.validation)){var c=("^"+g.validation+"$").replace(/^\^+/,"^").replace(/\$+$/,"$");
d=new RegExp(c);
}else{if(e instanceof Jui.basic.InputBox){if(e.getType()=="phone"){d=/^\s*[0-9()#+-]+\s*$/;
}else{if(e.getType()=="email"){d=/^\s*[\w\d-_\.]+@[\w\d-_\.]+\s*$/;
}}}}if(d!=null&&!d.test(f)){return false;
}}}return true;
};
Jui.option.BackForm.prototype.updateData=function(a){Jui.object.merge(this._record,a);
for(var c in this._map){var b=this._map[c];
if(c in a||b.acceptPureText&&(b.textField in a)){this._setControlValue(b.control,a[c],a[b.textField]);
}}};
Jui.option.BackForm.prototype.clearModificationFlag=function(){var b=this;
b._oldValues={};
for(var d in b._map){var c=b._map[d];
var a=c.control;
if(a.getValue){b._oldValues[d]=a.getValue();
if(a instanceof Jui.basic.EntityBox&&c.acceptPureText){b._oldValues[a.getTextField()]=a.getText();
}}}};
Jui.option.BackForm.prototype._showValidationMessage=function(a,d,c){if(Jui.cast.toBool(a,true)){var b=Jui.i18n.getText(c);
Jui.message.hint(b.replace("${0}",d.title));
d.control.focus();
}};
Jui.option.BackForm.prototype._setControlValue=function(b,a,c){if(b instanceof Jui.option.List){b.loadData(a);
}else{if(b.setValue){b.setValue(a,c);
}}};
