Jui.$define("Jui.option.Calendar",Jui.basic.Control);
Jui.option.Calendar.getHtml=function(d,f,c){d=d||{};
var b=d.hasLeft?true:null;
var e="JuiCalendar"+(Jui.string.isEmpty(d.className)?"":" "+d.className);
var a="<div"+Jui.$p({"class":e,id:f,style:d.style,hasLeft:b})+" unselectable=on onselectstart='return false'><div class=JuiCalendarLeftPane></div><div class=JuiCalendarRightPane><div class=JuiCalendarTopPane><div class='JuiCalendarButton JuiCalendarDay' _mode=day>"+Jui.i18n.getText("Jui.Calendar.Day")+"</div><div class='JuiCalendarButton JuiCalendarWeek' _mode=week>"+Jui.i18n.getText("Jui.Calendar.Week")+"</div><div class='JuiCalendarButton JuiCalendarMonth' _mode=month>"+Jui.i18n.getText("Jui.Calendar.Month")+"</div><div class='JuiCalendarButton JuiCalendarToday'>"+Jui.i18n.getText("Jui.Calendar.Today")+"</div><div class='JuiCalendarButton JuiCalendarBack'>&lt;</div><div class='JuiCalendarButton JuiCalendarForward'>&gt;</div><div class=JuiCalendarTitle></div></div><div class=JuiCalendarHeadPane></div><div class=JuiCalendarTimePane></div><div class=JuiCalendarBodyPane></div></div></div>";
return a;
};
Jui.option.Calendar.initialize=function(c,b,a){b=b||{};
a=a||this;
var d=this.superClass.initialize(c,b,a);
d._weekStart=(b.weekStart||0)%7;
d.ondata=b.ondata;
d.onactivityclick=b.onactivityclick;
d.onactivitydoubleclick=b.onactivitydoubleclick;
d.onactivitycontextmenu=b.onactivitycontextmenu;
d._leftPane=c.children[0];
d._rightPane=c.children[1];
d._topPane=d._rightPane.children[0];
d._headPane=d._rightPane.children[1];
d._timePane=d._rightPane.children[2];
d._bodyPane=d._rightPane.children[3];
d._dayButton=d._topPane.children[0];
d._weekButton=d._topPane.children[1];
d._monthButton=d._topPane.children[2];
d._todayButton=d._topPane.children[3];
d._backButton=d._topPane.children[4];
d._forwardButton=d._topPane.children[5];
d._title=d._topPane.children[6];
d._bodyPane.onscroll=a.doScroll;
d._bodyPane.onclick=a.doBodyClick;
d._bodyPane.ondblclick=a.doBodyDoubleClick;
d._bodyPane.oncontextmenu=a.doBodyContextMenu;
d._dayButton.onclick=a.doModeButtonClick;
d._weekButton.onclick=a.doModeButtonClick;
d._monthButton.onclick=a.doModeButtonClick;
d._todayButton.onclick=a.doTodayButtonClick;
d._backButton.onclick=a.doDirectionButtonClick;
d._forwardButton.onclick=a.doDirectionButtonClick;
d._initializeTimePane();
d.load({users:b.users||[],date:b.date||new Date(),mode:b.mode||"day"});
return d;
};
Jui.option.Calendar.prototype.refresh=function(){this._caculateRange();
eventObject={start:this._start,end:this._end,userIds:[]};
for(var a=0;
a<this._users.length;
++a){eventObject.userIds.push(this._users[a].id);
}this.fireEvent("ondata",eventObject);
};
Jui.option.Calendar.prototype.load=function(b,a){if(a!=null&&(a.start!=this._start||a.end!=this._end)){return;
}if(b.date!=null){this.setDate(b.date,false);
}if(b.users!=null){this.setUsers(b.users,false);
}if(b.mode!=null){this.setMode(b.mode,false);
}this._caculateRange();
if(this._users.length>1&&this._mode=="month"){this._rightPane.className="JuiCalendarRightPane JuiCalendarRightPaneMonthMultiple";
}else{if(this._users.length>1){this._rightPane.className="JuiCalendarRightPane JuiCalendarRightPaneMultiple";
}else{if(this._mode=="month"){this._rightPane.className="JuiCalendarRightPane JuiCalendarRightPaneMonth";
}else{this._rightPane.className="JuiCalendarRightPane";
}}}if(this._mode=="month"){this._loadMonth(b.activities||[]);
}else{if(this._mode=="week"){this._loadWeek(b.activities||[]);
}else{this._loadDay(b.activities||[]);
}}};
Jui.option.Calendar.prototype.setUsers=function(b,a){this._users=b||[];
if(a!=false){this.refresh();
}};
Jui.option.Calendar.prototype.setDate=function(a,b){this._date=a||new Date();
if(b!=false){this.refresh();
}};
Jui.option.Calendar.prototype.setMode=function(b,a){if(b!=this._mode){if(this._mode!=null){this["_"+this._mode+"Button"].removeAttribute("current");
}this["_"+b+"Button"].setAttribute("current",true);
this._mode=b;
if(a!=false){this.refresh();
}}};
Jui.option.Calendar.doScroll=function(){var a=Jui.$owner();
a._timePane.scrollTop=this.scrollTop;
};
Jui.option.Calendar.doModeButtonClick=function(){Jui.$owner().setMode(this.getAttribute("_mode"));
};
Jui.option.Calendar.doTodayButtonClick=function(){Jui.$owner().setDate(new Date());
};
Jui.option.Calendar.doDirectionButtonClick=function(){var e=Jui.$owner();
var c=this==e._backButton?-1:1;
if(e._mode=="month"){var g=e._date.getFullYear();
var a=e._date.getMonth();
var f=e._date.getDate();
var b=e._getMonthDayCount(g,a+c);
e.setDate(new Date(g,a+c,Math.min(f,b)));
}else{if(e._mode=="week"){e.setDate(new Date(e._date.getTime()+c*7*86400000));
}else{e.setDate(new Date(e._date.getTime()+c*86400000));
}}};
Jui.option.Calendar.doBodyClick=function(){var a=Jui.$owner();
var b=Jui.dom.getAncestorByClassName("JuiCalendarActivity");
if(b!=null){var c={id:b.getAttribute("_id"),name:b.innerText};
a.fireEvent("onactivityclick",{activity:c});
}};
Jui.option.Calendar.doBodyDoubleClick=function(){var a=Jui.$owner();
var b=Jui.dom.getAncestorByClassName("JuiCalendarActivity");
if(b!=null){var c={id:b.getAttribute("_id"),name:b.innerText};
a.fireEvent("onactivitydoubleclick",{activity:c});
}};
Jui.option.Calendar.doBodyContextMenu=function(){var a=Jui.$owner();
var b=Jui.dom.getAncestorByClassName("JuiCalendarActivity");
if(b!=null){var c={id:b.getAttribute("_id"),name:b.innerText};
a.fireEvent("onactivitycontextmenu",{activity:c});
return false;
}};
Jui.option.Calendar.prototype._loadDay=function(d){var k=Jui.cast.toString(this._date,"yyyy-MM-dd ww");
this._title.innerHTML=k;
var m=[[],[]];
var c=Math.max(this._users.length,1);
var a=100/c+"%";
var b=this._bodyPane.scrollTop;
for(var f=0;
f<c;
++f){m[0].push("<div class=JuiCalendarDataHeadOuter style='width:"+a+"'>");
if(c>1){m[0].push("<div class=JuiDataUserName>"+this._users[f].name+"</div>");
}m[0].push("<div class=JuiCalendarDataHeadBorder><table><tr><td class=JuiCalendarDataHead>"+k+"</td></tr>");
m[0].push("<tr><td class=JuiCalendarDataJaw></td></tr></table></div>");
m[0].push("</div>");
m[1].push("<div class=JuiCalendarDataBodyOuter style='width:"+a+"'><table>");
for(var e=0;
e<24;
++e){m[1].push("<tr><td"+(e==0?" top":"")+" up></td></tr>");
m[1].push("<tr><td"+(e==23?" bottom":"")+" down></td></tr>");
}m[1].push("</table><div class=JuiCalendarActivityColumn>");
var g=this._users.length>1?this._users[f].id:null;
var h=this._getDateAcitivities(d,g,this._date);
for(var e=0;
e<h.length;
++e){var l=h[e];
m[1].push("<div class=JuiCalendarActivity style='"+l.style+"' _id='"+Jui.$h(l.id)+"'>");
m[1].push(Jui.$h(l.name));
m[1].push("</div>");
}m[1].push("</div></div>");
}this._headPane.innerHTML=m[0].join("");
this._bodyPane.innerHTML=m[1].join("");
this._timePane.scrollTop=this._bodyPane.scrollTop=b;
};
Jui.option.Calendar.prototype._loadWeek=function(d){this._title.innerHTML=Jui.i18n.getText("Jui.Calendar.RangeTitle").replace("${0}",this._start).replace("${1}",this._end);
var q=[[],[]];
var c=Math.max(this._users.length,1);
var a=100/c+"%";
var f=Jui.cast.toDate(this._start).getTime();
var b=this._bodyPane.scrollTop;
for(var h=0;
h<c;
++h){q[0].push("<div class=JuiCalendarDataHeadOuter style='width:"+a+"'>");
if(c>1){q[0].push("<div class=JuiDataUserName>"+this._users[h].name+"</div>");
}q[0].push("<div class=JuiCalendarDataHeadBorder><table><tr>");
for(var g=0;
g<7;
++g){var o=Jui.util.getWeekDayName((this._weekStart+g)%7,true);
q[0].push("<td class=JuiCalendarDataHead>"+o+"</td>");
}q[0].push("</tr><tr>"+Jui.string.repeat("<td class=JuiCalendarDataJaw></td>",7)+"</tr></table></div>");
q[0].push("</div>");
q[1].push("<div class=JuiCalendarDataBodyOuter style='width:"+a+"'><table>");
for(var g=0;
g<24;
++g){q[1].push("<tr>"+Jui.string.repeat("<td"+(g==0?" top":"")+" up>",7)+"</td></tr>");
q[1].push("<tr>"+Jui.string.repeat("<td"+(g==23?" bottom":"")+" down>",7)+"</td></tr>");
}q[1].push("</table><div class=JuiCalendarActivityColumn>");
var l=this._users.length>1?this._users[h].id:null;
for(var g=0;
g<7;
++g){var m=this._getDateAcitivities(d,l,new Date(f+g*86400000),g);
for(var e=0;
e<m.length;
++e){var p=m[e];
q[1].push("<div class=JuiCalendarActivity style='"+p.style+"' _id='"+Jui.$h(p.id)+"'>");
q[1].push(Jui.$h(p.name));
q[1].push("</div>");
}}q[1].push("</div></div>");
}this._headPane.innerHTML=q[0].join("");
this._bodyPane.innerHTML=q[1].join("");
this._timePane.scrollTop=this._bodyPane.scrollTop=b;
};
Jui.option.Calendar.prototype._loadMonth=function(a){this._title.innerHTML=Jui.i18n.getText("Jui.Calendar.RangeTitle").replace("${0}",this._start).replace("${1}",this._end);
var u=[[],[]];
var f=Math.max(this._users.length,1);
var g=100/f+"%";
var r=this._getMonthWeekCount(this._date.getFullYear(),this._date.getMonth());
var e=this._getWeekStartDate(Jui.cast.toDate(this._start)).getTime();
for(var p=0;
p<f;
++p){u[0].push("<div class=JuiCalendarDataHeadOuter style='width:"+g+"'>");
if(f>1){u[0].push("<div class=JuiDataUserName>"+this._users[p].name+"</div>");
}u[0].push("<div class=JuiCalendarDataHeadBorder><table><tr>");
for(var o=0;
o<7;
++o){var w=Jui.util.getWeekDayName((this._weekStart+o)%7,true);
var q=(o==0?" left":"")+(o==6?" right":"");
u[0].push("<td class=JuiCalendarDataHead"+q+">"+w+"</td>");
}u[0].push("</tr></table></div>");
u[0].push("</div>");
u[1].push("<div class=JuiCalendarDataBodyOuter style='width:"+g+"'><table>");
var c=this._users.length>1?this._users[p].id:null;
for(var o=0;
o<r;
++o){var t=(o==0?" top":"")+(o==r-1?" bottom":"");
u[1].push("<tr>");
for(var l=0;
l<7;
++l){var v=new Date(e+(o*7+l)*86400000);
var q=(l==0?" left":"")+(l==6?" right":"");
var b=v.getMonth()==this._date.getMonth();
u[1].push("<td"+(b?"":" class=JuiCalendarOtherMonthDate")+t+q+">");
u[1].push("<div class=JuiCalendarMonthDate>"+v.getDate()+"</div>");
u[1].push("");
for(var h=0,d=this._getDateAcitivities(a,c,v);
h<d.length;
++h){var s=d[h];
u[1].push("<div class=JuiCalendarActivity _id='"+Jui.$h(s.id)+"'>");
u[1].push(Jui.$h(s.name));
u[1].push("</div>");
}u[1].push("</td>");
}u[1].push("</tr>");
}u[1].push("</table></div>");
}this._headPane.innerHTML=u[0].join("");
this._bodyPane.innerHTML=u[1].join("");
};
Jui.option.Calendar.prototype._getMonthDayCount=function(a,b){return(new Date(a,b+1,1).getTime()-new Date(a,b,1).getTime())/86400000;
};
Jui.option.Calendar.prototype._getMonthWeekCount=function(b,c){var d=this._getWeekStartDate(new Date(b,c,1));
var a=new Date(b,c,this._getMonthDayCount(b,c));
return((a.getTime()-d.getTime())/86400000+1)/7;
};
Jui.option.Calendar.prototype._getWeekStartDate=function(a){return new Date(a.getTime()-((a.getDay()-this._weekStart+7)%7)*86400000);
};
Jui.option.Calendar.prototype._initializeTimePane=function(){var a=["<table>"];
for(var b=0;
b<24;
++b){a.push("<tr><td"+(b==0?" top":b==23?" bottom":"")+">"+b+":00</td></tr>");
}a.push("</table>");
this._timePane.innerHTML=a.join("");
};
Jui.option.Calendar.prototype._caculateRange=function(){if(this._mode=="month"){var d=this._date.getFullYear();
var f=this._date.getMonth();
var e=this._getMonthDayCount(d,f);
var a=new Date(d,f,1);
this._start=Jui.cast.toString(a,"yyyy-MM-dd");
this._end=Jui.cast.toString(new Date(d,f,e),"yyyy-MM-dd");
}else{if(this._mode=="week"){var b=(this._date.getDay()-this._weekStart+7)%7;
var c=this._date.getTime();
this._start=Jui.cast.toString(new Date(c-b*86400000),"yyyy-MM-dd");
this._end=Jui.cast.toString(new Date(c-b*86400000+6*86400000),"yyyy-MM-dd");
}else{this._start=Jui.cast.toString(this._date,"yyyy-MM-dd");
this._end=this._start;
}}};
Jui.option.Calendar.prototype._getDateAcitivities=function(a,d,A,u){var f=Jui.cast.toDate(Jui.cast.toString(A,"yyyy-MM-dd"));
var e=new Date(f.getTime()+86400000);
var p=this._users.length>1;
var m=[];
for(var v=0;
v<a.length;
++v){var z=a[v];
if(!p||z.userId==d){var g=Jui.cast.toDate(z.start);
var q=Jui.cast.toDate(z.end);
if(g<e&&q>f){m.push(Jui.object.merge({start:g,end:q},z));
}}}m.sort(function(j,i){if(j.start==i.start){return j.end.getTime()-i.end.getTime();
}return j.start.getTime()-i.start.getTime();
});
if(this._mode=="month"){return m;
}var n=[];
for(var v=0;
v<m.length;
++v){var z=m[v];
var c=false;
var h=-1;
for(var s=0;
s<n.length;
++s){if(n[s]>z.start){c=true;
}else{if(h==-1){h=s;
}}}if(!c){for(var s=0;
s<v;
++s){if(m[s].slotCount==null){m[s].slotCount=n.length;
}}z.slotIndex=0;
n=[z.end];
}else{if(h!=-1){z.slotIndex=h;
n[h]=z.end;
}else{z.slotIndex=n.length;
n.push(z.end);
}}}var x=90/(this._mode=="day"?1:7);
var y=100/7;
u=u||0;
for(var v=0;
v<m.length;
++v){var z=m[v];
if(z.slotCount==null){z.slotCount=n.length;
}var r=y*u+(x*z.slotIndex/z.slotCount)+"%";
var k=(x/z.slotCount)+"%";
var o=Math.max(0,100*(z.start-f)/86400000)+"%";
var B=Math.max(0,100*Math.min(e-z.end,e-z.start-1800000)/86400000)+"%";
z.style=Jui.$s({left:r,width:k,top:o,bottom:B});
}return m;
};
