Jui.$define("Jui.option.Condition",Jui.basic.Control);
Jui.option.Condition.getHtml=function(b,c,a){b=b||{};
return"<div class=JuiCondition"+Jui.$p({id:c,style:b.style})+"><div class=JuiConditionEdit><div class=JuiConditionEditFieldCell></div><div class=JuiConditionEditOperatorCell></div><div class=JuiConditionEditValueCell></div><div class=JuiConditionEditDateCell></div><div class=JuiConditionEditDateCell></div></div></div>";
};
Jui.option.Condition.initialize=function(d,c,b){c=c||{};
b=b||this;
var e=this.superClass.initialize(d,c,b);
e.onloadselect=c.onloadselect;
e.onloadunit=c.onloadunit;
e._isSimpleMode=Jui.cast.toBool(c.isSimpleMode);
e._units={};
e._selectItems={};
e._currentNode=null;
e._menuNode=null;
e._edit=d.firstChild;
var a=e._edit.children;
e._relationBox=Jui.basic.ComboBox.create({owner:e,target:d,style:"width:200px",onchange:Jui.option.Condition.doRelationBoxChange});
e._addBox=Jui.basic.ComboBox.create({owner:e,target:d,style:"width:200px",onchange:Jui.option.Condition.doAddBoxChange});
e._fieldBox=Jui.basic.ComboBox.create({owner:e,target:a[0],style:"width:100%",onchange:Jui.option.Condition.doFieldBoxChange});
e._operatorBox=Jui.basic.ComboBox.create({owner:e,target:a[1],style:"width:100%",onchange:Jui.option.Condition.doOperatorBoxChange});
e._valueInputBox=Jui.basic.InputBox.create({target:a[2],style:"width:100%"});
e._valueComboBox=Jui.basic.ComboBox.create({target:a[2],style:"width:100%"});
e._valueEntityBox=Jui.basic.EntityBox.create({target:a[2],style:"width:100%",dropOnly:true,onselect:c.entityBoxSelectHandler,onview:c.entityBoxViewHandler,onbeforedrop:c.entityBoxBeforeDropHandler});
e._valueMultiEntityBox=Jui.basic.MultiEntityBox.create({target:a[2],style:"width:100%",dropOnly:true,onselect:c.multiEntityBoxSelectHandler});
e._valueDateBox=Jui.basic.DateBox.create({target:a[2],style:"width:100%",showWeek:false});
e._dateInputBox=Jui.basic.InputBox.create({target:a[3],style:"width:100%"});
e._dateComboBox=Jui.basic.ComboBox.create({target:a[4],style:"width:100%",items:Jui.option.Condition._DATE_COMBOBOX_ITEMS});
e._generalMenu=Jui.basic.PopupMenu.create({owner:e,items:Jui.option.Condition._GENERAL_MENU_ITEMS,onclick:Jui.option.Condition.doMenuClick});
e._groupMenu=Jui.basic.PopupMenu.create({owner:e,items:Jui.option.Condition._GROUP_MENU_ITEMS,onclick:Jui.option.Condition.doMenuClick});
e._valueBoxes=[];
e._valueBoxes.push(e._valueInputBox);
e._valueBoxes.push(e._valueComboBox);
e._valueBoxes.push(e._valueEntityBox);
e._valueBoxes.push(e._valueMultiEntityBox);
e._valueBoxes.push(e._valueDateBox);
e._valueBoxes.push(e._dateInputBox);
e._valueBoxes.push(e._dateComboBox);
d.removeChild(e._edit);
d.removeChild(e._relationBox.element);
d.removeChild(e._addBox.element);
e.setDisabled(Jui.cast.toBool(c.disabled,false));
return e;
};
Jui.option.Condition.prototype.load=function(b){var c=this;
c._unsetCurrentNode();
c._units={};
for(var a=0;
a<b.units.length;
++a){c._addUnit(b.units[a]);
}c._currentNode=null;
c._menuNode=null;
if(c._loadCheck(b.unitId,b.conditions)){c.element.innerHTML=c._getItemsHtml(b.unitId,b.conditions);
c._initializeNodes(c.element.firstChild,b.conditions,b.unitId);
c._refreshLines();
}else{c.element.innerHTML="";
}};
Jui.option.Condition.prototype.getData=function(){return this._getData(this.element.firstChild);
};
Jui.option.Condition.prototype.validate=function(){var a=this;
if(a._currentNode!=null&&a._isLeafNode(a._currentNode)){a._updateData();
}return a._validate(a.element.firstChild);
};
Jui.option.Condition.doBarClick=function(){var b=Jui.$owner();
if(!(b instanceof Jui.option.Condition)||b.isDisabled()){return;
}var a=this.parentElement.parentElement;
if(!event.ctrlKey&&!b._isGroupNode(a)){b._setCurrentNode(a);
}if(event.ctrlKey&&!b._isAddNode(a)){b._switchSelection(a);
}};
Jui.option.Condition.doRelationBoxChange=function(){var f=this._owner;
var e=f._currentNode;
var b=e.lastChild.children;
var a=f._relationBox.getValue().substring(1);
var d=f._units[e._data.unitId].relationMap[a];
e._data.relationId=a;
for(var c=b.length-2;
c>=0;
--c){f._removeNode(b[c]);
}b[0].lastChild._data={unitId:d.unitId};
Jui.dom.setInnerText(e._bar.firstChild,f._relationBox.getText());
};
Jui.option.Condition.doAddBoxChange=function(){var f=this._owner;
var b=f._currentNode;
var g=f._addBox.getValue().charAt(0);
var i=f._addBox.getValue().substring(1);
var d=b._data.unitId;
if(g=="F"){var j={fieldName:i};
var e=f._getLeafHtml(d,j);
Jui.dom.insertHtml(b,"BeforeBegin",e);
f._initializeNode(b.previousSibling,j,d);
f._setCurrentNode(b.previousSibling);
}else{var a=f._units[d].relationMap[i];
if(f._units[a.unitId]==null){var h=f.fireEvent("onloadunit",{unitId:a.unitId});
f._addUnit(h);
}var j={relationId:i,items:[]};
var e=f._getBranchHtml(d,j);
Jui.dom.insertHtml(b,"BeforeBegin",e);
f._initializeNode(b.previousSibling,j,d);
var c=b.previousSibling.lastChild.lastChild;
f._setCurrentNode(c);
}f._refreshLines();
};
Jui.option.Condition.doFieldBoxChange=function(){var a=this._owner;
a._refreshOperatorBox(false);
a._refreshValueBox(true,false);
};
Jui.option.Condition.doOperatorBoxChange=function(){var a=this._owner;
a._refreshValueBox(true,false);
};
Jui.option.Condition.doBarContextMenu=function(){var g=Jui.$owner();
var c=Jui.dom.getAncestorByClassName("JuiConditionNode");
if(c==null||!(g instanceof Jui.option.Condition)){return;
}if(g.isDisabled()||g._isAddNode(c)){return false;
}var b=g._isGroupNode(c)?g._groupMenu:g._generalMenu;
var d=false;
var a=false;
if(g._isSelected(c)&&!g._isSimpleMode){var h=c.parentElement.children;
var f=0;
for(var e=0;
e<h.length;
++e){if(g._isSelected(h[e])){++f;
}}if(f>1&&f==g._getSelectedCount(g.element.firstChild)){var j=c.parentElement.parentElement;
if(f<h.length-1){d=true;
a=true;
}else{if(j==g.element||g._isRelationNode(j)||j._data.operator=="and"){a=true;
}else{d=true;
}}}}b.setItemEnabled("GroupByAnd",d);
b.setItemEnabled("GroupByOr",a);
g._menuNode=c;
b.show();
return false;
};
Jui.option.Condition.doMenuClick=function(b){var a=this.getOwner();
if(b.id=="Delete"){a._removeNode(a._menuNode,true);
}else{if(b.id=="Select"){a._switchSelection(a._menuNode);
}else{if(b.id=="ReleaseGroup"){a._releaseGroup(a._menuNode);
}else{if(b.id=="SwitchGroup"){a._switchGroup(a._menuNode);
}else{if(b.id=="GroupByAnd"){a._groupBy(a._menuNode,"and");
}else{if(b.id=="GroupByOr"){a._groupBy(a._menuNode,"or");
}}}}}}};
Jui.option.Condition._getOperatorItems=function(){var a=[];
for(var c=0;
c<arguments.length;
++c){var b=arguments[c];
a.push({value:b,text:Jui.option.Condition._OPERATORS[b]});
}return a;
};
Jui.option.Condition._GENERAL_MENU_ITEMS=[{id:"Select",text:Jui.i18n.getText("Jui.Condition.SwitchSelection")},{id:"Delete",text:Jui.i18n.getText("Jui.Condition.Delete")},{splitter:true},{id:"GroupByAnd",text:Jui.i18n.getText("Jui.Condition.GroupByAnd")},{id:"GroupByOr",text:Jui.i18n.getText("Jui.Condition.GroupByOr")}];
Jui.option.Condition._GROUP_MENU_ITEMS=[{id:"Select",text:Jui.i18n.getText("Jui.Condition.SwitchSelection")},{id:"SwitchGroup",text:Jui.i18n.getText("Jui.Condition.SwitchGroup")},{id:"ReleaseGroup",text:Jui.i18n.getText("Jui.Condition.ReleaseGroup")},{id:"Delete",text:Jui.i18n.getText("Jui.Condition.Delete")},{splitter:true},{id:"GroupByAnd",text:Jui.i18n.getText("Jui.Condition.GroupByAnd")},{id:"GroupByOr",text:Jui.i18n.getText("Jui.Condition.GroupByOr")}];
Jui.option.Condition._SIMPLEMODE_OPERATORS=["HasData","NotHasData","True","False","Equal","NotEqual","Great","GreatEqual","Less","LessEqual"];
Jui.option.Condition._GROUP_OPERATORS={and:Jui.i18n.getText("Jui.Condition.And"),or:Jui.i18n.getText("Jui.Condition.Or")};
Jui.option.Condition._OPERATORS={Equal:Jui.i18n.getText("Jui.Condition.Equal"),EqualWithSub:Jui.i18n.getText("Jui.Condition.EqualWithSub"),NotEqual:Jui.i18n.getText("Jui.Condition.NotEqual"),Great:Jui.i18n.getText("Jui.Condition.Great"),GreatEqual:Jui.i18n.getText("Jui.Condition.GreatEqual"),Less:Jui.i18n.getText("Jui.Condition.Less"),LessEqual:Jui.i18n.getText("Jui.Condition.LessEqual"),HasData:Jui.i18n.getText("Jui.Condition.HasData"),NotHasData:Jui.i18n.getText("Jui.Condition.NotHasData"),In:Jui.i18n.getText("Jui.Condition.In"),InWithSub:Jui.i18n.getText("Jui.Condition.InWithSub"),Contain:Jui.i18n.getText("Jui.Condition.Contain"),NotContain:Jui.i18n.getText("Jui.Condition.NotContain"),StartWith:Jui.i18n.getText("Jui.Condition.StartWith"),NotStartWith:Jui.i18n.getText("Jui.Condition.NotStartWith"),EndWith:Jui.i18n.getText("Jui.Condition.EndWith"),NotEndWith:Jui.i18n.getText("Jui.Condition.NotEndWith"),Current:Jui.i18n.getText("Jui.Condition.Current"),Previous:Jui.i18n.getText("Jui.Condition.Previous"),Next:Jui.i18n.getText("Jui.Condition.Next"),CurrentPrevious:Jui.i18n.getText("Jui.Condition.CurrentPrevious"),CurrentNext:Jui.i18n.getText("Jui.Condition.CurrentNext"),CurrentUser:Jui.i18n.getText("Jui.Condition.CurrentUser"),NotCurrentUser:Jui.i18n.getText("Jui.Condition.NotCurrentUser"),CurrentDept:Jui.i18n.getText("Jui.Condition.CurrentDept"),CurrentDeptWithSub:Jui.i18n.getText("Jui.Condition.CurrentDeptWithSub"),NotCurrentDept:Jui.i18n.getText("Jui.Condition.NotCurrentDept"),NotCurrentDeptWithSub:Jui.i18n.getText("Jui.Condition.NotCurrentDeptWithSub"),True:Jui.i18n.getText("Jui.Condition.True"),False:Jui.i18n.getText("Jui.Condition.False")};
Jui.option.Condition._DATE_SPECIAL_OPERATORS={Previous:1,Next:1,CurrentPrevious:1,CurrentNext:1};
Jui.option.Condition._UNARY_OPERATORS={HasData:1,NotHasData:1,CurrentUser:1,NotCurrentUser:1,CurrentDept:1,CurrentDeptWithSub:1,NotCurrentDept:1,NotCurrentDeptWithSub:1,True:1,False:1};
Jui.option.Condition._ENTITYBOX_OPERATORS={Equal:1,EqualWithSub:1,NotEqual:1};
Jui.option.Condition._MULTIENTITYBOX_OPERATORS={In:1,InWithSub:1};
Jui.option.Condition._LINE_TYPES=["HorzLine","UpLLine","DownLLine","TLine"];
Jui.option.Condition._DATE_COMBOBOX_ITEMS=[{value:"year",text:Jui.i18n.getText("Jui.Condition.Year")},{value:"quarter",text:Jui.i18n.getText("Jui.Condition.Quarter")},{value:"month",text:Jui.i18n.getText("Jui.Condition.Month")},{value:"week",text:Jui.i18n.getText("Jui.Condition.Week")},{value:"day",text:Jui.i18n.getText("Jui.Condition.Day")},{value:"hour",text:Jui.i18n.getText("Jui.Condition.Hour")},{value:"minute",text:Jui.i18n.getText("Jui.Condition.Minute")}];
Jui.option.Condition._BOOLEAN_ITEMS=Jui.option.Condition._getOperatorItems("True","False");
Jui.option.Condition._NUMBER_ITEMS=Jui.option.Condition._getOperatorItems("Equal","NotEqual","Great","GreatEqual","Less","LessEqual","HasData","NotHasData");
Jui.option.Condition._DATE_ITEMS=Jui.option.Condition._getOperatorItems("Equal","NotEqual","Great","GreatEqual","Less","LessEqual","Current","Previous","Next","CurrentPrevious","CurrentNext","HasData","NotHasData");
Jui.option.Condition._TEXT_ITEMS=Jui.option.Condition._getOperatorItems("Equal","NotEqual","Contain","NotContain","StartWith","NotStartWith","EndWith","NotEndWith","HasData","NotHasData");
Jui.option.Condition._USER_ITEMS=Jui.option.Condition._getOperatorItems("CurrentUser","NotCurrentUser","Equal","NotEqual","Contain","NotContain","StartWith","NotStartWith","EndWith","NotEndWith","HasData","NotHasData");
Jui.option.Condition._DEPARTMENT_ITEMS=Jui.option.Condition._getOperatorItems("CurrentDept","CurrentDeptWithSub","NotCurrentDept","NotCurrentDeptWithSub","Equal","EqualWithSub","NotEqual","Contain","NotContain","StartWith","NotStartWith","EndWith","NotEndWith","HasData","NotHasData");
Jui.option.Condition._KEY_ITEMS=Jui.option.Condition._getOperatorItems("Equal","NotEqual","HasData","NotHasData");
Jui.option.Condition._KEY_USER_ITEMS=Jui.option.Condition._getOperatorItems("CurrentUser","NotCurrentUser","Equal","NotEqual","HasData","NotHasData");
Jui.option.Condition._KEY_DEPARTMENT_ITEMS=Jui.option.Condition._getOperatorItems("CurrentDept","CurrentDeptWithSub","NotCurrentDept","NotCurrentDeptWithSub","Equal","EqualWithSub","NotEqual","HasData","NotHasData");
Jui.option.Condition._MULTI_ENTITY_ITEMS=Jui.option.Condition._getOperatorItems("In","HasData","NotHasData");
Jui.option.Condition._TREE_MULTI_ENTITY_ITEMS=Jui.option.Condition._getOperatorItems("In","InWithSub","HasData","NotHasData");
Jui.option.Condition._TYPE_ITEM_MAP={CheckBox:Jui.option.Condition._BOOLEAN_ITEMS,"InputBox-Integer":Jui.option.Condition._NUMBER_ITEMS,"InputBox-BigInt":Jui.option.Condition._NUMBER_ITEMS,"InputBox-Double":Jui.option.Condition._NUMBER_ITEMS,"InputBox-Percent":Jui.option.Condition._NUMBER_ITEMS,"DateBox-Date":Jui.option.Condition._DATE_ITEMS,"DateBox-DateTime":Jui.option.Condition._DATE_ITEMS,"InputBox-Key":Jui.option.Condition._KEY_ITEMS};
Jui.option.Condition.prototype._getItemsHtml=function(f,b){var a=["<div class=JuiConditionNodeBlock>"];
for(var d=0;
d<b.length;
++d){var e=b[d];
var c=e.items==null?this._getLeafHtml(f,e):this._getBranchHtml(f,e);
a.push(c);
}a.push(this._getAddHtml());
a.push("</div>");
return a.join("");
};
Jui.option.Condition.prototype._getBranchHtml=function(h,f){var d=f.relationId!=null;
var a=Jui.option.Condition._GROUP_OPERATORS[f.operator];
var b=Jui.i18n.getText("Jui.Condition.Group").replace("${0}",a);
var e=d?this._units[h].relationMap[f.relationId]:null;
var g=d?e.text:b;
var c=d?e.unitId:h;
return"<div class=JuiConditionNode><div class=JuiConditionRow type="+(d?"Relation":"Group")+"><div class=JuiConditionBar><label>"+Jui.$h(g)+"</label></div></div>"+this._getItemsHtml(c,f.items)+"</div>";
};
Jui.option.Condition.prototype._getLeafHtml=function(d,b){var a=this._units[d].fieldMap[b.fieldName].text;
var c=this._getText(d,b.fieldName,b.operator,b.value,b.text);
return"<div class=JuiConditionNode><div class=JuiConditionRow type=Leaf><div class=JuiConditionBar><div class=JuiConditionFieldCell>"+Jui.$h(a)+"</div><div class=JuiConditionOperatorCell>"+Jui.option.Condition._OPERATORS[b.operator]+"</div><div class=JuiConditionValueCell>"+Jui.$h(c)+"</div></div></div></div>";
};
Jui.option.Condition.prototype._getAddHtml=function(){return"<div class=JuiConditionNode><div class=JuiConditionRow type=Add><div class=JuiConditionBar><label>"+Jui.i18n.getText("Jui.Condition.SelectHint")+"</label></div></div></div>";
};
Jui.option.Condition.prototype._initializeNodes=function(e,b,d){for(var c=0,a=e.children;
c<a.length;
++c){this._initializeNode(a[c],b[c],d);
}};
Jui.option.Condition.prototype._initializeNode=function(d,c,e){var b=this;
d._row=d.firstChild;
d._bar=d.firstChild.firstChild;
d._data=c||{unitId:e};
d._bar.onclick=Jui.option.Condition.doBarClick;
d._bar.oncontextmenu=Jui.option.Condition.doBarContextMenu;
if(c!=null){if(c.items==null){c.unitId=e;
}else{if(c.relationId==null){b._initializeNodes(d.lastChild,c.items,e);
}else{var a=b._units[e].relationMap[c.relationId];
c.unitId=e;
b._initializeNodes(d.lastChild,c.items,a.unitId);
}}}};
Jui.option.Condition.prototype._loadCheck=function(f,a){var g=this._units[f];
for(var d=0;
d<a.length;
++d){var e=a[d];
if(e.items==null&&!(g&&g.fieldMap[e.fieldName])){Jui.message.alert(Jui.i18n.getText("Jui.Condition.InvalidField").replace("${0}",e.fieldName));
return false;
}if(e.relationId!=null&&!(g&&g.relationMap[e.relationId])){Jui.message.alert(Jui.i18n.getText("Jui.Condition.InvalidRelation").replace("${0}",e.relationId));
return false;
}if(e.items!=null){var b=e.relationId==null?f:g.relationMap[e.relationId].unitId;
if(!this._loadCheck(b,e.items)){return false;
}}}return true;
};
Jui.option.Condition.prototype._setCurrentNode=function(c){var b=this;
b._unsetCurrentNode();
b._currentNode=c;
c._row.setAttribute("Current",true);
for(var a=0;
a<c._bar.children.length;
++a){c._bar.children[a].style.display="none";
}if(b._isRelationNode(c)){c._bar.appendChild(b._relationBox.element);
b._refreshRelationBox();
}else{if(b._isAddNode(c)){c._bar.appendChild(b._addBox.element);
b._refreshAddBox();
}else{if(b._isLeafNode(c)){c._bar.appendChild(b._edit);
b._refreshFieldBox();
b._refreshOperatorBox(true);
b._refreshValueBox(true,true);
}}}};
Jui.option.Condition.prototype._unsetCurrentNode=function(){var d=this;
var c=d._currentNode;
if(c!=null){if(d._isLeafNode(c)){d._updateData();
}c._row.removeAttribute("Current");
var b=c._bar;
b.removeChild(b.lastChild);
for(var a=0;
a<b.children.length;
++a){b.children[a].style.display="";
}d._currentNode=null;
}};
Jui.option.Condition.prototype._switchSelection=function(a){Jui.dom.tagAttribute(a._row,"Selected",!this._isSelected(a));
};
Jui.option.Condition.prototype._isSelected=function(a){return a._row.hasAttribute("Selected");
};
Jui.option.Condition.prototype._getSelectedCount=function(e){var d=0;
for(var b=0,a=e.children;
b<a.length;
++b){var c=a[b];
if(this._isSelected(c)){++d;
}if(c.children.length==2){d+=this._getSelectedCount(c.lastChild);
}}return d;
};
Jui.option.Condition.prototype._refreshAddBox=function(){var a=this._currentNode._data;
this._addBox.loadItems(this._units[a.unitId].allComboBoxItems);
this._addBox.setValue();
};
Jui.option.Condition.prototype._refreshRelationBox=function(){var a=this._currentNode._data;
this._relationBox.loadItems(this._units[a.unitId].relationComboBoxItems);
this._relationBox.setValue("R"+a.relationId);
};
Jui.option.Condition.prototype._refreshFieldBox=function(){var a=this._currentNode._data;
this._fieldBox.loadItems(this._units[a.unitId].fieldComboBoxItems);
this._fieldBox.setValue("F"+a.fieldName);
};
Jui.option.Condition.prototype._refreshOperatorBox=function(a){var e=this;
var b=e._currentNode._data;
var j=e._fieldBox.getValue();
var f=e._units[b.unitId].fieldMap[j.substring(1)];
var h=/ComboBox/.test(f.type)&&!f.textAsValue?"InputBox-Key":f.type;
var d=Jui.option.Condition._TYPE_ITEM_MAP[h];
if(f.type=="MultiEntityBox"){d=f.isTree?Jui.option.Condition._TREE_MULTI_ENTITY_ITEMS:Jui.option.Condition._MULTI_ENTITY_ITEMS;
}else{if(f.entityType=="Qs.User"){d=f.type=="EntityBox"?Jui.option.Condition._USER_ITEMS:Jui.option.Condition._KEY_USER_ITEMS;
}else{if(f.entityType=="Qs.Department"){d=f.type=="EntityBox"?Jui.option.Condition._DEPARTMENT_ITEMS:Jui.option.Condition._KEY_DEPARTMENT_ITEMS;
}else{if(d==null){d=Jui.option.Condition._TEXT_ITEMS;
}}}}if(e._isSimpleMode){for(var c=d.length-1;
c>=0;
--c){if(Jui.option.Condition._SIMPLEMODE_OPERATORS.indexOf(d[c].value)==-1){d.splice(c,1);
}}}var g=a&&!Jui.string.isEmpty(b.operator)?b.operator:d[0].value;
e._operatorBox.loadItems(d);
e._operatorBox.setValue(g);
};
Jui.option.Condition.prototype._refreshValueBox=function(clearValue,setValue){var me=this;
for(var i=0;
i<me._valueBoxes.length;
++i){me._valueBoxes[i].element.style.display="none";
}if(clearValue){for(var i=0;
i<me._valueBoxes.length;
++i){me._valueBoxes[i].setValue();
}me._dateComboBox.setValue("year");
}var data=me._currentNode._data;
var fieldName=me._fieldBox.getValue();
var operator=me._operatorBox.getValue();
var field=me._units[data.unitId].fieldMap[fieldName.substring(1)];
var valueCell=me._edit.children[2];
valueCell.style.display=operator in Jui.option.Condition._DATE_SPECIAL_OPERATORS?"none":"";
if(operator in Jui.option.Condition._UNARY_OPERATORS){}else{if(operator=="Current"){me._dateComboBox.element.style.display="";
if(setValue&&!Jui.string.isEmpty(data.value)){me._dateComboBox.setValue(data.value);
}}else{if(operator in Jui.option.Condition._DATE_SPECIAL_OPERATORS){me._dateInputBox.element.style.display="";
me._dateComboBox.element.style.display="";
if(setValue&&!Jui.string.isEmpty(data.value)){var pair=data.value.split("|");
me._dateInputBox.setValue(pair[0]);
me._dateComboBox.setValue(pair[1]);
}}else{if(/DateBox/.test(field.type)){me._valueDateBox.element.style.display="";
me._valueDateBox.setFormat(field.type=="DateBox-Date"?"yyyy-MM-dd":"yyyy-MM-dd HH:mm");
if(setValue&&!Jui.string.isEmpty(data.value)){me._valueDateBox.setValue(data.value);
}}else{if(/MultiEntityBox/.test(field.type)&&operator in Jui.option.Condition._MULTIENTITYBOX_OPERATORS){me._valueMultiEntityBox.element.style.display="";
me._valueMultiEntityBox.setEntityType(field.entityType);
if(setValue&&!Jui.string.isEmpty(data.value)){me._valueMultiEntityBox.setValue(eval(data.value).join("|"),data.text);
}}else{if(/EntityBox|InputBox-Key/.test(field.type)&&operator in Jui.option.Condition._ENTITYBOX_OPERATORS){me._valueEntityBox.element.style.display="";
me._valueEntityBox.setEntityType(field.entityType);
if(setValue&&!Jui.string.isEmpty(data.value)){me._valueEntityBox.setValue(data.value,data.text);
}}else{if(/ComboBox|MultiCheckBox/.test(field.type)){me._valueComboBox.element.style.display="";
me._valueComboBox.setDropOnly(field.dropOnly);
if(me._selectItems[field.selectId]==null){var args={selectId:field.selectId};
var ret=me.fireEvent("onloadselect",args);
if(ret!=null){me._selectItems[field.selectId]=ret.data;
}}if(me._selectItems[field.selectId]!=null){me._valueComboBox.loadItems(me._selectItems[field.selectId]);
}if(setValue&&!Jui.string.isEmpty(data.value)){me._valueComboBox.setValue(data.value,data.text);
}}else{me._valueInputBox.element.style.display="";
if(setValue&&!Jui.string.isEmpty(data.value)){me._valueInputBox.setValue(data.value);
}}}}}}}}};
Jui.option.Condition.prototype._isRelationNode=function(a){return a._row.getAttribute("type")=="Relation";
};
Jui.option.Condition.prototype._isGroupNode=function(a){return a._row.getAttribute("type")=="Group";
};
Jui.option.Condition.prototype._isLeafNode=function(a){return a._row.getAttribute("type")=="Leaf";
};
Jui.option.Condition.prototype._isAddNode=function(a){return a._row.getAttribute("type")=="Add";
};
Jui.option.Condition.prototype._updateData=function(){var d=this;
var a=d._currentNode._data;
a.fieldName=d._fieldBox.getValue().substring(1);
a.operator=d._operatorBox.getValue();
var e=d._units[a.unitId].fieldMap[a.fieldName];
a.value=null;
a.text=null;
if(a.operator in Jui.option.Condition._UNARY_OPERATORS){}else{if(a.operator=="Current"){a.value=d._dateComboBox.getValue();
}else{if(a.operator in Jui.option.Condition._DATE_SPECIAL_OPERATORS){var b=parseInt(d._dateInputBox.getValue());
var c=d._dateComboBox.getValue();
a.value=(isNaN(b)?"":b)+"|"+c;
}else{if(/DateBox/.test(e.type)){a.value=d._valueDateBox.getValue();
}else{if(/MultiEntityBox/.test(e.type)&&a.operator in Jui.option.Condition._MULTIENTITYBOX_OPERATORS){var g=d._valueMultiEntityBox.getValues();
a.value=g==null||g.length==0?null:JSON.stringify(g);
a.text=d._valueMultiEntityBox.getText();
}else{if(/EntityBox|InputBox-Key/.test(e.type)&&a.operator in Jui.option.Condition._ENTITYBOX_OPERATORS){a.value=d._valueEntityBox.getValue();
a.text=d._valueEntityBox.getText();
}else{if(/ComboBox|MultiCheckBox/.test(e.type)){a.value=d._valueComboBox.getValue();
a.text=d._valueComboBox.getText();
}else{if(/InputBox-Integer|InputBox-BigInt/.test(e.type)){var f=parseInt(d._valueInputBox.getValue());
a.value=isNaN(f)?null:f;
}else{if(/InputBox-Double|InputBox-Percent/.test(e.type)){var f=parseFloat(d._valueInputBox.getValue());
a.value=isNaN(f)?null:f;
}else{a.value=d._valueInputBox.getValue();
}}}}}}}}}var i=d._currentNode._bar.children;
var h=d._getText(a.unitId,a.fieldName,a.operator,a.value,a.text);
Jui.dom.setInnerText(i[0],d._fieldBox.getText());
Jui.dom.setInnerText(i[1],d._operatorBox.getText());
Jui.dom.setInnerText(i[2],h);
};
Jui.option.Condition.prototype._getText=function(f,g,a,b,e){var c=this._units[f].fieldMap[g];
if(!Jui.string.isEmpty(e)){return e;
}else{if(Jui.string.isEmpty(b)){return"";
}else{if(a in Jui.option.Condition._UNARY_OPERATORS){return"";
}else{if(a=="Current"){return this._dateComboBox.toText(b);
}else{if(a in Jui.option.Condition._DATE_SPECIAL_OPERATORS){var d=b.split("|");
return d[0]+" "+this._dateComboBox.toText(d[1]);
}else{if(((c.type=="EntityBox"||c.type=="InputBox-Key")&&a in Jui.option.Condition._ENTITYBOX_OPERATORS)||/ComboBox/.test(c.type)){return e;
}else{if(c.type=="InputBox-Integer"||c.type=="InputBox-BigInt"){return Jui.cast.toString(Jui.cast.toNumber(b),"#,##0");
}else{if(c.type=="InputBox-Double"||c.type=="InputBox-Percent"){return Jui.cast.toString(Jui.cast.toNumber(b),"#,##0.00");
}else{return b;
}}}}}}}}};
Jui.option.Condition.prototype._getData=function(c){var g=this;
var j=[];
for(var e=0,a=c.children;
e<a.length;
++e){var b=a[e];
var d=b._data;
if(g._isLeafNode(b)){var h={fieldName:d.fieldName,operator:d.operator};
if(d.value!=null){h.value=d.value;
}if(d.text!=null){h.text=d.text;
}j.push(h);
}else{if(g._isGroupNode(b)){var f=g._getData(b.lastChild);
j.push({operator:d.operator,items:f});
}else{if(g._isRelationNode(b)){var f=g._getData(b.lastChild);
j.push({relationId:d.relationId,items:f});
}}}}return j;
};
Jui.option.Condition.prototype._validate=function(e){for(var b=0,a=e.children;
b<a.length;
++b){var c=a[b];
if(this._isLeafNode(c)&&!this._validateLeaf(c._data)){if(c!=this._currentNode){this._setCurrentNode(c);
}Jui.message.alert(Jui.i18n.getText("Jui.Condition.ValueAlert"));
return false;
}if(c.children.length==2){var d=c.lastChild;
if(d.children.length<=1){if(c!=this._currentNode){this._setCurrentNode(d.firstChild);
}Jui.message.alert(Jui.i18n.getText("Jui.Condition.ConditionAlert"));
return false;
}if(!this._validate(d)){return false;
}}}return true;
};
Jui.option.Condition.prototype._validateLeaf=function(a){if(a.operator in Jui.option.Condition._UNARY_OPERATORS){return true;
}else{if(a.operator=="Current"){return !Jui.string.isEmpty(a.value);
}else{if(a.operator in Jui.option.Condition._DATE_SPECIAL_OPERATORS){return/^\d+\|\w+$/.test(a.value);
}else{return !Jui.string.isEmpty(a.value);
}}}};
Jui.option.Condition.prototype._addUnit=function(c){this._units[c.unitId]=c;
c.fieldMap={};
c.fieldComboBoxItems=[];
c.relationMap={};
c.relationComboBoxItems=[];
c.allComboBoxItems=[];
for(var a=0;
a<c.fields.length;
++a){var d=c.fields[a];
c.fieldMap[d.name]=d;
c.fieldComboBoxItems.push({value:"F"+d.name,text:d.text});
}for(var a=0;
a<c.relations.length;
++a){var b=c.relations[a];
c.relationMap[b.id]=b;
c.relationComboBoxItems.push({value:"R"+b.id,text:b.text});
}if(c.fieldComboBoxItems.length>0){c.allComboBoxItems.push({title:Jui.i18n.getText("Jui.Condition.Field"),items:c.fieldComboBoxItems});
}if(c.relationComboBoxItems.length>0){c.allComboBoxItems.push({title:Jui.i18n.getText("Jui.Condition.Relation"),items:c.relationComboBoxItems});
}};
Jui.option.Condition.prototype._removeNode=function(d,a){if(d==this._currentNode){this._unsetCurrentNode();
}if(d.children.length==2){var b=d.lastChild.children;
for(var c=b.length-1;
c>=0;
--c){this._removeNode(b[c],false);
}}d.parentElement.removeChild(d);
if(a){this._refreshLines();
}};
Jui.option.Condition.prototype._refreshLines=function(){this._refreshLinesRecursively(this.element.firstChild,true,true);
};
Jui.option.Condition.prototype._refreshLinesRecursively=function(c,d,e){var h=(d?"Top":"")+"NodeBlock"+(e?"":"WithLine");
c.className=Jui.string.isEmpty(h)?"":"JuiCondition"+h;
for(var f=0,a=c.children;
f<a.length;
++f){var b=a[f];
var j=d&&f==0;
var e=f==a.length-1;
var g=Jui.option.Condition._LINE_TYPES[(j?0:1)|(e?0:2)];
b._row.setAttribute("lineType",g);
if(b.children.length==2){this._refreshLinesRecursively(b.lastChild,false,e);
}}};
Jui.option.Condition.prototype._switchGroup=function(b){var c=b._data;
c.operator=c.operator=="or"?"and":"or";
var a=Jui.option.Condition._GROUP_OPERATORS[c.operator];
var d=Jui.i18n.getText("Jui.Condition.Group").replace("${0}",a);
Jui.dom.setInnerText(b._bar.firstChild,d);
};
Jui.option.Condition.prototype._releaseGroup=function(b){var a=b.lastChild.children;
for(var c=a.length-2;
c>=0;
--c){Jui.dom.insertElement(b,"AfterEnd",a[c]);
}this._removeNode(b,true);
};
Jui.option.Condition.prototype._groupBy=function(c,b){var h=c.parentElement.parentElement;
var g=c.parentElement.children;
var a=[];
for(var e=0;
e<g.length;
++e){var k=g[e];
if(this._isSelected(k)){a.push(k);
this._switchSelection(k);
}}if(a.length==g.length-1&&h!=this.element&&h._type=="Group"){this._switchGroup(h);
}else{var d=g[g.length-1]._data.unitId;
var l={operator:b,items:[]};
var f=this._getBranchHtml(d,l);
var j=Jui.dom.insertHtml(a[0],"BeforeBegin",f);
this._initializeNode(j,l,d);
for(var e=a.length-1;
e>=0;
--e){Jui.dom.insertElement(j.lastChild,"AfterBegin",a[e]);
}this._refreshLines();
}};
