Jui.$define("Jui.option.Layout",Jui.basic.Control);
Jui.option.Layout.getHtml=function(b,c,a){b=b||{};
return"<div class=JuiLayout"+Jui.$p({id:c,style:b.style})+" unselectable=on onselectstart='return false'></div>";
};
Jui.option.Layout.initialize=function(c,b,a){b=b||{};
a=a||this;
var d=this.superClass.initialize(c,b,a);
d.onmoduleclose=b.onmoduleclose;
d._moduleMap={};
d.setFormat(b.format||"1,1:3",b.modules||[]);
d.setDisabled(Jui.cast.toBool(b.disabled,false));
return d;
};
Jui.option.Layout.prototype.setFormat=function(k,c){var h=this;
var g="(\\d+(\\:\\d+)*|(\\d+px|\\*)(\\:(\\d+px|\\*))*)";
var b=new RegExp("^"+g+"(,"+g+")*$");
if(!b.test(k)){return false;
}if(c==null){c=h.getModules();
}var e=[];
for(var f=0,n=k.split(",");
f<n.length;
++f){var m=n[f].split(":");
e.push("<table class=JuiLayoutTable><tr>");
for(var d=0;
d<m.length;
++d){var l=m[d];
var a=/^\d+$/.test(l)?l+"%":(l=="*"?null:l);
e.push("<td class=JuiLayoutCell"+Jui.$p({width:a})+"></td>");
}e.push("</tr></table>");
}h.element.innerHTML=e.join("");
h._format=k;
h.loadModules(c);
return true;
};
Jui.option.Layout.prototype.getFormat=function(){return this._format;
};
Jui.option.Layout.prototype.addModule=function(c){var d=this;
if(c.id in this._moduleMap){return false;
}var a=d.element.firstChild.rows[0].cells[0];
Jui.dom.insertHtml(a,"AfterBegin",d._getModuleHtml(c));
Jui.dom.insertHtml(a,"AfterBegin",d._getSplitterHtml());
var b=a.children[1];
d._initModule(b);
d._moduleMap[c.id]=b;
return true;
};
Jui.option.Layout.prototype.updateModule=function(b){if(b.id in this._moduleMap){var a=this._moduleMap[b.id];
if(b.text!=null){Jui.dom.setInnerText(a._titleCell,b.text);
}if(b.height!=null){a._body.style.height=b.height+"px";
}}};
Jui.option.Layout.prototype.deleteModule=function(b){if(b in this._moduleMap){var a=this._moduleMap[b];
Jui.dom.removeElement(a.nextSibling);
Jui.dom.removeElement(a);
delete this._moduleMap[b];
}};
Jui.option.Layout.prototype.getModules=function(){var e=[];
var g=Jui.dom.getElementsByClassName(this.element,"JuiLayoutCell");
for(var d=0;
d<g.length;
++d){for(var c=1,b=g[d].children;
c<b.length;
c+=2){var f=b[c];
var a=parseInt(f._body.style.height);
e.push({id:f.getAttribute("_id"),text:f._titleCell.innerText,region:d+1,index:(c+1)/2,height:a});
}}return e;
};
Jui.option.Layout.prototype.loadModules=function(j){var h=this;
var a={};
var d=Jui.dom.getElementsByClassName(h.element,"JuiLayoutCell");
for(var f=0;
f<j.length;
++f){var b=j[f];
var g=b.region>d.length?1:b.region;
var e=a[g]||[h._getSplitterHtml()];
e.push(h._getModuleHtml(b));
e.push(h._getSplitterHtml());
a[g]=e;
}for(var f=0;
f<d.length;
++f){d[f].innerHTML=a[f+1]?a[f+1].join(""):h._getSplitterHtml();
}h._moduleMap={};
var c=Jui.dom.getElementsByClassName(h.element,"JuiLayoutModule");
for(var f=0;
f<c.length;
++f){var b=c[f];
h._initModule(b);
h._moduleMap[b.getAttribute("_id")]=b;
}};
Jui.option.Layout.doModuleCloseIconClick=function(){var c=Jui.$owner();
var a=Jui.dom.getAncestorByClassName("JuiLayoutModule");
var b=a.getAttribute("_id");
c.deleteModule(b);
c.fireEvent("onmoduleclose",{moduleId:b});
};
Jui.option.Layout.doModuleDragStart=function(){var a=this;
if(event.offsetX>=a._head.offsetWidth||event.offsetY>=a._head.offsetHeight){Jui.event.preventDefault();
return;
}var b=Jui.$owner();
b._draggingModule=a;
b.element.ondragover=Jui.option.Layout.doModuleDragOver;
b.element.ondrop=Jui.option.Layout.doModuleDrop;
Jui.option.Layout._draggingInstance=b;
event.dataTransfer.effectAllowed="move";
if(event.dataTransfer.setDragImage){event.dataTransfer.setData("custom","jui-layout-module-drag");
}a.setAttribute("Dragging",true);
};
Jui.option.Layout.doModuleDragEnd=function(){var a=Jui.$owner();
a._stopAutoScroll();
a._draggingModule.removeAttribute("Dragging");
a._draggingModule=null;
a.element.ondragover=null;
a.element.ondrop=null;
if(a._highlightSplitter!=null){a._highlightSplitter.removeAttribute("Highlight");
a._highlightSplitter=null;
}};
Jui.option.Layout.doModuleDragOver=function(){var s=Jui.$owner();
var l=event.clientX;
var k=event.clientY;
var r=s.element.offsetParent;
while(r!=null&&r.scrollHeight<=r.clientHeight){r=r.offsetParent;
}if(r!=null){var a=r.getBoundingClientRect();
var t=s.element.getBoundingClientRect();
var n=Jui.theme["Layout.ModuleAutoScrollMargin"];
if(k<Math.max(a.top,t.top)+n){s._startAutoScroll(r,-1);
}else{if(k>Math.min(a.bottom,t.bottom)-n){s._startAutoScroll(r,1);
}else{s._stopAutoScroll();
}}}var c=Jui.dom.getElementsByClassName(s.element,"JuiLayoutCell");
for(var p=0;
p<c.length;
++p){var g=c[p];
var b=g.getBoundingClientRect();
if(Jui.math.pointInRange({x:l,y:k},b)){var h=Jui.dom.getElementsByClassName(g,"JuiLayoutSplitter");
var e=null;
var m=-1;
for(var o=0;
o<h.length;
++o){var d=h[o];
var q=d.getBoundingClientRect();
var f=Math.abs(k-(q.top+q.bottom)/2);
if(o==0||f<m){m=f;
e=d;
}}if(e.nextSibling==s._draggingModule||s._draggingModule.nextSibling==e){if(s._highlightSplitter!=null){s._highlightSplitter.removeAttribute("Highlight");
s._highlightSplitter=null;
}return;
}if(e!=s._highlightSplitter){if(s._highlightSplitter!=null){s._highlightSplitter.removeAttribute("Highlight");
}e.setAttribute("Highlight",true);
s._highlightSplitter=e;
}Jui.event.preventDefault();
return;
}}};
Jui.option.Layout.doModuleDrop=function(){var a=Jui.$owner();
Jui.dom.insertElement(a._highlightSplitter,"BeforeBegin",a._draggingModule.previousSibling);
Jui.dom.insertElement(a._highlightSplitter,"BeforeBegin",a._draggingModule);
};
Jui.option.Layout.prototype._getModuleHtml=function(a){var b=a.height||Jui.theme["Layout.ModuleDefaultHeight"];
return"<div class=JuiLayoutModule draggable=true"+Jui.$p({_id:a.id})+"><table class=JuiLayoutModuleHead><tr><td class=JuiLayoutTitleCell>"+Jui.$h(a.text)+"</td><td class=JuiLayoutButtonCell><div class=JuiLayoutCloseIcon></div></td></tr></table><div class=JuiLayoutModuleBody style='height:"+b+"px'></div></div>";
};
Jui.option.Layout.prototype._getSplitterHtml=function(){return"<div class=JuiLayoutSplitter></div>";
};
Jui.option.Layout.prototype._initModule=function(a){a._head=a.children[0];
a._body=a.children[1];
a._titleCell=a._head.rows[0].cells[0];
a.ondragstart=Jui.option.Layout.doModuleDragStart;
a.ondragend=Jui.option.Layout.doModuleDragEnd;
var b=a._head.rows[0].cells[1].firstChild;
b.onclick=Jui.option.Layout.doModuleCloseIconClick;
};
Jui.option.Layout.prototype._startAutoScroll=function(c,a){var b=this;
if(b._autoScrollTimer!=null){if(b._autoScrollFactor==a){return;
}b._stopAutoScroll();
}b._autoScrollFactor=a;
b._autoScrollTimer=setInterval(function(){var d=c.scrollTop;
c.scrollTop=d+4*a;
if(c.scrollTop==d){b._stopAutoScroll();
}},15);
};
Jui.option.Layout.prototype._stopAutoScroll=function(){var a=this;
if(a._autoScrollTimer!=null){clearInterval(a._autoScrollTimer);
a._autoScrollTimer=null;
a._autoScrollFactor=null;
}};
