Jui.$define("Jui.option.Marquee",Jui.basic.Control);
Jui.option.Marquee.getHtml=function(b,d,a){b=b||{};
var c="JuiMarquee JuiMarquee"+(b.direction=="left"?"Horz":"Vert");
return"<div"+Jui.$p({"class":c,id:d,style:b.style})+"></div>";
};
Jui.option.Marquee.initialize=function(c,b,a){b=b||{};
a=a||this;
var d=this.superClass.initialize(c,b,a);
d._direction=b.direction||"top";
d._timer=null;
d._waitMillis=2000;
d._scrollMillis=800;
d._tickInterval=20;
d._waitTickCount=Math.round(d._waitMillis/d._tickInterval);
d._scrollTickCount=Math.round(d._scrollMillis/d._tickInterval);
d.onitemclick=b.onitemclick;
if(d._direction!="left"){c.style.textAlign=b.textAlign||"center";
}return d;
};
Jui.option.Marquee.prototype.load=function(b){var d=this;
var a=[];
if(d._direction=="left"){if(b.length!=0){a.push("<marquee>");
for(var c=0;
c<b.length;
++c){a.push(d._getItemHtml(b[c]));
}a.push("</marquee>");
}d._setHtml(a.join(""),b);
}else{if(b.length!=0){a.push("<div class=JuiMarqueeContent>");
a.push(d._getItemHtml(b[b.length-1]));
for(var c=0;
c<b.length;
++c){a.push(d._getItemHtml(b[c]));
}a.push(d._getItemHtml(b[0]));
a.push("</div>");
}d._clearTimer();
d._height=d.element.offsetHeight;
d._setHtml(a.join(""),b);
d._startTimer();
}};
Jui.option.Marquee.doItemClick=function(){var b=Jui.$owner();
var a=Jui.dom.getAncestorByTagName("div");
b.fireEvent("onitemclick",{item:Jui.util.clone(b._items[a._index])});
};
Jui.option.Marquee.doMouseOver=function(){var a=Jui.$owner();
if(a._direction=="left"){a.element.firstChild.stop();
}else{a._isMouseOver=true;
}};
Jui.option.Marquee.doMouseOut=function(){var a=Jui.$owner();
if(a._direction=="left"){a.element.firstChild.start();
}else{a._isMouseOver=false;
}};
Jui.option.Marquee.prototype._startTimer=function(){var a=this;
if(a._items.length==0){return;
}a._clearTimer();
a._setTopScrollPosition(0,true);
a._timer=setInterval(function(){if(!a._isMouseOver){++a._tickIndex;
if(a._tickIndex>=a._waitTickCount+a._scrollTickCount){a._setTopScrollPosition((a._itemIndex+1)%a._items.length,true);
}else{if(a._tickIndex>a._waitTickCount){a._setTopScrollPosition(a._itemIndex+(a._tickIndex-a._waitTickCount)/a._scrollTickCount);
}}}},a._tickInterval);
};
Jui.option.Marquee.prototype._clearTimer=function(){var a=this;
if(a._timer!=null){clearInterval(a._timer);
a._timer=null;
}};
Jui.option.Marquee.prototype._setTopScrollPosition=function(c,b){var a=this;
a.element.firstChild.style.top=-(c+1)*a._height+"px";
if(b){a._itemIndex=c;
a._tickIndex=0;
}};
Jui.option.Marquee.prototype._getItemHtml=function(b){var a="<div><span class=JuiMarqueeText";
if(b.ball!=null){a+=" ball="+b.ball.toLowerCase();
}a+=">"+(b.html||Jui.$h(b.name)).replace(/<\/?p>/ig,"")+"</span></div>";
return a;
};
Jui.option.Marquee.prototype._setHtml=function(c,a){var f=this;
f.element.innerHTML=c;
var e=f.element.firstChild;
if(e!=null){e.style.lineHeight=f.element.offsetHeight+"px";
for(var b=0;
b<e.children.length;
++b){var d=e.children[b];
d._index=f._direction=="left"?b:(b+a.length-1)%a.length;
d.firstChild.onclick=Jui.option.Marquee.doItemClick;
d.firstChild.onmouseover=Jui.option.Marquee.doMouseOver;
d.firstChild.onmouseout=Jui.option.Marquee.doMouseOut;
}}f._items=Jui.util.clone(a);
};
