Jui.$define("Jui.option.MessageReminder",Jui.basic.Control);
Jui.option.MessageReminder.getHtml=function(b,d,a){b=b||{};
var c=Jui.i18n.getText("Jui.MessageReminder.DefaultTitle");
return"<div class=JuiMessageReminder"+Jui.$p({id:d,style:b.style})+" unselectable=on onselectstart='return false'><div class='JuiTitle JuiMessageReminderTitle'>"+Jui.$h(c)+"</div><div class=JuiMessageReminderClose></div><div class=JuiMessageReminderIcon></div><div class=JuiMessageReminderContent></div></div>";
};
Jui.option.MessageReminder.initialize=function(c,b,a){b=b||{};
a=a||this;
var d=this.superClass.initialize(c,b,a);
d._title=c.children[0];
d._close=c.children[1];
d._content=c.children[3];
d._close.onclick=a.doCloseClick;
d.onitemclick=b.onitemclick;
c.onmouseover=a.doMouseOver;
c.onmouseout=a.doMouseOut;
return d;
};
Jui.option.MessageReminder.open=function(c){var d=Jui.window.getTop();
var b=d.Jui.option.MessageReminder;
var a=b._instance;
if(b._instance==null){b._instance=b.create({target:d.document.body});
}b._instance.open(c);
return b._instance;
};
Jui.option.MessageReminder._zIndex=300000000;
Jui.option.MessageReminder.prototype.open=function(a){this._clearCountdownTimer();
this._clearFadeTimer();
a=a||{};
this._visible=true;
this.element.style.zIndex=Jui.option.MessageReminder._zIndex;
this.element.style.display="block";
this._loadItems(a.items);
this._fadeIn(0);
};
Jui.option.MessageReminder.prototype.close=function(a){this._clearCountdownTimer();
this._clearFadeTimer();
this.element.style.display="none";
this._visible=false;
};
Jui.option.MessageReminder.doCloseClick=function(){var a=Jui.$owner();
a.close();
};
Jui.option.MessageReminder.doItemClick=function(){var c=Jui.$owner();
var b=Jui.dom.getAncestorByClassName("JuiMessageReminderItem");
b.className="JuiMessageReminderItem JuiMessageReminderItemRead";
var a={item:Jui.util.clone(c._items[b._index])};
c.fireEvent("onitemclick",a);
};
Jui.option.MessageReminder.doMouseOver=function(){var a=Jui.$owner();
a._clearFadeTimer();
};
Jui.option.MessageReminder.doMouseOut=function(){var a=Jui.$owner(event.fromElement);
if(a._isAllRead()){a._fadeOut(1);
}};
Jui.option.MessageReminder._instance=null;
Jui.option.MessageReminder.prototype._loadItems=function(c){var h=this;
h._items=Jui.util.clone(c);
var e=false;
var a=[];
for(var d=0;
d<c.length;
++d){var g=c[d];
a.push("<div class=JuiMessageReminderItem>");
if(g.countdown!=null){a.push("<label class=JuiMessageReminderCountdown></label>");
e=true;
}a.push("<label class='JuiMessageReminderItemText JuiLink'>");
a.push(g.text);
a.push("</label>");
a.push("</div>");
}h._content.innerHTML=a.join("");
for(var d=0,b=h._content.children;
d<b.length;
++d){var f=b[d];
f._index=d;
f.onclick=Jui.option.MessageReminder.doItemClick;
}if(e){h._loadMillis=new Date().getTime();
h._updateCountdown();
h._countdownTimer=setInterval(function(){h._updateCountdown();
},1000);
}};
Jui.option.MessageReminder.prototype._isAllRead=function(){for(var b=0,a=this._content.children;
b<a.length;
++b){if(!/Read/.test(a[b].className)){return false;
}}return true;
};
Jui.option.MessageReminder.prototype._updateCountdown=function(){var f=this;
var g=Math.round((new Date().getTime()-f._loadMillis)/1000);
var c=false;
for(var b=0,a=f._content.children;
b<a.length;
++b){var e=a[b];
var d=f._items[b];
if(d.countdown!=null){var h=Math.max(0,d.countdown-g);
if(h==0){e.className="JuiMessageReminderItem JuiMessageReminderItemRead";
delete d.countdown;
}else{c=true;
}Jui.dom.setInnerText(e.firstChild,"["+f._formatSeconds(h)+"]");
}}if(!c){f._clearCountdownTimer();
}};
Jui.option.MessageReminder.prototype._formatSeconds=function(f){var c=f%60;
var a=Math.floor(f/60)%60;
var b=Math.floor(f/3600)%24;
var e=Math.floor(f/86400);
return(e>0?e+",":"")+(b>9?b:"0"+b)+":"+(a>9?a:"0"+a)+":"+(c>9?c:"0"+c);
};
Jui.option.MessageReminder.prototype._fadeIn=function(a){var d=this;
var c=0.05;
var b=0.2;
a=Math.min(1,a+c+b*(1-a));
d._setOpacity(a);
if(a<1){d._fadeInTimer=setTimeout(function(){d._fadeIn(a);
},100);
}};
Jui.option.MessageReminder.prototype._fadeOut=function(a){var d=this;
var c=0.025;
var b=0.04;
a=Math.max(0,a-c-b*a);
d._setOpacity(a);
if(a>0){d._fadeOutTimer=setTimeout(function(){d._fadeOut(a);
},100);
}else{d.close();
}};
Jui.option.MessageReminder.prototype._setOpacity=function(a){this.element.style.filter=a==1||a==0?"":"alpha(opacity="+Math.round(a*100)+")";
this.element.style.opacity=a;
};
Jui.option.MessageReminder.prototype._clearCountdownTimer=function(){if(this._countdownTimer!=null){clearInterval(this._countdownTimer);
this._countdownTimer=null;
}};
Jui.option.MessageReminder.prototype._clearFadeTimer=function(){if(this._fadeInTimer!=null){clearTimeout(this._fadeInTimer);
}if(this._fadeOutTimer!=null){clearTimeout(this._fadeOutTimer);
}this._fadeInTimer=null;
this._fadeOutTimer=null;
this._setOpacity(1);
};
