Jui.$define("Jui.option.MiniCalendar",Jui.basic.Control);
Jui.option.MiniCalendar.getHtml=function(b,c,a){b=b||{};
return"<div class=JuiMiniCalendar"+Jui.$p({id:c,style:b.style,title:b.hint})+" unselectable=on onselectstart='return false'><table class=JuiMiniCalendarTable unselectable=on onselectstart='return false'><tr><td class=JuiMiniCalendarTopBarCell><table class=JuiMiniCalendarTopBar><tr><td class='JuiMiniCalendarNavigator JuiMiniCalendarPreviousYear' onclick=Jui.option.MiniCalendar.doPreviousYearClick()></td><td class='JuiMiniCalendarNavigator JuiMiniCalendarPreviousMonth' onclick=Jui.option.MiniCalendar.doPreviousMonthClick()></td><td class=JuiMiniCalendarCurrentYearMonth></td><td class='JuiMiniCalendarNavigator JuiMiniCalendarNextMonth' onclick=Jui.option.MiniCalendar.doNextMonthClick()></td><td class='JuiMiniCalendarNavigator JuiMiniCalendarNextYear' onclick=Jui.option.MiniCalendar.doNextYearClick()></td></tr></table></td></tr><tr><td align=center><table class=JuiMiniCalendarDateTable><tr><td>"+Jui.util.getWeekDayName(0,true)+"</td><td>"+Jui.util.getWeekDayName(1,true)+"</td><td>"+Jui.util.getWeekDayName(2,true)+"</td><td>"+Jui.util.getWeekDayName(3,true)+"</td><td>"+Jui.util.getWeekDayName(4,true)+"</td><td>"+Jui.util.getWeekDayName(5,true)+"</td><td>"+Jui.util.getWeekDayName(6,true)+"</td></tr><tr class=JuiMiniCalendarSplitter><td colspan=7><div></div></td></tr>"+Jui.string.repeat("<tr class=JuiMiniCalendarDateRow onclick=Jui.option.MiniCalendar.doDateClick()>"+Jui.string.repeat("<td></td>",7)+"</tr>",6)+"</table></td></tr></table></div>";
};
Jui.option.MiniCalendar.initialize=function(d,b,a){b=b||{};
a=a||this;
var e=this.superClass.initialize(d,b,a);
e._today=Jui.cast.toString(Jui.cast.toDate(b.today||new Date()),"yyyy-MM-dd");
var c=Jui.cast.toDate(b.selectedDate||e._today);
e._selectedDate=Jui.cast.toString(c,"yyyy-MM-dd");
e._monthCell=d.firstChild.rows[0].cells[0].firstChild.rows[0].cells[2];
e._dateTable=d.firstChild.rows[1].cells[0].firstChild;
e.ondateclick=b.ondateclick;
e.onmonthchange=b.onmonthchange;
e.setYearMonth(c.getFullYear(),c.getMonth()+1);
return e;
};
Jui.option.MiniCalendar.prototype.getYear=function(){return this._year;
};
Jui.option.MiniCalendar.prototype.getMonth=function(){return this._month;
};
Jui.option.MiniCalendar.prototype.getSelectedDate=function(){return this._selectedDate;
};
Jui.option.MiniCalendar.prototype.getYearMonth=function(){return this._monthCell.innerText;
};
Jui.option.MiniCalendar.prototype.setYearMonth=function(h,f,l){var g=this;
var a=new Date(h,f-1,1);
var c=new Date(h,f,1);
var b=new Date(h,f-1,1-a.getDay());
g._year=h;
g._month=f;
Jui.dom.setInnerText(g._monthCell,h+"-"+(f<10?"0"+f:f));
for(var e=0;
e<6;
++e){for(var d=0;
d<7;
++d){var k=g._dateTable.rows[e+2].cells[d];
k._date=Jui.cast.toString(b,"yyyy-MM-dd");
k.innerHTML=b.getDate();
Jui.dom.tagAttribute(k,"disabled",b<a||b>=c);
b=new Date(b.getFullYear(),b.getMonth(),b.getDate()+1);
}}g._refreshCellClass();
if(l){g.fireEvent("onmonthchange",{yearMonth:g._monthCell.innerText});
}};
Jui.option.MiniCalendar.prototype.highlight=function(d){var e={};
for(var c=0;
c<d.length;
++c){e[d[c]]=1;
}for(var c=0;
c<6;
++c){for(var b=0;
b<7;
++b){var a=this._dateTable.rows[c+2].cells[b];
Jui.dom.tagAttribute(a,"highlight",a._date in e);
}}};
Jui.option.MiniCalendar.doPreviousYearClick=function(){var a=Jui.$owner();
a.setYearMonth(a._year-1,a._month,true);
};
Jui.option.MiniCalendar.doPreviousMonthClick=function(){var b=Jui.$owner();
var a=b._month==1?b._year-1:b._year;
var c=b._month==1?12:b._month-1;
b.setYearMonth(a,c,true);
};
Jui.option.MiniCalendar.doNextMonthClick=function(){var b=Jui.$owner();
var a=b._month==12?b._year+1:b._year;
var c=(b._month%12)+1;
b.setYearMonth(a,c,true);
};
Jui.option.MiniCalendar.doNextYearClick=function(){var a=Jui.$owner();
a.setYearMonth(a._year+1,a._month,true);
};
Jui.option.MiniCalendar.doDateClick=function(){var b=Jui.$owner();
var a=event.srcElement;
b._selectedDate=a._date;
if(a.hasAttribute("disabled")){if(a.parentElement.rowIndex==2){Jui.option.MiniCalendar.doPreviousMonthClick();
}else{Jui.option.MiniCalendar.doNextMonthClick();
}}else{b._refreshCellClass();
}b.fireEvent("ondateclick",{date:b._selectedDate});
};
Jui.option.MiniCalendar.prototype._refreshCellClass=function(){for(var c=0;
c<6;
++c){for(var b=0;
b<7;
++b){var a=this._dateTable.rows[c+2].cells[b];
var d=[];
if(a._date==this._today){d.push("JuiMiniCalendarTodayCell");
}if(a._date==this._selectedDate){d.push("JuiMiniCalendarSelectedDateCell");
}a.className=d.join(" ");
}}};
