Jui.$define("Jui.option.MultiRowTabStrip",Jui.basic.Control);
Jui.option.MultiRowTabStrip.getHtml=function(b,d,a){b=b||{};
var c="JuiMultiRowTabStrip";
return"<div"+Jui.$p({"class":c,id:d,style:b.style})+"><div class=JuiMultiRowTabStripTabZoneOuter><div class=JuiMultiRowTabStripTabZone></div></div><div class=JuiMultiRowTabStripBodyZone></div></div>";
};
Jui.option.MultiRowTabStrip.initialize=function(c,b,a){b=b||{};
a=a||this;
var d=this.superClass.initialize(c,b,a);
d._fireSwitchEventOnLoad=Jui.cast.toBool(b.fireSwitchEventOnLoad,false);
d._maxTabWidth=b.maxTabWidth||200;
d.onswitch=b.onswitch;
d._tabZone=c.firstChild.firstChild;
d._bodyZone=c.lastChild;
d._current=null;
d._tabs=d._tabZone.children;
d._serial=0;
Jui.event.attach(window,"resize",function(){d._updateTabSize();
});
return d;
};
Jui.option.MultiRowTabStrip.prototype.size=function(){return this._tabs.length;
};
Jui.option.MultiRowTabStrip.prototype.setTabTitle=function(e,d){var c=this;
for(var a=0;
a<c._tabs.length;
++a){var b=c._tabs[a];
if(b._json.id==e){b._text.style.width="auto";
b._tab.style.width="auto";
b._text.innerHTML=Jui.$h(d);
b._textChanged=true;
c._updateTabSize();
break;
}}};
Jui.option.MultiRowTabStrip.prototype.getItem=function(b){var a=this._getTab(b);
return a&&Jui.util.clone(a._json);
};
Jui.option.MultiRowTabStrip.prototype.getItems=function(){var a=[];
for(var b=0;
b<this._tabs.length;
++b){a.push(Jui.util.clone(this._tabs[b]._json));
}return a;
};
Jui.option.MultiRowTabStrip.prototype.getCurrentId=function(){return this._current&&this._current._json.id;
};
Jui.option.MultiRowTabStrip.prototype.setCurrentId=function(a){this._activate(this._getTab(a));
};
Jui.option.MultiRowTabStrip.prototype.exists=function(a){return this._getTab(a)!=null;
};
Jui.option.MultiRowTabStrip.prototype.add=function(c,f,e){var g=this;
if(!Jui.string.isEmpty(c.id)){for(var b=0,a=g._tabs;
b<a.length;
++b){var d=a[b];
if(d._json.id==c.id){g._activate(d);
return c.id;
}}}var d=Jui.dom.insertHtml(g._tabZone,"BeforeEnd",g._getTabHtml(c));
d._body=Jui.dom.insertHtml(g._bodyZone,"BeforeEnd",g._getBodyHtml());
g._initializeTab(d,c);
g._updateTabSize();
if(g._tabs.length==1||f!=false){g._activate(d);
}return e?d._json.id:d._body;
};
Jui.option.MultiRowTabStrip.prototype.remove=function(b){var a=this._getTab(b);
if(a!=null){this._remove(a);
}};
Jui.option.MultiRowTabStrip.prototype.removeByIndex=function(a){this._remove(this._tabs[a]);
};
Jui.option.MultiRowTabStrip.prototype.getBody=function(b){var a=this._getTab(b);
return a&&a._body;
};
Jui.option.MultiRowTabStrip.prototype.load=function(d){d=d||[];
var f=this;
var b=[];
var a=[];
for(var c=0;
c<d.length;
++c){b.push(f._getTabHtml(d[c]));
a.push(f._getBodyHtml());
}f._current=null;
f._tabZone.innerHTML=b.join("");
f._bodyZone.innerHTML=a.join("");
for(var c=0;
c<f._tabs.length;
++c){var e=f._tabs[c];
e._body=f._bodyZone.children[c];
f._initializeTab(e,d[c]);
}if(f._tabs.length>0){f._activate(f._tabs[0],f._fireSwitchEventOnLoad);
}f._updateTabSize();
};
Jui.option.MultiRowTabStrip.doTabClick=function(){Jui.$owner()._activate(Jui.dom.getAncestorByClassName("JuiMultiRowTabStripTab"),true);
};
Jui.option.MultiRowTabStrip.prototype._getTab=function(c){for(var b=0,a=this._tabs;
b<a.length;
++b){if(a[b]._json.id==c){return a[b];
}}};
Jui.option.MultiRowTabStrip.prototype._getTabHtml=function(a){return"<div class=JuiMultiRowTabStripTab unselectable=on onselectstart='return false'><div class='JuiTitle JuiMultiRowTabStripTabText'"+(a.icon?" WithIcon style='background-image:url("+a.icon+")'":"")+">"+Jui.$h(a.text)+"</div></div>";
};
Jui.option.MultiRowTabStrip.prototype._getBodyHtml=function(){return"<div class=JuiMultiRowTabStripBody></div>";
};
Jui.option.MultiRowTabStrip.prototype._initializeTab=function(c,b){var d=this;
if(Jui.string.isEmpty(b.id)){b.id="JUI_TABSTRIP_TAB"+ ++d._serial;
}c._json=b;
c._text=c.firstChild;
c._textChanged=true;
c.onclick=Jui.option.MultiRowTabStrip.doTabClick;
if(Jui.dom.element(b.body)!=null){var a=Jui.dom.element(b.body);
c._body.appendChild(a);
a.style.display="block";
}};
Jui.option.MultiRowTabStrip.prototype._remove=function(c){var a=Jui.dom.getFrameWindow(c._body);
if(Jui.event.fireCustomEvent(a,"beforeclose")==false){return;
}var b=null;
if(c==this._current){b=c.nextSibling||c.previousSibling;
this._current=null;
}this._bodyZone.removeChild(c._body);
this._tabZone.removeChild(c);
if(b!=null){this._activate(b);
}this._updateTabSize();
};
Jui.option.MultiRowTabStrip.prototype._activate=function(b,a){if(b==this._current){return;
}if(this._current!=null){this._current.style.zIndex=0;
this._current.className="JuiMultiRowTabStripTab";
this._current._body.style.display="none";
}b.style.zIndex=1;
b.className="JuiMultiRowTabStripTab JuiMultiRowTabStripTabCurrent";
b._body.style.display="block";
this._current=b;
if(a){this.fireEvent("onswitch",{item:b._json});
}};
Jui.option.MultiRowTabStrip.prototype._updateTabSize=function(){var g=this;
var b=g._bodyZone.offsetWidth;
if(b<=10||g._tabs.length==0){return;
}var a=g._maxTabWidth<=0?b>>1:Math.min(b>>1,g._maxTabWidth);
for(var e=0;
e<g._tabs.length;
++e){var f=g._tabs[e];
if(f._textChanged){f._textWidth=f._text.offsetWidth;
f._tabWidth=f.offsetWidth;
f._textChanged=false;
}}var h=g._getMostSuitableArrangeInfo(b,a);
if(h.rows.length==1){g._refreshSingleRowTabWidth(h.rows[0].tabs,a);
}else{for(var e=0;
e<h.rows.length;
++e){g._refreshMultiRowTabWidth(h.rows[e].tabs,b,a);
}}for(var e=0;
e<h.rows.length;
++e){for(var c=0,d=h.rows[e].tabs;
c<d.length;
++c){Jui.dom.tagAttribute(d[c],"LastRow",e==h.rows.length-1);
}}g._bodyZone.style.top=g._tabZone.offsetHeight+"px";
};
Jui.option.MultiRowTabStrip.prototype._refreshSingleRowTabWidth=function(c,a){this._refreshOverlap(c);
for(var b=0;
b<c.length;
++b){var d=c[b];
if(d._tabWidth<=a){d._text.style.width="auto";
d.style.width="auto";
}else{d._text.style.width=Math.max(0,a-(d._tabWidth-d._textWidth))+"px";
d.style.width=a+"px";
}}};
Jui.option.MultiRowTabStrip.prototype._refreshMultiRowTabWidth=function(l,d,m){this._refreshOverlap(l);
l.sort(function(n,i){return n._tabWidth-i._tabWidth;
});
d+=(l.length-1)*Jui.theme["MultiRowTabStrip.TabOverLap"];
var b=0;
var h=-1;
for(var f=0;
f<l.length;
++f){var c=l[f];
if(c._tabWidth<=m||b+c._tabWidth*(l.length-f)<=d){b+=c._tabWidth;
}else{h=f;
break;
}}var a=d-b;
if(h==-1){var e=Math.floor(a/l.length);
var j=l.length-(a-l.length*e);
for(var f=0;
f<l.length;
++f){var c=l[f];
c._text.style.width="auto";
c.style.width=(c._tabWidth+e+(f>=j?1:0))+"px";
}}else{var g=l.length-h;
var k=Math.floor(a/g);
var j=l.length-(a-g*k);
for(var f=0;
f<l.length;
++f){var c=l[f];
c._text.style.width=f<h?"auto":"100%";
c.style.width=(f<h?c._tabWidth:k+(f>=j?1:0))+"px";
}}};
Jui.option.MultiRowTabStrip.prototype._refreshOverlap=function(c){var a=Jui.theme["MultiRowTabStrip.TabOverLap"];
for(var b=0;
b<c.length;
++b){c[b].style.left=-(b*a)+"px";
}};
Jui.option.MultiRowTabStrip.prototype._getMostSuitableArrangeInfo=function(c,f){var d=this;
var b=d._getArrangeInfo(c,f);
var e=b.rows.length;
var a=Math.min(b.minWidth,c);
var g=b.maxWidth;
while(g>a+1){var i=Math.ceil((a+g)/2);
var h=d._getArrangeInfo(i,f);
if(h.rows.length==e){g=i;
b=h;
}else{a=i;
}}return b;
};
Jui.option.MultiRowTabStrip.prototype._getArrangeInfo=function(c,g){var e=this;
var m=[];
var l={tabs:[],width:0};
var h=Jui.theme["MultiRowTabStrip.TabOverLap"];
for(var d=0;
d<e._tabs.length;
++d){var b=e._tabs[d];
var f=Math.min(b._tabWidth,g);
if(l.tabs.length>0&&l.width+f-h>c){m.push(l);
l={tabs:[],width:0};
}l.width+=f-(l.tabs.length==0?0:h);
l.tabs.push(b);
}m.push(l);
var a=2147483647;
var j=0;
for(var d=0;
d<m.length;
++d){var l=m[d];
var k=c-l.width;
a=Math.min(a,l.width);
j=Math.max(j,l.width);
}return{rows:m,minWidth:a,maxWidth:j};
};
