Jui.$define("Jui.option.OutlookBar",Jui.basic.Control);
Jui.option.OutlookBar.getHtml=function(c,e,b){c=c||{};
var d=c.showBorder==false?"JuiOutlookBar":"JuiOutlookBar JuiOutlookBarWithBorder";
var a="<div"+Jui.$p({"class":d,id:e,style:c.style})+"><div class=JuiOutlookBarInner></div></div>";
return a;
};
Jui.option.OutlookBar.initialize=function(c,b,a){b=b||{};
a=a||this;
var d=this.superClass.initialize(c,b,a);
d.onswitch=b.onswitch;
d._panel=c.firstChild;
d._current=null;
d._zIndex=0;
Jui.event.attach(window,"resize",function(){d._adjust();
});
return d;
};
Jui.option.OutlookBar.prototype.add=function(f,c){var e=this;
if(f.id!=null){for(var b=0,a=e._panel.children;
b<a.length;
++b){if(a[b]._json.id==f.id){throw new Error("OutlookBar item with id '"+f.id+"' already exists.");
}}}var d=Jui.dom.insertHtml(e._panel,"BeforeEnd",e._getItemHtml(f));
e._initElem(d,f);
c?e._activate(d):e._adjust();
return d._body;
};
Jui.option.OutlookBar.prototype.remove=function(f){var d=this;
for(var b=0,a=d._panel.children;
b<a.length;
++b){var c=a[b];
if(c._json.id==f){if(c==d._current){var e=c.previousSibling||c.nextSibling;
d._panel.removeChild(c);
d._current=null;
d._activate(e);
}else{d._panel.removeChild(c);
}d._adjust();
return;
}}};
Jui.option.OutlookBar.prototype.update=function(b){var c=this._getElem(b.id);
if(c!=null){var a=c._head.rows[0].cells[0];
if("text" in b){Jui.dom.setInnerText(a,b.text);
}if("icon" in b){a.style.backgroundImage="url("+b.icon+")";
}Jui.object.merge(c._json,b,true);
}};
Jui.option.OutlookBar.prototype.size=function(){return this._panel.children.length;
};
Jui.option.OutlookBar.prototype.getIndex=function(){return this._getIndex(this._current);
};
Jui.option.OutlookBar.prototype.getBody=function(b){var a=this._getElem(b);
return a==null?null:a._body;
};
Jui.option.OutlookBar.prototype.getBodyByIndex=function(a){return this._panel.children[a]._body;
};
Jui.option.OutlookBar.prototype.getItems=function(){var c=[];
for(var b=0,a=this._panel.children;
b<a.length;
++b){c.push(this._getItemJson(a[b]));
}return c;
};
Jui.option.OutlookBar.prototype.getItem=function(b){var a=this._getElem(b);
return a==null?null:this._getItemJson(a);
};
Jui.option.OutlookBar.prototype.getItemByIndex=function(a){var b=this._panel.children(a);
return b==null?null:this._getItemJson(b);
};
Jui.option.OutlookBar.prototype.getTextCell=function(b){var a=this._getElem(b);
return a==null?null:a._head.rows[0].cells[0];
};
Jui.option.OutlookBar.prototype.getCustomCell=function(b){var a=this._getElem(b);
return a==null?null:a._head.rows[0].cells[1];
};
Jui.option.OutlookBar.prototype.getCurrentId=function(){return this._current==null?null:this._current._json.id;
};
Jui.option.OutlookBar.prototype.setCurrentId=function(b){var a=this._getElem(b);
if(a!=null){this._activate(a);
}};
Jui.option.OutlookBar.prototype.load=function(d){var e=this;
d=d||[];
var a=[];
for(var c=0;
c<d.length;
++c){a.push(this._getItemHtml(d[c]));
}e._panel.innerHTML=a.join("");
var b=e._panel.children;
for(var c=0;
c<b.length;
++c){e._initElem(b[c],d[c]);
}if(b.length>0){e._activate(b[0]);
}};
Jui.option.OutlookBar.doItemHeadClick=function(){var b=Jui.dom.getAncestorByClassName("JuiOutlookBarItem");
var a=Jui.$owner(b);
if(b!=a._current){if(a._current!=null){a._current._head.removeAttribute("Current");
}b._head.setAttribute("Current",true);
a._adjust();
a._slide(b,a._current,0);
a._current=b;
a.fireEvent("onswitch",{item:a._getItemJson(b),index:a._getIndex(b)});
}};
Jui.option.OutlookBar.prototype._getItemHtml=function(a){var b=++this._zIndex;
return"<div class=JuiOutlookBarItem style='z-index:"+b+"'><table class='JuiTitle JuiOutlookBarItemHead' unselectable=on onselectstart='return false' onclick='Jui.option.OutlookBar.doItemHeadClick()'><tr><td class=JuiOutlookBarItemHeadText style='background-image:url("+a.icon+")'>"+Jui.$h(a.text)+"</td><td class=JuiOutlookBarItemHeadCustom></td></tr></table><div class=JuiOutlookBarItemBody></div></div>";
};
Jui.option.OutlookBar.prototype._initElem=function(c,a){c._head=c.children[0];
c._body=c.children[1];
c._json=Jui.util.clone(a);
var b=Jui.dom.element(a.body);
if(b!=null){c._body.appendChild(b);
b.style.display="block";
}};
Jui.option.OutlookBar.prototype._getElem=function(c){for(var b=0,a=this._panel.children;
b<a.length;
++b){if(a[b]._json.id==c){return a[b];
}}};
Jui.option.OutlookBar.prototype._getIndex=function(c){for(var b=0,a=this._panel.children;
b<a.length;
++b){if(a[b]==c){return b;
}}return -1;
};
Jui.option.OutlookBar.prototype._getItemJson=function(a){return Jui.util.clone(a._json);
};
Jui.option.OutlookBar.prototype._activate=function(b){var a=this;
if(b==a._current){return;
}if(a._current!=null){a._current._head.removeAttribute("Current");
}a._current=b;
a._adjust();
if(b!=null){b._head.setAttribute("Current",true);
a.fireEvent("onswitch",{item:a._getItemJson(b),index:a._getIndex(b)});
}};
Jui.option.OutlookBar.prototype._adjust=function(){if(this._timer!=null){clearTimeout(this._timer);
}var e=Jui.theme["OutlookBar.HeadHeight"];
var d=Jui.theme["OutlookBar.PaddingTop"];
for(var b=0,a=this._panel.children,f=false;
b<a.length;
++b){var c=a[b];
c.style.top=f?"auto":b*e+d+"px";
f=f||c==this._current;
c.style.bottom=f?(a.length-b-1)*e+"px":"auto";
c._body.style.display=c==this._current?"block":"none";
c._body.style.overflow=c==this._current?"auto":"hidden";
}};
Jui.option.OutlookBar.prototype._slide=function(k,o,d){var l=this;
var a=l._panel.children;
if(d==0){for(var f=0;
f<a.length;
++f){a[f]._index=f;
}}var g=k._index<o._index;
var e=g?k:o;
var h=g?o:k;
if(d==0){o._body.style.overflow="hidden";
k._body.style.display="block";
for(var f=e._index+1;
f<h._index;
++f){a[f].style.bottom="auto";
}}var m=Jui.theme["OutlookBar.HeadHeight"];
var j=Jui.theme["OutlookBar.PaddingTop"];
var b=a.length;
var c=l._panel.clientHeight-b*m-j;
d=Math.min(d+50,c);
e.style.bottom=(b-e._index-1)*m+(g?c-d:d)+"px";
for(var f=e._index+1;
f<=h._index;
++f){a[f].style.top=(f*m+j)+(g?d:c-d)+"px";
}if(d==c){l._timer=null;
o._body.style.display="none";
k._body.style.overflow="auto";
}else{l._timer=setTimeout(function(){l._slide(k,o,d);
},10);
}};
