Jui.$define("Jui.option.Resizer",Jui.basic.Control);
Jui.option.Resizer.create=function(a){a=a||{};
var d=new Jui.option.Resizer();
d._offset=a.offset;
d._reside=a.reside;
d._shrinks=a.shrinks||[0,0];
d._isNextFixed=a.fixed=="right"||a.fixed=="bottom";
d._dragger=Jui.dom.insertHtml(document.body,"BeforeEnd","<div class=JuiResizerDragger></div>");
d._dragger._owner=d;
d._mask=Jui.dom.insertHtml(document.body,"BeforeEnd","<div class=JuiResizerMask></div>");
d._mask._owner=d;
var c="<div class=JuiResizer><div class=JuiResizerInner draggable=true></div><div class=JuiResizerArrow></div></div>";
var b=Jui.dom.insertHtml(document.body,"BeforeEnd",c);
d._inner=b.firstChild;
d._arrow=b.lastChild;
d._inner.onmousedown=Jui.option.Resizer.doMouseDown;
d._inner.ondragstart=Jui.option.Resizer.doDragStart;
d._inner.ondragend=Jui.option.Resizer.doDragEnd;
d._inner.ondragover=Jui.option.Resizer.doDragOver;
d._inner.ondrop=Jui.option.Resizer.doDrop;
d._mask.ondragover=Jui.option.Resizer.doDragOver;
d._mask.ondrop=Jui.option.Resizer.doDrop;
Jui.$bind(d,b);
d.setElements(a.elements);
window.addEventListener("resize",function(){d._refresh();
});
if(!Jui.cast.toBool(a.transparent,true)){b.style.backgroundColor="#ddf";
}if(a.minimize!=null){d._arrow.setAttribute("direction",a.minimize);
}return d;
};
Jui.option.Resizer.prototype.setVisible=function(b){var a=this;
Jui.basic.Control.prototype.setVisible.call(a,b);
if(b&&a._elems!=null){a._refresh();
}};
Jui.option.Resizer.prototype.setElements=function(b){var a=this;
a._elems=b==null?null:[Jui.dom.element(b[0]),Jui.dom.element(b[1])];
a.setVisible(b!=null);
};
Jui.option.Resizer.doMouseDown=function(){var a=Jui.$owner();
a._start=a._isHorzLine?event.pageY:event.pageX;
};
Jui.option.Resizer.doDragStart=function(){var a=Jui.$owner();
a._mask.style.display="block";
a._dragger.style.display="block";
a.element.setAttribute("jui-dragging",true);
event.dataTransfer.effectAllowed="move";
if(event.dataTransfer.setDragImage){event.dataTransfer.setData("custom","resizer");
}Jui.option.Resizer._currentResizer=a;
};
Jui.option.Resizer.doDragEnd=function(){var a=Jui.$owner();
a._mask.style.display="none";
a._dragger.style.display="none";
a.element.removeAttribute("jui-dragging");
a._refresh();
};
Jui.option.Resizer.doDragOver=function(){var a=Jui.$owner();
if(a._isHorzLine){a._dragger.style.top=parseInt(a.element.style.top)+event.pageY-a._start+"px";
}else{a._dragger.style.left=parseInt(a.element.style.left)+event.pageX-a._start+"px";
}Jui.event.preventDefault();
};
Jui.option.Resizer.doDrop=function(){var f=Jui.$owner();
var a=10;
if(f._isHorzLine){var k=event.pageY-f._start;
var i=f._elems[0].offsetHeight;
var g=f._elems[1].offsetHeight;
if(f._isNextFixed){var c=Math.max(a,Math.min(i+g-a,g-k));
f._elems[0].style.bottom=parseInt(Jui.dom.getComputedStyle(f._elems[0]).bottom)-g+c+"px";
f._elems[1].style.height=c+"px";
f._elems[0].style.height="auto";
f._elems[1].style.top="auto";
}else{var c=Math.max(a,Math.min(i+g-a,i+k));
f._elems[0].style.height=c+"px";
f._elems[1].style.top=f._elems[1].offsetTop+c-i+"px";
f._elems[0].style.bottom="auto";
f._elems[1].style.height="auto";
}}else{var k=event.pageX-f._start;
var e=f._elems[0].offsetWidth;
var d=f._elems[1].offsetWidth;
if(f._isNextFixed){var j=Math.max(a,Math.min(e+d-a,d-k));
f._elems[0].style.right=parseInt(Jui.dom.getComputedStyle(f._elems[0]).right)-d+j+"px";
f._elems[1].style.width=j+"px";
f._elems[0].style.width="auto";
f._elems[1].style.left="auto";
}else{var j=Math.max(a,Math.min(e+d-a,e+k));
f._elems[0].style.width=j+"px";
f._elems[1].style.left=f._elems[1].offsetLeft+j-e+"px";
f._elems[0].style.right="auto";
f._elems[1].style.width="auto";
}}var b=document.createEvent("UIEvents");
b.initEvent("resize",true,true);
window.dispatchEvent(b);
};
Jui.option.Resizer.prototype._refresh=function(){var f=this;
if(!f.isVisible()||f._elems==null){return;
}var c=[f._elems[0].getBoundingClientRect(),f._elems[1].getBoundingClientRect()];
var d=(c[0].left+c[0].right)/2-(c[1].left+c[1].right)/2;
var b=(c[0].top+c[0].bottom)/2-(c[1].top+c[1].bottom)/2;
f._isHorzLine=Math.abs(d)<Math.abs(b);
f.element.setAttribute("jui-line-type",f._isHorzLine?"H":"V");
f._dragger.setAttribute("jui-line-type",f._isHorzLine?"H":"V");
if(f._isHorzLine){var g=f._getOffset(c[0].bottom,c[1].top);
var e=c[0].width||(c[0].right-c[0].left);
f.element.style.top=c[0].bottom+g+"px";
f._dragger.style.top=c[0].bottom+g+"px";
f.element.style.left=c[0].left+f._shrinks[0]+"px";
f._dragger.style.left=c[0].left+f._shrinks[0]+"px";
f.element.style.width=e-f._shrinks[0]-f._shrinks[1]+"px";
f._dragger.style.width=e-f._shrinks[0]-f._shrinks[1]+"px";
}else{var g=f._getOffset(c[0].right,c[1].left);
var a=c[0].height||(c[0].bottom-c[0].top);
f.element.style.left=c[0].right+g+"px";
f._dragger.style.left=c[0].right+g+"px";
f.element.style.top=c[0].top+f._shrinks[0]+"px";
f._dragger.style.top=c[0].top+f._shrinks[0]+"px";
f.element.style.height=a-f._shrinks[0]-f._shrinks[1]+"px";
f._dragger.style.height=a-f._shrinks[0]-f._shrinks[1]+"px";
}};
Jui.option.Resizer.prototype._getOffset=function(d,c){if(this._reside==0){return -Jui.theme["Resizer.Width"];
}else{if(this._reside==1){return 0;
}else{return this._offset==null?(c-d-Jui.theme["Resizer.Width"])/2:this._offset;
}}};
