Jui.$define("Jui.graph.MapGraph",Jui.graph.Graph);
Jui.graph.MapGraph.initialize=function(c,b,a){b=b||{};
b.scrollable=false;
a=a||this;
var d=this.superClass.initialize(c,b,a);
d.element.className="JuiGraph JuiMapGraph";
d._image=Jui.dom.insertHtml(d._content,"AfterBegin","<img class=JuiMapGraphMap>");
d._image.src=b.image;
d._imageSize=b.imageSize;
d._imageRect=b.imageRect;
return d;
};
Jui.graph.MapGraph.prototype.load=function(l){this._resizeImage();
l=Jui.util.clone(l||{nodes:[],lines:[]});
var d=this._content.clientWidth;
var a=this._content.clientHeight;
this._gridSize=128;
var g=Math.floor(a/2*this._gridSize);
var f=0;
for(var e=0;
e<l.nodes.length;
++e){var b=l.nodes[e];
b.x=b.x*this._ratioX+this._rectX;
b.y=b.y*this._ratioY+this._rectY;
if(b.x<0||b.x>=d||b.y<0||b.y>=a){b.x=this._gridSize*(0.6+Math.floor(f/g));
b.y=this._gridSize*(0.6+(f%g));
++f;
}}for(var e=0;
e<l.lines.length;
++e){for(var c=0,k=l.lines[e].routes||[];
c<k.length;
++c){var h=k[c];
h.x=h.x*this._ratioX+this._rectX;
h.y=h.y*this._ratioY+this._rectY;
}}Jui.graph.Graph.prototype.load.call(this,l);
};
Jui.graph.MapGraph.prototype.getJson=function(){var b=Jui.graph.Graph.prototype.getJson.call(this);
for(var a=0;
a<b.nodes.length;
++a){var c=b.nodes[a];
c.x=(c.x-this._rectX)/this._ratioX;
c.y=(c.y-this._rectY)/this._ratioY;
}return b;
};
Jui.graph.MapGraph.prototype._resizeImage=function(){var b=this._imageSize;
var e=this._imageRect;
var a=this._content.clientWidth;
var d=this._content.clientHeight;
if(e==null){this._image.style.width="100%";
this._image.style.height="100%";
this._ratioX=a/b.width;
this._ratioY=d/b.height;
this._rectX=0;
this._rectY=0;
}else{var c=b.width-e.left-e.right;
var f=b.height-e.top-e.bottom;
if(a>0&&d>0&&c>0&&f>0){this._ratioX=this._ratioY=Math.min(a/c,d/f);
this._rectX=a/c<=d/f?0:a/2-c*0.5*this._ratioX;
this._rectY=a/c>=d/f?0:d/2-f*0.5*this._ratioY;
this._image.style.width=Math.round(this._ratioX*b.width)+"px";
this._image.style.height=Math.round(this._ratioY*b.height)+"px";
this._image.style.left=Math.round(a/2-this._ratioX*(c/2+e.left))+"px";
this._image.style.top=Math.round(d/2-this._ratioY*(f/2+e.top))+"px";
}}};
