--Minglei.Lee

--Qs.RemoteApiParameter---------------------------------------------------------

create table TsRemoteApiParameter
(
	FId uuid primary key,
	FCode varchar(50),
	FRemoteApiId uuid,
	FPosition varchar(20),
	FEnabled bit,
	FValue varchar(100)
);

insert into TsUnit set FId='814a20f6-d539-4f8f-bc40-5361de321cc6', FCode='Qs.RemoteApiParameter', FName='遠端 API 參數', FIcon='quicksilver/image/unit/RemoteApiParameter.png', FBigIcon=null, FEditId='541c707d-79dd-4dbb-85fc-1a214fd5fce4', FModuleId='00000000-0000-0000-0008-990000000020', FOpenMode='System', FIsTreeStructure=0, FMaxTreeLevel=null, FIsSlaveUnit=1, FMasterUnitId='d9fae961-1ef3-4879-893c-fe68913ff828', FSupportWorkflow=0, FSupportUser=0, FSupportDepartment=0, FSupportEditType=0, FSupportAttachment=0, FSupportDataPrivilege=0, FSupportVersion=0, FSupportBusinessLog=0, FSupportNote=0, FSupportSort=0, FSupportPrivilegeField=0, FIsFullTextSearch=0, FSearchAttachment=0, FSupportEqualQuery=0, FUseSystemI18nTable=0, FExtraQueryResultLimit=0, FRecordCreateInfo=0, FRecordUpdateInfo=0, FRecordDeleteInfo=0, FViewPageConditionForList=null, FViewPageConditionForLink=null, FDataSource='default', FTable='TsRemoteApiParameter', FKeyField='FId', FKeyType='Uuid', FNameField='FCode', FMasterField='FRemoteApiId', FHomeClassName='com.jeedsoft.quicksilver.integration.RemoteApiParameterHome', FDaoClassName='com.jeedsoft.quicksilver.integration.dao.impl.RemoteApiParameterDaoImpl', FServiceClassName='com.jeedsoft.quicksilver.integration.service.impl.RemoteApiParameterServiceImpl', FActionClassName='com.jeedsoft.quicksilver.integration.action.impl.RemoteApiParameterActionImpl', FWebServiceUniqueField=null, FUnitFilterSql='', FBusinessFilterSql='', FDescription='';

insert into TsField set FId='ce1241ac-f330-4ef7-96bc-9572dec1ceae', FUnitId='814a20f6-d539-4f8f-bc40-5361de321cc6', FName='FCode',        FTitle='名稱',     FType='InputBox-Text',       FSize=50,   FVisible=1, FFilterByRole=0, FRequired=1, FReadOnly=0, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=200, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValueType=null,          FDefaultValue=null,   FHint=null, FAlwaysBringDataToClient=0, FValidation=null, FMobileListFormat=null, FFollowingField=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='f379be00-7c13-44b3-ac41-9f0f91b515d1', FUnitId='814a20f6-d539-4f8f-bc40-5361de321cc6', FName='FEnabled',     FTitle='是否啟用', FType='CheckBox',            FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValueType='ServerValue', FDefaultValue='true', FHint='',   FAlwaysBringDataToClient=0, FValidation=null, FMobileListFormat=null, FFollowingField=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='756f3284-af58-4d57-8bf3-05d6bb729935', FUnitId='814a20f6-d539-4f8f-bc40-5361de321cc6', FName='FId',          FTitle='ID',       FType='InputBox-Key',        FSize=null, FVisible=0, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=0, FDictionaryId=null,                                   FEntityUnitId='814a20f6-d539-4f8f-bc40-5361de321cc6', FSupportLocalText=null, FSupportI18n=null, FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=null, FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValueType=null,          FDefaultValue=null,   FHint=null, FAlwaysBringDataToClient=0, FValidation=null, FMobileListFormat=null, FFollowingField=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData=null;
insert into TsField set FId='7c2cbf7f-7675-493a-86db-707729282561', FUnitId='814a20f6-d539-4f8f-bc40-5361de321cc6', FName='FPosition',    FTitle='位置',     FType='ComboBox-SelectOnly', FSize=20,   FVisible=1, FFilterByRole=0, FRequired=1, FReadOnly=0, FQueryable=1, FDictionaryId='0f870b63-23c4-4de8-a1e2-f5e9b42c60d4', FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=120, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValueType=null,          FDefaultValue=null,   FHint='',   FAlwaysBringDataToClient=0, FValidation=null, FMobileListFormat=null, FFollowingField=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='4e4cb5cf-3a9e-4c75-ab43-5d2cc310db3c', FUnitId='814a20f6-d539-4f8f-bc40-5361de321cc6', FName='FRemoteApiId', FTitle='遠端 API', FType='EntityBox',           FSize=null, FVisible=0, FFilterByRole=0, FRequired=1, FReadOnly=0, FQueryable=0, FDictionaryId=null,                                   FEntityUnitId='d9fae961-1ef3-4879-893c-fe68913ff828', FSupportLocalText=null, FSupportI18n=null, FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=null, FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValueType=null,          FDefaultValue=null,   FHint=null, FAlwaysBringDataToClient=0, FValidation=null, FMobileListFormat=null, FFollowingField=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData=null;
insert into TsField set FId='5d435c5d-4591-44b8-9793-d7c700e2d642', FUnitId='814a20f6-d539-4f8f-bc40-5361de321cc6', FName='FValue',       FTitle='值',       FType='InputBox-Text',       FSize=100,  FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null,                                   FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValueType=null,          FDefaultValue=null,   FHint='',   FAlwaysBringDataToClient=0, FValidation=null, FMobileListFormat=null, FFollowingField=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';

insert into TsRelation set FId='beb35e7c-8ae0-463d-9700-fcf8f63e7810', FOppositeId='ad98a76d-30ee-4e42-b42b-8fdb45d5dcbf', FName='遠端 API 參數-遠端 API', FOppositeName='遠端 API-遠端 API 參數', FUnitId1='814a20f6-d539-4f8f-bc40-5361de321cc6', FUnitId2='d9fae961-1ef3-4879-893c-fe68913ff828', FType='field', FTable='', FField1='FId', FField2='FRemoteApiId', FDeleteAction1='unset', FDeleteAction2='cancel', FPrivilegeTypeId1=null, FPrivilegeTypeId2=null;

insert into TsPage set FId='cc09f61e-5ae2-4d1c-aa4b-e8ce2269e78a', FName='遠端 API 參數主列表',   FTitle='遠端 API 參數列表', FCode='Qs.RemoteApiParameter.List',       FEditId='4e9b96a5-4c20-42a0-8929-d83efc27af4e', FPlatform='Computer', FType='EntityList', FIcon='quicksilver/image/unit/RemoteApiParameter.png', FUrl='quicksilver/page/template/EntityList.jsp', FActionMethodName='Qs.RemoteApiParameter.prepareList', FLoadHandler=null, FRelationId=null, FUnitId='814a20f6-d539-4f8f-bc40-5361de321cc6', FMasterUnitId=null,                                   FIsSlavePage=0, FIndex=null, FFormColumnCount=null, FDialogWidth=null, FDialogHeight=null, FDialogMaximized=null, FQueryFormAutoQuery=1, FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription=null;
insert into TsPage set FId='0c70c8e8-d53e-4411-8f94-b6af5b5e912e', FName='遠端 API 參數選擇列表', FTitle='遠端 API 參數列表', FCode='Qs.RemoteApiParameter.SelectList', FEditId='4e9b96a5-4c20-42a0-8929-d83efc27af4e', FPlatform='Computer', FType='EntityList', FIcon='quicksilver/image/unit/RemoteApiParameter.png', FUrl='quicksilver/page/template/EntityList.jsp', FActionMethodName='Qs.RemoteApiParameter.prepareList', FLoadHandler=null, FRelationId=null, FUnitId='814a20f6-d539-4f8f-bc40-5361de321cc6', FMasterUnitId=null,                                   FIsSlavePage=0, FIndex=null, FFormColumnCount=null, FDialogWidth=null, FDialogHeight=null, FDialogMaximized=null, FQueryFormAutoQuery=1, FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription=null;
insert into TsPage set FId='9325bf52-f213-41d7-a46a-aba1938c65c2', FName='遠端 API 參數表單',     FTitle='表單',              FCode='Qs.RemoteApiParameter.Form',       FEditId='4e9b96a5-4c20-42a0-8929-d83efc27af4e', FPlatform='Computer', FType='EntityForm', FIcon='quicksilver/image/unit/Form.png',               FUrl='quicksilver/page/template/EntityForm.jsp', FActionMethodName='Qs.RemoteApiParameter.prepareForm', FLoadHandler=null, FRelationId=null, FUnitId='814a20f6-d539-4f8f-bc40-5361de321cc6', FMasterUnitId='814a20f6-d539-4f8f-bc40-5361de321cc6', FIsSlavePage=1, FIndex=1,    FFormColumnCount=null, FDialogWidth=null, FDialogHeight=500,  FDialogMaximized=null, FQueryFormAutoQuery=1, FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription=null;

--遠端 API 參數主列表
insert into TsToolItem set FId='c8938e9f-1f3a-4a44-95dc-ad491eba47be', FPageId='cc09f61e-5ae2-4d1c-aa4b-e8ce2269e78a', FCode='Add',     FName='新增', FHint='新增一筆記錄',                                         FLabel=null, FType='Button',      FAlign='right', FIndex=1, FWidth=0, FIcon='quicksilver/image/16/Add.png',     FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doAdd';
insert into TsToolItem set FId='6626b90a-9e8c-4d07-b971-5eb9b32b3ca3', FPageId='cc09f61e-5ae2-4d1c-aa4b-e8ce2269e78a', FCode='Open',    FName='打開', FHint='打開當前選中的記錄。如果選中了多筆，第一筆將被打開。', FLabel=null, FType='Button',      FAlign='right', FIndex=2, FWidth=0, FIcon='quicksilver/image/16/Open.png',    FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doOpen';
insert into TsToolItem set FId='6c539398-8b76-428e-994b-07966f50a06e', FPageId='cc09f61e-5ae2-4d1c-aa4b-e8ce2269e78a', FCode='Delete',  FName='刪除', FHint='刪除當前選中的記錄',                                   FLabel=null, FType='Button',      FAlign='right', FIndex=3, FWidth=0, FIcon='quicksilver/image/16/Delete.png',  FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doDelete';
insert into TsToolItem set FId='83d0c5d9-067b-409a-92a5-1cd888ddda46', FPageId='cc09f61e-5ae2-4d1c-aa4b-e8ce2269e78a', FCode='Refresh', FName='刷新', FHint='刷新清單內容',                                         FLabel=null, FType='Button',      FAlign='right', FIndex=4, FWidth=0, FIcon='quicksilver/image/16/Refresh.png', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doRefresh';

--遠端 API 參數選擇列表
insert into TsToolItem set FId='29cd6126-cf06-424e-b343-b093808e8fe5', FPageId='0c70c8e8-d53e-4411-8f94-b6af5b5e912e', FCode='ConfirmSelection', FName='確定', FHint=null,                                                   FLabel=null, FType='Button', FAlign='right', FIndex=1, FWidth=0, FIcon='quicksilver/image/16/Ok.png',   FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doSelectListConfirm';
insert into TsToolItem set FId='9476826c-dee9-470a-a1bd-0aabf1bbb68e', FPageId='0c70c8e8-d53e-4411-8f94-b6af5b5e912e', FCode='Add',              FName='新增', FHint='新增一筆記錄',                                         FLabel=null, FType='Button', FAlign='right', FIndex=2, FWidth=0, FIcon='quicksilver/image/16/Add.png',  FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doAdd';
insert into TsToolItem set FId='ed68a2ee-86df-4de7-bf67-9b6dc0487e31', FPageId='0c70c8e8-d53e-4411-8f94-b6af5b5e912e', FCode='Open',             FName='打開', FHint='打開當前選中的記錄。如果選中了多筆，第一筆將被打開。', FLabel=null, FType='Button', FAlign='right', FIndex=3, FWidth=0, FIcon='quicksilver/image/16/Open.png', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doOpen';

--遠端 API 參數表單
insert into TsToolItem set FId='70bd2b3c-a798-45d1-ac71-ba273e462607', FPageId='9325bf52-f213-41d7-a46a-aba1938c65c2', FCode='Save',  FName='保存', FHint=null, FLabel=null, FType='Button',      FAlign='right', FIndex=1, FWidth=0, FIcon='quicksilver/image/16/Save.png',  FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='EntityForm.doSave';

insert into TsForm set FDefault=1, FEditableCondition=null, FGroupMode='Double', FId='99d6239c-9ba0-43eb-8632-a8bc3321d23a', FIndex=1, FName='默認', FPageId=null, FPlatform='Computer', FUnitId='814a20f6-d539-4f8f-bc40-5361de321cc6';
java setFormFields('99d6239c-9ba0-43eb-8632-a8bc3321d23a', '基本資訊', 'aa2d35a5-4035-4d5b-a4c6-3830b9e3a52b', null, 'FCode,FPosition,FEnabled,FValue');

insert into TsList set FDefault=1, FId='d76c3fbe-8d80-4134-a54c-36f8a77aab72', FIndex=null, FMultiPage=1, FName='遠端 API 參數列表',     FPageId=null,                                   FPlatform='Computer', FUnitId='814a20f6-d539-4f8f-bc40-5361de321cc6';
insert into TsList set FDefault=0, FId='2d9ee53d-b800-4a11-8bae-776e03e111f9', FIndex=null, FMultiPage=1, FName='遠端 API 參數選擇列表', FPageId='0c70c8e8-d53e-4411-8f94-b6af5b5e912e', FPlatform='Computer', FUnitId='814a20f6-d539-4f8f-bc40-5361de321cc6';
insert into TsList set FDefault=0, FId='5cd25783-6a31-4b9a-b008-9cb86e874a8c', FIndex=null, FMultiPage=1, FName='遠端 API 參數首頁列表', FPageId='9b796431-f132-49d1-b306-5d1d618f9c1b', FPlatform='Computer', FUnitId='814a20f6-d539-4f8f-bc40-5361de321cc6';
java setListFields('d76c3fbe-8d80-4134-a54c-36f8a77aab72', 'FCode,FPosition,FEnabled,FValue');
java setListFields('2d9ee53d-b800-4a11-8bae-776e03e111f9', 'FCode,FPosition,FEnabled,FValue');
java setListFields('5cd25783-6a31-4b9a-b008-9cb86e874a8c', 'FCode,FPosition,FEnabled,FValue');

insert into TsSlaveUnitPrivilege set FId='ffefd2d7-d451-4421-a93e-3a1f3f0b3ecb', FUnitId='814a20f6-d539-4f8f-bc40-5361de321cc6', FCreatePrivilegeTypeId='00000000-0000-0000-1005-000000000003', FReadPrivilegeTypeId='00000000-0000-0000-1005-000000000003', FReadUserFieldName='', FUpdatePrivilegeTypeId='00000000-0000-0000-1005-000000000003', FUpdateUserFieldName='', FDeletePrivilegeTypeId='00000000-0000-0000-1005-000000000003', FDeleteUserFieldName='';

update TsPage set FIndex = 3 where FCode='Qs.RemoteApi.RemoteApiTestCaseList';
insert into TsPage set FId='3fbf89eb-28ef-4e9b-93c3-8c1f36144767', FName='遠端 API 參數列表',		  FTitle='參數',		FCode='Qs.RemoteApi.RemoteApiParameterList', FEditId='4e9b96a5-4c20-42a0-8929-d83efc27af4e', FPlatform='Computer', FType='EditableList', FIcon='quicksilver/image/unit/RemoteApiParameter.png', FUrl='quicksilver/page/template/EditableList.jsp', FActionMethodName='Qs.RemoteApiParameter.prepareEditableList', FLoadHandler=null,                   FRelationId='ad98a76d-30ee-4e42-b42b-8fdb45d5dcbf', FUnitId='814a20f6-d539-4f8f-bc40-5361de321cc6', FMasterUnitId='d9fae961-1ef3-4879-893c-fe68913ff828', FIsSlavePage=1, FIndex=2,    FFormColumnCount=null, FDialogWidth=null, FDialogHeight=null, FDialogMaximized=null, FQueryFormAutoQuery=1, FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription=null;

--遠端 API远端 API 参数列表
insert into TsToolItem set FId='341fb418-911e-482a-9adc-7a543abe628c', FPageId='3fbf89eb-28ef-4e9b-93c3-8c1f36144767', FCode='Add',     FName='新增', FHint='新增一笔记录',       FLabel=null, FType='Button',      FAlign='right', FIndex=1, FWidth=0, FIcon='quicksilver/image/16/Add.png',     FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='EditableList.doAdd';
insert into TsToolItem set FId='10aa1ddc-46e1-4a73-8cf2-be3da18ba6c6', FPageId='3fbf89eb-28ef-4e9b-93c3-8c1f36144767', FCode='Delete',  FName='删除', FHint='删除当前选中的记录', FLabel=null, FType='Button',      FAlign='right', FIndex=2, FWidth=0, FIcon='quicksilver/image/16/Delete.png',  FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='EditableList.doDelete';
insert into TsToolItem set FId='4ab1d881-35f8-4122-a698-4471f1bf1d6f', FPageId='3fbf89eb-28ef-4e9b-93c3-8c1f36144767', FCode='Save',    FName='保存', FHint=null,                 FLabel=null, FType='Button',      FAlign='right', FIndex=3, FWidth=0, FIcon='quicksilver/image/16/Save.png',    FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='EditableList.doSave';
insert into TsToolItem set FId='7b444d3b-e218-4cb5-a997-5a7c57f1524c', FPageId='3fbf89eb-28ef-4e9b-93c3-8c1f36144767', FCode='Refresh', FName='刷新', FHint='刷新列表内容',       FLabel=null, FType='Button',      FAlign='right', FIndex=4, FWidth=0, FIcon='quicksilver/image/16/Refresh.png', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='EditableList.doRefresh';

insert into TsDictionary set FBuiltin=0, FDescription='', FId='0f870b63-23c4-4de8-a1e2-f5e9b42c60d4', FName='QS-遠端API參數-位置', FParentId=null, FTextAsValue=0;
insert into TsDictionaryItem set FDictionaryId='0f870b63-23c4-4de8-a1e2-f5e9b42c60d4', FEnabled=1, FId='293755a0-304c-4113-8323-09743c121caf', FIndex=1, FParentValue=null, FText='URL',      FValue='Url';
--insert into TsDictionaryItem set FDictionaryId='0f870b63-23c4-4de8-a1e2-f5e9b42c60d4', FEnabled=1, FId='c0e35c6c-1cf3-4b7a-af4f-5359a5624652', FIndex=2, FParentValue=null, FText='請求數據', FValue='Data';
