--Qs.OuterWebSocketRegion-------------------------------------------------------

create table TsOuterWebSocketRegion
(
	FId uuid primary key,
	FCode varchar(50),
	FEnabled bit,
	FTimeoutMinutes int,
	FHandlerClassName varchar(100),
	FDescription varchar(500)
);

insert into TsUnit set FId='e5fd6763-5afd-42ab-bb0e-78639fec4b49', FCode='Qs.OuterWebSocketRegion', FName='WebSocket 外接設置', FIcon='quicksilver/image/unit/OuterWebSocketRegion.png', FBigIcon=null, FEditId='541c707d-79dd-4dbb-85fc-1a214fd5fce4', FModuleId='00000000-0000-0000-0008-990000000020', FOpenMode='System', FIsTreeStructure=0, FMaxTreeLevel=null, FIsSlaveUnit=0, FMasterUnitId=null, FSupportWorkflow=0, FSupportUser=0, FSupportDepartment=0, FSupportEditType=0, FSupportAttachment=0, FSupportDataPrivilege=0, FSupportVersion=0, FSupportBusinessLog=0, FSupportNote=0, FSupportSort=0, FSupportPrivilegeField=0, FIsFullTextSearch=0, FSearchAttachment=0, FSupportEqualQuery=0, FUseSystemI18nTable=1, FExtraQueryResultLimit=0, FRecordCreateInfo=0, FRecordUpdateInfo=0, FRecordDeleteInfo=0, FViewPageConditionForList=null, FViewPageConditionForLink=null, FDataSource='default', FTable='TsOuterWebSocketRegion', FKeyField='FId', FKeyType='Uuid', FNameField='FCode', FMasterField=null, FHomeClassName='com.jeedsoft.quicksilver.websocket.OuterWebSocketRegionHome', FDaoClassName='com.jeedsoft.quicksilver.websocket.dao.impl.OuterWebSocketRegionDaoImpl', FServiceClassName='com.jeedsoft.quicksilver.websocket.service.impl.OuterWebSocketRegionServiceImpl', FActionClassName='com.jeedsoft.quicksilver.websocket.action.impl.OuterWebSocketRegionActionImpl', FWebServiceUniqueField=null, FUnitFilterSql='', FBusinessFilterSql='', FDescription='';

insert into TsField set FId='0c766c15-c045-4762-a05c-45c6f8150de6', FUnitId='e5fd6763-5afd-42ab-bb0e-78639fec4b49', FName='FCode',             FTitle='Region',         FType='InputBox-Text',    FSize=50,   FVisible=1, FFilterByRole=0, FRequired=1, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=120, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValueType=null,          FDefaultValue=null, FHint='',   FAlwaysBringDataToClient=0, FValidation=null, FMobileListFormat=null, FFollowingField=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='7ad01413-0cd6-4293-b91e-7cddebd7de02', FUnitId='e5fd6763-5afd-42ab-bb0e-78639fec4b49', FName='FDescription',      FTitle='描述',           FType='TextBox',          FSize=500,  FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=1,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=0, FRowSpan=3, FIsNewRow=0,    FListWidth=120, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValueType=null,          FDefaultValue=null, FHint='',   FAlwaysBringDataToClient=0, FValidation=null, FMobileListFormat=null, FFollowingField=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='0f919881-9f2d-4106-9229-f99080001490', FUnitId='e5fd6763-5afd-42ab-bb0e-78639fec4b49', FName='FEnabled',          FTitle='是否啟用',       FType='CheckBox',         FSize=null, FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=120, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValueType=null,          FDefaultValue=null, FHint='',   FAlwaysBringDataToClient=0, FValidation=null, FMobileListFormat=null, FFollowingField=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='f7e49a6c-645a-4443-b0cf-6ced5aae1103', FUnitId='e5fd6763-5afd-42ab-bb0e-78639fec4b49', FName='FHandlerClassName', FTitle='處理類',         FType='InputBox-Text',    FSize=100,  FVisible=1, FFilterByRole=0, FRequired=1, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=0, FRowSpan=1, FIsNewRow=0,    FListWidth=240, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValueType=null,          FDefaultValue=null, FHint='',   FAlwaysBringDataToClient=0, FValidation=null, FMobileListFormat=null, FFollowingField=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='bc88cefa-324b-4595-b46f-341c21598adc', FUnitId='e5fd6763-5afd-42ab-bb0e-78639fec4b49', FName='FId',               FTitle='ID',             FType='InputBox-Key',     FSize=null, FVisible=0, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=0, FDictionaryId=null, FEntityUnitId='e5fd6763-5afd-42ab-bb0e-78639fec4b49', FSupportLocalText=null, FSupportI18n=null, FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=null, FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValueType=null,          FDefaultValue=null, FHint=null, FAlwaysBringDataToClient=0, FValidation=null, FMobileListFormat=null, FFollowingField=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData=null;
insert into TsField set FId='699381eb-69bd-427f-8b79-7ccb4f6e4a35', FUnitId='e5fd6763-5afd-42ab-bb0e-78639fec4b49', FName='FTimeoutMinutes',   FTitle='超時時間(分鐘)', FType='InputBox-Integer', FSize=null, FVisible=1, FFilterByRole=0, FRequired=1, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=120, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValueType='ServerValue', FDefaultValue='10', FHint='',   FAlwaysBringDataToClient=0, FValidation=null, FMobileListFormat=null, FFollowingField=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';

insert into TsPage set FId='a9b3b426-0b8e-4fd7-9205-d1838114b00b', FName='WebSocket 外接設置主列表',   FTitle='WebSocket 外接設置列表', FCode='Qs.OuterWebSocketRegion.List',       FEditId='4e9b96a5-4c20-42a0-8929-d83efc27af4e', FPlatform='Computer', FType='EntityList', FIcon='quicksilver/image/unit/OuterWebSocketRegion.png', FUrl='quicksilver/page/template/EntityList.jsp', FActionMethodName='Qs.OuterWebSocketRegion.prepareList', FLoadHandler=null, FRelationId=null, FUnitId='e5fd6763-5afd-42ab-bb0e-78639fec4b49', FMasterUnitId=null,                                   FIsSlavePage=0, FIndex=null, FFormColumnCount=null, FDialogWidth=null, FDialogHeight=null, FDialogMaximized=null, FQueryFormAutoQuery=1, FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription=null;
insert into TsPage set FId='de38e0e7-b126-4570-8994-5390ea13e00c', FName='WebSocket 外接設置選擇列表', FTitle='WebSocket 外接設置列表', FCode='Qs.OuterWebSocketRegion.SelectList', FEditId='4e9b96a5-4c20-42a0-8929-d83efc27af4e', FPlatform='Computer', FType='EntityList', FIcon='quicksilver/image/unit/OuterWebSocketRegion.png', FUrl='quicksilver/page/template/EntityList.jsp', FActionMethodName='Qs.OuterWebSocketRegion.prepareList', FLoadHandler=null, FRelationId=null, FUnitId='e5fd6763-5afd-42ab-bb0e-78639fec4b49', FMasterUnitId=null,                                   FIsSlavePage=0, FIndex=null, FFormColumnCount=null, FDialogWidth=null, FDialogHeight=null, FDialogMaximized=null, FQueryFormAutoQuery=1, FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription=null;
insert into TsPage set FId='f616e51f-0a0e-4743-9215-719bb56ea055', FName='WebSocket 外接設置表單',     FTitle='表單',                   FCode='Qs.OuterWebSocketRegion.Form',       FEditId='4e9b96a5-4c20-42a0-8929-d83efc27af4e', FPlatform='Computer', FType='EntityForm', FIcon='quicksilver/image/unit/Form.png',             FUrl='quicksilver/page/template/EntityForm.jsp', FActionMethodName='Qs.OuterWebSocketRegion.prepareForm', FLoadHandler=null, FRelationId=null, FUnitId='e5fd6763-5afd-42ab-bb0e-78639fec4b49', FMasterUnitId='e5fd6763-5afd-42ab-bb0e-78639fec4b49', FIsSlavePage=1, FIndex=1,    FFormColumnCount=null, FDialogWidth=null, FDialogHeight=500,  FDialogMaximized=null, FQueryFormAutoQuery=1, FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription=null;

--WebSocket 外接設置主列表
insert into TsToolItem set FId='e9b9420d-129c-461f-b177-9cf4c786a76b', FPageId='a9b3b426-0b8e-4fd7-9205-d1838114b00b', FCode='Add',     FName='新增', FHint='新增一筆記錄',                                         FLabel=null, FType='Button',      FAlign='right', FIndex=1, FWidth=0, FIcon='quicksilver/image/16/Add.png',     FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doAdd';
insert into TsToolItem set FId='74e50f3a-d53d-4918-8906-3b729f21ca54', FPageId='a9b3b426-0b8e-4fd7-9205-d1838114b00b', FCode='Open',    FName='打開', FHint='打開當前選中的記錄。如果選中了多筆，第一筆將被打開。', FLabel=null, FType='Button',      FAlign='right', FIndex=2, FWidth=0, FIcon='quicksilver/image/16/Open.png',    FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doOpen';
insert into TsToolItem set FId='c5412447-c44e-4ba0-b892-c13c5979298b', FPageId='a9b3b426-0b8e-4fd7-9205-d1838114b00b', FCode='Delete',  FName='刪除', FHint='刪除當前選中的記錄',                                   FLabel=null, FType='Button',      FAlign='right', FIndex=3, FWidth=0, FIcon='quicksilver/image/16/Delete.png',  FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doDelete';
insert into TsToolItem set FId='e2160640-0f4e-49e0-9b0a-ad0ed6ef7ba3', FPageId='a9b3b426-0b8e-4fd7-9205-d1838114b00b', FCode='Refresh', FName='刷新', FHint='刷新清單內容',                                         FLabel=null, FType='Button',      FAlign='right', FIndex=4, FWidth=0, FIcon='quicksilver/image/16/Refresh.png', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doRefresh';

--WebSocket 外接設置選擇列表
insert into TsToolItem set FId='1aca9861-9009-4bba-ad0e-53dcdd80c7e2', FPageId='de38e0e7-b126-4570-8994-5390ea13e00c', FCode='ConfirmSelection', FName='確定', FHint=null,                                                   FLabel=null, FType='Button', FAlign='right', FIndex=1, FWidth=0, FIcon='quicksilver/image/16/Ok.png',   FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doSelectListConfirm';
insert into TsToolItem set FId='898638d7-47c2-4f9b-9e7b-824e2a82de80', FPageId='de38e0e7-b126-4570-8994-5390ea13e00c', FCode='Add',              FName='新增', FHint='新增一筆記錄',                                         FLabel=null, FType='Button', FAlign='right', FIndex=2, FWidth=0, FIcon='quicksilver/image/16/Add.png',  FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doAdd';
insert into TsToolItem set FId='acaa0474-e5ad-42a3-9998-4e3e325139d8', FPageId='de38e0e7-b126-4570-8994-5390ea13e00c', FCode='Open',             FName='打開', FHint='打開當前選中的記錄。如果選中了多筆，第一筆將被打開。', FLabel=null, FType='Button', FAlign='right', FIndex=3, FWidth=0, FIcon='quicksilver/image/16/Open.png', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doOpen';

--WebSocket 外接設置表單
insert into TsToolItem set FId='82f0c98f-cd42-4501-b885-13feef6cb875', FPageId='f616e51f-0a0e-4743-9215-719bb56ea055', FCode='Save',  FName='保存', FHint=null, FLabel=null, FType='Button',      FAlign='right', FIndex=1, FWidth=0, FIcon='quicksilver/image/16/Save.png',  FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FChartId=null, FConfirmMessage=null, FDefaultEventHandler='EntityForm.doSave';

insert into TsForm set FDefault=1, FEditableCondition=null, FGroupMode='None', FId='6158e103-df6b-4606-90bc-3bd3afa85655', FIndex=1, FName='默認', FPageId=null, FPlatform='Computer', FUnitId='e5fd6763-5afd-42ab-bb0e-78639fec4b49';
java setFormFields('6158e103-df6b-4606-90bc-3bd3afa85655', 'FCode,FTimeoutMinutes,FEnabled,FHandlerClassName,FDescription');

insert into TsList set FDefault=1, FId='df30e8c0-ae79-427f-9647-28ed5812586c', FIndex=null, FMultiPage=1, FName='WebSocket 外接設置列表',     FPageId=null,                                   FPlatform='Computer', FUnitId='e5fd6763-5afd-42ab-bb0e-78639fec4b49';
insert into TsList set FDefault=0, FId='367890f1-7293-4640-a04f-4176fb224e32', FIndex=null, FMultiPage=1, FName='WebSocket 外接設置選擇列表', FPageId='de38e0e7-b126-4570-8994-5390ea13e00c', FPlatform='Computer', FUnitId='e5fd6763-5afd-42ab-bb0e-78639fec4b49';
insert into TsList set FDefault=0, FId='eca08e69-4cb7-4ffe-a7d7-e8b51724fcc0', FIndex=null, FMultiPage=1, FName='WebSocket 外接設置首頁列表', FPageId='9b796431-f132-49d1-b306-5d1d618f9c1b', FPlatform='Computer', FUnitId='e5fd6763-5afd-42ab-bb0e-78639fec4b49';
java setListFields('df30e8c0-ae79-427f-9647-28ed5812586c', 'FCode,FEnabled,FTimeoutMinutes,FHandlerClassName,FDescription');
java setListFields('367890f1-7293-4640-a04f-4176fb224e32', 'FCode,FEnabled,FTimeoutMinutes,FHandlerClassName,FDescription');
java setListFields('eca08e69-4cb7-4ffe-a7d7-e8b51724fcc0', 'FCode,FEnabled,FTimeoutMinutes,FHandlerClassName,FDescription');

insert into TsPrivilege set FId='6ccb2b56-4e70-4234-8785-29f60570ade0', FName='WebSocket 外接設置查看', FUnitId='e5fd6763-5afd-42ab-bb0e-78639fec4b49', FModuleId='00000000-0000-0000-0008-990000000020', FPrivilegeTypeId='00000000-0000-0000-1005-000000000002', FUseExisting=0, FSourcePrivilegeId=null, FEditId='5992c3d2-0b4a-478c-bbfa-2089819ad575', FIndex=null;
insert into TsPrivilege set FId='62375668-5c07-45a1-befc-5968850bcc49', FName='WebSocket 外接設置管理', FUnitId='e5fd6763-5afd-42ab-bb0e-78639fec4b49', FModuleId='00000000-0000-0000-0008-990000000020', FPrivilegeTypeId='00000000-0000-0000-1005-000000000006', FUseExisting=0, FSourcePrivilegeId=null, FEditId='5992c3d2-0b4a-478c-bbfa-2089819ad575', FIndex=null;

insert into TsQuerySchema set FId='8b465be7-bbd0-420d-b5f7-e5dc043220b0', FUnitId='e5fd6763-5afd-42ab-bb0e-78639fec4b49', FName='全部WebSocket 外接設置',   FType='condition',  FPublic=1, FVisible=1, FTemp=0, FGlobalAutoQuery=0, FShare=0, FUserId=null, FConditionId=null, FSqlSource='None', FSql=null, FIndex=1, FUpdateTime=null, FOriginSchemaId=null, FParentId=null;
insert into TsQuerySchema set FId='3ba6787b-1233-4379-91dc-91f908563349', FUnitId='e5fd6763-5afd-42ab-bb0e-78639fec4b49', FName='WebSocket 外接設置我的最愛', FType='collection', FPublic=1, FVisible=1, FTemp=0, FGlobalAutoQuery=0, FShare=0, FUserId=null, FConditionId=null, FSqlSource='None', FSql=null, FIndex=3, FUpdateTime=null, FOriginSchemaId=null, FParentId=null;

insert into TsMenu set FId='e82d52f0-41e0-4d16-83f6-96382943cb52', FParentId='813ac0b2-a881-409f-ad05-f16bff890b11', FIndex=10, FTreeLevel=4, FTreeSerial='002.002.007.009', FName='WebSocket 外接設置', FIcon='quicksilver/image/unit/OuterWebSocketRegion.png', FType='InternalPage', FTabTitleSource='PageTitle', FTabTitle=null, FAlwaysOpenNewTab=0, FPageId='a9b3b426-0b8e-4fd7-9205-d1838114b00b', FQueryFormHidden=0, FQuerySchemaId=null, FQuerySchemaLocked=0, FArguments='', FExternalPageUrl=null, FOpenMode=null, FFunctionName=null, FLicensed=1, FEnabled=1, FReplaceByChildren=0, FSubMenuSource='MenuTable', FSubMenuRoutine='';

delete from TsTextResource where FId='6de8e48c-91de-47f4-8431-9050008026af';
delete from TsTextResource where FId='ee9a7466-bd2b-445e-908f-89045166286f';
delete from TsTextResource where FId='1c343c51-e591-466a-91ad-35f11147d155';
insert into TsTextResource set FId='6de8e48c-91de-47f4-8431-9050008026af', FCode='E.Qs.OuterWebSocket.RegionNotExist',					FValue='编码为“${0}”的 WebSocket 外接设置不存在。';
insert into TsTextResource set FId='ee9a7466-bd2b-445e-908f-89045166286f', FCode='E.Qs.OuterWebSocket.RegionNotEnabled',				FValue='编码为“${0}”的 WebSocket 外接设置未启用。';
insert into TsTextResource set FId='1c343c51-e591-466a-91ad-35f11147d155', FCode='E.Qs.OuterWebSocket.HandlerClassInvalid',				FValue='编码为“${0}”的 WebSocket 外接设置处理类“${1}”不正确。该类必须可访问并实现 OuterWebSocketHandler 接口。';

insert into TsOuterWebSocketRegion set FId='ab01b48e-739b-4e16-b549-9258b5fdcd05', FCode='Qs.Demo.Echo', FEnabled=0, FTimeoutMinutes=1, FHandlerClassName='com.jeedsoft.quicksilver.handler.websocket.DemoEchoWebSocketHandler', FDescription='簡易演示，將外部使用者輸入的消息及其長度作為回復。';

--Qs.Demo-----------------------------------------------------------------------

insert into TsUnit set FId='db52ac85-ccb2-4d5f-b3bc-e41144b071db', FCode='Qs.Demo', FName='功能演示', FIcon='quicksilver/image/unit/Demo.png', FBigIcon=null, FEditId='8b7ebd7e-8173-4787-9e34-3d27ad4c9c29', FModuleId='00000000-0000-0000-0008-990000000020', FOpenMode='System', FIsTreeStructure=null, FMaxTreeLevel=null, FIsSlaveUnit=null, FMasterUnitId=null, FSupportWorkflow=null, FSupportUser=null, FSupportDepartment=null, FSupportEditType=null, FSupportAttachment=null, FSupportDataPrivilege=null, FSupportVersion=null, FSupportBusinessLog=null, FSupportNote=null, FSupportSort=null, FSupportPrivilegeField=0, FIsFullTextSearch=0, FSearchAttachment=0, FSupportEqualQuery=0, FUseSystemI18nTable=0, FExtraQueryResultLimit=0, FRecordCreateInfo=0, FRecordUpdateInfo=0, FRecordDeleteInfo=0, FViewPageConditionForList=null, FViewPageConditionForLink=null, FDataSource='default', FTable=null, FKeyField='FId', FKeyType='Uuid', FNameField='FName', FMasterField=null, FHomeClassName='com.jeedsoft.quicksilver.demo.DemoHome', FDaoClassName='com.jeedsoft.quicksilver.demo.dao.impl.DemoDaoImpl', FServiceClassName='com.jeedsoft.quicksilver.demo.service.impl.DemoServiceImpl', FActionClassName='com.jeedsoft.quicksilver.demo.action.impl.DemoActionImpl', FWebServiceUniqueField=null, FUnitFilterSql=null, FBusinessFilterSql=null, FDescription='';

insert into TsPage set FId='dedabe83-0f3e-470a-aee0-d09f6efddf2b', FName='WebChat 演示',				FTitle='WebChat 演示',			FCode='Qs.Demo.WebChat',    FType='Other', FIcon='quicksilver/image/unit/OuterWebSocketRegion.png',					FUrl='quicksilver/page/demo/WebChat.jsp',													FActionMethodName=null,										FLoadHandler=null, FRelationId=null, FUnitId=null, FMasterUnitId='db52ac85-ccb2-4d5f-b3bc-e41144b071db',                                   FIsSlavePage=0, FIndex=null, FDialogWidth=null, FDialogHeight=null, FDialogMaximized=null, FQueryFormAutoQuery=1,    FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription='',   FEditId='5c6ae004-d69f-4c45-acb1-d1a049bd8aa9', FFormColumnCount=null;

insert into TsSpecialPath set FId='c464c77c-c59a-4cd2-bedb-ea48cd0ddc1e', FPath='Qs.Demo.WebChat.page',                             FMatchMode='PlainText',         FKey='BypassSession',    FValue='true',        FIndex=2;

delete from TsSpecialPath where exists (
    select * from TsSpecialPath T
    where FPath=TsSpecialPath.FPath
        and FMatchMode=TsSpecialPath.FMatchMode
		and FKey=TsSpecialPath.FKey
		and FValue=TsSpecialPath.FValue
		and ((ifnull(FIndex, 0) < ifnull(TsSpecialPath.FIndex, 0)) or (ifnull(FIndex, 0) = ifnull(TsSpecialPath.FIndex, 0) and FId < TsSpecialPath.FId))
);
