--Qs.User------------------------------------------------------------------
insert into TsToolItem set FId='6f995824-7a65-473b-92a7-326f82e5a210', FPageId='eaa06693-4d59-4d51-905c-1d845ca8903c', FCode='Copy',        	  FName='複製',                       FLabel=null,             FType='Button',      		   FAlign='right', FIndex=9, FWidth=0,  FDefaultEventHandler='EntityList.doCopy',				FIcon='quicksilver/image/16/Copy.png',      FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null;
insert into TsToolItem set FId='daf76c39-998c-47da-8600-166f9c371c8c', FPageId='97369772-ee08-48f5-b770-30dbf3f8fb3f', FCode='Copy',        FName='複製',     FLabel='', FType='Button', FAlign='right', FIndex=5, FWidth=0, FDefaultEventHandler='EntityForm.doCopy',		FIcon='quicksilver/image/16/Copy.png',    FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine='',   FVisibleCondition=null, FEnableCondition='${entity.FId} != null',                         FHandleType='JavaScript', FHandlePageId=null;

--Qs.Role-----------------------------------------------------------------------
insert into TsToolItem set FId='2cdba330-564b-4f79-b4fb-0eaae6c5b6f2', FPageId='5b45309a-053e-423c-9271-4ed6f30f32af', FCode='Copy',    		  FName='複製',                       FLabel='', FType='Button',      		 FAlign='right', FIndex=6, FWidth=0,   FDefaultEventHandler='EntityList.doCopy',			  FIcon='quicksilver/image/16/Copy.png',    FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine='',   FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null;
insert into TsToolItem set FId='1e20124b-662d-4e71-9c56-4ac01b884f36', FPageId='dc22de1a-d478-4bf2-88fc-e7c6364dc4f9', FCode='Copy', FName='複製', FLabel='', FType='Button', FAlign='right', FIndex=2, FWidth=0, FDefaultEventHandler='EntityForm.doCopy', FIcon='quicksilver/image/16/Copy.png', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine='',   FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null;

--Qs.Attachement

alter table TsAttachment add FDescription varchar(100);
insert into TsField set FId='fc489b09-5900-4906-bb93-61501c8494ff', FUnitId='00000000-0000-0000-0001-000000000019', FName='FDescription',			FTitle='說明',     			FType='InputBox-Text',    	FSize=100, 	FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FLocalTextField=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FValidation=null, FRelationCapacity=null;
java setFormFields('82880b60-242e-4271-8192-3ddd24868eb8', 'FName,FEntityId,FUploadTime,FUnitId,FSize,FUserId,FDescription');
java setListFields('78a566fb-50a2-4d14-9e59-35227457fa01', 'FName,FSize,FUploadTime,FUserId,FDescription');

insert into TsTextResource set FId='7631dd6c-19eb-443a-ae50-ef81385e361a', FCode='T.Qs.Misc.FileBatchUpload.Description',				FValue='說明';

--Qs.FieldGridLink-------------------------------------------------------------------

create table TsFieldGridLink
(
	FId uuid primary key,
	FName varchar(50),
	FIndex int,
	FFieldGridColumnId uuid,
	FEvent varchar(50)
);

insert into TsUnit set FId='f1ed815e-5848-4cd2-9b8c-c22b5e6ff636', FCode='Qs.FieldGridLink', FName='欄位網格鏈結', FIcon='quicksilver/image/unit/FieldGridLink.png', FEditId='541c707d-79dd-4dbb-85fc-1a214fd5fce4', FModuleId='00000000-0000-0000-0008-990000000020', FOpenMode='System', FIsTreeStructure=0, FMaxTreeLevel=null, FIsSlaveUnit=1, FMasterUnitId='7477c6b4-6db8-4969-ace9-659234e58974', FSupportWorkflow=0, FSupportUser=0, FSupportDepartment=0, FSupportEditType=0, FSupportAttachment=0, FSupportDataPrivilege=0, FSupportVersion=0, FSupportBusinessLog=0, FSupportNote=0, FSupportSort=1, FSupportPrivilegeField=0, FIsFullTextSearch=0, FSearchAttachment=0, FSupportEqualQuery=0, FUseSystemI18nTable=0, FExtraQueryResultLimit=0, FRecordCreateInfo=0, FRecordUpdateInfo=0, FRecordDeleteInfo=0, FViewPageConditionForList=null, FViewPageConditionForLink=null, FDataSource='default', FTable='TsFieldGridLink', FKeyField='FId', FKeyType='Uuid', FNameField='FName', FMasterField='FFieldGridColumnId', FHomeClassName='com.jeedsoft.quicksilver.unit.FieldGridLinkHome', FDaoClassName='com.jeedsoft.quicksilver.unit.dao.impl.FieldGridLinkDaoImpl', FServiceClassName='com.jeedsoft.quicksilver.unit.service.impl.FieldGridLinkServiceImpl', FActionClassName='com.jeedsoft.quicksilver.unit.action.impl.FieldGridLinkActionImpl', FWebServiceUniqueField=null, FUnitFilterSql='', FBusinessFilterSql='', FDescription='';

insert into TsField set FId='58586cab-a696-4407-b759-33a8ad4d0abb', FUnitId='f1ed815e-5848-4cd2-9b8c-c22b5e6ff636', FName='FEvent',             FTitle='事件',       FType='InputBox-Text',    FSize=50,   FVisible=1, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=0,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';
insert into TsField set FId='a5504046-f258-424a-b22b-af681095e574', FUnitId='f1ed815e-5848-4cd2-9b8c-c22b5e6ff636', FName='FFieldGridColumnId', FTitle='欄位網格列', FType='EntityBox',        FSize=null, FVisible=0, FFilterByRole=0, FRequired=1, FReadOnly=0, FQueryable=0, FDictionaryId=null, FEntityUnitId='7477c6b4-6db8-4969-ace9-659234e58974', FSupportLocalText=null, FSupportI18n=null, FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=null, FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData=null;
insert into TsField set FId='19fb79b2-4c25-442f-81bf-690734bb2591', FUnitId='f1ed815e-5848-4cd2-9b8c-c22b5e6ff636', FName='FId',                FTitle='ID',         FType='InputBox-Key',     FSize=null, FVisible=0, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=0, FDictionaryId=null, FEntityUnitId='f1ed815e-5848-4cd2-9b8c-c22b5e6ff636', FSupportLocalText=null, FSupportI18n=null, FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=null, FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData=null;
insert into TsField set FId='9e9c194d-0eaf-4d2e-ba03-b1e67580a352', FUnitId='f1ed815e-5848-4cd2-9b8c-c22b5e6ff636', FName='FIndex',             FTitle='順序',       FType='InputBox-Integer', FSize=null, FVisible=0, FFilterByRole=0, FRequired=0, FReadOnly=0, FQueryable=0, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=null, FSupportI18n=null, FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql=null, FSelectListVariableFilterSql=null, FSourceType='local', FJoinField=null, FSourceField=null, FSource=null, FColSpan=1, FRowSpan=1, FIsNewRow=null, FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData=null;
insert into TsField set FId='9d7c0069-ac35-492f-9751-8771df14a0c1', FUnitId='f1ed815e-5848-4cd2-9b8c-c22b5e6ff636', FName='FName',              FTitle='名稱',       FType='InputBox-Text',    FSize=50,   FVisible=1, FFilterByRole=0, FRequired=1, FReadOnly=0, FQueryable=1, FDictionaryId=null, FEntityUnitId=null,                                   FSupportLocalText=0,    FSupportI18n=1,    FLocalTextField=null, FRelationTable=null, FRelationCapacity=null, FRelationId=null, FSelectListConstantFilterSql='',   FSelectListVariableFilterSql='',   FSourceType='local', FJoinField=null, FSourceField=null, FSource='',   FColSpan=1, FRowSpan=1, FIsNewRow=0,    FListWidth=100, FListAlign='default', FScale=null, FLabelColor=null, FDefaultValue=null, FHint=null, FValidation=null, FWebServiceListQueryField=null, FWebServiceItemQueryField=null, FWebServiceCreateField=null, FCustomData='';

java setOrderFields('f1ed815e-5848-4cd2-9b8c-c22b5e6ff636', 'FIndex', '0');

insert into TsRelation set FId='07cbfe03-b252-4860-92dc-54ed749fb01c', FOppositeId='b49f9c4a-1120-4f12-b5f0-f7add04b738d', FName='欄位網格鏈結-欄位元網格列', FOppositeName='欄位網格列-欄位網格鏈結', FUnitId1='f1ed815e-5848-4cd2-9b8c-c22b5e6ff636', FUnitId2='7477c6b4-6db8-4969-ace9-659234e58974', FType='field', FTable='', FField1='FId', FField2='FFieldGridColumnId', FDeleteAction1='unset', FDeleteAction2='cancel', FPrivilegeTypeId1=null, FPrivilegeTypeId2=null;

insert into TsPage set FId='25bbf176-ae6c-4900-b0c0-d616b92f7587', FName='欄位網格鏈結主列表',   FTitle='欄位網格鏈結列表', FCode='Qs.FieldGridLink.List',       FPlatform='Computer', FType='EntityList', FIcon='quicksilver/image/unit/FieldGridLink.png',  FUrl='quicksilver/page/template/EntityList.jsp', FActionMethodName='Qs.FieldGridLink.prepareList', FLoadHandler=null, FRelationId=null, FUnitId='f1ed815e-5848-4cd2-9b8c-c22b5e6ff636', FMasterUnitId=null,                                   FIsSlavePage=0, FIndex=null, FDialogWidth=null, FDialogHeight=null, FDialogMaximized=null, FQueryFormAutoQuery=1, FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription=null;
insert into TsPage set FId='d588f731-14f1-4fe8-9f4c-608127675c17', FName='欄位網格鏈結選擇列表', FTitle='欄位網格鏈結列表', FCode='Qs.FieldGridLink.SelectList', FPlatform='Computer', FType='EntityList', FIcon='quicksilver/image/unit/FieldGridLink.png',  FUrl='quicksilver/page/template/EntityList.jsp', FActionMethodName='Qs.FieldGridLink.prepareList', FLoadHandler=null, FRelationId=null, FUnitId='f1ed815e-5848-4cd2-9b8c-c22b5e6ff636', FMasterUnitId=null,                                   FIsSlavePage=0, FIndex=null, FDialogWidth=null, FDialogHeight=null, FDialogMaximized=null, FQueryFormAutoQuery=1, FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription=null;
insert into TsPage set FId='eee7b39d-851c-4092-9500-3ef144596b65', FName='欄位網格鏈結排序',     FTitle='排序',           FCode='Qs.FieldGridLink.Sort',       FPlatform='Computer', FType='Sort',       FIcon='quicksilver/image/unit/FieldGridLink.png',  FUrl='quicksilver/page/template/Sorter.jsp',     FActionMethodName='Qs.FieldGridLink.prepareSort', FLoadHandler=null, FRelationId=null, FUnitId='f1ed815e-5848-4cd2-9b8c-c22b5e6ff636', FMasterUnitId=null,                                   FIsSlavePage=0, FIndex=null, FDialogWidth=null, FDialogHeight=null, FDialogMaximized=null, FQueryFormAutoQuery=1, FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription=null;
insert into TsPage set FId='34485c6b-f231-4c11-ad59-b4b678738c30', FName='欄位網格鏈結表單',     FTitle='表單',           FCode='Qs.FieldGridLink.Form',       FPlatform='Computer', FType='EntityForm', FIcon='quicksilver/image/unit/Form.png', FUrl='quicksilver/page/template/EntityForm.jsp', FActionMethodName='Qs.FieldGridLink.prepareForm', FLoadHandler=null, FRelationId=null, FUnitId='f1ed815e-5848-4cd2-9b8c-c22b5e6ff636', FMasterUnitId='f1ed815e-5848-4cd2-9b8c-c22b5e6ff636', FIsSlavePage=1, FIndex=1,    FDialogWidth=750,  FDialogHeight=500,  FDialogMaximized=null, FQueryFormAutoQuery=1, FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription=null;

--欄位網格鏈結主列表
insert into TsToolItem set FId='72504efc-2af1-4b43-b8a0-0f748a9b64b6', FPageId='25bbf176-ae6c-4900-b0c0-d616b92f7587', FCode='Add',     FName='新增', FHint='新增一筆記錄',                                         FLabel=null, FType='Button',      FAlign='right', FIndex=1, FWidth=0, FIcon='quicksilver/image/16/Add.png',     FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doAdd';
insert into TsToolItem set FId='b85d6691-1b0c-49e3-8879-3559591d10f2', FPageId='25bbf176-ae6c-4900-b0c0-d616b92f7587', FCode='Open',    FName='打開', FHint='打開當前選中的記錄。如果選中了多筆，第一筆將被打開。', FLabel=null, FType='Button',      FAlign='right', FIndex=2, FWidth=0, FIcon='quicksilver/image/16/Open.png',    FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doOpen';
insert into TsToolItem set FId='89e58945-34fe-483a-b2d4-eaa0208ddaee', FPageId='25bbf176-ae6c-4900-b0c0-d616b92f7587', FCode='Delete',  FName='刪除', FHint='刪除當前選中的記錄',                                   FLabel=null, FType='Button',      FAlign='right', FIndex=3, FWidth=0, FIcon='quicksilver/image/16/Delete.png',  FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doDelete';
insert into TsToolItem set FId='fd4d9749-2974-40e5-aa94-3b793504f72d', FPageId='25bbf176-ae6c-4900-b0c0-d616b92f7587', FCode='Refresh', FName='刷新', FHint='刷新列表內容',                                         FLabel=null, FType='Button',      FAlign='right', FIndex=4, FWidth=0, FIcon='quicksilver/image/16/Refresh.png', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doRefresh';
insert into TsToolItem set FId='de2dcecb-6464-4fdd-9e92-1a2088d607a6', FPageId='25bbf176-ae6c-4900-b0c0-d616b92f7587', FCode='Other',   FName=null,   FHint=null,                                                   FLabel=null, FType='ComboButton', FAlign='right', FIndex=5, FWidth=0, FIcon='quicksilver/image/16/Other.png',   FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource='SubItemTable', FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='None',       FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler=null;
insert into TsToolSubItem set FId='2a349343-e2f8-4285-94e7-4cab9e72bc7a', FToolItemId='de2dcecb-6464-4fdd-9e92-1a2088d607a6', FCode='Sort',        FName='排序',       FExpandMode='None', FIndex=1, FIcon='quicksilver/image/16/Sort.png',   FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FEventHandler='EntityList.doSort';

--欄位網格鏈結選擇列表
insert into TsToolItem set FId='20105f04-4d31-4cae-b368-4174f1380a0c', FPageId='d588f731-14f1-4fe8-9f4c-608127675c17', FCode='ConfirmSelection', FName='確定', FHint=null,                                                   FLabel=null, FType='Button', FAlign='right', FIndex=1, FWidth=0, FIcon='quicksilver/image/16/Ok.png',   FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doSelectListConfirm';
insert into TsToolItem set FId='61e661e7-09fc-42f4-9ec6-a704914645bf', FPageId='d588f731-14f1-4fe8-9f4c-608127675c17', FCode='Add',              FName='新增', FHint='新增一筆記錄',                                         FLabel=null, FType='Button', FAlign='right', FIndex=2, FWidth=0, FIcon='quicksilver/image/16/Add.png',  FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doAdd';
insert into TsToolItem set FId='347f024f-5165-43be-8a37-2586754273f1', FPageId='d588f731-14f1-4fe8-9f4c-608127675c17', FCode='Open',             FName='打開', FHint='打開當前選中的記錄。如果選中了多筆，第一筆將被打開。', FLabel=null, FType='Button', FAlign='right', FIndex=3, FWidth=0, FIcon='quicksilver/image/16/Open.png', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doOpen';

--欄位網格鏈結排序
insert into TsToolItem set FId='24c64508-be4f-4ec2-a982-66a21968bafc', FPageId='eee7b39d-851c-4092-9500-3ef144596b65', FCode='MoveUp',     FName='上升', FHint=null, FLabel=null, FType='Button', FAlign='left',  FIndex=1, FWidth=0, FIcon='quicksilver/image/16/MoveUp.png',     FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='Sorter.doMoveUp';
insert into TsToolItem set FId='2dd056b7-5035-4f1d-852e-770750484084', FPageId='eee7b39d-851c-4092-9500-3ef144596b65', FCode='MoveDown',   FName='下降', FHint=null, FLabel=null, FType='Button', FAlign='left',  FIndex=2, FWidth=0, FIcon='quicksilver/image/16/MoveDown.png',   FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='Sorter.doMoveDown';
insert into TsToolItem set FId='4341583c-daff-45aa-8d76-b3543433b2bb', FPageId='eee7b39d-851c-4092-9500-3ef144596b65', FCode='MoveTop',    FName='置頂', FHint=null, FLabel=null, FType='Button', FAlign='left',  FIndex=3, FWidth=0, FIcon='quicksilver/image/16/MoveTop.png',    FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='Sorter.doMoveTop';
insert into TsToolItem set FId='c3e4a8f7-0dbe-4d7c-bc98-0b0f908557cc', FPageId='eee7b39d-851c-4092-9500-3ef144596b65', FCode='MoveBottom', FName='置底', FHint=null, FLabel=null, FType='Button', FAlign='left',  FIndex=4, FWidth=0, FIcon='quicksilver/image/16/MoveBottom.png', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='Sorter.doMoveBottom';
insert into TsToolItem set FId='64807060-132f-4a06-871b-c6ba72fd90c9', FPageId='eee7b39d-851c-4092-9500-3ef144596b65', FCode='Save',       FName='保存', FHint=null, FLabel=null, FType='Button', FAlign='right', FIndex=1, FWidth=0, FIcon='quicksilver/image/16/Save.png',       FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null, FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='Sorter.doSave';

--欄位網格鏈結表單
insert into TsToolItem set FId='a10a9f3d-79ef-479e-9052-0678985ab82d', FPageId='34485c6b-f231-4c11-ad59-b4b678738c30', FCode='Save',  FName='保存', FHint=null, FLabel=null, FType='Button',      FAlign='right', FIndex=1, FWidth=0, FIcon='quicksilver/image/16/Save.png',  FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityForm.doSave';

insert into TsForm set FDefault=1, FEditableCondition=null, FGroupMode='Double', FId='2fc5d294-1168-4c91-b86d-ebeea3864118', FIndex=1, FName='默認', FPageId=null, FUnitId='f1ed815e-5848-4cd2-9b8c-c22b5e6ff636';
java setFormFields('2fc5d294-1168-4c91-b86d-ebeea3864118', '基本資訊', '4927a356-7aed-405d-8e91-ef4e23bee91d', null, 'FName,FEvent');

insert into TsList set FDefault=1, FId='0c1ed9ae-7969-48db-ac77-775fdfa02807', FIndex=null, FMultiPage=1, FName='欄位網格鏈結列表',     FPageId=null,                                   FUnitId='f1ed815e-5848-4cd2-9b8c-c22b5e6ff636';
insert into TsList set FDefault=0, FId='43771d50-b5ef-40f0-9c56-ee298fe90eda', FIndex=null, FMultiPage=1, FName='欄位網格鏈結選擇列表', FPageId='d588f731-14f1-4fe8-9f4c-608127675c17', FUnitId='f1ed815e-5848-4cd2-9b8c-c22b5e6ff636';
insert into TsList set FDefault=0, FId='ccc4384e-7835-4abf-b500-e6acf224b0a5', FIndex=null, FMultiPage=1, FName='欄位網格鏈結首頁列表', FPageId='9b796431-f132-49d1-b306-5d1d618f9c1b', FUnitId='f1ed815e-5848-4cd2-9b8c-c22b5e6ff636';
java setListFields('0c1ed9ae-7969-48db-ac77-775fdfa02807', 'FName,FEvent');
java setListFields('43771d50-b5ef-40f0-9c56-ee298fe90eda', 'FName,FEvent');
java setListFields('ccc4384e-7835-4abf-b500-e6acf224b0a5', 'FName,FEvent');

insert into TsSlaveUnitPrivilege set FId='2b8e9b6e-0fe3-4f52-9262-2e456f683d7f', FUnitId='f1ed815e-5848-4cd2-9b8c-c22b5e6ff636', FCreatePrivilegeTypeId='00000000-0000-0000-1005-000000000003', FReadPrivilegeTypeId='00000000-0000-0000-1005-000000000003', FReadUserFieldName='', FUpdatePrivilegeTypeId='00000000-0000-0000-1005-000000000003', FUpdateUserFieldName='', FDeletePrivilegeTypeId='00000000-0000-0000-1005-000000000003', FDeleteUserFieldName='';

insert into TsDictionaryItem set FDictionaryId='5317d1e1-5785-4ffd-b2a1-4fd5d0bbd99c', FEnabled=1, FId='82b0455a-3487-4d3d-b1c3-f14f52046da1', FIndex=7, FParentValue=null, FText='鏈結',     FValue='Link';

insert into TsPage set FId='ec8043ec-6064-44ab-9b48-331a39a290b8', FName='欄位元網格列欄位網格鏈結列表', FTitle='網格鏈結',     FCode='Qs.FieldGridColumn.FieldGridLinkList', FPlatform='Computer', FType='EntityList', FIcon='quicksilver/image/unit/FieldGridLink.png',             FUrl='quicksilver/page/template/EntityList.jsp', FActionMethodName='Qs.FieldGridLink.prepareList',        FLoadHandler=null, FRelationId='b49f9c4a-1120-4f12-b5f0-f7add04b738d', FUnitId='f1ed815e-5848-4cd2-9b8c-c22b5e6ff636', FMasterUnitId='7477c6b4-6db8-4969-ace9-659234e58974', FIsSlavePage=1, FIndex=2,    FDialogWidth=null, FDialogHeight=null, FDialogMaximized=null, FQueryFormAutoQuery=1, FHasViewFrame=null, FQueryOnLoad=null, FQuerySchemaId=null, FCreateQuerySchemaBox=null, FCreateKeywordBox=null, FToolItemInitArguments=null, FVisible=1, FVisibleCondition=null, FDescription=null;
insert into TsToolItem set FId='32ee6a8d-6e21-452b-903e-620684a926ab', FPageId='ec8043ec-6064-44ab-9b48-331a39a290b8', FCode='Add',     FName='新增', FHint='新增一筆記錄',                                         FLabel=null, FType='Button',      FAlign='right', FIndex=1, FWidth=0, FIcon='quicksilver/image/16/Add.png',     FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doAdd';
insert into TsToolItem set FId='1eec842d-bd8e-4f43-b994-d5ff54e13e56', FPageId='ec8043ec-6064-44ab-9b48-331a39a290b8', FCode='Open',    FName='打開', FHint='打開當前選中的記錄。如果選中了多筆，第一筆將被打開。', FLabel=null, FType='Button',      FAlign='right', FIndex=2, FWidth=0, FIcon='quicksilver/image/16/Open.png',    FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doOpen';
insert into TsToolItem set FId='c6713f91-8445-41f3-b33a-60e2e4f634a3', FPageId='ec8043ec-6064-44ab-9b48-331a39a290b8', FCode='Delete',  FName='刪除', FHint='刪除當前選中的記錄',                                   FLabel=null, FType='Button',      FAlign='right', FIndex=3, FWidth=0, FIcon='quicksilver/image/16/Delete.png',  FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doDelete';
insert into TsToolItem set FId='013190db-8cd5-41a1-9b80-08edbb235fe6', FPageId='ec8043ec-6064-44ab-9b48-331a39a290b8', FCode='Refresh', FName='刷新', FHint='刷新列表內容',                                         FLabel=null, FType='Button',      FAlign='right', FIndex=4, FWidth=0, FIcon='quicksilver/image/16/Refresh.png', FScale=null, FEntityUnitId=null, FDefaultValue=null, FSubItemSource=null,           FDictionaryId=null, FSubItemRoutine=null, FVisibleCondition=null, FEnableCondition=null, FHandleType='JavaScript', FHandlePageId=null, FConfirmMessage=null, FDefaultEventHandler='EntityList.doRefresh';
