Jui.$define("Jui.graph.Graph",Jui.basic.Control);
Jui.graph.Graph.getHtml=function(e,g,d){e=e||{};
var b=Jui.cast.toBool(e.isDesignMode,false);
var f=b?"Jui.Graph.LegendTitleDesign":"Jui.Graph.LegendTitleDisplay";
var a=Jui.i18n.getText(f);
var c="<div class=JuiGraph"+Jui.$p({id:g,style:e.style})+" unselectable=on onselectstart='return false'><div class=JuiGraphLegend><div class=JuiGraphLegendHead>"+Jui.$h(a)+"</div><div class=JuiGraphLegendBody></div></div><div class=JuiGraphContent><canvas class=JuiGraphGridCanvas></canvas><canvas class=JuiGraphLineCanvas></canvas><canvas class=JuiGraphTempCanvas></canvas><div class=JuiGraphNodePanel></div><div class=JuiGraphMask></div></div></div>";
return c;
};
Jui.graph.Graph.initialize=function(c,b,a){b=b||{};
a=a||this;
var d=this.superClass.initialize(c,b,a);
b=b||{};
d._isDesignMode=Jui.cast.toBool(b.isDesignMode,false);
d._showLegend=Jui.cast.toBool(b.showLegend,true);
d._scrollable=Jui.cast.toBool(b.scrollable,true);
d._gridVisible=Jui.cast.toBool(b.gridVisible,true);
d._gridSize=b.gridSize||Jui.theme["Graph.GridSize"];
d._useGridUnitForNode=Jui.cast.toBool(b.useGridUnitForNode,false);
d._showNodeText=Jui.cast.toBool(b.showNodeText,true);
d._maxNodeTextWidth=b.maxNodeTextWidth||100;
d._nodeSelectable=d._isDesignMode||Jui.cast.toBool(b.nodeSelectable,false);
d._lineSelectable=d._isDesignMode||Jui.cast.toBool(b.lineSelectable,false);
d._highlightCurrentNode=Jui.cast.toBool(b.highlightCurrentNode,true);
d._nodeTextClass=b.nodeTextClass;
d._nodeTextStyle=b.nodeTextStyle;
d._lineTextClass=b.lineTextClass;
d._lineTextStyle=b.lineTextStyle;
d._autoCenter=!d._isDesignMode&&Jui.cast.toBool(b.autoCenter,true);
d._autoShrinkLine=Jui.cast.toBool(b.autoShrinkLine,false);
d._lineMargin=b.lineMargin||0;
d._nodes=[];
d._nodeMap={};
d._lines=[];
d._lineMap={};
d._legend=c.children[0];
d._legendBody=d._legend.lastChild;
d._content=c.children[1];
d._gridCanvas=d._content.children[0];
d._lineCanvas=d._content.children[1];
d._tempCanvas=d._content.children[2];
d._nodePanel=d._content.children[3];
d._mask=d._content.children[4];
d._mask.onclick=a.doMaskClick;
d._mask.onmousemove=a.doMaskMouseMove;
d.onlinetextclick=b.onlinetextclick;
d.onnodeadd=b.onnodeadd;
d.onnodeclick=b.onnodeclick;
d.onnodedoubleclick=b.onnodedoubleclick;
d.onnodetextclick=b.onnodetextclick;
c.onkeydown=a.doKeyDown;
d._content.onclick=a.doContentClick;
d._lineCanvas.onclick=d._lineSelectable?a.doLineCanvasClick:null;
if(d._isDesignMode){d._legend.setAttribute("design",true);
}if(!d._scrollable){d._content.style.overflow="hidden";
}d.setMetaData(b.nodeTypes,b.lineTypes,b.legendItems);
Jui.dom.tagAttribute(c,"HasLegend",d._showLegend);
Jui.event.attach(window,"resize",function(){d.$resize();
});
return d;
};
Jui.graph.Graph.prototype.clear=function(a){this.load({nodes:[],lines:[]});
};
Jui.graph.Graph.prototype.setMetaData=function(a,c,b){this._initializeNodeTypes(a,this.$class.$DEFAULT_NODE_TYPES);
this._initializeLineTypes(c,this.$class.$DEFAULT_LINE_TYPES);
if(this._showLegend){this._initializeLegend(b,this.$class.$DEFAULT_LEGENDS);
}};
Jui.graph.Graph.prototype.load=function(r){var m=this;
if(m._autoCenter){var b=m._content.offsetWidth;
var q=m._content.offsetHeight;
var c=2147483647;
var k=-2147483647;
var p=2147483647;
var d=-2147483647;
var o=[];
for(var h=0,a=r.nodes||[];
h<a.length;
++h){o.push(a[h]);
}for(var h=0,s=r.lines||[];
h<s.length;
++h){for(var g=0,n=s[h].routes||[];
g<n.length;
++g){o.push(n[g]);
}}for(var h=0;
h<o.length;
++h){c=Math.min(c,o[h].x);
k=Math.max(k,o[h].x);
p=Math.min(p,o[h].y);
d=Math.max(d,o[h].y);
}var f=40;
var l=k-c>b-2*f?0:(b-(k-c))/2-c;
var e=d-p>q-2*f?0:(q-(d-p))*0.35-p;
for(var h=0;
h<o.length;
++h){o[h].x+=l;
o[h].y+=e;
}}m._currentNode=null;
m._currentLine=null;
m._setNodes(r.nodes);
m._setLines(r.lines);
m._refreshGrid();
};
Jui.graph.Graph.prototype.addLine=function(a){var b=Jui.dom.insertHtml(this._nodePanel,"BeforeEnd",this._getLineHtml(a));
this._initializeLine(a,b);
this._lines.push(a);
this._refreshLines();
};
Jui.graph.Graph.prototype.getJson=function(){var b=[];
for(var c=0;
c<this._nodes.length;
++c){b.push(this._getNodeJson(this._nodes[c]));
}var a=[];
for(var c=0;
c<this._lines.length;
++c){a.push(this._getLineJson(this._lines[c]));
}return{nodes:b,lines:a};
};
Jui.graph.Graph.prototype.getCurrentNode=function(){var a=this._currentNode;
return a==null?null:this._getNodeJson(a);
};
Jui.graph.Graph.prototype.getCurrentLine=function(){var a=this._currentLine;
return a==null?null:this._getLineJson(a);
};
Jui.graph.Graph.prototype.updateNode=function(f,e,b,d){var c=this._nodeMap[f];
if(c!=null){c.text=e;
c.data=d;
c.icon=b;
}var a=this._nodeTypeMap[c.type];
if(a.updateFunc==null){Jui.dom.setInnerText(c.textElement,e);
c.element.style.backgroundImage=Jui.string.isEmpty(b)?"":"url("+b+")";
}else{a.updateFunc(f,c.element,e,b,d);
}this._refreshNodePosition(c);
};
Jui.graph.Graph.prototype.deleteCurrentElement=function(){var d=this;
if(d._currentLine!=null){for(var b=0;
b<d._lines.length;
++b){if(d._lines[b]==d._currentLine){d._lines.splice(b,1);
}}d._currentLine==null;
d._refreshLines();
}if(d._currentNode!=null){var c=d._currentNode;
for(var b=d._lines.length-1;
b>=0;
--b){var a=d._lines[b];
if(d._nodeMap[a.from]==c||d._nodeMap[a.to]==c){d._lines.splice(b,1);
}}for(var b=0;
b<d._nodes.length;
++b){if(d._nodes[b]==d._currentNode){d._nodes.splice(b,1);
}}delete d._nodeMap[c.id];
d._nodePanel.removeChild(c.textElement);
d._nodePanel.removeChild(c.element);
d._currentNode=null;
d._refreshLines();
}};
Jui.graph.Graph.doKeyDown=function(){if(event.keyCode==46){Jui.$owner().deleteCurrentElement();
}};
Jui.graph.Graph.doContentClick=function(){var a=Jui.$owner();
if(event.srcElement==a._content){a._setCurrentNode(null);
a._setCurrentLine(null);
}};
Jui.graph.Graph.doNodeClick=function(){var c=Jui.$owner();
var b=this._node;
var a={node:{id:b.id,text:b.text,data:b.data}};
c.fireEvent("onnodeclick",a);
};
Jui.graph.Graph.doNodeDoubleClick=function(){var c=Jui.$owner();
var b=this._node;
var a={node:{id:b.id,text:b.text,data:b.data}};
c.fireEvent("onnodedoubleclick",a);
};
Jui.graph.Graph.doNodeMouseDown=function(){var b=this;
var a=Jui.$owner(b);
if(a._nodeSelectable){a._setCurrentNode(b._node);
}};
Jui.graph.Graph.doNodeDragStart=function(){var b=Jui.$owner();
if(b._isDesignMode){var a=this;
b._nodeDragInfo={node:a._node,eventPoint:{x:event.clientX,y:event.clientY},nodeCenter:{x:a._node.x,y:a._node.y},nodePosition:{x:a.offsetLeft,y:a.offsetTop},textPosition:{x:a._node.textElement.offsetLeft,y:a._node.textElement.offsetTop}};
b._content.ondragover=Jui.graph.Graph.doNodeDragOver;
if(event.dataTransfer.setDragImage){event.dataTransfer.setData("custom","jui-graph-node");
}}};
Jui.graph.Graph.doNodeDragEnd=function(){var a=Jui.$owner();
a._content.ondragover=null;
a._dragPoint=null;
};
Jui.graph.Graph.doNodeDragOver=function(){var f=Jui.$owner();
var h={x:event.clientX,y:event.clientY};
Jui.event.preventDefault();
if(!Jui.math.pointsEqual(h,f._dragPoint)){var a=f._nodeDragInfo;
var c=a.node;
var b=Math.max(0,a.nodePosition.x+h.x-a.eventPoint.x);
var g=Math.max(0,a.nodePosition.y+h.y-a.eventPoint.y);
if(!f._scrollable){b=Math.min(b,f._nodePanel.clientWidth-c.element.offsetWidth);
g=Math.min(g,f._nodePanel.clientHeight-c.element.offsetHeight);
}if(f._useGridUnitForNode){var e=Jui.dom.getRelativePoint(f._nodePanel,h.x,h.y);
var d={x:Math.floor(e.x/f._gridSize),y:Math.floor(e.y/f._gridSize)};
if(Jui.math.pointsEqual(d,f._gridDragPoint)){return;
}f._gridDragPoint=d;
b=d.x*f._gridSize;
g=d.y*f._gridSize;
}var k=b-a.nodePosition.x;
var j=g-a.nodePosition.y;
c.element.style.left=b+"px";
c.element.style.top=g+"px";
c.textElement.style.left=a.textPosition.x+k+"px";
c.textElement.style.top=a.textPosition.y+j+"px";
c.x=a.nodeCenter.x+k;
c.y=a.nodeCenter.y+j;
f._dragPoint=h;
f._refreshLines();
}};
Jui.graph.Graph.prototype.$stopDrag=function(){var a=this;
a.element.onmousemove=null;
a.element.style.cursor="default";
a._nodeDragInfo=null;
};
Jui.graph.Graph.doLegendRowClick=function(){var a=Jui.$owner();
a._setCurrentLegend(this._json);
a._setCurrentNode(null);
a._setCurrentLine(null);
};
Jui.graph.Graph.doLineCanvasClick=function(){var g=Jui.$owner();
var l=null;
var a=9999;
var b=5.1;
var h=g.$toCanvasPoint(event.clientX,event.clientY);
for(var e=0;
e<g._lines.length;
++e){var k=g._getLinePoints(g._lines[e]);
for(var c=1;
c<k.length;
++c){var f=Jui.math.getPointLineDistance(h,k[c-1],k[c]);
if(f<b&&f<a){a=f;
l=g._lines[e];
}}}g._setCurrentNode(null);
g._setCurrentLine(l);
};
Jui.graph.Graph.doMaskClick=function(){if(this.style.cursor!="move"){return;
}var d=Jui.$owner();
var g=d._currentLegend;
if(g.category=="Node"){d._hideMask();
var h=d.$toCanvasPoint(event.clientX,event.clientY);
var b=Jui.graph.Graph._generateNextId(d._nodeMap,"NODE-");
var j=Jui.graph.Graph._generateNextText(d._nodes,g.text);
var c={id:b,text:j,type:g.type,x:h.x,y:h.y};
Jui.dom.insertHtml(d._nodePanel,"BeforeEnd",d._getNodeHtml(c));
d._initializeNode(c,d._nodePanel.lastChild.previousSibling);
d.fireEvent("onnodeadd",{node:c});
}else{if(g.category=="Line"){var c=d._nodeFromPoint(event);
var a=d._tempCanvas.style.display!="block";
var f=a?c:d._newLineFromNode;
var e=a?null:c;
if(a){d._newLineFromNode=c;
d._tempCanvas.style.display="block";
d._mask.style.cursor=d.$canAccept(f,e,null,g.type,a)?"move":"not-allowed";
}else{d._hideMask();
d._tempCanvas.style.display="none";
d.addLine({type:g.type,from:d._newLineFromNode.id,to:c.id});
}}}};
Jui.graph.Graph.doMaskMouseMove=function(){var e=Jui.$owner();
var d=e._nodeFromPoint(event);
var j=e._currentLegend;
if(j.category=="Node"){e._mask.style.cursor=d==null?"move":"not-allowed";
}else{if(j.category=="Line"){var a=e._tempCanvas.style.display!="block";
var g=a?d:e._newLineFromNode;
var h=a?null:d;
e._mask.style.cursor=e.$canAccept(g,h,null,j.type,a)?"move":"not-allowed";
if(!a){var k=e.$toCanvasPoint(event.clientX,event.clientY);
var f=e._newLineFromNode;
var l=[{x:f.x,y:f.y},k];
var c=e._tempCanvas;
var b=c.getContext("2d");
e._setCanvasSize(c,Math.max(l[0].x,l[1].x,1),Math.max(l[0].y,l[1].y,1));
b.clearRect(0,0,c.width,c.height);
e._drawLine(b,j.type,l);
}}}};
Jui.graph.Graph.doNodeTextClick=function(){var a=Jui.$owner();
a.fireEvent("onnodetextclick",{node:a._getNodeJson(this._node)});
};
Jui.graph.Graph.doLineTextClick=function(){var a=Jui.$owner();
a.fireEvent("onlinetextclick",{line:a._getLineJson(this._line)});
};
Jui.graph.Graph.$DEFAULT_NODE_TYPES=[{name:"NormalNode",width:31,height:31,virtual:false,className:"JuiGraphNormalNode"},{name:"VirtualNode",width:31,height:31,virtual:true,className:"JuiGraphVirtualNode"}];
Jui.graph.Graph.$DEFAULT_LINE_TYPES=[{name:"Line",width:1,color:"#0000FF"},{name:"Arrow",width:1,arrow:"single"},{name:"DoubleArrow",width:1,arrow:"double"}];
Jui.graph.Graph.$DEFAULT_LEGENDS=[{type:"Cursor",text:Jui.i18n.getText("Jui.Graph.LegendSelect"),className:"JuiGraphLegendSelect"},{type:"Line",text:Jui.i18n.getText("Jui.Graph.LegendLine"),className:"JuiGraphLegendLine"},{type:"Arrow",text:Jui.i18n.getText("Jui.Graph.LegendArrow"),className:"JuiGraphLegendArrow"},{type:"DoubleArrow",text:Jui.i18n.getText("Jui.Graph.LegendDoubleArrow"),className:"JuiGraphLegendDoubleArrow"},{type:"NormalNode",text:Jui.i18n.getText("Jui.Graph.LegendNormalNode"),className:"JuiGraphLegendNormalNode"},{type:"VirtualNode",text:Jui.i18n.getText("Jui.Graph.LegendVirtualNode"),className:"JuiGraphLegendVirtualNode"}];
Jui.graph.Graph._generateNextId=function(c,b){for(var a=1;
;
++a){var d=b+a;
if(c[d]==null){return d;
}}};
Jui.graph.Graph._generateNextText=function(a,c){var e=Jui.array.toSet(a,"text");
for(var b=1;
;
++b){var d=c+b;
if(e[d]==null){return d;
}}};
Jui.graph.Graph.prototype.$resize=function(){this._refreshGrid();
this._refreshLines();
};
Jui.graph.Graph.prototype.$canAccept=function(d,c,b,e,a){return this.$isValidLineTarget(a?d:c,e,a);
};
Jui.graph.Graph.prototype.$isValidLineTarget=function(b,d,a){if(b==null||d==null){return false;
}var c=this._lineTypeMap[d];
var e=a?c.startNodeTypeSet:c.endNodeTypeSet;
return e==null||d in e;
};
Jui.graph.Graph.prototype.$toCanvasPoint=function(e,c){var b=this._content.getBoundingClientRect();
var a=e-b.left+this._content.scrollLeft;
var d=c-b.top+this._content.scrollTop;
return{x:a,y:d};
};
Jui.graph.Graph.prototype._initializeNodeTypes=function(a,e){var d=this;
d._nodeTypeMap=d._getTypeMap(a,e);
for(var b in d._nodeTypeMap){var c=d._nodeTypeMap[b];
c.width=c.width=="cell"?d._gridSize-1:c.width;
c.height=c.height=="cell"?d._gridSize-1:c.height;
}};
Jui.graph.Graph.prototype._initializeLineTypes=function(g,f){var e=this;
e._lineTypeMap=e._getTypeMap(g,f);
for(var a in e._lineTypeMap){var b=e._lineTypeMap[a];
var c=b.startNodeTypes||b.nodeTypes;
var d=b.endNodeTypes||b.nodeTypes;
b.startNodeTypeSet=c==null?null:Jui.array.toSet(c);
b.endNodeTypeSet=d==null?null:Jui.array.toSet(d);
}};
Jui.graph.Graph.prototype._getTypeMap=function(a,f){var e=Jui.array.toMap(Jui.util.clone(f),"name");
if(a==null){return e;
}var d={};
for(var b=0;
b<a.length;
++b){var c=a[b];
if(typeof(c)=="string"){c=e[c];
if(c==null){Jui.util.alertAndThrow("unsupported default node/line: "+a[b]);
}}d[c.name]=Jui.util.clone(c);
}return d;
};
Jui.graph.Graph.prototype._getCanvasSize=function(b,p){var o={width:0,height:0};
for(var g=0;
g<b.length;
++g){var k=b[g].element;
var n=b[g].textElement;
o.width=Math.max(o.width,k.offsetLeft+k.offsetWidth+6,n.offsetLeft+n.offsetWidth+6);
o.height=Math.max(o.height,n.offsetTop+n.offsetHeight);
}for(var g=0;
g<p.length;
++g){for(var f=0,m=p[g].routes||[];
f<m.length;
++f){o.width=Math.max(o.width,m[f].x+6);
o.height=Math.max(o.height,m[f].y+6);
}}var d=this._content.offsetWidth;
var a=this._content.offsetHeight;
var c=Jui.browser.getScrollBarWidth();
var h=o.width>d||o.width>d-c&&o.height>a;
var l=o.height>a||o.height>a-c&&o.width>d;
o.width=Math.max(o.width,l?d-c:d);
o.height=Math.max(o.height,h?a-c:a);
return o;
};
Jui.graph.Graph.prototype._initializeLegend=function(e,h){var l=this;
var k=h;
if(e!=null){k=[];
var c=Jui.array.toMap(h,"type");
var o=false;
for(var g=0;
g<e.length;
++g){var n=e[g];
if(typeof(n)=="string"){n=c[n];
if(n==null){Jui.util.alertAndThrow("unsupported default legend item: "+k[g]);
}}if(n.type=="Cursor"){o=true;
}k.push(n);
}if(!o&&l._isDesignMode){k.unshift(h[0]);
}}var f=[];
f.push("<table class=JuiGraphLegendTable>");
for(var g=0;
g<k.length;
++g){var n=k[g];
if(n.type!="Cursor"&&l._nodeTypeMap[n.type]==null&&l._lineTypeMap[n.type]==null){Jui.util.alertAndThrow("legend item is neither node nor line: "+n.type);
}var j="JuiGraphLegendIcon"+(Jui.string.isEmpty(n.className)?"":" "+n.className);
var b=Jui.string.isEmpty(n.icon)?"":"background-image:url("+n.icon+")'";
f.push("<tr class=JuiGraphLegendItem>");
f.push("<td class=JuiGraphLegendIconCell valign=middle>");
f.push("<div class='"+j+"' style='"+b+"'></div>");
f.push("</td>");
f.push("<td class=JuiGraphLegendTextCell>"+Jui.$h(n.text||"")+"</td>");
f.push("</tr>");
}f.push("</table>");
l._legendBody.innerHTML=f.join("");
if(l._isDesignMode){for(var g=0,a=l._legendBody.firstChild.rows;
g<a.length;
++g){var d=a[g];
var m=Jui.util.clone(k[g]);
d.onclick=Jui.graph.Graph.doLegendRowClick;
d._json=m;
m.element=d;
m.category=m.type in l._nodeTypeMap?"Node":(m.type in l._lineTypeMap?"Line":"Cursor");
if(m.type=="Cursor"){l._cursorLegend=m;
l._setCurrentLegend(m);
}}}};
Jui.graph.Graph.prototype._extend=function(g,e,c){if(!this._autoShrinkLine&&this._lineMargion==0){return{x:g.x,y:g.y};
}var b=c+this._lineMargin;
var f=Math.sqrt(Math.pow(g.x-e.x,2)+Math.pow(g.y-e.y,2));
if(f<b){return{x:g.x,y:g.y};
}var a=g.x+(e.x-g.x)*b/f;
var h=g.y+(e.y-g.y)*b/f;
return{x:a,y:h};
};
Jui.graph.Graph.prototype._genAngle=function(b,a){if(b.x==a.x&&b.y==a.y){return 0;
}else{if(b.x==a.x){return a.y>b.y?Math.PI/2:-Math.PI/2;
}else{if(b.y==a.y){return a.x>b.x?0:Math.PI;
}else{return Math.atan((a.y-b.y)/(a.x-b.x))+(a.x>b.x?0:Math.PI);
}}}};
Jui.graph.Graph.prototype._drawArrow=function(d,c,h){var g=this._genAngle(h,c);
var f=g-Jui.theme["Graph.ArrowAngle"]/2;
var b=g+Jui.theme["Graph.ArrowAngle"]/2;
var e=h.x+Jui.theme["Graph.ArrowSize"]*Math.cos(f);
var k=h.y+Jui.theme["Graph.ArrowSize"]*Math.sin(f);
var a=h.x+Jui.theme["Graph.ArrowSize"]*Math.cos(b);
var j=h.y+Jui.theme["Graph.ArrowSize"]*Math.sin(b);
d.beginPath();
d.moveTo(e,k);
d.lineTo(h.x,h.y);
d.lineTo(a,j);
d.stroke();
d.closePath();
};
Jui.graph.Graph.prototype._refreshGrid=function(){if(!this._gridVisible){return;
}var b=this._gridCanvas;
var d=this._getCanvasSize(this._nodes,this._lines);
this._setCanvasSize(b,d.width,d.height);
var c=b.getContext("2d");
c.clearRect(0,0,b.width,b.height);
c.strokeStyle=Jui.theme["Graph.GridColor"];
for(var a=this._gridSize-0.5;
a<b.width;
a+=this._gridSize){c.beginPath();
c.moveTo(a,0);
c.lineTo(a,b.height);
c.stroke();
c.closePath();
}for(var e=this._gridSize-0.5;
e<b.height;
e+=this._gridSize){c.beginPath();
c.moveTo(0,e);
c.lineTo(b.width,e);
c.stroke();
c.closePath();
}};
Jui.graph.Graph.prototype._setNodes=function(c){var e=this;
c=c||[];
var a=[];
for(var d=0;
d<c.length;
++d){a.push(e._getNodeHtml(c[d]));
}e._nodePanel.innerHTML=a.join("");
e._nodes=[];
e._nodeMap={};
for(var d=0,b=e._nodePanel.children;
d<c.length;
++d){e._initializeNode(c[d],b[d*2]);
}};
Jui.graph.Graph.prototype._getNodeHtml=function(d){var g=this._nodeTypeMap[d.type];
if(g==null){Jui.util.alertAndThrow("unsupported node type: "+node.type);
}var b=[];
if(g.htmlFunc==null){var f="JuiGraphNode"+(g.className==null?"":" "+g.className);
b.push("<div class='"+f+"' draggable=true style='width:"+g.width+"px;height:"+g.height+"px");
var e=d.icon||g.icon;
if(e!=null){b.push(";background-image:url("+e+")");
}b.push("'></div>");
}else{b.push(g.htmlFunc(d));
}var c=g.textStyle||this._nodeTextStyle||"";
var h=g.textClass||this._nodeTextClass||"";
var a="JuiGraphNodeText"+(Jui.string.isEmpty(h)?"":" "+h);
b.push("<div class='"+a+"' style='"+c+"'>");
b.push(this._showNodeText?Jui.$h(d.text||""):"");
b.push("</div>");
return b.join("");
};
Jui.graph.Graph.prototype._initializeNode=function(b,c){if(b.id==null){b.id=Jui.graph.Graph._generateNextId(this._nodeMap,"NODE-");
}this._nodes.push(b);
this._nodeMap[b.id]=b;
var a=c.nextSibling;
c._node=b;
a._node=b;
b.element=c;
b.textElement=a;
a.style.width=this._maxNodeTextWidth+"px";
c.onmousedown=this.$class.doNodeMouseDown;
c.onclick=this.$class.doNodeClick;
c.ondblclick=this.$class.doNodeDoubleClick;
c.ondragstart=this.$class.doNodeDragStart;
c.ondragend=this.$class.doNodeDragEnd;
a.onclick=this.$class.doNodeTextClick;
a.onmousedown=this.$class.doNodeMouseDown;
this._refreshNodePosition(b);
if(this._highlightCurrentNode){c.setAttribute("highlight",true);
}};
Jui.graph.Graph.prototype._refreshNodePosition=function(c){if(typeof(c.x)!="number"||typeof(c.y)!="number"){Jui.util.alertAndThrow("x or y attribute not specified for node '"+(c.text||c.id)+"'");
}var b=c.element;
b.style.left=(c.x-Math.floor(b.offsetWidth/2))+"px";
b.style.top=(c.y-Math.floor(b.offsetHeight/2))+"px";
var a=b.nextSibling;
a.style.left=(c.x-Math.floor(this._maxNodeTextWidth/2))+"px";
a.style.top=(c.y+Math.ceil(b.offsetHeight/2)+2)+"px";
};
Jui.graph.Graph.prototype._setLines=function(c){var e=this;
e._lines=c||[];
var b=[];
for(var d=0;
d<e._lines.length;
++d){b.push(e._getLineHtml(e._lines[d]));
}var a=e._nodePanel;
Jui.dom.insertHtml(a,"BeforeEnd",b.join(""));
for(var d=0,f=e._lines.length;
d<f;
++d){e._initializeLine(e._lines[d],a.children[a.children.length-f+d]);
}e._refreshLines();
};
Jui.graph.Graph.prototype._getLineHtml=function(b){var d=this._lineTypeMap[b.type];
if(d.htmlFunc==null){var c=d.textStyle||this._lineTextStyle||"";
var e=d.textClass||this._lineTextClass||"";
var a="JuiGraphLineText"+(Jui.string.isEmpty(e)?"":" "+e);
return"<div class='"+a+"' style='"+c+"'>"+Jui.$h(b.text||"")+"</div>";
}else{return d.htmlFunc(b);
}};
Jui.graph.Graph.prototype._initializeLine=function(a,b){a.textElement=b;
b._line=a;
b.onclick=this.$class.doLineTextClick;
};
Jui.graph.Graph.prototype._refreshLines=function(){var b=this._lineCanvas;
var e=this._getCanvasSize(this._nodes,this._lines);
this._setCanvasSize(b,e.width,e.height);
var d=b.getContext("2d");
d.clearRect(0,0,b.width,b.height);
for(var c=0;
c<this._lines.length;
++c){var a=this._lines[c];
var f=this._getLinePoints(a);
this._drawLine(d,a.type,f,a);
}};
Jui.graph.Graph.prototype._drawLine=function(f,m,u,w){var c=w!=null&&w==this._currentLine;
var o=this._lineTypeMap[m];
f.beginPath();
for(var k=0;
k<u.length-1;
++k){var l=1,e=1;
for(var h=k+1;
h==k+1||(h<u.length&&l!=e);
++h){l+=u[h].x==u[k].x?1:0;
e+=u[h].y==u[k].y?1:0;
}if(l!=e){var d=l>e?"x":"y";
var v=Math.round(u[k][d]);
var t=u[k][d]>v?v+0.5:v-0.5;
for(var h=k,g=Math.max(l,e);
h<g;
++h){u[h][d]=t;
}}}for(var k=0;
k<u.length;
++k){var s=u[k];
k==0?f.moveTo(s.x,s.y):f.lineTo(s.x,s.y);
}f.strokeStyle=c?"#000000":(o.color||"#000000");
f.lineWidth=(c?2:0)+(o.width||1);
f.stroke();
f.closePath();
if(o.arrow=="single"||o.arrow=="double"){this._drawArrow(f,u[u.length-2],u[u.length-1]);
}if(o.arrow=="double"){this._drawArrow(f,u[1],u[0]);
}if(w!=null){var s;
if(u.length%2==1){s=u[u.length>>1];
}else{var r=u[u.length>>1],q=u[(u.length>>1)-1];
s={x:(r.x+q.x)/2,y:(r.y+q.y)/2};
}w.textElement.style.left=(s.x-(w.textElement.offsetWidth>>1))+"px";
w.textElement.style.top=(s.y-(w.textElement.offsetHeight>>1))+"px";
}};
Jui.graph.Graph.prototype._getLinePoints=function(c){var e=this._nodeMap[c.from];
var b=this._nodeMap[c.to];
if(e==null||b==null){Jui.util.alertAndThrow("line #"+i+": start node or end node not found");
}var f=Jui.util.clone(c.routes||[]);
var d=e.element;
var a=b.element;
f.unshift(this._extend(e,f[0]||b,(d.offsetWidth+d.offsetHeight)/4));
f.push(this._extend(b,f[f.length-1],(a.offsetWidth+a.offsetHeight)/4));
return f;
};
Jui.graph.Graph.prototype._setCurrentLegend=function(a){var b=this;
a=a||b._cursorLegend;
if(a!=b._currentLegend){if(b._currentLegend!=null){b._currentLegend.element.className="JuiGraphLegendRow";
}a.element.className="JuiGraphLegendRow JuiGraphLegendRowCurrent";
b._currentLegend=a;
b._mask.style.display=a.type=="Cursor"?"none":"block";
}};
Jui.graph.Graph.prototype._setCurrentNode=function(b){var a=this;
if(a._currentNode!=b){if(a._currentNode!=null){Jui.dom.removeClass(a._currentNode.element,"JuiGraphNodeSelected");
}if(b!=null){Jui.dom.addClass(b.element,"JuiGraphNodeSelected");
a._setCurrentLine(null);
}a._currentNode=b;
}};
Jui.graph.Graph.prototype._setCurrentLine=function(a){var b=this;
if(b._currentLine!=a){b._currentLine=a;
b._refreshLines();
}};
Jui.graph.Graph.prototype._nodeFromPoint=function(e){var a={x:e.clientX,y:e.clientY};
for(var b=0;
b<this._nodes.length;
++b){var d=this._nodes[b];
var c=d.element.getBoundingClientRect();
if(Jui.math.pointInRange(a,c)){return d;
}}return null;
};
Jui.graph.Graph.prototype._hideMask=function(){this._mask.style.display="none";
this._mask.style.cursor="";
this._setCurrentLegend();
};
Jui.graph.Graph.prototype._setCanvasSize=function(b,c,a){b.style.width=c+"px";
b.style.height=a+"px";
b.width=c;
b.height=a;
};
Jui.graph.Graph.prototype._getNodeJson=function(b){var a={id:b.id,text:b.text,type:b.type,x:b.x,y:b.y,data:b.data};
if(!Jui.string.isEmpty(b.icon)){a.icon=b.icon;
}return a;
};
Jui.graph.Graph.prototype._getLineJson=function(b){var a=Jui.array.isEmpty(b.routes)?null:b.routes;
return{id:b.id,type:b.type,from:b.from,to:b.to,routes:a};
};
