Jui.$define("Jui.graph.StretchGraph",Jui.graph.Graph);
Jui.graph.StretchGraph.initialize=function(c,b,a){b=b||{};
b.scrollable=false;
a=a||this;
var d=this.superClass.initialize(c,b,a);
d.element.className="JuiGraph JuiStretchGraph";
if(Jui.browser.ie&&Jui.browser.majorVersion<7){d._image=Jui.dom.insertHtml(d._content,"AfterBegin","<img class=JuiStretchGraphImage>");
}d.setImage(b.image);
return d;
};
Jui.graph.StretchGraph.prototype.setImage=function(a){var b=Jui.string.isEmpty(a);
if(this._image==null){this._content.style.backgroundImage=b?"":"url("+a+")";
}else{this._image.style.display=b?"none":"block";
this._image.src=b?"":a;
}this._imageUrl=b?null:a;
};
Jui.graph.StretchGraph.prototype.load=function(e){e=Jui.util.clone(e||{});
e.nodes=e.nodes||[];
e.lines=e.lines||[];
this._ratioX=this._content.clientWidth/100;
this._ratioY=this._content.clientHeight/100;
for(var d=0;
d<e.nodes.length;
++d){var f=e.nodes[d];
f.x=f.x*this._ratioX;
f.y=f.y*this._ratioY;
}for(var d=0;
d<e.lines.length;
++d){for(var c=0,b=e.lines[d].routes||[];
c<b.length;
++c){var a=b[c];
a.x=a.x*this._ratioX;
a.y=a.y*this._ratioY;
}}Jui.graph.Graph.prototype.load.call(this,e);
};
Jui.graph.StretchGraph.prototype.getJson=function(){var e=Jui.graph.Graph.prototype.getJson.call(this);
for(var d=0;
d<e.nodes.length;
++d){var f=e.nodes[d];
f.x=f.x/this._ratioX;
f.y=f.y/this._ratioY;
}for(var d=0;
d<e.lines.length;
++d){for(var c=0,b=e.lines[d].routes||[];
c<b.length;
++c){var a=b[c];
a.x=a.x/this._ratioX;
a.y=a.y/this._ratioY;
}}return e;
};
